### ISSUE TITLE
Track UI

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1007]
Depends on #1006 

- Track a peer outside the projects' maintainer graph (seeing as there's only projects of 1 maintainer)

User story:
1. Get a `PeerId` out of band
2. Go to a projects' member tab (network tab)
3. Press "add peer to replicate"
4. Paste `PeerId` there
5. Now you start to listen for that peers' project changes

/cc @juliendonck - I just copy+pasted your card :innocent:

**Comment by juliendonck** [comment]
![Uploading manage-remote.gif…]()
