### ISSUE TITLE
Browse peer branch

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1012]
When we replicate our view looks like:
```
|> tree ~/.local/share/radicle/git/refs
/home/xla/.local/share/radicle/git/refs
├── heads
├── namespaces
│   ├── hwd1yreb5addursjwiemqnaa4cq4satpnjk77mbdhnp61oms3hurcydysbw
│   │   └── refs
│   │       ├── heads
│   │       │   └── master
│   │       └── rad
│   │           ├── id
│   │           ├── ids
│   │           │   └── hwd1yrey9nwynotkkamguh8yy81qks83qb8uhw6p47q4fjh563omuakakre
│   │           ├── self
│   │           └── signed_refs
│   ├── hwd1yref58x5ceewffrdd3cd7euqsegp8toi75w9sez54djnrg1zm4j7n3w
│   │   └── refs
│   │       ├── rad
│   │       │   ├── id
│   │       │   ├── self
│   │       │   └── signed_refs
│   │       └── remotes
│   │           ├── hybh5cb7spafgs7skjg6qkssts3uxht31zskpgs4ypdzrnaq7ye83k
│   │           │   └── rad
│   │           │       └── id
│   │           └── hybwm6qummpzc6rk4h4ur437z1thfc4hqfkkntxtzfjk5k7c3o6hoa
│   │               ├── heads
│   │               │   └── master
│   │               └── rad
│   │                   ├── id
│   │                   ├── ids
│   │                   │   └── hwd1yreri919uggmg1pgg7tw9sot5jfmhfrtsc3uyj7ciqxtp88jajcmmkh
│   │                   ├── self
│   │                   └── signed_refs
│   └── hwd1yrey9nwynotkkamguh8yy81qks83qb8uhw6p47q4fjh563omuakakre
│       └── refs
│           └── rad
│               ├── id
│               ├── self
│               └── signed_refs
└── tags
```

As we can see we're now able to replicate the `hybwm6qummpzc6rk4h4ur437z1thfc4hqfkkntxtzfjk5k7c3o6hoa` remote's `master` branch. However, in the UI when we try to browse the project we try to look at our level of the tree where there is no `master`. We don't have a `master` because we haven't checked out the project and pushed any changes yet.

It seems like this could be a UI bug, but it would be good to test this scenario in proxy and see what the output getting revisions is.

**Comment by FintanH** [comment]
Found the issue for this. We always assumed that for getting a `Browser` for a project that we create the `Browser` using our own default branch. This worked for us in the past because we always DID have the default branch. But now we need to figure out a way to initialise a `Browser` based off of some heuristics:
* Our own branch if it exists
* The first maintainer's branch

**Comment by rudolfs** [comment]
@FintanH I remember we had a chat about this sometime in the beginning when we started work on checkouts.

There was also [this spec](https://www.notion.so/monadic/Overview-4969e31627984cc1938a6603d7d33738#3f74974beb934d81a911fc1eed1f8a88):

> Within the scope of any project, there is always a so called *default repository.* This is the repository that is shown by default to the user, when the user hasn't made a selection. It can be determined as follows:
> - If I have my own, *modified* copy of the project, ie. I've made and published changes to the project under my user, then **my** repository is the default selected.
> - Else, if there is only **one** maintainer of the project, then that maintainer's repository is the default. This is also called the **canonical** repository.
> - Otherwise, the maintainer repository with the most recent changes on the project's **default** branch is the default repository.

@cloudhead do you remember if there was another place where we discussed this in writing?

**Comment by FintanH** [comment]
Ya, thanks for finding that :grin: At least for `with_browser`, I think it can be pretty simple in that it only needs one code reference to kick off. But for showing the revisions we can order them on returning.

**Comment by FintanH** [comment]
@rudolfs Created a follow-up ticket for that https://github.com/radicle-dev/radicle-upstream/issues/1016
