### ISSUE TITLE
Revision ordering

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1016]
> Within the scope of any project, there is always a so called default repository. This is the repository that is shown by default to the user, when the user hasn't made a selection. It can be determined as follows:
> * If I have my own, modified copy of the project, ie. I've made and published changes to the project under my user, then my repository is the default selected.
> * Else, if there is only one maintainer of the project, then that maintainer's repository is the default. This is also called the canonical repository.
> * Otherwise, the maintainer repository with the most recent changes on the project's default branch is the default repository.

We should ensure that this is the behaviour of our revision selection by writing a test, and if it's not the case then we should fix the ordering.

Noting here that the current implementation doesn't look like it does that ordering. In fact, it's pretty stupid and just gets all the revisions in the order of peers it is given -- however, the local peer is always the first peer.

We might need to order the peers supplied to the `source::revisions` function. Something like get `tracked` but order by most recent commits in `rad_signed_refs`.

**Comment by xla** [comment]
Superseded by #1243
