### ISSUE TITLE
Opening a `.patch` file in the source browser leads to error

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1021]
Proxy:
```
 ERROR api::http::error      > Rejection(State(Source(PathNotFound(Path(NonEmpty { head: Label { label: "patches", hidden: false }, tail: [Label { label: "eslint-plugin-svelte3 2.7.3.patch", hidden: false }] })))))
```

UI:
<img width="816" alt="Screenshot 2020-10-12 at 17 26 52" src="https://user-images.githubusercontent.com/158411/95764031-2d605f00-0cb0-11eb-8344-6faf58cbab01.png">

**Comment by cloudhead** [comment]
Interesting, I wonder if it has to do with syntax highlighting? Or perhaps something to do with the filename not being escaped correctly?

**Comment by cloudhead** [comment]
Looks like the latter, the `+` isn't url-encoded it seems, so it ends up as a ` ` (whitespace) in the backend.

**Comment by FintanH** [comment]
Oh good spot, you can see that in the error too -- Long live surf!
