### ISSUE TITLE
Improve seed node input in setting

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1029]
As experienced in the integration party there's a need to improve the seed node input. There's an old commit lying around somewhere where it was implemented in a better way. Let's see if we can revert it to that or else I think we still have the designs somewhere.

This is what it is about:
<img width="1151" alt="Screenshot 2020-10-13 at 20 36 16" src="https://user-images.githubusercontent.com/2326909/95901512-c1efbd80-0d93-11eb-90d2-b587c69ea239.png">

**Comment by juliendonck** [comment]
This is the commit: https://github.com/radicle-dev/radicle-upstream/pull/629/commits/457a086598ddee17abb01d2313b7c1e920572ef4

**Comment by rudolfs** [comment]
As discussed with @cloudhead, @juliendonck and @brandonhaslegs.

We'll be going for [this design](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=5848%3A2641):

<img width="788" alt="Screenshot 2020-10-20 at 18 23 59" src="https://user-images.githubusercontent.com/158411/96709352-e0107b80-139a-11eb-9b2a-bd8967b346ae.png">
<img width="776" alt="Screenshot 2020-10-20 at 18 24 04" src="https://user-images.githubusercontent.com/158411/96709359-e141a880-139a-11eb-8488-ac97d40717f5.png">
<img width="777" alt="Screenshot 2020-10-20 at 18 24 11" src="https://user-images.githubusercontent.com/158411/96709361-e272d580-139a-11eb-9834-9223a6e15248.png">

**Comment by rudolfs** [comment]
@xla for the "Restart" button I was thinking of wiring up a new IPC call to the Electron `main.js` to restart the proxy, but am open for other suggestions.

**Comment by xla** [comment]
> @xla for the "Restart" button I was thinking of wiring up a new IPC call to the Electron `main.js` to restart the proxy, but am open for other suggestions.

Does electron support a restart? If so then it sounds like the correct approach.

**Comment by rudolfs** [comment]
@xla in the end I had to go a different route, because currently we have two different ways of managing the proxy lifecycle: dev and production. I felt it would have been too big of a change to make it work for both.

Instead I opted for calling the `v1/control/reload` endpoint to reload the seed configuration.

**Comment by xla** [comment]
> Instead I opted for calling the `v1/control/reload` endpoint to reload the seed configuration.

That endpoint should not be present in production. This is in violation with the reason we provided that endpoint in the first place.

**Comment by xla** [comment]
Discussed offline with @rudolfs that for now we are going to show the notification and escalate the restart to the user. The correct change will be to have dynamic discovery in the proxy where newly entered addresses are fed correctly into the network stack.

**Comment by rudolfs** [comment]
> That endpoint should not be present in production.

@xla btw. just checked, the endpoint is available also in production at the moment.

**Comment by xla** [comment]
> @xla btw. just checked, the endpoint is available also in production at the moment.

Yeah it was a notion that was lost in the refactor, it should be that way and ideally not assumed to be present.
