### ISSUE TITLE
Represent and validate RadUrns in ui

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1036]
We use mostly strings and the validation regex is unlikely correct. A proper representation needs to be introduced.

https://github.com/radicle-dev/radicle-upstream/blob/ec582fef4739915639da1b1ce0a29b87dc98d643/ui/src/search.ts#L78-L85

**Comment by FintanH** [comment]
Also note that we need to fix the regex to validate `z-base32` since I misremembered what schema we were using.

**Comment by xla** [comment]
>  validation regex is unlikely correct

**Comment by FintanH** [comment]
Whoops! Well the schema is mentioned now at least. Also I'll link the [URN](https://github.com/radicle-dev/radicle-link/blob/master/docs/spec/identities.md#radicle-urns) section for good measure.

**Comment by juliendonck** [comment]
@geigerzaehler @rudolfs is this something we want to do?

**Comment by rudolfs** [comment]
We can do it once we touch that part of the code, but I don't think we need an issue for it.

**Comment by geigerzaehler** [comment]
> @geigerzaehler @rudolfs is this something we want to do?

I don’t see a need for this at the moment so I’ll close it. If this becomes an issue we can reopen it.
