### ISSUE TITLE
Entity not found when navigating to maintainer profile

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1041]
When tracking a peer project locally and clicking in the peer selector to navigate to the profile of the maintainer it show entity not found.

**Comment by FintanH** [comment]
One thing to check is that when we clone we should have the user entity for the peer we cloned from. We could add this check to our clone test in `tests/replication.rs`.

**Comment by xla** [comment]
AFAIK we don't replicate the user repos when getting a project. Is that an application concern?

**Comment by FintanH** [comment]
I was under the assumption it happens during a `Storage::clone_repo` since we need the certifiers of the project. So we _should_ have the maintainer.

**Comment by xla** [comment]
If we down prio this issue, all actions that lead to a users profile need to be removed/disabled.
