### ISSUE TITLE
Commit propagation

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1044]
When testing out the app through the seed node we found that commits weren't propagated to other peers. To first rule out that this isn't a proxy issue we should set up a test scenario as follows:
* Create 3 peers
* Peer1 creates a project
* Peer2 clones the project
* Peer3 clones the project from Peer2
* Peer1 commits a change to the project
* Assert Peer2 gets the change after Peer1 announces it
* Assert Peer3 gets the change after Peer2 announces it

I wonder if it's the case that we only build announcements based off of our _own_ branches but not peers? (I haven't checked personally)

**Comment by xla** [comment]
In hindsight the announcement period is way low, esp. in scenarios where you'd like realtime-ish collab. Hard to emit but maybe @cloudhead was right on this one.

Generally we don't seem to have an integration test which assert the observation of subsequent commits. Furthermore a three proxy setup might not give us an accurate picture given that usually our intermediate is a seed.

**Comment by FintanH** [comment]
> Furthermore a three proxy setup might not give us an accurate picture given that usually our intermediate is a seed.

Hence, why I said, "To first rule out that this isn't a proxy issue we should set up a test scenario as follows:" :) I think it's worth checking that everything works fine in this simplified scenario. We can then figure out if this is seed communication or radicle-link issue.

**Comment by xla** [comment]
Looked into it briefly by setting up the test case described in the description up top. It didn't yield much, replication worked. The issue here is that when setting peers up like we currently do in our integration tests , they will learn about each other through gossiping, connect directly and will see announcement from the origin. Where what we need to test where `A <> B <> C`, `A` and `C` can only connect to `B`.

**Comment by FintanH** [comment]
> Looked into it briefly by setting up the test case described in the description up top.

Do you have a branch to share and look at? I was also setting up the same scenario but hadn't finished.

> Where what we need to test where A <> B <> C, A and C can only connect to B.

I believe I was coming to the same conclusion.

**Comment by xla** [comment]
> Do you have a branch to share and look at? I was also setting up the same scenario but hadn't finished.

Unfortunately vanished in my git stashes. Used the one below as a basis, added an eve peer and chained them with `build_peer_with_seeds`:

https://github.com/radicle-dev/radicle-upstream/blob/6d32133b512a72b3c87dcfaa9accbccd9c60a7ab/proxy/coco/tests/replication.rs#L99-L106

**Comment by FintanH** [comment]
Investigation:
* Set up project
* Confirm seed has the project
* Maintainer pushes commit
* Monitor Seed for Have
* Other peer monitors for Have and see if the advertisement is for the Seed or the Maintainer -- if it's the Maintainer then NAT will get in the way.

**Comment by FintanH** [comment]
Since we know that fetching works to get the commit, one idea we could execute for the beta is have a "sync" button on a peer that, when pressed, directly calls a fetch for that peer.

/cc @radicle-dev/product @xla

**Comment by FintanH** [comment]
I think I know the issue:
* We build announcements by getting our `Refs` and building the `RadUrn` using the `heads` of the `Refs` https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/coco/src/peer/announcement.rs#L70.
* `heads` give us `OneLevel` refs so we don't have it qualified by `heads` -- I'm sure you know where this is going from here
* `PeerStorage` will use its method `git_has` to determine if this change was applied https://github.com/radicle-dev/radicle-link/blob/master/librad/src/net/peer.rs#L441-L455
* This in turn calls `has_commit` and this line, in particular, https://github.com/radicle-dev/radicle-link/blob/master/librad/src/git/storage.rs#L294, I bet you my bottom euro, will resolve to `refs/namespaces/<id>/refs/remotes/<peer>/<branch>` instead of `refs/namespaces/<id>/refs/remotes/<peer>/heads/<branch>`. 

@kim: Since `Refs` point to heads, should they be `Qualified` instead of `OneLevel`? Or what's the best way to resolve this mismatch? :thinking:

**Comment by kim** [comment]
On Sat Oct 31, 2020 at 11:16 AM CET, Fintan Halpenny wrote:
> I bet you my bottom euro, will resolve to
> `refs/namespaces/<id>/refs/remotes/<peer>/<branch>` instead of
> `refs/namespaces/<id>/refs/remotes/<peer>/heads/<branch>`.

I feel like this has been reported before ("heads" gone missing), but
`net::peer::urn_context` hasn't received a patch.

> @kim: Since `Refs` point to heads, should they be `Qualified` instead of
> `OneLevel`? Or what's the best way to resolve this mismatch? :thinking:

They should indeed be allowed to point to either heads or tags, but since tags
are not well-defined at the moment, `OneLevel` (ie. heads only) is most
sensible. Note that the receiving end has to map the path either way.

**Comment by FintanH** [comment]
Fixed in https://github.com/radicle-dev/radicle-upstream/pull/1177
