### ISSUE TITLE
Session, keystore, and identity APIs

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1049]
I’m outlining the needs for updated APIs that deal with the session unsealing the key store and the identity creation that arise from #868.

With respect to identity and the key store the proxy can be in three states
1. There is no identity yet (and consequently no keystore)
2. There is an identity but the key is sealed
3. There is an identity and the key is unsealed and can sign artifacts.

The first two states are handled by the app as follows:
1. If there is no identity yet, the app shows the onboarding screen. The user inputs their handle and passphrase. This data is used to create a key pair and an identity and encrypts the key pair with the passphrase.
2. If there is an identity but the key is sealed the app shows a dialog that asks the user for their passphrase. That passphrase is sent to the proxy. The proxy uses the passphrase to unseal the key store.

In both cases the frontend receives a token that is used in subsequent requests to the proxy to authorize the use of the key.

### APIs

We implement this with the following APIs

`GET /session`

1. Returns a 404 if there is no idenitty
2. Returns a 403 if there is an identity but the key is sealed
3. Returns current session payload if the key is unsealed an a valid session token is provided (see `POST /session/unseal`).

`POST /identity`

Takes the user handle and passphrase and returns the identity (as currently implemented) and moves proxy from state 1 to 3. Sets the session token as a cookie.

`POST /session/unseal`

Takes `passphrase` as payload, moves session from state 1 to 3, returns the `Session` payload (`{ status: "unsealed", identity: ... }`) and sets the session token as cookie.

### API use in App

On start of the app the app queries `GET /session`. If the session is uninitialized we create and identity with `POST /identity` and get the session with `GET /session`. If the session is sealed is request `POST /session/unseal` with the user provided password.
 
If a session token still exists in the cookie jar (e.g. the app is reloaded) a request to `GET /session` will return the unsealed session and there is nothing to do for the app.

**Comment by xla** [comment]
Thanks for the write-up. The design seems like a good high-level approach. A couple of things that make use of our transport protocol.

* `GET /session` when returning `404 NOT FOUND` communicates `uninitialised` - no other endpoint but the for identity creation should be enabled
* `POST /identity` - also expects the `passphrase` as part of the payload
* the sealed state can be deduced from any endpoint returning `403 FORBIDDEN` as implemented in the recently introduced guard

https://github.com/radicle-dev/radicle-upstream/blob/d84a88c50cd0cfe0a8cfa28c895d1178410b0ec4/proxy/api/src/http.rs#L126-L140

**Comment by geigerzaehler** [comment]
Thanks. I’ve updated the description accordingly. I’ve also noticed that is does not make sense for `GET /session` to set the session token. This also means that the identity creation flow requires an additional request to `POST /session/unseal`.

**Comment by xla** [comment]
> Thanks. I’ve updated the description accordingly. I’ve also noticed that is does not make sense for `GET /session` to set the session token. This also means that the identity creation flow requires an additional request to `POST /session/unseal`.

As I said you can require the `passphrase` as part of the identity creation endpoint and set the header in that response, this way there are no two calls required.

**Comment by geigerzaehler** [comment]
> As I said you can require the `passphrase` as part of the identity creation endpoint and set the header in that response, this way there are no two calls required.

Ok. I just find it strange that `POST /identity` sets the session token. But will update it

**Comment by xla** [comment]
> Ok. I just find it strange that `POST /identity` sets the session token. But will update it

It's not that odd if you think of it along the lines of more conventional authenticated APIs. Where `POST /identity` is the account creation and `PUT /session/unseal` is the equivalent of login. After both operations the user ends up with a valid session.

**Comment by geigerzaehler** [comment]
Superseded by #1083
