### ISSUE TITLE
Restyle searchbox

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1050]
The search box has lost some styles in the last week or so in the latest build.

- [x] the border radius should be .5rem
- [x] there should be no border on the field
- [x] the height of the field should be 3rem
- [x] the `.left-item-wrapper` should have a height of 3rem so it remains vertically centered in the field
- [x]  the background color of the form should not change on `:hover` or `:focus`

Currently looks like this:
![image](https://user-images.githubusercontent.com/4406983/96115177-d55f6d80-0ee6-11eb-925a-391a34706d6d.png)

Final result should look like this:
![image](https://user-images.githubusercontent.com/4406983/96116325-94685880-0ee8-11eb-8e68-a5c8c00ad824.png)

**Comment by xla** [comment]
> [ ] the `.left-item-wrapper` should have a height of 3rem so it remains vertically centered in the field

This breaks the icon when the input has an error. Could we adjust the designs with invalid inputs in mind. Happy to fix the diverged styles then.

**Comment by xla** [comment]
Refs #1031

**Comment by brandonhaslegs** [comment]
> > [ ] the `.left-item-wrapper` should have a height of 3rem so it remains vertically centered in the field
> 
> This breaks the icon when the input has an error. Could we adjust the designs with invalid inputs in mind. Happy to fix the diverged styles then.

Sorry, what does centering the 🔍 icon have to do with errors?

**Comment by xla** [comment]
> Sorry, what does centering the mag icon have to do with errors? Maybe centering can be achieved without changing the height of the `.left-item-wrapper`. All I'm saying is to make sure the icon stays vertically centered when the field height is increased.

Absolutely, just wanted to point out that the change you are referring to by itself won't fix the issue of centering.
