### ISSUE TITLE
Upgrade to tokio v1.0

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-upstream#1078]
Reminder that [tokio v0.3.0](https://github.com/tokio-rs/tokio/releases/tag/tokio-0.3.0) introduces [cancellable JoinHandle](https://github.com/tokio-rs/tokio/pull/2474)s, which would obsolete [`SpawnAbortable`](https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/coco/src/spawn_abortable.rs).

Other changes may or may not be compatible, and may or may not be immediate improvements.

**Comment by geigerzaehler** [comment]
Since tokio v1 has been released we want to upgrade to that version.

**Comment by FintanH** [comment]
Depends on #1463 I believe.

**Comment by kim** [comment]
Is there a good grasp on how much would break if `upstream` moved to tokio 1?

It looks like `quinn` merged their migration -- while `link` doesn't care much about tokio 1, that patch also includes moving to `rustls` 0.19, which we would benefit from (we need to use the exact same version of `rustls` as `quinn`). It is also that this was a major blocker for `quinn` to make a new official release, and it would be good to be able to move away from the pinned git dependency.

Due to the breaking nature of this migration, the question is how we want to coordinate it? Do we want to wait until #1463 lands, then make a coordinated effort to move both projects to tokio 1, then proceed with `net/next`? Or is it a small enough change to conflate it with either `next` or `net/next`?

**Comment by FintanH** [comment]
> Or is it a small enough change to conflate it with either next or net/next?

I could do a quick check on #1463 to see how much the compiler complains
