### ISSUE TITLE
Proxy daemon stays alive after terminating app

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1085]
Tested with the latest build from `master`: https://buildkite.com/monadic/radicle-upstream/builds/5677#f7249be0-1547-4cf9-9d58-0df79746b152

This happens on macOS, haven't tested on Linux.

Steps to reproduce:
1. Look at the process list to ensure there are no `proxy` daemons running:
```
$ ps aux | grep 'Contents/Resources/proxy' | grep -v grep
```
2. download dmg, install and start app
3. quit app with <kbd>⌘</kbd>+<kbd>q</kbd>
4. look at the process list again

Expected: no processes running.
Actual result:
```
$ ps aux | grep 'Contents/Resources/proxy' | grep -v grep
rudolfs           7119   0.1  0.4  4447880  71128   ??  S     8:58AM   0:00.74 /Applications/radicle-upstream.app/Contents/Resources/proxy
```

**Comment by xla** [comment]
How does electron handle the app close? What signals does it send its children?

**Comment by xla** [comment]
Might be we need to listen for more signals

https://github.com/radicle-dev/radicle-upstream/blob/def2f51166833efe7ceaaa32ec39273557660c54/proxy/api/src/main.rs#L58-L62

**Comment by rudolfs** [comment]
@xla https://github.com/radicle-dev/radicle-upstream/blob/master/native/main.js#L137

**Comment by xla** [comment]
Haha, that would explain something.

> Daemon programs sometimes use SIGHUP as a signal to restart themselves, the most common reason for this being to re-read a configuration file that has been changed. 

We probably wanna emit a signal like `SIGTERM`.

**Comment by rudolfs** [comment]
> Haha, that would explain something.

Used to work! :trollface:  🤷

**Comment by xla** [comment]
It used to, but then we introduce `SIGHUP` handling explicitly. Will take this issue on.

**Comment by cloudhead** [comment]
![](https://media3.giphy.com/media/y1ewxG8aFWk0M/giphy.gif?cid=ecf05e47j6iyk02q03j9jl1z0z7mgr6ng0rd81bimdbgmiis&rid=giphy.gif)

**Comment by rudolfs** [comment]
@cloudhead looool
