### ISSUE TITLE
Bubble up error when proxy fails on startup

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1095]
A wide host of issues we observed during network parties was old or unexpected state leading to startup errors of the proxy. This has not sufficiently capture or bubbled up in the UI/app container. The app ought to crash entirely with a proper report or there are other ways to surface these errors so they can be addressed and avoided.

**Comment by rudolfs** [comment]
How about [this](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=5952%3A4461)?
<img width="793" alt="Screenshot 2020-11-04 at 10 40 19" src="https://user-images.githubusercontent.com/158411/98094963-3f39ba00-1e8a-11eb-89f7-1c548e8dc02a.png">
