### ISSUE TITLE
Broken project state when creating project with existing name

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#1118]
Reproduce with:

1. New project
2. Create a new repository
3. Choose a path which has an existing project in it
4. Use an existing project name
5. Create project

You should get "Incorrect input" and the project dashboard doesn't work.

**Comment by FintanH** [comment]
One thing: the user shouldn't be able to choose the name if it's an existing project. So this is a genuine bug. Going to see how it affects my project dashboard now.

**Comment by FintanH** [comment]
I can see why this breaks, it doesn't get to push the default branch so we end up in a state where the project gets created in the monorepo but the branch doesn't get created.

**Comment by cloudhead** [comment]
I wonder if an approach to this would be something like database transactions: being able to rollback state if there's an error somewhere in the process.

**Comment by FintanH** [comment]
Well, one thing is that if there's an error in _any_ of the projects then this gets bubbled up, i.e. `Result<Vec<Project>, Error>`. Something we could consider is returning something that returns both. So we either have:
1. A list of projects
2. A list of errors
3. Both a list of projects and a list of errors

The front-end might be able to show a different widget for the error'd cases

**Comment by cloudhead** [comment]
Yeah that's exactly the issue. I think a `Vec<Result<Project, Error>>` would make more sense for eg., unless we also have to deal with "global" errors. Then I think we could do something more like `(Vec<Project>, Vec<Error>)`.

**Comment by FintanH** [comment]
Could you expand on what you mean by '"global" errors'?

**Comment by cloudhead** [comment]
> Could you expand on what you mean by '"global" errors'?

I mean errors that don't pertain to a specific project

**Comment by xla** [comment]
We start to get better representing different states wrt. replication status. It would not be a bad idea to encode other dimensions in a similar fashion. An errored or corrupted state can happen for many reason and in most cases means the file layout for the project in the monorepo is not what is expected. This could for example occur during migration of radicle versions, in which case we actually want to surface that and do some operation to bring the state into shape.

> Well, one thing is that if there's an error in _any_ of the projects then this gets bubbled up, i.e. `Result<Vec<Project>, Error>`. Something we could consider is returning something that returns both. So we either have:

Preserving actual errors for network or malformed requests is important, if `Project` would be a sum type a la:

```
Project
  = NotReplicated
  | Incomplete [Reason]
  | Full ActualProjectData
```

we could surface those where sensible and even provide actions of how to remedy broken states. For example when the default branch wasn't pushed.

**Comment by FintanH** [comment]
This is exactly the right idea :100: To extend on it though, `Incomplete` can actually contain some partial data. If we can't get the branch then we still have Urn and the project name -- we just can't get the stats. 

A global failure in this case is there's no way to get the list of projects in the first place. I think we're all on the same page so I'll start whipping something up for this.

I'll add the bug fix in a different PR after. Going to keep the bug to make these partial failures easy for me to test for now :sweat_smile:

**Comment by cloudhead** [comment]
:100:

**Comment by cloudhead** [comment]
> I'll add the bug fix in a different PR after. Going to keep the bug to make these partial failures easy for me to test for now sweat_smile

I don't care about the bug, just get met the dashboard not to break! :joy:

**Comment by FintanH** [comment]
_I CARE_
