### ISSUE TITLE
Disable inputs and button when submitting password on onboarding

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1127]
When submitting the password, we show a notification `creating the identity`, but we don't disable the interaction. Since this takes a few seconds we should show a cursor spinner and disable all interaction. We can use the screen lock functionality that we use on `NewProject.svelte`

**Comment by rudolfs** [comment]
Done in: https://github.com/radicle-dev/radicle-upstream/pull/1194.
