### ISSUE TITLE
Validate existing repository setup

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1135]
The PR https://github.com/radicle-dev/radicle-upstream/pull/1134 is a good start for ensuring paths are valid. I think it would be good to continue along this vein and validate things if we want to create an existing repository.

At least two things come to mind:
* Check that the specified default branch exists
* Check that if a rad remote exists then see if the URLs match

**Comment by rudolfs** [comment]
Would this also solve: https://github.com/radicle-dev/radicle-upstream/issues/822?

**Comment by FintanH** [comment]
Ya, we would just throw the validation error and not mess with the remote. This would give the user the chance to maybe rename the remote themselves to keep a backup.

**Comment by FintanH** [comment]
@cloudhead: Would you be willing to do this one? I can walk you through my thoughts on it.

**Comment by FintanH** [comment]
To elaborate, the things to validate:
* We should check if a `rad` remote exists and ensure the RadUrls match if it does, otherwise we should throw a validation error: https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/coco/src/project/create.rs#L276-L289
* In the case of an existing repository setup we should validate that the repository has the default branch selected: https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/coco/src/project/create.rs#L328-L334
* The existing path should be validated to ensure that it's a non-empty PathBuf https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/coco/src/project/create.rs#L103-L108 (this could probably be the same for New)

All of these could essentially be their own functions, and be reused in at their existing points too.
