### ISSUE TITLE
"Incorrect input" when opening project

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#1141]
* Followed a project
* Clicked on it in "Following" tab
* It shows up fine, but I get an "Incorrect input" notification, and the following log:
```
 ERROR api::http::error      > Rejection(State(MissingRef { reference: Reference { remote: None, category: Heads, name: RefLike("main"), _namespace: Hash(Multihash([160, 228, 2, 32, 144, 117, 148, 247, 128, 224, 111, 175, 161, 56, 59, 10, 98, 217, 79, 141, 110, 190, 147, 188, 176, 16, 3, 203, 53, 178, 248, 117, 106, 75, 186, 52])) } }))
```

In the project stats, I see `0 Branches`, but the branch shows up in the branch selector.

**Comment by juliendonck** [comment]
Can we make the error more descriptive or less wrong?
