### ISSUE TITLE
Announcements of projects dont land with current diffing and long period

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1143]
In the recent party projects only reliably landed on the seed if we reduced the announcement period and always announce everything.

**Comment by FintanH** [comment]
1. We should advertise a new project being created immediately on the network -- the outcome of this should be to see if the seed node picks up these projects properly, as we were seeing that it would miss projects easily.
2. Survey diffing logic of new commit updates  
3. If 1. and 2. don't help with project and commit propagation, we should shotgun advertise the HEADs of projects - interval at a low number, e.g. 5s -- need to work on more sensible announce strategy.
