### ISSUE TITLE
Persist project searches

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1147]
Currently we don't persist project searches beyond app starts.

**Comment by FintanH** [comment]
Safest route: 
* Save on new request made
* Consequences: A request might have progressed in state but regresses if the app is shutdown before a _new_ request is made.

Add a new subroutine command for persisting waiting room.

**Comment by cloudhead** [comment]
Hmm I'm not sure this is what we want. Can't we look at the monorepo and fetch projects that have not been fetched yet? The state should already be there.

**Comment by xla** [comment]
> Hmm I'm not sure this is what we want. Can't we look at the monorepo and fetch projects that have not been fetched yet? The state should already be there.

Mid/long-term it should be a protocol concern, for now it's implemented in the app. There will be more iterations on this feature. For now we aim to provide the feature requirements.

**Comment by cloudhead** [comment]
Gotcha.
