### ISSUE TITLE
Add cursor: default; to all text

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1168]
This will make the app feel more like an app and less like a website. 🌠 Should be applied to all text elements (`h1` `h2` `h3` `h4` `h5` `p`).

What is complicated about this is that there's a lot text elements that are clickable and thus need to retain the `pointer` cursor, for example the `urn` on the profile, and the `menu-list-item` nav links. There are a lot more instances of this.

**Comment by juliendonck** [comment]
this is too complicated to do in β1
