### ISSUE TITLE
Hover state for shell config tip is full width, but should only span the width of the text and copy icon

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1172]
Not sure when this happened, but maybe related to the Seeds input in the Settings page maybe? We're using the same component there.

![image](https://user-images.githubusercontent.com/4406983/97882542-0aabee00-1d24-11eb-81c5-8a89387007eb.png)

**Comment by juliendonck** [comment]
was already resolved
