### ISSUE TITLE
Improve unlock screen

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#1179]
- on unsuccessful unlock
  - [ ] (re-)focus on the passphrase input
  - [ ] select the value of the passphrase input

**Comment by juliendonck** [comment]
@MeBrei is this still relevant?

**Comment by MeBrei** [comment]
> @MeBrei is this still relevant?

@juliendonck The behavior outlined in the description is not implemented and still seems like a nice small improvement.

**Comment by juliendonck** [comment]
Pull in password component in lock screen and make it work for this specific case
