### ISSUE TITLE
Identity can't be created 

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-upstream#1181]
_macOS Catalina - 10.15.7_

After trying out three of the most recent builds, I am unable to create a new identity, even after clearing application state:

**Builds tried:**
https://buildkite.com/monadic/radicle-upstream/builds/6116#5be4429a-55e0-457b-ad07-6d7455c3bf8c
https://buildkite.com/monadic/radicle-upstream/builds/6131
https://buildkite.com/monadic/radicle-upstream/builds/6121#cbbc9da3-95cc-4604-8f67-d66bd7928a9b

Each time, I've deleted the app and cleared the application state using `./reset-state.sh`

After first application reset, the proxy was still running. With @rudolfs advice I ran from CLI via `/Applications/radicle-upstream.app/Contents/MacOS/radicle-upstream` and received output:

```
Error: Command failed: /Applications/radicle-upstream.app/Contents/Resources/proxy
 INFO  coco::git_helper > Making sure git-remote-rad helper is set up
 INFO  librad::net::protocol > Protocol::run; local.id=hydqrao8oq1oa858emchywxice1rhpg8huzpiwjhb1qxeh951bb4pn local.addr=0.0.0.0:59262
 INFO  api                   > Starting...
 INFO  api                   > ... API
Error: Warp(hyper::Error(Listen, Os { code: 48, kind: AddrInUse, message: "Address already in use" }))

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Applications/radicle-upstream.app/Contents/Resources/proxy'
}

```
In the app, this threw an "incorrect input" error after trying to set my passphrase.

![image](https://user-images.githubusercontent.com/18275452/98026909-24286500-1e0c-11eb-9971-6db4e7c9104f.png)

After running, `ps aux | grep 'target/debug/proxy' | grep -v grep | awk '{print $2}`, the proxy was still running and error persisted.

@FintanH and I then killed the proxy which fixed the initial "incorrect input" error, but resulted in the app timing out in the "Creating identity..." state.

<img width="351" alt="image" src="https://user-images.githubusercontent.com/18275452/98027156-81bcb180-1e0c-11eb-8785-25e830a470fc.png">

On refresh, I'm met with the blue screen of death.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/18275452/98027170-8b461980-1e0c-11eb-96cf-22c3eef33898.png">

Not sure what's up. All tips welcome.

**Comment by xla** [comment]
Ref #1095

**Comment by rudolfs** [comment]
Turns out the problem was that there was a webserver already running on port `8080`, so the proxy didn't start up, but the front-end didn't show the BSOD screen as it could still reach whatever was listening on `8080`. We should handle this better.

**Comment by FintanH** [comment]
> Turns out the problem was that there was a webserver already running on port 8080, so the proxy didn't start up, but the front-end didn't show the BSOD screen as it could still reach whatever was listening on 8080. We should handle this better.

But does that explain why @abbey-titcomb was able to get to the identity creation screen and it would then freeze not progressing after entering the passphrase?

**Comment by rudolfs** [comment]
> But does that explain why @abbey-titcomb was able to get to the identity creation screen and it would then freeze not progressing after entering the passphrase?

Yes, because the passphrase is the first point where we actually make a request to the backend. In her case the backend sent back a 404 and the frontend showed an error notification.

**Comment by FintanH** [comment]
Ah, weird. I couldn't spot the existing port error when we started her application from the terminal :thinking: Like initially we saw: `Error: Warp(hyper::Error(Listen, Os { code: 48, kind: AddrInUse, message: "Address already in use" }))`, killed the process, and then when she got further we didn't see that error.

**Comment by rudolfs** [comment]
Maybe something changed between the debug sessions we had. At least when we looked at it, there was an nginx instance running on `8080`.

**Comment by geigerzaehler** [comment]
With #1189, #1095, and ##1187 we have follow-ups for this issue.
