### ISSUE TITLE
Refactor Project into an enum

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1182]
Part of making our lives better, Project will become an enum where it's `Tracked`, `Contributed`, or `Failure`.

Refs: https://github.com/radicle-dev/radicle-upstream/issues/1132#issuecomment-719585854.

**Comment by geigerzaehler** [comment]
@FintanH: Since you asked @rudolfs to open this, could you provide more detail on what needs to be done and why?

**Comment by FintanH** [comment]
If we look at what's existing, there's a `struct Project` that contains `full` and `partial` projects -- i.e. we were able to load the project data successfully or we could only get a portion of the data.

This approach is a bit janky and would be better served by an `enum` that can capture the cases, we could then do something like provide an iterator over `Failure`s for example.

It seems like the above description also mentions the difference in `Tracked` and `Contributed` which should also be variants in the `enum`.

This can all be found in `api/project.rs`, I believe.

**Comment by geigerzaehler** [comment]
Not applicable anymore.
