### ISSUE TITLE
Failed builds stall

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1184]
In #1167 we started seeing that builds stall because the proxy was not shutdown properly. We tried to fix this with [`cypress:run && kill pidof api`](https://github.com/radicle-dev/radicle-upstream/pull/1167/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L118). However this does not work if the tests fail and `cypress:run` exits with a non-zero status code. This again results in failing builds stalling.

**Comment by FintanH** [comment]
Better not write failing tests so 🤠
