### ISSUE TITLE
Fail to create identity after clear session

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#1188]
Upstream currently can't handle multiple identities and key stores.

With #1153 an individual passphrase is used to create the key store. On that branch, after clearing the session, trying to create a new identity fails, as the key store already exists. 
An approach to fix this was to not create a new key store if the same passphrase was supplied. And if a new on was supplied, the key file at `librad.key` would be deleted and a new one would be created with the new passphrase. The latter lead to a `State(PeerApi(Pool(Backend(SignerKeyMismatch))))` error.

The problem causing `SignerKeyMismatch` is that on `clear session` only the session is deleted, which was enough when the same hardcoded passphrase was used every time. Now, since we delete the key store, processes connected to the state are still relying on the old key store. 

The `yarn reset:state` script resolves the problems above. 

Open questions: 
- Should the `clear session` button be removed from settings?
- Can we provide something similar to `yarn reset:state` so that users can start from scratch? (eg on persisting errors, forgotten passphrase,...)

**Comment by rudolfs** [comment]
> Should the clear session button be removed from settings?

https://github.com/radicle-dev/radicle-upstream/issues/1192 -> https://github.com/radicle-dev/radicle-upstream/pull/1195

> Can we provide something similar to yarn reset:state so that users can start from scratch? (eg on persisting errors, forgotten passphrase,...)

Power-users can use our fancy foot-gun as described in: https://github.com/radicle-dev/radicle-upstream/blob/master/QA.md#prerequisites

```
wget https://github.com/radicle-dev/radicle-upstream/blob/master/scripts/reset-state.sh
chmod +x reset-state.sh
./reset-state.sh
```
