### ISSUE TITLE
Use a random free port to bind proxy to

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1189]
Currently, the proxy always binds to port 8080. This is a frequently used port. If the proxy fails to bind, the app becomes unusable.

To address this the app should find a random free port and bind the proxy to that port. An intermediate solution would be to bind to a fixed port of high order without implementing the check for a free port and passing this information to the frontend.

**Comment by FintanH** [comment]
Can we set the port to `0` and let it be assigned by the system?

**Comment by xla** [comment]
> Can we set the port to `0` and let it be assigned by the system?

This is not possible as we need to know what the port is from the ui. Instead the native should do a best effort random port check and pass that down when starting the proxy, if it happens to be occupied in between, we are out of luck.

**Comment by geigerzaehler** [comment]
We are using a fixed random port now (#1212). The rest is not crucial for β1 so I’m removing it from the milestone.

**Comment by Kaihuang724** [comment]
Closing this issue unless there's a clear need for it
