### ISSUE TITLE
Refactor "Create Project"

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#119]
- [x] split out smaller components where it makes sense
  - [x] radio chooser
- [x] think about how to reduce complexity around validations
  - [x] take a look around for other validation libs
  - [x] check if it is feasible to extract the validation logic

Refs #97

**Comment by rudolfs** [comment]
Maybe svelte actions can somehow help to clean up the validation logic:
https://svelte.dev/tutorial/actions
https://medium.com/better-programming/practical-svelte-the-use-directive-60635671335f

**Comment by MeBrei** [comment]
There is currently no feasible way to extract validations that would reduce the amount of repetition and code. We should check this again, once we implement more validations.

**Comment by xla** [comment]
Validation should also be looked at together with the API and where what authority lies. To avoid divergence and surpprising UX.

@MeBrei Wanna create a follow-up issue for that topic?
