### ISSUE TITLE
Resolve cross-Site Cookie warning

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#1197]
Upstream uses cookies to authenticate with the proxy and all requests to the proxy are cross-origin. Electron may enable stricter cookie handling in the future (https://github.com/electron/electron/issues/24225). This would change the default cookie policy from `SameSite=None` to `SameSite=Lax` and would require `Secure` when using `SameSite=None`. This would mean that setting cross-origin cookies on unencrypted connections is disallowed and this would break our app. Here’s a [good article](https://web.dev/samesite-cookies-explained/) explaining what is going on. 

The only way for us to address this is to not use cookies or to serve the Upstream code from the proxy.

*edited by @geigerzaehler*

**Comment by geigerzaehler** [comment]
@MeBrei can you find out how pressing this is? I.e. when this will break?

**Comment by MeBrei** [comment]
The feature has been already rolled out on the Chrome side: [Chrome Same Site Update](https://www.chromium.org/updates/same-site)
The Electron v11.1.1 we are using seems to be using chromium v87 but the feature is not enabled yet. There is an open issue in https://github.com/electron/electron/issues/24225

**Comment by geigerzaehler** [comment]
It should be possible to set the cookie with the `Secure` attribute because that attribute [is not considered](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies) for request to localhost domains. However electron does not respect that yet.
