### ISSUE TITLE
Allow the user to start the app with a different directory

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#1199]
To have a solution for a forgotten passphrase, but also to be able to later build rotating your passphrase, having multiple identities and having completely separate environments for dev and production, we want to be able to start the app with a different directory (different state). 

Currently all files are created in `XDG_CONFIG_HOME`, `XDG_DATA_HOME` or `HOME`, when building from source there is the possibility to delete all files created by the app via `yarn reset:state`. dev and production mode store their data files in different directories but share the same config files.

So far the following scenarios have been discussed:
- start the app from console, setting `XDG_CONFIG_HOME`, `XDG_DATA_HOME` or `HOME` to a new directory
- the directory is set "behind the scenes" and a button is created in `Settings` (like the former clear session button) which provokes switching to a new directory and therefor a new identity/key store has to be created

**Comment by MeBrei** [comment]
As a first step towards this, we should consolidate all data/files created by the app under the same root, eg `.radicle`. We can then organise all files under a specific `session` (name tbd) directory and adjust the app to always use the `current` session. 

This way if users need to create a new identity, instead of handing over the `rm` script, we can instruct them to unlink the `current session`. 
Regarding the developer experience this could also enable us to switch between identities down the line, though more thought needs to be put in to eg how we can persist which projects the respective identity manages.

**Comment by xla** [comment]
> Regarding the developer experience this could also enable us to switch between identities down the line, though more thought needs to be put in to eg how we can persist which projects the respective identity manages.

Are you referring to rad remotes in working copies, because otherwise this won't be an issue as sessions will be self-contained. So projects in the link monorepo live along side all other config. Which also means this is the stepping stone to enable the end-user feature for multiple states/identities.

**Comment by MeBrei** [comment]
> Are you referring to rad remotes in working copies, because otherwise this won't be an issue as sessions will be self-contained. So projects in the link monorepo live along side all other config. Which also means this is the stepping stone to enable the end-user feature for multiple states/identities.

How about projects that I create my self on the app, they will already be managed by radicle?

**Comment by rudolfs** [comment]
> Which also means this is the stepping stone to enable the end-user feature for multiple states/identities.

Which leads me to thing that it should rather be called `identity` in the filesystem instead of `session`.

E.g.:
```
.radicle
├── bin
│   └── git-remote-rad
└── identities
    └── rad:git:hwd1yrebnwx3pzbcu8qqdymh8q41munyryj5kosnxdn58ocws6shzj84sua
        ├── electron
        │   ├── Cache
        │   ├── Code\ Cache
        │   ├── Cookies
        │   ├── Cookies-journal
        │   ├── Dictionaries
        │   ├── GPUCache
        │   ├── Local\ Storage
        │   ├── Network\ Persistent\ State
        │   ├── Preferences
        │   ├── Session\ Storage
        │   ├── TransportSecurity
        │   └── blob_storage
        ├── git
        │   ├── FETCH_HEAD
        │   ├── HEAD
        │   ├── config
        │   ├── description
        │   ├── hooks
        │   ├── info
        │   ├── objects
        │   ├── packed-refs
        │   └── refs
        ├── git-includes
        │   ├── hwd1yre8g7nrk4kzr8a76mms136geysridrgrddw15szroxmrajj9h8d51h.inc
        │   ├── hwd1yrenyh4g8fs4dmongwgsjszb338ynu3ubzk1fx83hf3nwmz63w8h4fy.inc
        │   └── hwd1yreyu1sbiimpr7dehoa5mu8wxmt1a8wqwxawwrpeynn7qkxim34j1py.inc
        ├── keys
        │   └── librad.key
        └── store
            ├── blobs
            ├── conf
            ├── db
            └── snap.00000000000DFB52
```

I also wonder whether the `bin` directory should not be under `identities`, since it's tied to the version of the app with which a certain identity was created?

**Comment by xla** [comment]
> How about projects that I create my self on the app, they will already be managed by radicle?

I don't quite get the notion of managed in this context. If you create a project in through the app, you will have a working copy with a rad remote. That working copy isn't managed it's just one copy of potentially many. Lingering rad remotes is a separate issue which we bumped into a couple of times now.

> Which leads me to thing that it should rather be called `identity` in the filesystem instead of `session`.

That's not a bad idea.

> I also wonder whether the `bin` directory should not be under `identities`, since it's tied to the version of the app with which a certain identity was created?

Seems independent to me as this is about version coordination, and we want to update these bins without even an identity existing.

**Comment by MeBrei** [comment]
> > Which also means this is the stepping stone to enable the end-user feature for multiple states/identities.
> 
> Which leads me to think that it should rather be called `identity` in the filesystem instead of `session`.

Should `electron` be outside of the `identity`? The files are probably already created/necessary before an `identity` is created.

**Comment by rudolfs** [comment]
> Should electron be outside of the identity? The files are probably already created/necessary before an identity is created.

Yeah, I think this is probably similar to what @xla said about the git helper.

**Comment by xla** [comment]
> Should `electron` be outside of the `identity`? The files are probably already created/necessary before an `identity` is created.

This depends on if the Electron stores config/data considered to be "session" dependent, so altering the current user's experience of the app.

**Comment by rudolfs** [comment]
> This depends on if the Electron stores config/data considered to be "session" dependent, so altering the current user's experience of the app.

AFAIK we don't store anything Upstream related in Electron's localstorage. The only thing that comes to mind is if the user has tweaked some developer settings in the developer tools, those would be persisted to disk. Besides that, there's probably some cache and cookies, but I don't see any harm if these are shared across identities.

**Comment by xla** [comment]
> AFAIK we don't store anything Upstream related in Electron's localstorage. The only thing that comes to mind is if the user has tweaked some developer settings in the developer tools, those would be persisted to disk. Besides that, there's probably some cache and cookies, but I don't see any harm if these are shared across identities.

What about the cookie that is set when authenticating?

**Comment by MeBrei** [comment]
> What about the cookie that is set when authenticating?

If the app was stopped before "switching" to a different or no identity, this shouldn't be a problem, as the cookie in electron is not persisted and, once started, the app should automatically show the lock or onboarding screen.

When switching while the app is running, we need to think more, how the app would recognize it and shift to the correct state. Here the cookie could help, ie since the cookie no longer would be set correctly, the session should go back into sealed state., but we should also check if there is still a keystore.

**Comment by MeBrei** [comment]
The support of `RAD_HOME` was introduced in #1527 
The rest of the upstream work is now captured in #1528
