### ISSUE TITLE
Refactor "Register Project"

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#120]
- [x] implement "wallet / transaction" object properly, right now it is implemented via `ProjectRegistration/Row.svelte`
- [x] use extracted avatars consistently across the app

Refs #97

**Comment by rudolfs** [comment]
Blocked by: https://github.com/radicle-dev/radicle-upstream/pull/161

**Comment by MeBrei** [comment]
Already fixed by #123
