### ISSUE TITLE
Network activity indicator is not updated automatically

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1208]
When Upstream is started, the network activity indicator icon is stuck in the "syncing" state indefinitely.
It should reflect the actual connectivity state.

<img width="529" alt="Screenshot 2020-11-09 at 15 21 51" src="https://user-images.githubusercontent.com/158411/98553082-81eefe00-229f-11eb-92aa-47a69ef86527.png">

When refreshing the app manually, it shows the correct state:

<img width="347" alt="Screenshot 2020-11-09 at 15 24 57" src="https://user-images.githubusercontent.com/158411/98553297-c5e20300-229f-11eb-9eca-42eae032d6cd.png">

It seems like a regression somewhere in SSE event handling.

Related to: https://github.com/radicle-dev/radicle-upstream/issues/1191.

**Comment by MeBrei** [comment]
I could not reproduce this, both after creating an identity and restarting and unlocking the app, the correct "connected" state was shown. For me the "syncing" state was actually never shown.

**Comment by xla** [comment]
> I could not reproduce this, both after creating an identity and restarting and unlocking the app, the correct "connected" state was shown. For me the "syncing" state was actually never shown.

Track a project from the seed and/or create one to force the syncing state, it might be related to taht.

**Comment by MeBrei** [comment]
> Track a project from the seed and/or create one to force the syncing state, it might be related to taht.

👍 I was able to reproduce it after creating a new project

**Comment by MeBrei** [comment]
After adding some logs on the proxy and ui end I was able to see, that the subroutines loop sent `StatusChanged` events (as described in #1191 ), but the event listener in `localPeer.ts` never receives any new message after the initial one. In the `EventStream` tab of the `local_peer_events` request, also only the initial data entry is shown.
