### ISSUE TITLE
Untrack selected peer

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1210]
Setup: I have tracked a peer and they appear in my manage remotes modal and peer selector.

1. Select this peer in the project view
2. Open manage remotes and untrack them

The selector will stay on the peer and you will still see their project. The only reason we still see their project is because we do not prune refs in librad (yet, it is implemented in `next`).

Note that the manage remotes modal does correctly update.

When I untrack a peer while I've selected them the view stays on them.

**Comment by xla** [comment]
Ref #1080

**Comment by rudolfs** [comment]
I believe this is just a UI issue, we're not re-fetching the peer list after removing a remote in the "Manage Remotes" modal. Could be done either right away, or when closing the modal.

If you refresh the app after removing a peer, then the peer selector has the correct list of peers.

**Comment by FintanH** [comment]
> adding a remote via the "Manage remotes" modal doesn't update the peer selector automatically after the modal is closed

Well adding a remote doesn't mean you have the peer's code yet anyway.

**Comment by rudolfs** [comment]
> Well adding a remote doesn't mean you have the peer's code yet anyway.

Yea, you're right. I guess this would have to be fixed similar to how we update projects in the waiting area via some sort of SSE event.

**Comment by FintanH** [comment]
Ya, so this is actually a problem I'm working on currently because we need similar behaviour for updating the include file :)
