### ISSUE TITLE
Fix source maps for packaged app

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1214]
It should be easy to debug the packaged app with source maps. However, at the moment source maps don’t work in the packaged app.

**Comment by geigerzaehler** [comment]
This is a known issue (https://github.com/electron/electron/issues/22996). A solution is to [disable asar](https://www.electron.build/configuration/configuration#overridable-per-platform-options) in the electron-builder configuration. While asar is recommended to speed up file loading it’s not needed if we bundle everything.

**Comment by geigerzaehler** [comment]
I’ve tried this and it might be fixed now. Could you confirm @rudolfs?

**Comment by rudolfs** [comment]
Seems to be working.
