### ISSUE TITLE
Following project shows no branches

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1223]
![image](https://user-images.githubusercontent.com/3503528/98827199-7c73ee00-242e-11eb-9f52-6a496dc50b0f.png)

This is likely down to something happening with the stats. Probably the fact that these are remote branches and not local branches in the monorepo.

**Comment by cloudhead** [comment]
Since this is potentially too much to get in for B1, a quick hack that would be acceptable is to either:

1. Show a `?` if the number is zero, or
2. Not show the branch stat for followed projects, or when the number is zero

**Comment by rudolfs** [comment]
I'm gonna go with 2. for now -> #1291.

**Comment by FintanH** [comment]
Is this bug still here? Do we know if it's a wrong call to the daemon or should `radicle-source` be fixed?

**Comment by Kaihuang724** [comment]
Closing this issue as I believe it has been fixed
