### ISSUE TITLE
User Identity document

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1224]
The introduction of identity documents allows us to define an extended payload for a `User`. This means we can put in extra metadata in there that we'd like to persist. The `Identity` type in `api` would become a slimmer version of what it is today. We should audit the fields but these are my initial thoughts on the fields
- `peer_id` will be in the delegates of the `User`, no need to duplicate it
- `urn` - not sure about this one. I doubt it's serialized in the `User` so we may want to add it to the payload
- `shareable_identifier` is dead code afaict so we should remove it
- `handle` is already part of the `User` payload
- `avatar` we add to the `User` payload extension

**Comment by kim** [comment]
There are two suspicious things here:

* It is nonsensical to talk about a user's peer id -- a user identity delegates to _keys_ (plural). While the types `PublicKey` / `PeerId` are isomorphic, it is a misconception to use them interchangeably.
* The `urn` is obtained via the _identity_, not the document -- this distinction is important, because the identity must be verified.

**Comment by FintanH** [comment]
So to give some insight into the data type we're talking about, this is the "user identity" that gets surfaced in the application. So an example of its use is when we are on a project and want to select another peer to look at their version of the project. The selector there will show the `PeerId` and their user handle.

> It is nonsensical to talk about a user's peer id -- a user identity delegates to keys (plural). While the types PublicKey / PeerId are isomorphic, it is a misconception to use them interchangeably.

Good point. So maybe the document payload could be extended with the user's current `PeerId` that's associated with the device they're using.

> The urn is obtained via the identity, not the document -- this distinction is important, because the identity must be verified.

Again, the urn is something we'll want to display to the user so that they could eventually copy-and-paste it for others to replicate their profile.

**Comment by kim** [comment]
I just think the abstraction "User" is not captured precisely at the moment -- you may want to express the notion of a _user of upstream_, but this is not the same as an identity. Specifically, an upstream user may have **zero or more** `radicle-link` identities, which in turn are bound to **one or more** _keypairs_. The _set_ of public keys can be turned into a set of peer ids, which are addressable on the network.

Only the (device-)local user has an unambiguously "current" `PeerId`.

**Comment by FintanH** [comment]
Right, I have some of this outside-in. 

The formalisation should be that there is a device user, which looks something like:
```rust
pub struct Device {
  /// The identifier for the current device
  current: PeerId,
  /// The current profile the user is acting with (includes the Avatar payload)
  profile: Person,
  /// The other profiles the user has set up and can act with
  profiles: Set<Person>,
}
```

**Comment by FintanH** [comment]
Closing this as I don't think it's that relevant anymore.
