### ISSUE TITLE
Project document

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1225]
The introduction of identity documents allows us to define an extended payload for a `Project`. This means we can put in extra metadata in there that we'd like to persist. The `Identity` type in `api` would become a slimmer version of what it is today. We should audit the fields but these are my initial thoughts on the fields:
- A lot of the fields are simply duplicated from the `Project` document in the first place
- One field of interest is the `stats`. We could possibly add this into the payload extension, that we will often update.

**Comment by kim** [comment]
> One field of interest is the stats. We could possibly add this into the payload extension, that we will often update.

It is generally not a smart idea to add volatile data to the identity documents -- every update must be acknowledged by all delegations. These stats in particular are also a very local concept, and should not be replicated.

**Comment by FintanH** [comment]
Ya, I had a niggling feeling it might have been a bad idea. Thanks for setting me straight :+1:

**Comment by FintanH** [comment]
Not relevant anymore. I'm sure the maintainers here will think of future metadata that can be persisted in projects at a later date and link's higher-level API will provide the ability to set/update them :)
