### ISSUE TITLE
Decide where to place coco::seed

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1229]
The `coco::seed` module is free-standing and could live on its own. I think we have two choices:
1. Move it up into the `proxy` workspace
2. Migrate it to the `radicle-link` workspace

Part of this issue is to make an informed decision as to which option is better.

**Comment by xla** [comment]
More so the streaming disco should be contributed back to link.

**Comment by rudolfs** [comment]
@FintanH: is this still relevant after parts of proxy got moved out of upstream?
