### ISSUE TITLE
Move request + waiting room

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1232]
The waiting room logic is free-standing and doesn't depend on any of the other `coco` functionality.

We could move this into a separate `radicle-search` crate either:
1. Top level workspace of `proxy`
2. Top level workspace of `radicle-link`
3. It's own repository

**Comment by FintanH** [comment]
The link half of this work is being PR'd here https://github.com/radicle-dev/radicle-link/pull/515

**Comment by rudolfs** [comment]
@FintanH: is this still relevant after parts of proxy got moved out of upstream?
