### ISSUE TITLE
Move fetch synchronisation

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1233]
Currently, our fetch synchronisation is built into the proxy. I believe this could be easily moved to `radicle-link` in the `fetch` API. This will allow other consumers, like the seed, to also use this logic.

**Comment by FintanH** [comment]
Started in https://github.com/radicle-dev/radicle-link/pull/520

**Comment by rudolfs** [comment]
@FintanH: is this still relevant after parts of proxy got moved out of upstream?
