### ISSUE TITLE
Move announcement logic

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1234]
The announcement logic is not proxy specific and could easily be moved to `radicle-link`. My feeling is that it could go under the `gossip` API, but I'm not 100% sure.

**Comment by FintanH** [comment]
Started in https://github.com/radicle-dev/radicle-link/pull/520

**Comment by rudolfs** [comment]
@FintanH: is this still relevant after parts of proxy got moved out of upstream?
