### ISSUE TITLE
Working copy creation

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1235]
The working copy creation logic living in `proxy` can either live in:
1. `radicle-link` as a top-level workspace
2. Its own `radicle-working-copy` crate

It should be its own crate so that it'll make it easier for working copy creation by other tools other than `radicle-upstream`.

**Comment by FintanH** [comment]
Started the link portion of the work in https://github.com/radicle-dev/radicle-link/pull/507

**Comment by rudolfs** [comment]
@FintanH: is this still relevant after parts of proxy got moved out of upstream?
