### ISSUE TITLE
Distinguish between checkout and fork

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#1239]
Currently, doing a checkout is a public action: it pushes your own refs. If we want to preserve this behavior, we should rename this to "Fork", and have another way of doing a regular checkout. Otherwise, the behavior should be changed so that a checkout is a purely local action, and to "fork", one has to push to `rad`. Regardless, the copy and instructions currently don't match the behavior.

**Comment by FintanH** [comment]
To shed some light on the behaviour:

> Currently, doing a checkout is a public action: it pushes your own refs.

This is so that there are branches when you create the working copy. The branches are the peer's that you "checkout" from. 

> we should rename this to "Fork", and have another way of doing a regular checkout.

Ya, I noticed that @juliendonck became confused for a moment about "checking out" his own project. We allow this, and it means creating another working copy -- even though you might already have one since you created the project.
One thing to also note here is that it's only like a "fork" when we're in the **Following** tab.

**Comment by cloudhead** [comment]
Interesting, so maybe it should be “checkout” when it’s your own project, and when it’s a following project you would get the option to fork it or just create a working copy (checkout)?

**Comment by xla** [comment]
Ref #1244

**Comment by FintanH** [comment]
> and when it’s a following project you would get the option to fork it

What would this entail?

**Comment by cloudhead** [comment]
Fork: create & publish your own project tree from an existing project (others can fetch it)
Checkout: create a working copy on your local disk, from any of the existing (replicated) trees

**Comment by xla** [comment]
> Checkout: create a working copy on your local disk, from any of the existing (replicated) trees (private)

This will open up the challenge of what to do once the user wants to publish the private checkout.

**Comment by cloudhead** [comment]
> This will open up the challenge of what to do once the user wants to publish the private checkout.

`git push rad`?

**Comment by xla** [comment]
> `git push rad`?

What is the setup of that remote?

**Comment by cloudhead** [comment]
> What is the setup of that remote?

Well I'd imagine that the remote is your peer-id, and when you push the first time, it creates the refs etc. Basically the first push would do what the current checkout does.

**Comment by xla** [comment]
> Well I'd imagine that the remote is your peer-id, and when you push the first time, it creates the refs etc. Basically the first push would do what the current checkout does.

Sounds sane, but might require refactoring that logic out of the upstream code and push it closer to the git-remote-helper, not entirely clear how much work that would be, prob. @FintanH and @rudolfs have a better idea.

**Comment by cloudhead** [comment]
Yeah I think it may be tricky, so perhaps for the B1 we just change the copy :shrug:

**Comment by xla** [comment]
> Yeah I think it may be tricky, so perhaps for the B1 we just change the copy shrug

@abbey-titcomb Flagging this for your :eyes:

**Comment by abbey-titcomb** [comment]
Okie, so @cloudhead , you're suggesting we change `Checkout` to `Fork`? 
 
Assuming we'd change the subtext as well? Maybe to something like:

_"Checkout a working copy to your local disk and publish it to Radicle"_
_"Checkout this project to your local disk and publish it to Radicle"_
_"Checkout this project to your local disk and publish it to Radicle"_
_"Checkout this project to your local disk and publish your view to Radicle"_

<img width="419" alt="image" src="https://user-images.githubusercontent.com/18275452/99411942-78474500-28f4-11eb-8f8f-2b824aeeaeb2.png">

Also, where does `clone` come in? 🤔 Is it a better way to describe whats happening here?

Alternatively, if we plan on refactoring to make publishing a private checkout an option, would it make more sense to keep Checkout as it is, and just note that it it's not possible to clone a project without publishing it to the network?

**Comment by FintanH** [comment]
> Also, where does clone come in? thinking Is it a better way to describe whats happening here?

Cloning is basically what's happening under the hood. We clone the copy from the monorepo.

@cloudhead So if I'm understanding correctly you're thinking:
**Fork**: is current behaviour -- you get a working copy and you start off with the `<default>` ref
**Checkout**: the behaviour is that you create a working copy and nothing is pushed yet.

Is that correct? I think one issue of the **Checkout** is that you can't set an upstream branch without pushing it first (I may be wrong on this one), so when the person goes to their working copy they'll have to handle all that themselves. It's doable though.

**Comment by cloudhead** [comment]
> Is that correct? I think one issue of the **Checkout** is that you can't set an upstream branch without pushing it first (I may be wrong on this one), so when the person goes to their working copy they'll have to handle all that themselves. It's doable though.

That's right. However we should really find a way to set the `rad` upstream without pushing. But if we can't do that at first, it's okay, and we can document the steps.

So basically, **Fork = Checkout + Push**

**Comment by cloudhead** [comment]
> _"Checkout a working copy to your local disk and publish it to Radicle"_
> _"Checkout this project to your local disk and publish it to Radicle"_
> _"Checkout this project to your local disk and publish it to Radicle"_
> _"Checkout this project to your local disk and publish your view to Radicle"_

I'd rather something like:
* "Fork this project and create a local checkout"
* "Fork this project and create a local working copy"

**Comment by cloudhead** [comment]
Ok this is a bit more complicated than I thought: the behavior actually depends on whether you already have a fork of the project or not! If so, the button should say `Checkout`, otherwise it should say `Fork`!
