### ISSUE TITLE
Announce Want on track

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1240]
To kick off tracking a peer, we should attempt to send a `Want` to the network.

We could consider doing this periodically for all tracked but not found peers.

**Comment by xla** [comment]
What is the content of the want? We don't know the urn of the peer at that point, So what can we really query the network for?

**Comment by FintanH** [comment]
Sure we do. When we track we have a PeerId _and_ a RadUrn

**Comment by xla** [comment]
We have the RadUrn of the project, but we can't scope our want to get specific data for this peers view. Or am I misisng something?

**Comment by FintanH** [comment]
I _think_ we could do something like ask for:

```rust
RadUrn {
  urn,
  path: "refs/remotes/<peer>/heads/<default>"
}
```

Would that be right @kim?

**Comment by FintanH** [comment]
This is [done in Upstream](https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/coco/src/state.rs#L573)
