### ISSUE TITLE
Wrong default peer

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1243]
During testing we noticed the following:
* A peer had tracked two other peers -- a maintainer and a contributor
* The contributor had the most up to date changes
* The default view was selecting the contributor rather than the maintainer on refreshing

**Comment by xla** [comment]
To add, if the user viewing the project was the original maintainer the default was correct.

**Comment by FintanH** [comment]
Further heuristics to add:

> Initially mentioned here: #1080 (comment)
>
> When we navigate to a project via the maintainer's profile the selected peer won't necessarily be the maintainer themselves. I think that it should be to keep with the continuity of actions.

**Comment by juliendonck** [comment]
Order of default of remote selector: you > maintainer > contributor

**Comment by FintanH** [comment]
I'm wondering if the returned data from the proxy could be made better to start this off. For example, we could have a response type that looks like:

```
struct Peers {
  defaults: NonEmpty<Peer>,
  others: Vec<Peer>,
}
```

In this way, the head of the `defaults` is _the_ default, followed by a list of the other defaults. Then `others` is any other peer, i.e. list of contributors.
