### ISSUE TITLE
Track remote users

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1245]
As discussed in https://github.com/radicle-dev/radicle-link/issues/420 we need to explicitly fetch users if they are not the maintainers. We can do this by inspecting `rad/self` and cloning the URN for that user.

I think the tricky part to this is knowing when to call this clone.

**Comment by rudolfs** [comment]
Is this related to https://github.com/radicle-dev/radicle-upstream/pull/2028?

**Comment by FintanH** [comment]
Ya, I believe #2028 would fix this
