### ISSUE TITLE
Handle all session variants in app gracefully

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1248]
At the moment, the content of the `session` store has three variants: `NoSession`, `SealedSession`, and `UnsealedSession`. The session is made available as context, for example in `ui/DesignSystem/Component/SidebarLayout`. There, however, we tell TypeScript that the session is always `UnsealedSession` which leads to runtime errors when we access properties on the session that are not present, such as `session.identity`.

As far as we know, this issue cannot be triggered by normal user operation.

**Comment by xla** [comment]
Can this be triggered by a user during normal operation?

**Comment by geigerzaehler** [comment]
> Can this be triggered by a user during normal operation?

No. I’ve updated the issue accordingly.

**Comment by geigerzaehler** [comment]
These tests were moved out of the repo in #1753.
