### ISSUE TITLE
Push all branches for existing repository

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1249]
Was playing around with the application and I wonder if we should push all existing branches to the `rad` remote on setup. I believe that's expected behaviour in other VCS hubs. At the moment we only push the default branch.

**Comment by rudolfs** [comment]
Sounds like a good idea.

**Comment by xla** [comment]
Let's do tags as well.

**Comment by rudolfs** [comment]
> Let's do tags as well.

We should not push tags. Tags as a feature are still _experimental_ and disabled in production.

**Comment by FintanH** [comment]
I feel wary about tags too: https://radicle.community/t/git-tags/214

**Comment by cloudhead** [comment]
Was just wondering about this. +1 this should be in the beta.

**Comment by FintanH** [comment]
>  +1 this should be in the beta.

What are you working on @cloudhead? :eyes:

**Comment by xla** [comment]
> Due to the subtly non-standard layout of our remote tracking branches (we keep heads/ so we can fit in rad/), we can actually replicate tags as well

Don't see an issue with pushing tags.

**Comment by FintanH** [comment]
There's plenty of issues laid out in the community post and they're currently not supported by the `radicle-link` protocol. Sure they could be pushed to your local view of the project, but they won't be replicated and only you will be able to see them. That seems like a bad user experience in comparison to fleshing out how we can handle tags in the protocol and propagate the feature into upstream.

**Comment by xla** [comment]
> There's plenty of issues laid out in the community post and they're currently not supported by the `radicle-link` protocol. Sure they could be pushed to your local view of the project, but they won't be replicated and only you will be able to see them. That seems like a bad user experience in comparison to fleshing out how we can handle tags in the protocol and propagate the feature into upstream.

You won't seem them as they are behind a flag, I don't feel strongly about it.

**Comment by rudolfs** [comment]
> You won't seem them as they are behind a flag, I don't feel strongly about it.

Even if you enable them, once if you click on a tag in the UI it leads to an error.
