### ISSUE TITLE
Limited source code syntax highlighting

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1258]
Currently only a limited amount of file extensions seem to be syntax highlighted when browsing source code. Apparent examples missing are common configuration formats often found at the top-level of repositories like: Makefile and TOML.

Files people expected to work:

* Typescript
* TOML
* tsx
* svelte
* solidity

**Comment by juliendonck** [comment]
Don't see why this is beta 1?

**Comment by xla** [comment]
Doesn't need to be, just strange that almost all files typically found on the top-level of a repo are rendered in plain text.

**Comment by juliendonck** [comment]
Yeah it's a nice to have. I guess it hard with a milestone to show what's nice-to-have if there's any time left without making it look like a blocker.

**Comment by xla** [comment]
Moved it to ß2, not a blocker at all. Thanks for the pushback.
