### ISSUE TITLE
Prettier does not wrap long attributes in Svelte files

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#1263]
Prettier should wrap attributes in Svelte files that overflow the max length of `80` automatically were possible or issue a warning. 

How to reproduce:
Adjust the `d` attribute of an `Icon` `path` to be on a single line and try to commit it. There is no change or warning from the pre-commit hook.

**Comment by geigerzaehler** [comment]
[`prettier-plugin-svelte`](https://github.com/sveltejs/prettier-plugin-svelte) does not have an option that controlls this. The fact that this would touch attribute values also makes it likely that this is not sensible. I assume this worked when the SVGs where plain html files.
