### ISSUE TITLE
Research open questions for Release II

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#127]
We gathered open questions we want to expand on in order to outline the work that needs to be done for the next iteration of build and release processs of the application, including upgrades:

* [x] What infrastructure can we expect/use to advertise and distribute new versions?
* [x] How and where do we want to advertise new versions?
* [x] How much of the process do we want to automatise? (ceremonies, signed binaries)
* [ ] How do we handle version changes in the protocols we depend on?

**Comment by xla** [comment]
@abbey-titcomb This one should be very interseting to keep an eye on with regards to community and propaganda.

**Comment by abbey-titcomb** [comment]
👍👍👍

**Comment by rudolfs** [comment]
Here's some answers on these topics I gathered from product (@cloudhead):

- Code signing: we won't do Apple code signing, cause it's against our values, but we should look into Linux AppImage signing

- App updates: spend max 1 day of research on it, look for p2p ways to do it (like query for new tags in a certain repo and then show a notification). Product is looking into how to surface this to the user.

- Releases: it is fine if we do the first releases by hand, and most likely we'll just put it on our website.

**Comment by xla** [comment]
Stale.
