### ISSUE TITLE
Update links to documentation

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#1271]
Once the docs are finished and the website is set up, all links should be updated in the app.
(Extracted from [836#issuecomment-721708446](https://github.com/radicle-dev/radicle-upstream/issues/836#issuecomment-721708446))

<img width="30%" alt="Screenshot 2020-11-04 at 13 28 31" src="https://user-images.githubusercontent.com/158411/98112267-3523b580-1ea2-11eb-97e3-857a0c005b06.png">
<img width="30%" alt="Screenshot 2020-11-04 at 13 28 39" src="https://user-images.githubusercontent.com/158411/98112272-3654e280-1ea2-11eb-94cc-957f326cadaa.png">
<img width="30%" alt="Screenshot 2020-11-04 at 13 28 47" src="https://user-images.githubusercontent.com/158411/98112277-37860f80-1ea2-11eb-84e4-a6446e84f620.png">
(This list might not be complete)

**Comment by abbey-titcomb** [comment]
Okay @MeBrei here are the pages with links on them:

### Settings
`Learn more about managing devices` -> https://docs.radicle.xyz/docs/understanding-radicle/faq

`Learn more about seeds` -> https://docs.radicle.xyz/docs/using-radicle/running-a-seed-node

`Get in touch directly` -> ✅

Change `#radicle on freenode` to `matrix.radicle.community` -> https://matrix.radicle.community/

^ can you also change `Join the developer chat` to `Join the community chat` as well?

### Start a new project Modal

To publish code to Radicle, you need to add this to your shell configuration file. Not sure how? `Read more` -> https://docs.radicle.xyz/docs/getting-started/getting-started#configuring-your-system

### Checkout Modal

To publish code to Radicle.... `Read more` -> https://docs.radicle.xyz/docs/getting-started/getting-started#configuring-your-system

I think this should be it....
