### ISSUE TITLE
Commits view pagination

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#1274]
When loading the commits view of a big project, things can be a bit slow, due to it loading the full history. It would be nice to only load the first 100 or so commits and have a "load more" button or something to load another 100 commits.

**Comment by xla** [comment]
Additionally when switching to the commits tab, it's slow to render with long histories.

**Comment by NunoAlexandre** [comment]
@juliendonck we don't have a design for this, do we? Can't find it on Figma :detective:

**Comment by cloudhead** [comment]
Don't think we do.. We can start building something with a simple "Click to load more" button at the end though, then jules can style it :shrug:

**Comment by xla** [comment]
Flagging that this likely need support all the way down in radicle-surf to be effective.
