### ISSUE TITLE
No scrollbars in project view

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#1275]
There are no scrollbars on the project page (and perhaps in other places). Looks like a regression of #762 

* EDIT: There are also no scrollbars in the branch selector, which means some branches get hidden.

**Comment by xla** [comment]
Is this for the code/file view only, or do you imagine scrollbars in other places as well?

**Comment by cloudhead** [comment]
I think everywhere where you have scrollable content should have scrollbars.

**Comment by xla** [comment]
On this note it is odd that the tree and the file scroll together, this will have the tree go out of the viewport when scrolling down a longer file. This makes it harder to navigate, as one has to scroll up again to do so.

**Comment by cloudhead** [comment]
Why did you remove bug? It's a regression.

**Comment by xla** [comment]
Bug should be reserved for high priority things that break the ux.

**Comment by juliendonck** [comment]
It's not a regression. We removed the scrollbars cause it created this weird tiny horizontal scroll. It's been like that for 3 months or something

**Comment by cloudhead** [comment]
> It's not a regression. We removed the scrollbars cause it created this weird tiny horizontal scroll. It's been like that for 3 months or something

:/
