### ISSUE TITLE
Independent dev environment

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#1276]
To be able to develop features independently after the launch, we should be able to switch between production and dev environment not only from a ui perspective. Projects & Identities created solely for testing purposes should not be directly sent to the production seed node, especially when working on changes of the data structure etc. 

Part of the solution might be #1199

**Comment by cloudhead** [comment]
I think #1199 is indeed a nice solution for this.

**Comment by rudolfs** [comment]
Now that we'll be able to easily separate identities with: https://github.com/radicle-dev/radicle-upstream/pull/1489, the only thing that keeps us from having an isolated dev setup is Upstream pointing to our production seed node by default.

We could solve this by:
  - adding a new CLI option to proxy: `--default-seed` which overrides the hardcoded [default](https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/api/src/session/settings.rs#L64)
  - adjust the dev scripts in `package.json` (`yarn start*`) to pass a different development seed node via `--default-seed`
  - spin up an alternative seed node only for dev purposes and assign it a different dns entry, like `

**Comment by rudolfs** [comment]
We now have everything together:
 - separate seed nodes for dev and prod
 - Upstream in dev mode uses `sandbox/rad_home` as the default storage location.
