### ISSUE TITLE
Following a project does not update the “Following” tab

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1279]
Following a project does not always update the “following” tab on a user’s profile. The followed project should be added to the list displayed in the “following” tab after a user has clicked the “follow” button.

I believe the problem is reliably reproducible if the proxy is not connected to any peer. This can be simulated with the `--test` flag. To reproduce this issue take a look at the cypress tests for following which include a reload that forces the update which should happen automatically.

**Comment by xla** [comment]
Could you expand on what is not updated? Does it not add the searched for project to the list of projects that it's looking for?

**Comment by FintanH** [comment]
I couldn't reproduce after removing the seed from my listing -- so I'm not connected. I followed a project and it shows up in "Still looking..."
