### ISSUE TITLE
Removing a seed does not automatically disconnect from it

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1283]
- If a seed is removed from settings, the peer is still connected to it.
The connection is only closed when we restart the app.

  ![no-disconnect-on-remove](https://user-images.githubusercontent.com/158411/99659271-e90b7000-2a60-11eb-8edd-06fccbc74cca.gif)

- Removing the last seed from settings, leaves us still connected. I expected the networking icon to show that we are disconnected.
  ![last-peer](https://user-images.githubusercontent.com/158411/99659530-456e8f80-2a61-11eb-9b66-9a2d94f27021.gif)

**Comment by cloudhead** [comment]
I think we chatted about this and decided to leave it as-is, but I agree this behavior makes more sense.

**Comment by xla** [comment]
As this is a discovery concern we need to look towrads link and its behaviour. The proxy does not handle connections directly. A follow-up after ß1 is to move more of the coco code into the protocol. One of these is to contribute back the streaming discovery, in that context we should evaluate how the protocol stack reacts to removals.

**Comment by rudolfs** [comment]
Closing this, because radicle-link doesn't give us control over connections to other peers in the network.
