### ISSUE TITLE
Screens missing bottom margin

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1285]
- In the project source view long files don't have a bottom margin when the view is scrolled all the way down.
  <img width="80%" alt="Screenshot 2020-11-19 at 14 49 28" src="https://user-images.githubusercontent.com/158411/99674644-a2287500-2a76-11eb-84bb-85b702ead64f.png">

- Settings screen.
  <img width="80%" alt="Screenshot 2020-11-19 at 15 21 53" src="https://user-images.githubusercontent.com/158411/99678432-17964480-2a7b-11eb-87af-4f11ce6e19d1.png">

**Comment by juliendonck** [comment]
single commit page is another one that has no bottom margin.

<img width="1440" alt="Screenshot 2021-01-20 at 15 41 44" src="https://user-images.githubusercontent.com/2326909/105232327-3c1fa300-5b36-11eb-8802-5f2592416212.png">
