### ISSUE TITLE
Collaboration features/modules

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#129]
In the upcoming cycle we will implement the first collaboration features associated with a project (i.e. issues, changesets). This will help people to truly start working together on their repos. Before we can start getting in the thick of things and dive head first into implementation we need to figure a good deal of things.

* [ ] How extendable should projects be?
* [ ] How can per project configuration look like for attached features? (Think github Settings -> Options -> Features)
* [ ] How pluggable should features be?
* [ ] How can we guarantee isolation/sandboxing?
* [ ] What kind of mechanisms do we provide for cross-referencing/linking to enable richer semantic webbing between entities?

**Comment by garbados** [comment]
What does it mean for a project to be "extendable"?

**Comment by xla** [comment]
@garbados As mentioned in the bullet point, think of adding new functionality to the proejct, like wikis, isssues, etc.

**Comment by xla** [comment]
Not relevant at this point, will be looked at in the context of issues and revisiosn.
