### ISSUE TITLE
Fix tooltips on sidenav indicators

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1296]
The hover area for the sidenav items should show the tooltip any time the indicator is shown. See below that the indicator (the line to the left) is activated but the tooltip is not shown. (The tooltip is currently only shown on hover of the bounds of the icon.)

![image](https://user-images.githubusercontent.com/4406983/99795836-ba5acb80-2b2c-11eb-972b-73ac68972413.png)

**Comment by geigerzaehler** [comment]
In addition the clickable area (red) for the settings and profile icon are smaller than the hover and cursor pointer area (green).
![sidebar](https://user-images.githubusercontent.com/3919579/99797898-5cc87e00-2b30-11eb-8d89-f77b4efc3a1c.png)

**Comment by rudolfs** [comment]
Seems like this got fixed in #1387.

![fixed](https://user-images.githubusercontent.com/158411/100746845-8cee0780-33e1-11eb-9da8-170b260918b4.gif)
