### ISSUE TITLE
General repo structure

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#130]
Currently we face the situation that a lot of the repo-level commands and infrastructure is inside of `app`, which is a bit non-problematic in itself as the entirety of the repository produces an application. Factually we have three main concenrs:

* container/wrapper/shell - the shell around our components to provide a native application
* ui - the interface/experience exposed to users of the application
* proxy - the API provder/data access layer for the ui

So we should find out:

* [ ] How to utilise the top-level to host all relevant information and code to ship and develop the application?
* [ ] What directory structure makes most sense?
* [ ] Do we learn/improve anything for separation of concerns?

**Comment by rudolfs** [comment]
I propose to pull whatever is in `app` to the top level, like so:
```
radicle-upstream-back » tree -a -L 1
.
├── .buildkite
├── .git
├── .gitignore
├── .gitmodules
├── CHANGELOG.md
├── DEVELOPMENT.md
├── LICENSE
├── README.md
├── cypress
├── cypress.json
├── dist
├── fixtures
├── graphiql
├── native
├── node_modules
├── package.json
├── proxy
├── public
├── rollup.app.js
├── rollup.config.js
├── rollup.electron.js
├── scripts
├── src
├── tokens
└── yarn.lock
```

Here's a couple of thoughts on why:
  - `app` is the only consumer of `proxy`
  - final binary packages are generated with electron builder which lives in `app`
  - release automation happens via `app`
  - automatic pre-commit linting happens via `app`
  - it is a common convention amongst js/electron apps to have `package.json` and the rest of the UI at the top-level:
    - https://github.com/Microsoft/vscode/
    - https://github.com/ssbc/patchwork
    - https://github.com/webtorrent/webtorrent

**Comment by xla** [comment]
@rudolfs Coming more and more to terms with this approach. Could you expand how the file structure would loo like under `ui`?

**Comment by rudolfs** [comment]
@xla it would stay exactly as it is now:
```
app/src
.
├── App.svelte
├── DesignSystem
│   ├── Components
│   └── Primitives
├── Screens
│   ├── CreateProject.svelte
│   ├── DesignSystemGuide
│   ├── DesignSystemGuide.svelte
│   ├── Feed.svelte
│   ├── Help.svelte
│   ├── NotFound.svelte
│   ├── Profile.svelte
│   ├── Project
│   ├── Project.svelte
│   ├── Projects.svelte
│   ├── RegisterProject
│   ├── RegisterProject.svelte
│   ├── Search.svelte
│   └── Wallet.svelte
├── config.js
├── index.js
├── lib
│   ├── hash.js
│   ├── path.js
│   └── types.js
└── stores
    ├── notification.js
    ├── project.js
    └── sourceBrowser.js
```
