### ISSUE TITLE
Sign macOS release binaries

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1306]
**Why?**

Gatekeeper on macOS prevents users from running unsigned binaries that are downloaded from the internet.

Even though there is a workaround [[1], [7]] where the user has to click through some security warnings allowing to open the app, this leads to a bad user experience. This only works x86 binaries under macOS Big Sur, if we start building our app for the native arm (Apple silicon) architecture, then code signing is mandatory.

**What needs to be done**
- [x] [Enrol][4] our company account apple ID in the Apple dev program (according to [some][2] [sources][3] this can take **2 - 4 weeks**).
- [x] Generate signing certificates.
- [x] [Set up electron builder][5] to sign the macOS binary with our certificates.
  - [x] set up `proxy` and `git-remote-rad` binary signing
    > Enable code-signing for all of the executables you distribute, and ensure that executables have valid code signatures, as described in Ensure a Valid Code Signature. [Link](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution#3087727).
- [x] Do a release and sign the binary.
- [x] [Notarise the binary with Apple][6].
- [x] Figure out a new storage location, because signing won't happen on CI and the signed binary won't be uploaded to buildkite.
- [x] Upload the binary there, so we can link to it in our website downloads section.

**Open questions**

- ~~can we even sign rust binaries?~~ -> electron-builder takes care of everything
- ~~what will the release procedure look like, now that we have to sign the binaries manually?~~ -> we do it manually for macOS

[1]: https://lapcatsoftware.com/articles/unsigned.html
[2]: https://developer.apple.com/forums/thread/31202
[3]: https://support.guidebook.com/hc/en-us/articles/360000228487-Creating-an-Apple-Developer-Account
[4]: https://developer.apple.com/programs/enroll/
[5]: https://www.electron.build/configuration/mac
[6]: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution
[7]: https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

**Comment by abbey-titcomb** [comment]
Great, thanks for the write up. I believe we should move ahead with the sign-up since it's the biggest time constraint on the whole process, then start working on everything else post-Beta release.
