### ISSUE TITLE
Set up Apple Silicon CI target

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1308]
To extened supported plaforms to the lately released apple devices, we need a CI target running the test suit on M1 and later chips, similar to how we run master on x86 macos. 

Ref. #1287

**Comment by jenkijo** [comment]
Hello

I've fork and build from source with Apple Silicon chip, everything work fine. As I know, electron is take care everything for build app. So how can I contribute my build to main repo

![](https://i.imgur.com/xusYBN9.png)

**Comment by juliendonck** [comment]
@rudolfs aren't we doing this? Or is it just that you are doing this cause you do QA on your M1 machine

**Comment by rudolfs** [comment]
No, we don't have a native M1 build host yet. We build intel binaries only, we should invest some time getting this to work. There's potentially good performance improvements related to this.
