### ISSUE TITLE
Husky hook to prevent skipped tests from being committed

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#131]
https://github.com/radicle-dev/radicle-upstream/pull/122#discussion_r375872932

**Comment by znarf** [comment]
Whhen using mocha for tests, there is an eslint rule to detect skipped tests: https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md It should be possible to add a similar rule to the cypress eslint plugin https://github.com/cypress-io/eslint-plugin-cypress

Also, developers are sometimes annoyed by pre-commit hooks (they can be slow and the configuration is not always reliable), so maybe it's best to stick to a simple CI check.

**Comment by rudolfs** [comment]
@znarf this seems like the way to go. They even had a PR for this: https://github.com/cypress-io/eslint-plugin-cypress/pull/25. I wonder why there was no follow up after it got closed.
