### ISSUE TITLE
Missing padding at the end of settings

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1317]
There should be 4rem of padding at the end of the Settings. Right now there is none.

![image](https://user-images.githubusercontent.com/4406983/99983033-a83a9080-2dab-11eb-8741-6d8a13e3246b.png)

**Comment by xla** [comment]
@brandonhaslegs What are the window dimensions of this screenshot, I don't see the issue you have on latest master.

**Comment by brandonhaslegs** [comment]
It's at every viewport size on the latest master on MacOS. 

![no padding at every viewport](https://user-images.githubusercontent.com/4406983/99984738-c0abaa80-2dad-11eb-8bfc-564c8ebb99f9.gif)

Sorry for the 🥔 quality.

**Comment by xla** [comment]
Addressed in #1318
