### ISSUE TITLE
Make "copied" notifications more specific

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1321]
![image](https://user-images.githubusercontent.com/4406983/100091797-69f9ab80-2e55-11eb-9f52-951ed2a40fa1.png)

---

![image](https://user-images.githubusercontent.com/4406983/100091870-84338980-2e55-11eb-833f-c947fd7ba3a8.png)

## Profile
Especially since we don't ever say explicitly on the profile that this is your Device ID (we just show the device icon), we could note in the notification that you've in fact copied your Device ID.

Suggestion: `Device ID copied to your clipboard`

---

![image](https://user-images.githubusercontent.com/4406983/100091770-5a7a6280-2e55-11eb-8e62-6740dd09d275.png)

## Project
Also need to add it here then too, when you copy a Radicle ID.

Suggestion: `Radicle ID copied to your clipboard`

**Comment by rudolfs** [comment]
I believe this was solved by https://github.com/radicle-dev/radicle-upstream/pull/2274. Re-open the issue if not.

**Comment by brandonhaslegs** [comment]
For the most part yes!

![image](https://user-images.githubusercontent.com/4406983/132457235-114c061b-4041-43dd-b419-349e25abd1fb.png)

this one should say "Radicle ID"

---

![image](https://user-images.githubusercontent.com/4406983/132457350-4d1f9b5d-ff0a-4e06-9af4-099b7f4f92fd.png)

This one should say "command"

---

![image](https://user-images.githubusercontent.com/4406983/132457403-e17677f9-d932-443d-becb-3d8dc3ef0a58.png)

Should say "command"
