### ISSUE TITLE
Remove `⌘ + V` from input fields & search bar

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-upstream#1322]
It was raised in #1313 that the tooltip for copy paste hotkey is unnecessary and might make the user believe they *have* to copy-paste. Let's remove it since it's not adding anything specific.

We can add it back in if we have it only appear if something is copied to user's clipboard.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/18275452/100082456-29dbfe00-2e40-11eb-9a4d-d1254738efd9.png">

Appears in `Manage Remotes`, `Search`, and `Settings`

**Comment by rudolfs** [comment]
> We can add it back in if we have it only appear if something is copied to user's clipboard.

This would require Upstream to "sniff" the user's clipboard periodically without the user explicitly interacting with the clipboard. Not sure it's a good idea for privacy reasons.

**Comment by cloudhead** [comment]
Yeah I agree it's not good practice. I'd be in favor of just removing it.
