### ISSUE TITLE
Integration test strategy

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#133]
At the moment most of our e2e tests are skipped due to recent changes to proxy. We have to figure out how we want to do e2e tests in the future, so we can fix our test suite.

**Comment by xla** [comment]
To avoid just pachtworking the current situation we met and briefly layed out a strategy to enable the ui test suite(s) to control their test environment.

For that we, when started with some `test` flag, will spin up a second API endpoint on the proxy which gives more raw access/control of the proxy state. The functionality exposed can/might look like:

* [ ] create project with given metadata and point at specific repo (e..g. `git-platinum`)
* [ ] reset/nuke CoCo state
* [ ] reset/nuke Registry state
* [ ] declare remote peer and its state
* [ ] modify remote peer state/behaviour

**Comment by rudolfs** [comment]
Next steps for this issue, once #159 is completed and merged:

  - integrate the test API in our cypress test-suite
  - recover all skipped tests
```
cypress/integration/navigation.spec.js
130:      it.skip("stays fixed at the top", () => {

cypress/integration/source_browsing.spec.js
10:      it.skip("shows timeframe in hours", () => {
18:      it.skip("shows timeframe in days", () => {
26:      it.skip("shows timeframe in days", () => {
34:      it.skip("shows timeframe in weeks", () => {
42:      it.skip("shows timeframe in weeks", () => {
51:    it.skip("expands a tree starting at the root of the repo", () => {
58:    it.skip("shows contents of the root folder for the latest revision", () => {
88:      it.skip("allows switching to a different branch", () => {
95:      it.skip("allows switching to a different tag", () => {
104:      it.skip("allows diving deep into directory structures", () => {
120:      it.skip("shows the file contents", () => {
135:    it.skip("shows files and directories", () => {
149:      it.skip("allows diving deep into directory structures", () => {
169:      it.skip("shows the contents of the directory", () => {
187:        it.skip("shows the contents of the file", () => {
209:        it.skip("does not render the binary content", () => {
```
  - find a workaround for #145, as it seems like it's not moving forward
  - finish #146 based on the workaround
