### ISSUE TITLE
Make error more clear when user has already added the seed

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1331]
Suggestion:
`You are already connected to this seed.`

![image](https://user-images.githubusercontent.com/4406983/100106907-62dc9880-2e69-11eb-9128-11927f0bfd2f.png)

**Comment by xla** [comment]
> You are already connected to this seed

This is only true, if you are online and have a working connection to the seed.

**Comment by rudolfs** [comment]
We don't have this screen anymore.
