### ISSUE TITLE
Allow specifying version in release script

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1334]
At the moment we are not using the breaking change convention according to the [Conventional Commits spec](https://www.conventionalcommits.org/en/v1.0.0/). That is, we don't mark breaking changes with a `!` when merging commits into master, because we prefer to manage the version numbers manually during release. This results in releases being incremented only by a patch version number, i.e. the `0.0.X` part.

It is currently not possible to pass down additional parameters to the `standard-version` command when cutting a release via `yarn release`. As a workaround, whenever we need to bump a minor or major version, I patch the `release.js` file  as outlined in [this comment](https://github.com/radicle-dev/radicle-upstream/issues/1312#issuecomment-732174429).

We should add a way to pass the version number to `yarn release` as either a parameter or an environment variable and document it in [DEVELOPMENT.md](https://github.com/radicle-dev/radicle-upstream/blob/master/DEVELOPMENT.md#preparing-a-release).

**Comment by geigerzaehler** [comment]
@rudolfs: Can you provide more details on what needs to be done and why?

**Comment by rudolfs** [comment]
@geigerzaehler updated the issue description. Is it clearer now what needs to be done?
