### ISSUE TITLE
External links are not consistent

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1338]
Refs: https://github.com/radicle-dev/radicle-upstream/issues/1335.

- [ ] on the BSOD screen, the `Reach out for support` button link is dead -> https://radicle.community/c/support/13
- [ ] `Settings` -> `Learn more about managing devices` -> https://docs.radicle.xyz/docs/understanding-radicle/faq
    **is this the correct link?**
- [ ] `Settings` -> `Learn more about seeds` -> https://docs.radicle.xyz/docs/understanding-radicle/glossary#seed
    **the anchor doesn't exist**

**Comment by abbey-titcomb** [comment]
Here's the correct links:

> Refs: #1335.
> 
>     * [ ]  on the BSOD screen, the `Reach out for support` button link is dead -> https://radicle.community/c/support/13

https://radicle.community/c/help

>     * [ ]  `Settings` -> `Learn more about managing devices` -> https://docs.radicle.xyz/docs/understanding-radicle/faq

https://docs.radicle.xyz/docs/understanding-radicle/faq#can-i-use-radicle-with-multiple-devices

>     * [ ]  `Settings` -> `Learn more about seeds` -> https://docs.radicle.xyz/docs/understanding-radicle/glossary#seed
>       **the anchor doesn't exist**

It will soon! Pushing the change now.
