### ISSUE TITLE
Linux AppImage not executable

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1339]
When downloading the `0.1.0` binary it lacks the executable flag:

```
-rw-r--r-- 1 xla xla  93M Nov 24 19:09  radicle-upstream-0.1.0.AppImage
```

Ref. #1336

**Comment by geigerzaehler** [comment]
I don’t think there’s anything we can do about this. How the download is written to disk is controlled by the browser and as far as I know HTTP does no allow us to convey that the file should be executable.

**Comment by rudolfs** [comment]
Perhaps it's enough to fix up the QA docs to mention doing a `chmod +x ...` after the download:
`on Linux: just run /<PATH_TO_DOWNLOAD>/radicle-upstream-X.X.X.AppImage` -> https://github.com/radicle-dev/radicle-upstream/issues/1345.

**Comment by xla** [comment]
> I don’t think there’s anything we can do about this. How the download is written to disk is controlled by the browser and as far as I know HTTP does no allow us to convey that the file should be executable.

Guess the only remedy for that is to put it in an archive like zip.

**Comment by geigerzaehler** [comment]
> > I don’t think there’s anything we can do about this. How the download is written to disk is controlled by the browser and as far as I know HTTP does no allow us to convey that the file should be executable.
> 
> Guess the only remedy for that is to put it in an archive like zip.

Seem to be more effort and would require an extra step to unpack. Also keep in mind that this is an app for developers. I’m pretty sure they will be able to deal with this.

**Comment by xla** [comment]
> Seem to be more effort and would require an extra step to unpack. Also keep in mind that this is an app for developers. I’m pretty sure they will be able to deal with this.

Not arguing to do that, just context to what we can do if we care about it.

**Comment by geigerzaehler** [comment]
This is already documented on `docs.radicle.xyz`: https://github.com/radicle-dev/radicle-docs/pull/26/files#diff-649b2d3ef0f2bb0bc9ba8ea8fe05493a20be64b3e26f302b84f9be36cbbde5b6R60

I think we can close this issue

**Comment by xla** [comment]
It will be closed with the attached PR. :>
