### ISSUE TITLE
On linux open folder opens a browser tab

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1344]
After doing a checkout in the app and pressing the open folder action in the notification it opens up a tab in the browser.

![2020-11-24-194011_1278x1408_scrot](https://user-images.githubusercontent.com/1585/100137586-f83d5400-2e8c-11eb-9341-a23406a90445.png)

Ref #1336

**Comment by geigerzaehler** [comment]
For me, the same interaction opens the folder in my file browser (KDE’s Dolphin). This might be an issue the desktop environment configuration.Can you check what `xdg-open <SOME_FOLDER>` does?

**Comment by xla** [comment]
> For me, the same interaction opens the folder in my file browser (KDE’s Dolphin). This might be an issue the desktop environment configuration.Can you check what `xdg-open <SOME_FOLDER>` does?

It does the same, guess it's my xdg registry that is not set up correctly. Thanks for looking into it.
