### ISSUE TITLE
Improve QA documentation

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1345]
**Fixups**:
- ~~when QA instructions are copied to issue, the "this script" link breaks~~
- ~~After passphrase input the identity is created and a copyable URN is
provided  -- should be Device ID instead of URN~~
- ~~test that " " is replaced with "-" in onboarding and project creation~~
- ~~current QA still mentions `radicle-upstream` as password~~
- ~~remove the section about dancing round Apple Gatekeeper, our package is signed now~~
- ~~"Peer entries" -> "Network -> seeds"~~

**Add new sections**:
  - ~~replicate a project from seed~~
    - ~~checkout~~
    - ~~add changes~~
    - ~~publish changes~~
    - ~~add other remotes~~
    - pull changes from a different remote
  - peer selector
  - ~~network indicator~~
  - ~~search~~
    - ~~follow a project~~
    - ~~waiting area~~

**Comment by NunoAlexandre** [comment]
we also miss having a setup git as a pre-requisite. I failed to create a repo because:

```
{
  "code": "ProjectCreationFailure",
  "message": "Could not create project: the author name for creating the project could not be found - have you configured your git config?",
  "source": {
    "response": {}
  }
}
```
