### ISSUE TITLE
Can't create a repo and can't load it

### ISSUE THREAD

**Issue by Tbaut** [radicle-dev/radicle-upstream#1348]
Hi there,
I've been building and launching upstream 0.1 (master as of writing) and I can't manage to create a repo.
I get an error when creating it, or when I relaunch the app:
> {"code": "ProjectRequestFailure","message": "The project hello-radicle could not be loaded","details": {"type": "defaultBranch","urn": "rad:git:hwd1yreyasxuhk6d3dwai5r6wb5tngw7rj443m73htq4zyxpbu8u8uerq3w","shareableEntityIdentifier": "%rad:git:hwd1yreyasxuhk6d3dwai5r6wb5tngw7rj443m73htq4zyxpbu8u8uerq3w","metadata": {"name": "hello-radicle","description": "a first project","defaultBranch": "main","maintainers": ["rad:git:hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc"]},"stats": null}}

The console prints:
>  we could not find a default branch for REPO_NAME

Here is what I did:
```
$ yarn
$ export PATH="$HOME/.radicle/bin:$PATH"
$ yarn start
```

- created an identity
- created a new folder
- select it
- try to create a new repo in there
- --> get the error

I've tried a couple times, also with a repo name that I believe is unique.
[Here is the full terminal log](https://gist.github.com/Tbaut/78b0f87c40aa50e653ec475158c49191)

**Comment by rudolfs** [comment]
Hey Thibaut,

Did you try out Upstream before perhaps, is there any old data laying around by any chance?

Could you perhaps do this in the repository that was created:
```
git branch -a
git remove -v
```

Also a `tree /home/thib/.config/radicle/` would be helpful for debugging this.

Thanks!

**Comment by Tbaut** [comment]
I don't recall having built and launched Upstream before.

I had 3 repos:
- `hello-radicle/hello-radicle`
- `hello-radicle/hello-radicle-2`
- `radic/thibaut/radicle`

None of them have branches when doing `git branch -a`.
`git remote -v` doesn't print anything.

An additional info in case it helps, the .git/config look like this on all 3 repo:

```
$ cat hello-radicle/hello-radicle/.git/config 
[core]
	bare = false
	repositoryformatversion = 0
	filemode = true
	logallrefupdates = true
```
Also what you asked:
```bash
$ tree /home/thib/.config/radicle/                                           
/home/thib/.config/radicle/
├── git-includes
│   ├── hwd1yredhofab7czds8hw9gbmuf37t93imeupsxx5tn9r5cqh4t4tbgi4zh.inc
│   ├── hwd1yrenrimg8oz6eqm9yw4qwsgejafuad9uggfpd8mykfkztbgr4ap7hia.inc
│   └── hwd1yreyasxuhk6d3dwai5r6wb5tngw7rj443m73htq4zyxpbu8u8uerq3w.inc
└── keys
    └── librad.key
```

**Comment by FintanH** [comment]
One last thing to check is `tree ~/.local/share/radicle/git/refs`, the output there would be helpful. And even better would be to output some metadata from one of the projects. To do this you should do the following:
```
$ cd ~/.local/share/radicle/git
$ git ls-tree refs/namespaces/<project id>/refs/rad/id
```

Where `<project id>` is `hwd1yreyasxuhk6d3dwai5r6wb5tngw7rj443m73htq4zyxpbu8u8uerq3w` for example. This should output something like:

```
100644 blob 92759b7dd3103435172a2b2703cc2aa2343bb6df    id
```

Taking the SHA after `blob` you should run:

```
git cat-file -p 92759b7dd3103435172a2b2703cc2aa2343bb6df
```

which will output some metadata that looks like:

```
{"certifiers":["rad:git:hwd1yreytz7zgzjcnwjpq64rmjqi7g1hjg6mcmzij35byzgzsy64wp5887r"],"hash":"hwd1yrer9woq9s77cpo9m6hdw4pnqc84wj1dqikd89eutko1xfqgkjr93na","info":{"default_branch":"master","description":"","project":null},"keys":["hynppkigso6bg4t4g3ugojt3fhrh8thax5q7cr4dkp4j6usdujybng"],"name":"git-platinum","rad_version":2,"revision":1,"root_hash":"hwd1yreyr5y7rohy8ofz3ywos7cxy9kjk3jftbt8hejicmkbf8ktxekrmwo","signatures":{"hynppkigso6bg4t4g3ugojt3fhrh8thax5q7cr4dkp4j6usdujybng":{"sig":"wC5HZZxZ9wEkWdptRBZ1JxDgAv6yLy7GEEaoMcXkBs61dtqaJM43RoHyEGPNhhMRdgEXX1zS4GAekxMvHhTHH64","user":"rad:git:hwd1yreytz7zgzjcnwjpq64rmjqi7g1hjg6mcmzij35byzgzsy64wp5887r"}}}
```

Let us know what the `tree` output is and the metadata output, and that should hopefully shed some light on the situation :seedling:

**Comment by rudolfs** [comment]
Last but not least:
  - what OS are you running and
  - what's your Git version (`git --version`)?

**Comment by Tbaut** [comment]
Here we go

```bash
$ tree ~/.local/share/radicle/git/refs
/home/thib/.local/share/radicle/git/refs
├── heads
├── namespaces
│   ├── hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc
│   │   └── refs
│   │       └── rad
│   │           ├── id
│   │           ├── self
│   │           └── signed_refs
│   ├── hwd1yredhofab7czds8hw9gbmuf37t93imeupsxx5tn9r5cqh4t4tbgi4zh
│   │   └── refs
│   │       └── rad
│   │           ├── id
│   │           ├── ids
│   │           │   └── hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc
│   │           ├── self
│   │           └── signed_refs
│   ├── hwd1yrenrimg8oz6eqm9yw4qwsgejafuad9uggfpd8mykfkztbgr4ap7hia
│   │   └── refs
│   │       └── rad
│   │           ├── id
│   │           ├── ids
│   │           │   └── hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc
│   │           ├── self
│   │           └── signed_refs
│   └── hwd1yreyasxuhk6d3dwai5r6wb5tngw7rj443m73htq4zyxpbu8u8uerq3w
│       └── refs
│           └── rad
│               ├── id
│               ├── ids
│               │   └── hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc
│               ├── self
│               └── signed_refs
└── tags
```

```bash
$ git ls-tree refs/namespaces/hwd1yreyasxuhk6d3dwai5r6wb5tngw7rj443m73htq4zyxpbu8u8uerq3w/refs/rad/id  
100644 blob 196ba74cfe5ea9fecc17f8c315f1b616c546341b	id
$ git ls-tree refs/namespaces/hwd1yrenrimg8oz6eqm9yw4qwsgejafuad9uggfpd8mykfkztbgr4ap7hia/refs/rad/id
100644 blob 3ca232dfd510c3c515fc42d65832678cb849b0dc	id
$ git ls-tree refs/namespaces/hwd1yredhofab7czds8hw9gbmuf37t93imeupsxx5tn9r5cqh4t4tbgi4zh/refs/rad/id
100644 blob ab6c4937b9b8b17891b3c1dcf27d59e7b1045434	id
$ git ls-tree refs/namespaces/hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc/refs/rad/id
100644 blob 6f89e374ce5d4635fd1eefbd5b40d8ae586e8fc6	id
```

```bash
$ git cat-file -p 196ba74cfe5ea9fecc17f8c315f1b616c546341b | jq; \
git cat-file -p 3ca232dfd510c3c515fc42d65832678cb849b0dc | jq; \
git cat-file -p ab6c4937b9b8b17891b3c1dcf27d59e7b1045434 | jq; \
git cat-file -p 6f89e374ce5d4635fd1eefbd5b40d8ae586e8fc6 | jq;

{
  "certifiers": [
    "rad:git:hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc"
  ],
  "hash": "hwd1yre8x9dmh1qfia3yt7ofkkrmi8c4a1is4spjhyz1ni6rxwu1w4wnude",
  "info": {
    "default_branch": "main",
    "description": "a first project",
    "project": null
  },
  "keys": [
    "hybx51sxkf3rr4s9r5thbid8u38j95ejm7a6nkbxxtx9fixxp14hnn"
  ],
  "name": "hello-radicle",
  "rad_version": 2,
  "revision": 1,
  "root_hash": "hwd1yreyasxuhk6d3dwai5r6wb5tngw7rj443m73htq4zyxpbu8u8uerq3w",
  "signatures": {
    "hybx51sxkf3rr4s9r5thbid8u38j95ejm7a6nkbxxtx9fixxp14hnn": {
      "sig": "jXsAYRrdY6KMepnSWS6gCJiZp5EidUcuHkFhTyVgZjVTXfJ9NmjPKjSG1UHL8c2ubhUtux63r8EPJLzCK9bkydn",
      "user": "rad:git:hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc"
    }
  }
}
{
  "certifiers": [
    "rad:git:hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc"
  ],
  "hash": "hwd1yregbhgxgqabg4tnmy4ps8e5jhsd13d1p58nse1ed4q41frrwf5yghy",
  "info": {
    "default_branch": "main",
    "description": "a new name",
    "project": null
  },
  "keys": [
    "hybx51sxkf3rr4s9r5thbid8u38j95ejm7a6nkbxxtx9fixxp14hnn"
  ],
  "name": "thibaut-radicle",
  "rad_version": 2,
  "revision": 1,
  "root_hash": "hwd1yrenrimg8oz6eqm9yw4qwsgejafuad9uggfpd8mykfkztbgr4ap7hia",
  "signatures": {
    "hybx51sxkf3rr4s9r5thbid8u38j95ejm7a6nkbxxtx9fixxp14hnn": {
      "sig": "2TcL2nGoEYCrcvbPm9vBWAvhKRWs3A8mQiX2Sto5Q1RYYD8BMqfJ3wyMmyuKF5m1Ddjrnec5XKss38UaiY39KtvC",
      "user": "rad:git:hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc"
    }
  }
}
{
  "certifiers": [
    "rad:git:hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc"
  ],
  "hash": "hwd1yreghifj6m1dp1ayz7e6rub5o83buzik6oecq6tkakapmt88a94bmge",
  "info": {
    "default_branch": "main",
    "description": "another try",
    "project": null
  },
  "keys": [
    "hybx51sxkf3rr4s9r5thbid8u38j95ejm7a6nkbxxtx9fixxp14hnn"
  ],
  "name": "hello-radicle-2",
  "rad_version": 2,
  "revision": 1,
  "root_hash": "hwd1yredhofab7czds8hw9gbmuf37t93imeupsxx5tn9r5cqh4t4tbgi4zh",
  "signatures": {
    "hybx51sxkf3rr4s9r5thbid8u38j95ejm7a6nkbxxtx9fixxp14hnn": {
      "sig": "4Syf3GsG1TtQrE2HBqGrMHRmdj27XaMV3msvZzgptnHHLUravhWGiC8nDDuxfPxMXoLLdSqhSui9Ct3ebLSNLsBM",
      "user": "rad:git:hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc"
    }
  }
}
{
  "hash": "hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc",
  "info": {
    "user": null
  },
  "keys": [
    "hybx51sxkf3rr4s9r5thbid8u38j95ejm7a6nkbxxtx9fixxp14hnn"
  ],
  "name": "thibaut",
  "rad_version": 2,
  "revision": 1,
  "root_hash": "hwd1yre887ux43bcatd4e7kkkybppdt3rc4o5yj61keame5cfc3h1aic1zc",
  "signatures": {
    "hybx51sxkf3rr4s9r5thbid8u38j95ejm7a6nkbxxtx9fixxp14hnn": {
      "sig": "2oLwVNkbuXk3k2teDnVxPXbZ1o2Q4RfovSdN5oyfj35QmBSuah9UCx3YyhrEYE7quJZCXfWyAB3oth1SdiFN6Trj",
      "user": null
    }
  }
}
```

OS: Linux Mint 19.3 Cinnamon, kernel 5.7.1-050701-generic

```bash
$ git --version
git version 2.17.1
```

**Comment by FintanH** [comment]
Right, so there seems to be something wrong when creating a project where the initial branch is getting created. We would expect to see `refs/heads/main` under one of those projects. This means there's something not quite right with creating the working copy, which lines up with you not being able to see any branches or remotes.

Could you create another project and capture the logs during that? I'm hoping there's a clear error in there for what's going wrong during that moment.

**Comment by Tbaut** [comment]
Sure, [here the full log](https://gist.github.com/Tbaut/157f078dcd7cb4a127bde13dd6d9c07f) I guess the most important is what happened last:

>  ERROR api::http::error      > Rejection([MethodNotAllowed, MethodNotAllowed, MethodNotAllowed, MethodNotAllowed, MethodNotAllowed, State(Create(Git(Error { code: -3, klass: 7, message: "config value \'user.name\' was not found" })))])

When I click on "copy error", I get the following in the 
```bash
{
  "code": "ProjectCreationFailure",
  "message": "Could not create project: Incorrect input",
  "source": {
    "response": {}
  }
}
```

**Comment by FintanH** [comment]
Ah I see, so you don't have a global git config set up. For example, I have:
```
more ~/.gitconfig 
[user]
        email = fintan.halpenny@gmail.com
        name = FintanH
```

This is good to know :) One fix for you now is to set that up https://docs.github.com/en/free-pro-team@latest/github/using-git/setting-your-username-in-git

**Comment by Tbaut** [comment]
:tada: thanks a lot, looks like I've never needed it so far!
In case someone lands here, setup your name with: 
```bash
git config --global user.name "YOUR NAME"
```

It's solved now, I'll let you decide whether or not you want to close the issue to track this and maybe show an error or something.

**Comment by xla** [comment]
Thanks @Tbaut for reaching out and following up with all that great level of detail. Follow-up is captured in #1358.

**Comment by FintanH** [comment]
I added a ticket under #1358 to discuss this. We should at least catch this case at a validation stage and warn the user. :) Thanks for the help :100:
