### ISSUE TITLE
Announce releases on discourse

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1350]
When cutting a release we should with the help of a template announce the following information:

* summary of changes
* links to binaries
* where to get support
* where to file bugs

**Comment by rudolfs** [comment]
Could we add it to: https://github.com/radicle-dev/radicle-upstream/blob/master/DEVELOPMENT.md#releases? The person who does the release also has to create the QA issues, would be good to have this in one place.

**Comment by abbey-titcomb** [comment]
I'm assuming one of you will put together the list of changes, then I'll create the official post?

**Comment by xla** [comment]
> I'm assuming one of you will put together the list of changes, then I'll create the official post?

The question is where in the release lifecycle  does it happen, likely after Q&A sign-off. And it would be nice to automate it.

**Comment by abbey-titcomb** [comment]
I propose we add this to the QA checklist to make sure that we complete it for each issue. The post on Discourse can be tracked outside of GitHub by me.

@rudolfs can you add this? Or tell me where I can do so?

**Comment by rudolfs** [comment]
@abbey-titcomb will add it.

**Comment by abbey-titcomb** [comment]
Great. Thanks @rudolfs. Closing this.

**Comment by rudolfs** [comment]
Hold on, that was only about updating the download links on the website. Will have to add another paragraph about announcing the release.
