### ISSUE TITLE
Git config user set up

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1358]
As we found out in https://github.com/radicle-dev/radicle-upstream/issues/1348, if there's no global git config set up with user details, we won't be able to create projects as we can't create commits.

We should add this to validations and figure out a flow as to how we want the user to set this up.

**Comment by rudolfs** [comment]
As a stop gap, we should probably add this to https://docs.radicle.xyz/docs/getting-started/getting-started#configuring-your-system

**Comment by abbey-titcomb** [comment]
> As a stop gap, we should probably add this to https://docs.radicle.xyz/docs/getting-started/getting-started#configuring-your-system.

Yup. Adding it now.
