### ISSUE TITLE
Proxy crashes in long-running app

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1359]
When leaving the app running (couple of hours) the proxy will crash, likely from the captured logs filling up

```
Proxy process exited with status code ERR_CHILD_PROCESS_STDIO_MAXBUFFER and signal null
```

**Comment by cloudhead** [comment]
I'm guessing it's because we spawn the proxy with `exec` and not `spawn`. The former returns a buffer, which will fill up pretty quickly.
