### ISSUE TITLE
Migrate proxy to async/await

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#136]
With juniper now supporting the async/await feature we should properly migrate to it. While that we should evaluate runtime/executor usage esp. in conjunction with the registry client.

**Comment by xla** [comment]
Spent half a day on this, diving deep into the guts of [graphql-rust/juniper](https://github.com/graphql-rust/juniper), which is the main dependency we have to look into for this issue. Firstly `async/await` support just recently landedon master and there is no crates version with it yet. When pulling in master a lot of the macro infrastructure to crate and derive graphql types has changed. One of them being how to setup unions, which now require complex trait boilerplate. Unfortunately not all of these macro implementations are updated to implement the correct `Async` versions, which are needed. For now we need to hold of on the migration until `async/await` and has stabilised in juniper. Beyond that there is hiding a can of worms in that the new definition of unions requires handling of trait objects.

**Comment by sarahscott** [comment]
@xla can this be closed?

**Comment by xla** [comment]
Absolutely.
