### ISSUE TITLE
Add "are you sure" confirmation when a user removes a seed

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1360]
Since removing the initial seed node makes the app almost unusable, and finding that seed address will be non-trivial for the user, we should pop up an "are you sure" modal.

**BTW this is a new modal style that we should build. It could be very useful in other situations too, and is a standard UI element we should have anyway.**

Design is here: https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=6690%3A17

![image](https://user-images.githubusercontent.com/4406983/100231365-3424f780-2f27-11eb-81d6-bafcde8b9b52.png)

**Comment by mkroehnert** [comment]
Hi, as an additional idea, I like how GitLab handles project removal.
For their `remove project` to become active, you need to type the name of the project to be deleted into a textbox.
