### ISSUE TITLE
Try to reproduce remote management state error

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1368]
* add remote
* refresh after 3s
* see if still looking state is persisted

**Comment by MeBrei** [comment]
I was not able to reproduce it. All added remotes where still under `still looking...` after waiting some time and refreshing.

What I tried:
- tested the following both while being connected and disconnected from the seed
- varied the time before refresh
- added online and offline remotes
- re-added remotes after unfollowing them
- limitations: 
  - I picked "random" remotes from the seed, not knowing if they had a replication of the project or not
  - none of the remotes were found
