### ISSUE TITLE
Investigate logging and telemetry in proxy

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#138]
We need a sound strategy for logging and telemetry in the proxy codebase, both to improve introspectibility.

**Comment by garbados** [comment]
Because Radicle's stack is open source, it makes sense to choose an open source logging component. [Prometheus](https://prometheus.io/) has a [Rust crate](https://docs.rs/prometheus/0.7.0/prometheus/) that should be easy to integrate.

**Comment by xla** [comment]
Superseeded by #680
