### ISSUE TITLE
Investigate why git remote in checkouts are shortened

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1389]
When collaborating with other peers and fetching their remotes ?git? would shorten the name omitting the peer_id suffix.

To test here is having two remotes with the same handle.

**Comment by FintanH** [comment]
It seems refspecs in our include files aren't being created with the suffix. For example,

```
fetch = +refs/remotes/hydxmk8cx8mcbijp6kgb8htm6jdhpstiow3kbezxp438adybaaqzgy/heads/*:refs/remotes/xla/*
```

**Comment by MeBrei** [comment]
Update the [docs](https://github.com/radicle-dev/radicle-docs/pull/49#discussion_r531619331) once the fix is in upstream
