### ISSUE TITLE
Show badge for local user in remote listings

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1391]
When listing remotes like in the context of the project it's hard to distinguish ones own peer/remtoe. To remedy that we could show another badge like the `maintainer` one to highlight the users view of the project.

**Comment by cloudhead** [comment]
This is a cool idea. @juliendonck? Maybe `[you]` or something.

**Comment by rudolfs** [comment]
> This is a cool idea. @juliendonck? Maybe [you] or something.

Or `me`? : P

**Comment by juliendonck** [comment]
[you] is also what came to mind for me
