### ISSUE TITLE
Networking icon weird during reconnect

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1397]
Would be nice to have a separate visual representation for this re-connection phase.

- multiple reconnect attempts
![reconnect1](https://user-images.githubusercontent.com/158411/100452641-d8d73e80-30b9-11eb-8532-ac35aaa3fc58.gif)

- connection established after reconnect attempts
![reconnect2](https://user-images.githubusercontent.com/158411/100452681-ebea0e80-30b9-11eb-8e23-215db9f2471a.gif)

**Comment by brandonhaslegs** [comment]
There should just be an animation between these two states.

**Comment by rudolfs** [comment]
Haven't noticed this issue lately.
