### ISSUE TITLE
Publish our GitHub repositories to Radicle 

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-upstream#1407]
How can we ask projects to mirror their codebases if we aren't mirroring ours? Let's publish all active Radicle repositories to the network so they can be shared and discovered throughout next week. I propose that one maintainer from each publishes the project so we know which one to share, then everyone can fork and create their own views.

Whoever publishes should also be responsible for keeping the repositories up-to-date.

- [x] radicle-upstream: `rad:git:hwd1yre8sihxpdxkfkeyidaxaumnbwk7e9b8you3qw5tmwsbkp6simabznr`
- [x] radicle-link `rad:git:hwd1yrer8jcanc4skh76w5hkmgpu7q486z3n8ys4ap8epykwhaerz35x4ho`
- [x] radicle-surf `rad:git:hwd1yrenyh4g8fs4dmongwgsjszb338ynu3ubzk1fx83hf3nwmz63w8h4fy`
- [x] radicle-docs `rad:git:hwd1yrerftjeixnt8nqhr9mhsfayqd47pr38rrrzign16z9hysbcu6y6exa`
- [x] radilce-bins `rad:git:hwd1yref154w5616obsw7uam14nzbzx4qfx5wyb7a5mt6wg5zfrympnia7a`
- [x] radilce-keystore `rad:git:hwd1yre8g7nrk4kzr8a76mms136geysridrgrddw15szroxmrajj9h8d51h`
- [x] radicle-avatar `rad:git:hwd1yredna5k7undw9xurpm6mtfyczodz4fkute7bcpii3jb9uoj7tf1sho`
- [ ] ~~radicle-contracts~~ <- this is private
- [x] radicle-decisions `rad:git:hwd1yreb15ip5794fzf6rtzowwq8m1puifsrbo875f6f8xm4oy5doysfopo`
- [x] radicle.xyz: `rad:git:hwd1yregohr8n6og8w8roem8t4gchanoywrhajzf4kudqqhajots1kdzfah`
- [ ] Anything else?

Whoever publishes should share the Radicle IDs here so I can log them as the projects we should share on our channels.de

**Comment by xla** [comment]
Added a bunch of reos.

**Comment by rudolfs** [comment]
Added all the repos under my user. See Radicle IDs in the issue description.

**Comment by mkroehnert** [comment]
@abbey-titcomb @rudolfs @xla first of all, thanks for your work on Radicle.

I found this issue by accident. It might be a good idea to add the Radicle IDs to the respective README files in the repositories.
At least for me, this was the first place I looked for them.
