### ISSUE TITLE
Snap isolation prevents accessing git config

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1419]
When using the snap build of the app I cannot create a project. I always get the error
```
{
  "code": "ProjectCreationFailure",
  "message": "Could not create project: the author name for creating the project could not be found - have you configured your git config?",
  "source": {
    "response": {}
  }
}
```
This works however if I use the AppImage package.

I believe that the issue lies in the isolation the snap does. An app running snap does not have full access to the users filesystem and I believe other things might not work because of that.

I suggest we don’t provide snap packages until we thoroughly investigate this.

**Comment by rudolfs** [comment]
We don't publish snap images anymore.
