### ISSUE TITLE
panic at unlock

### ISSUE THREAD

**Issue by MrChico** [radicle-dev/radicle-upstream#1420]
Hey,

Upstream crashes after I unlock my account. I'm building from source and starting the app with `yarn start`, currently on `fc026b377367e71a7ec6a12a8422a861f3a7d94a` (but the crash happens on `fa25874` as well). There's a very long error message, but here are some parts that seemed relevant:
```
thread 'tokio-runtime-worker' panicked at 'overflow when subtracting duration from instant', library/std/src/time.rs:384:33
...
thread 'tokio-runtime-worker' panicked at 'receiver is gone: RecvError(())', ~/radicle-upstream/proxy/coco/src/peer/control.rs:93:24
thread 'tokio-runtime-worker' panicked at 'Failed to receive peer event: Closed', ~/radicle-upstream/proxy/api/src/process.rs:179:30
stack backtrace:
   0:        0x1096cd294 - std::backtrace_rs::backtrace::libunwind::trace::hf8598643f9eebc26thread '
tokio-runtime-worker ' panicked at ' receiver is gone: RecvError(()) '

...
Error: Sled(Io(Custom { kind: Other, error: "could not acquire lock on \"~/Library/Application Support/xyz.radicle.radicle-upstream/store/db\": Os { code: 35, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" }))
error Command failed with exit code 1.
```

I'm on a mac

**Comment by xla** [comment]
Hej, thanks for reaching out. Could you check what the process listing for this shows:

```
ps auxwww | grep api
```

**Comment by MrChico** [comment]
Before the panic, I see a process `target/debug/api`, after the panic, there's nothing

**Comment by xla** [comment]
Can you try the official release: https://releases.radicle.xyz/radicle-upstream-0.1.4.AppImage

**Comment by MrChico** [comment]
unfortunately not because it is incompatible with my High Sierra mac

**Comment by xla** [comment]
We unfortunately don't support High Sierra. See #382 for the rationale.

**Comment by MrChico** [comment]
nuking my state with `scripts/reset-state.sh` seems to have resolved this problem for now
