### ISSUE TITLE
Error message `The user aborted a request` when adding a remote

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1424]
When I added a remote I got an error twice even though everything worked as expected.
Error: `The user aborted a request`

<img width="1280" alt="Screen Shot 2020-11-30 at 13 08 36" src="https://user-images.githubusercontent.com/2326909/100608805-44651a00-330d-11eb-9d50-4be3a5cc836d.png">

**Comment by cloudhead** [comment]
I got a more advanced version of this bug today, after adding a remote, while two other remotes were pending:

![upstream-remote-bug](https://user-images.githubusercontent.com/40774/101013175-2fce8f00-3564-11eb-9a93-1c50b8074d7c.gif)
