### ISSUE TITLE
Red error messages disappear without user interaction

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1425]
Error showed up but disappeared too quickly to interact. It should only disappear after a dismiss or copy action

<img width="943" alt="Screen Shot 2020-11-30 at 13 08 33" src="https://user-images.githubusercontent.com/2326909/100608964-88f0b580-330d-11eb-8e9d-c17edd713483.png">

**Comment by geigerzaehler** [comment]
>  It should only disappear after a dismiss or copy action

@juliendonck: Currently there is no “dismiss action”. Should we add it?

**Comment by cloudhead** [comment]
Yeah that would be needed. Maybe the "copy" button should use the icon we use everywhere, so it's:

`[error message] [copy-icon] | [dismiss button]`

**Comment by rudolfs** [comment]
Or we make the notification slightly bigger so it can have 2 buttons, like @brandonhaslegs once suggested:
<img width="50%" alt="Screenshot 2020-12-01 at 14 05 26" src="https://user-images.githubusercontent.com/158411/100744591-5b277180-33de-11eb-9c59-bf569d7a4c8a.png">

**Comment by rudolfs** [comment]
At one point we had "sticky" notifications, but we removed that later on: https://github.com/radicle-dev/radicle-upstream/pull/1082/files#diff-b5c03286b2896eafb427a5abb0c8d9cba006234ee487078c0fce3131bf4efba7R92.

**Comment by rudolfs** [comment]
@juliendonck @brandonhaslegs: should this be closed in favour of: https://github.com/radicle-dev/radicle-upstream/issues/760?

**Comment by brandonhaslegs** [comment]
No this one is about adding the feature of being able to set certain notifications to never disappear (only go away when a close button is pressed)

**Comment by juliendonck** [comment]
@geigerzaehler tell me what to do

**Comment by geigerzaehler** [comment]
All error messages are shown using [this function](https://github.com/radicle-dev/radicle-upstream/blob/cad2675e446f2bb47d0ef3ac6843209c5b3a9d17/ui/src/error.ts#L172-L187). To make the error persistent you can set the `persistent` option on `notification.error`. To add a “dismiss” button you can just add another action. To dismiss the notification you’ll need to call `remove` on the handle returned by `notification.error`.

**Comment by brandonhaslegs** [comment]
So this issue can be closed right?

**Comment by juliendonck** [comment]
> So this issue can be closed right?

No, need to implement what @geigerzaehler is talking about above.
