### ISSUE TITLE
Killing the app leads to unresolvable state on macOs

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#1428]
To reproduce:

1. Find the `pid` of the running Radicle Upstream app
2. Run `kill -9 <pid>`
3. Open the app
    You should see the BSOD
4. Close the app by clicking on the `x` button at the top left
5. Click on the app icon in the dock
    You should see the screen that shows the error `Error: Invalid authentication token`

Hard-exiting the app doesn't resolve the issue.

**Comment by NunoAlexandre** [comment]
And here's my terminal logs from running the steps above:


```
$ /Applications/Radicle\ Upstream.app/Contents/MacOS/Radicle\ Upstream

(node:14511) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
 INFO  coco::git_helper > Copied git remote helper to: "/Users/nuno/.radicle/bin/git-remote-rad"
Error: Sled(Io(Custom { kind: Other, error: "could not acquire lock on \"/Users/nuno/Library/Application Support/xyz.radicle.radicle-upstream/store/db\": Os { code: 35, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" }))
^[[A(node:14511) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

**Comment by xla** [comment]
Do you still have a proxy running? Try `ps auxww | grep proxy`

**Comment by geigerzaehler** [comment]
Running `kill -9` will send `SIGKILL` to the process which cannot be intercepted by the process. This is why it leaves all child processes (including the proxy) dangling. There’s really nothing we can do about this. See [this article](https://linuxhandbook.com/sigterm-vs-sigkill/) for more info.

**Comment by NunoAlexandre** [comment]
@xla yes, it does. Thanks for the command.

**Comment by NunoAlexandre** [comment]
@geigerzaehler thanks for pointing that out. This might happen to a user though, so we probably should document how to get the app usable again in [troubleshooting](https://docs.radicle.xyz/docs/using-radicle/troubleshooting). @abbey-titcomb how does it sound to you?

**Comment by xla** [comment]
I don't think someone kill -9ing their app is a common case. The actionable item here is for the app to gracefully error when a proxy process exist, or it should try to clean it up.

**Comment by xla** [comment]
Captured in #1454
