### ISSUE TITLE
Preselect 'main' or 'master' when adding an existing project

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1429]
When I create a project, we should preselect `main` or `master` in the dropdown, cause otherwise a lot of people will have wrong default branches.

**Comment by cloudhead** [comment]
Also, branch list isn't scrollable, and:

![2020-11-30-135704_1278x1414_scrot](https://user-images.githubusercontent.com/40774/100612933-07e8ec80-3314-11eb-9ba4-2d58722c6f9a.png)

**Comment by rudolfs** [comment]
> When I create a project, we should preselect main or master in the dropdown, cause otherwise a lot of people will have wrong default branches.

We already preselect `main` if it is present in the repository.
Are there any other branch names which should be preselected if `main` or `master` are not present?

**Comment by xla** [comment]
> We already preselect `main` if it is present in the repository.

I don't think that's the case, it currently selects the first branch in the list.

![2020-12-01-190440_1278x1408_scrot](https://user-images.githubusercontent.com/1585/100779065-1b757f80-3408-11eb-8462-766eb2de8fca.png)

**Comment by rudolfs** [comment]
> I don't think that's the case, it currently selects the first branch in the list.

That list only contains `master`, I don't see `main`.

**Comment by cloudhead** [comment]
> Are there any other branch names which should be preselected if `main` or `master` are not present?

`main` is our default and `master` is the git default, so I think that covers it without going much more complicated.

**Comment by Nemo157** [comment]
The git default is user customizeable, you could also check `git config --get init.defaultBranch`.

**Comment by rudolfs** [comment]
@Nemo157: good call! I think this could work if we're on a relatively new git version, since this was introduced in [`2.28`](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch). Will probably have to fall back to something if it's not available.

**Comment by NunoAlexandre** [comment]
Done in e9bac61c9809ebb95bf86dbce43dd3a0a9782baa
