### ISSUE TITLE
Put ~/.radicle/bin in XDG_BIN_HOME

### ISSUE THREAD

**Issue by poperigby** [radicle-dev/radicle-upstream#1432]
I think it's a good idea to move `~/.radicle/bin` to `$XDG_BIN_HOME/radicle` or `~/.local/bin/radicle` if that isn't set. [It's not yet in the XDG spec](https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/14), but it I've seen other projects doing this.

**Comment by xla** [comment]
Thanks for bringing this up, we discussed this multiple times in the team as well and usually like to stick to XDG where possible. The question that this posses is what to do about macOS installations where XDG paths point into `~/Library`, which are not commonly found in shell paths. Happy to hear what ideas others might have of how to combine the needs.

**Comment by PopeRigby** [comment]
Correct me if I'm wrong, but wouldn't `.radicle/bin` also not be a part of `PATH`?

**Comment by rudolfs** [comment]
See https://github.com/radicle-dev/radicle-upstream/issues/763#issuecomment-671374819 for more context.

**Comment by xla** [comment]
> Correct me if I'm wrong, but wouldn't `.radicle/bin` also not be a part of `PATH`?

That's correct, this is why we require the addition in the shell configs. It's a not perfectly figured out yet and likely something that will get a lot less painless with package distributions.

**Comment by PopeRigby** [comment]
I see. Maybe shells will set `XDG_BIN_HOME` correctly for Apple devices when it becomes standardized in the spec.

**Comment by rudolfs** [comment]
Closing this for now, because `XDG_BIN_HOME` still isn't cross-platform compatible: https://docs.rs/directories/latest/directories/struct.BaseDirs.html#method.executable_dir.
