### ISSUE TITLE
Streamline hotkeys

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#1435]
Currently 3 different kinds of destinations can be accessed via hotkeys: Modals (eg help), Fullscreen (design system guide) and a sidebar view page (settings). Some of the behavior of the hotkeys do not make sense for all kinds:

- [ ] `⌘+,` closes the settings page which navigates back to the previous page

**Comment by rudolfs** [comment]
This got fixed in the router upgrade.
