### ISSUE TITLE
Can't create new repo

### ISSUE THREAD

**Issue by pet3r-pan** [radicle-dev/radicle-upstream#1439]
![image](https://user-images.githubusercontent.com/25356454/100771531-a0858680-3452-11eb-8830-1c1a707d8a41.png)

```
error: {
  "code": "ProjectCreationFailure",
  "message": "Could not create project: early EOF; class=Net (12); code=Eof (-20)",
  "source": {
    "response": {}
  }
}
```

When I try to re-open radicle:

```
{
  "code": "ProjectRequestFailure",
  "message": "The project Hello-R could not be loaded",
  "details": {
    "type": "defaultBranch",
    "urn": "rad:git:hwd1yrenpy6jxrfr3t8imaf8skoznymddaythf3hb8usi4n9bq7m55he4ka",
    "shareableEntityIdentifier": "%rad:git:hwd1yrenpy6jxrfr3t8imaf8skoznymddaythf3hb8usi4n9bq7m55he4ka",
    "metadata": {
      "name": "Hello-R",
      "description": "",
      "defaultBranch": "main",
      "maintainers": [
        "rad:git:hwd1yrefqc7xrfd7xjr1gcdfyeiy63es3qfwwde665jfdpun9yusxkrg9wr"
      ]
    },
    "stats": null
  }
}
```

**Comment by xla** [comment]
Hej @pet3r-pan thanks for reaching out with your issue. As the creation of the project failed, you will see it linger around showing you the second error. The app should still be usable, the error is there so you can share it with us and we can investigate.

Does the project creation still fail after you restart the app and could you share the error that occurs? Also could you share your platform, OS version and app version.

**Comment by pet3r-pan** [comment]
Yes still fails

Radicle ver: Version 0.1.4 (0.1.4)
Mac: Mojave 10.14.4 (18E226)
