### ISSUE TITLE
Electron hang on "contiune with existing repository"

### ISSUE THREAD

**Issue by Gozala** [radicle-dev/radicle-upstream#1440]
I have encountered a problem on my first run, where I attempted to add repo from "continue with an existing repository" and clicking "Choose". Electron processes seemed to hang on an attempt to open system file picker. This lead to more problems:

- Killing app and restarting complained about locked store (as far as I recall, unfortunately I have not noted it)
- Nuking `~/Library/Application Support/Radicle...` resolved that problem but started reporting new one

```
NFO  coco::git_helper > Copied git remote helper to: "/Users/gozala/.radicle/bin/git-remote-rad"
 INFO  api::process     > starting API
Error: Warp(hyper::Error(Listen, Os { code: 48, kind: AddrInUse, message: "Address already in use" }))
```

Turns out problem here was with a  a stray proxy process. After @xla helped me figure that out killing it fixed the problem.

I can no longer reproduce the hang, so I think only actionable items here can be:

1. Allow re-connection to that proxy process (maybe unix socket or something ?)
2. Maybe handle "address already in use" by providing an instructions how to kill it ?
3. Rename radicle processes to `radicle-*` so it's easy to spot leftovers ?

### Versions

Radicle Upstream: Version 0.1.4 (0.1.4)
OS: macOs 10.15.7 (19H15)

**Comment by xla** [comment]
Thanks for reaching out and bringing up the issues you ran into. Captured in #1441 #1442
