### ISSUE TITLE
Surface instructions on how to resolve address in use error

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1442]
A common error case is the proxy lingering and therefore the app not able to start properly. There are easy ways to remedy that:

* show instructions of how to get rid of the stray process
* let the app kill the process
* attempt a reconnect (this one is tricky as the process won't be part of the process tree and therefore cleanup might be more invovled)

**Comment by Gozala** [comment]
It seems like proxy should either terminate if it has no clients or it should be designed to outlive clients in which case it should accept connections.

**Comment by xla** [comment]
> It seems like proxy should either terminate if it has no clients or it should be designed to outlive clients in which case it should accept connections.

Both of these are not that obvious. The first option because it's unclear when a client went away, as the protocol is HTTP and requests can roll in at any time there is no guarantee for a connection to exist at all, so determining that a client exists is tough. For the second we end up with the same problem of ownership and lifecycle management where we depend on the electron shell to manage it currently.

**Comment by Gozala** [comment]
> Both of these are not that obvious. The first option because it's unclear when a client went away, as the protocol is HTTP and requests can roll in at any time there is no guarantee for a connection to exist at all, so determining that a client exists is tough.

Maybe using a websocket would be a better option here that way you can tell client is gone when it disconnects. (I do understand this is probably non trivial change, but probably aligned with idea of a deamon process in the future).

**Comment by Gozala** [comment]
Even better option might be to use unix domain sockets (I believe there are similar windows things on crates.io) on the server and have a websocket or even HTTP wrapper (could even be in js) that electron runs for itself. 

That addresses the problem owneship of the daemon / proxy process as first one starts it and it is shared among all users as long as there is a user. It does however introduces issue of possible API incompatibilities across client multiple clients.

**Comment by rudolfs** [comment]
We have proper shutdown cleanup now.
