### ISSUE TITLE
Creating a new project does not use branch name specified in git config

### ISSUE THREAD

**Issue by Nemo157** [radicle-dev/radicle-upstream#1445]
I use a custom default branch name for my repositories:

```console
> git config --get init.defaultBranch
prīmum
```

I would expect any tool creating a git repository for me to follow this config, but it appears that radicle-upstream uses a hardcoded `main` branch name instead.

**Comment by cloudhead** [comment]
So one way this could work is:
* If I haven't set my config, upstream defaults to `main`
* If I have set my config, upstream defaults to whatever I set

```
> git config --get init.defaultBranch            # default to 'main'
> git config --global --add init.defaultBranch master   # default to 'master'                                                              
> git config --get init.defaultBranch
master
>
```

**Comment by NunoAlexandre** [comment]
@Nemo157 thanks for raising this! It has merged in https://github.com/radicle-dev/radicle-upstream/commit/1ad2ae34d8ebe97bef201f6fde5b63ee57b9b10e. Keep tuned for the next release :surfing_man: 

![primum](https://user-images.githubusercontent.com/7075260/108542605-3d362280-72e4-11eb-82ef-76393dd3e7fa.png)
