### ISSUE TITLE
Could not load project after deleting default branch

### ISSUE THREAD

**Issue by Nemo157** [radicle-dev/radicle-upstream#1446]
Following on from #1445 I tried deleting the default branch and pushing a different name instead, then when opening my user page the project doesn't appear because of an error:

```json
{
  "code": "ProjectRequestFailure",
  "message": "The project default-branch could not be loaded",
  "details": {
    "type": "defaultBranch",
    "urn": "rad:git:hwd1yref6d6prw65nh4oj96u8cdx1z6x8pppnfka6d36d3cu6wgay9rf5da",
    "shareableEntityIdentifier": "%rad:git:hwd1yref6d6prw65nh4oj96u8cdx1z6x8pppnfka6d36d3cu6wgay9rf5da",
    "metadata": {
      "name": "default-branch",
      "description": "",
      "defaultBranch": "main",
      "maintainers": [
        "rad:git:hwd1yrerta6rfsmdpfyqmn8n63cgw93hwe9obr8bb378ga9m1nek9qpfimy"
      ]
    },
    "stats": null
  }
}
```

**Comment by Nemo157** [comment]
Probably it shouldn't actually be possible to delete the default branch, trying to do so with github returns:

```console
> git push origin :prīmum
To github.com:Nemo157/bsx-rs
 ! [remote rejected] prīmum (refusing to delete the current branch: refs/heads/prīmum)
error: failed to push some refs to 'github.com:Nemo157/bsx-rs'
```

**Comment by lyoshenka** [comment]
i did the same thing. any way to recover the default branch, or change it?

**Comment by FintanH** [comment]
> i did the same thing. any way to recover the default branch, or change it?

You could recreate the default branch again by push a fresh one.

There's no way to change it yet. Changing projects is part of some ongoing work.

> Probably it shouldn't actually be possible to delete the default branch, trying to do so with github returns:

That's a great point, I need to look into how that's done!

**Comment by FintanH** [comment]
Putting this in **Housekeeping** so that we look at it during our weekly upstream syncs.
