### ISSUE TITLE
Show an informative error when proxy is already running

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1454]
There are many cases where when starting up the app there is an existing proxy process which prevents the app to start up a new one. We have a descriptive error surfaced for it, which we can use to translate into a friendly error screen and potetially link to the FAQs.

/cc @abbey-titcomb

**Comment by rudolfs** [comment]
Duplicate of https://github.com/radicle-dev/radicle-upstream/issues/1442.
