### ISSUE TITLE
Update radicle-link to use the next branch

### ISSUE THREAD

**Issue by bltavares** [radicle-dev/radicle-upstream#1457]
I only now realized that [radicle-link repo is using[(https://github.com/radicle-dev/radicle-link/pull/458) `next` as the default branch, but `maint` is the one [being used in radicle-upstream](https://github.com/radicle-dev/radicle-upstream/pull/1402) - and my #468 are based on `next`.

I have some to changes started on https://github.com/radicle-dev/radicle-upstream to compile on Windows, but now I can't compile `coco` anymore, as the `next` and `maint` introduced a lot of namespace changes. I'm eager to see this updated on radicle-upstream to continue trying Windows compilation

**Comment by xla** [comment]
Thanks for raising this @bltavares - this is our next big upgrade we are doing right now. The work for it is tracked https://github.com/orgs/radicle-dev/projects/17 - keep an eye on that one to get an idea of the progress. Will close this one as we are tracking the work already. :>
