### ISSUE TITLE
Is Windows support planned?

### ISSUE THREAD

**Issue by aggieben** [radicle-dev/radicle-upstream#1462]
Does the team plan to support Windows in the near future?

**Comment by xla** [comment]
Hej thanks for reaching out. Yes we are planning to support all major platforms at some point. So far we didn't have the capacity to make it priority, but a lot of people have been asking, so expect an update on that front very soon.

Will close this issue, join the community to stay up-to-date on the latest feature, or just keep track of the CHANGELOG here. :>
