### ISSUE TITLE
Does anyone have a nix expression for building `radicle-upstream`?

### ISSUE THREAD

**Issue by mitchmindtree** [radicle-dev/radicle-upstream#1464]
Just curious, as I noticed there are `default.nix` files in a couple of the other repositories. I did a quick search of this repository and checked the PRs at nixpkgs but didn't see anything. If anyone has one up their sleeve please share :)

**Comment by xla** [comment]
Hej @xwvvvvwx is working on an initial nix package over in NixOs/nixpkgs#105674 - we would be happy to accept a contribution to this repo with a working nix expression.

**Comment by geigerzaehler** [comment]
@xla, @FintanH: Have we made any progress on this?

**Comment by FintanH** [comment]
@mitchmindtree I have the following in a `shell.nix` locally:

```
let
  moz_overlay = import (builtins.fetchTarball https://github.com/mozilla/nixpkgs-mozilla/archive/master.tar.gz);
  nixpkgs = import <nixpkgs> {
    overlays = [ moz_overlay ];
  };
  ruststable = (nixpkgs.latest.rustChannels.stable.rust.override {
    extensions = [ "rust-src" "rust-analysis" ];}
  );
in
  with nixpkgs;
  mkShell {
    name = "rust";
    buildInputs = [
        cargo-watch
        openssl
        pkgconfig
        rustup
        ruststable

        electron
        yarn
        nodejs
    ];
  }
```

Now, my nix-fu is terrible, so the above works perfectly for developing the rust packages. However, running and testing the UI is hacky at best. I have to run `yarn install` and replace the `electron` it gets with the one I get from nix by doing a `rm ./node_modules/electron/dist/electron` and `cp $(which electron) ./node_modules/electron/dist`. Please don't judge me :flushed: 

If anyone has some tips on how to make that better please do tell :smile: 

But since the above `nixpkgs` PR got accepted, if you want to just run the application I think it's available on `ustable` or you can run the following command `nix run -f https://github.com/nixos/nixpkgs/archive/master.tar.gz radicle-upstream`.

**Comment by xwvvvvwx** [comment]
If you're interested in a `default.nix` that can build `radicle-upstream` from source, the following might serve a good starting point. The usage of `RUSTC_BOOTSTRAP` is a hack to work around the lack of unstable rust in `nixpkgs`, but it should be relatively easy to modify this to use the `nixpkgs-mozilla` overlay (as in the `shell.nix` above).

```nix
{ stdenv, fetchgit , makeWrapper, makeDesktopItem, mkYarnPackage , electron, rustPlatform }:

let
  executableName = "radicle-upstream";
  version = "0.1.5";

  src = fetchgit {
    url = "https://www.github.com/radicle-dev/radicle-upstream.git";
    sha256 = "1rgzih2fj522bdpiqm8scafwyip08iz53h2jmhxxa6g3kf90k9qq";
    fetchSubmodules = true;
    rev = "v${version}";
  };

  proxy = rustPlatform.buildRustPackage {
    pname = "radicle-proxy";
    inherit version;
    src = "${src}/proxy";
    cargoSha256 = "11vqg50q8d1md48k7dn7aajwnrq7imgqwi9qjjv0q515dpr23324";

    # TODO: investigate test failures here
    doCheck = false;

    # radicle-macros v0.1.0 needs unstable features
    # apparently using RUSTC_BOOTSTRAP is bad, but I don't know how else to get this to build....
    # see: https://github.com/NixOS/nixpkgs/pull/65303
    RUSTC_BOOTSTRAP = 1;
  };
in mkYarnPackage rec {
  name = "${executableName}-${version}";
  inherit version src;

  nativeBuildInputs = [ makeWrapper ];

  preBuild = ''
    yarn rollup:build
  '';

  installPhase = let
    share = "$out/share/${executableName}";
    icons = "$out/share/icons/hicolor";
  in ''
    mkdir -p ${share}
    # javascript
    cp -r ./deps/${executableName} ${share}/electron
    rm ${share}/electron/node_modules
    cp -r ./node_modules ${share}/electron
    # binaries
    cp ${proxy}/bin/radicle-proxy ${share}/radicle-proxy
    cp ${proxy}/bin/git-remote-rad ${share}/git-remote-rad
    # icons
    mkdir -p ${icons}/512x512/apps
    mkdir -p ${icons}/1024x1024/apps
    ln -s ${src}/public/icon.png ${icons}/512x512/apps/${executableName}.png
    ln -s ${src}/public/icon@2x.png ${icons}/1024x1024/apps/${executableName}.png
    # assets
    cp -r ${src}/proxy/assets ${share}/assets
    cp ./node_modules/twemoji-svg-assets/assets/svg/* ${share}/electron/public/twemoji/
    # wrap with electron
    makeWrapper '${electron}/bin/electron' "$out/bin/${executableName}" \
      --add-flags "${share}/electron"
    # add git helper to user path
    cp ${proxy}/bin/git-remote-rad $out/bin/git-remote-rad
  '';

  # skip distPhase. `doDist = false` doesn't work.
  distPhase = "true";

  desktopItem = makeDesktopItem {
    name = executableName;
    exec = executableName;
    icon = "radicle";
    desktopName = "Radicle Upstream";
    genericName = "P2P Git Client";
    comment = meta.description;
    categories = "Development;RevisionControl;P2P";
  };
}
```

**Comment by FintanH** [comment]
Thanks @xwvvvvwx! I'll play around with this and can make a PR adding it. Do you have any recommendations on a nix file for development, out of curiosity?

**Comment by mitchmindtree** [comment]
@xwvvvvwx just thought I'd mention [this alternative solution to the `nixpkgs-mozilla` overlay](https://discourse.nixos.org/t/rust-overlay-a-better-rust-toolchain-provider-and-drop-in-replacement-of-nixpkgs-mozilla/10986/7) that was recently announced in the nixos forums. I haven't looked closely at it myself yet, but looked interesting at a glance.

**Comment by rudolfs** [comment]
Since the sharing of nix files happened, I'm gonna assume that this can be closed. :)
Feel free to re-open or submit a patch that contains the nix files.
