### ISSUE TITLE
Not working on Debian 10 SUID Error

### ISSUE THREAD

**Issue by stevavoliajvar** [radicle-dev/radicle-upstream#1465]
Hi,

I wan’t to try out radicle, downloaded app and sadly system won’t run it.
I am running Debian 10.
The error I get is this:

```
[7207:1205/234345.685735:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_radiclHy5nT5/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```
I cannot chmod that file, it’s like it doesn’t exist, tried with sudo and everything.

My guess is that this is some Electron problem. 

Any ideas on how to fix this ?

**Comment by xla** [comment]
> I had the same issue on my Debian computer. I couldn’t find a “good” workaround, but running the AppImage with --no-sandbox got it to open.

**Comment by wschwab** [comment]
+1 on the issue, also on Debian. This error often comes up in Electron, I second @stevavoliajvar 's guess. I'd rather not disable the sandbox.

**Comment by barak** [comment]
You can fix it like this:
```shell
$ sudo sysctl kernel.unprivileged_userns_clone=1
```
Don't worry it's not actually doing anything scary. It enables appimage's preferred security mechanism. If that preferred mechanism is not enabled, it falls back to the nasty old sandbox thing, which also fails with that sandbox error message.

Running with `--no-sandbox` totally disables security, eek, scary, this is a better solution.

**Comment by barak** [comment]
And do this if you want it to persist across boots:
```shell
$ echo 'kernel.unprivileged_userns_clone=1' | sudo tee --append /etc/sysctl.d/local.conf
```
