### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by barak** [radicle-dev/radicle-upstream#1470]
I think it would be great if people could `apt install radicle` from the regular Debian archives, and Debian-derivative distributions like Ubuntu. This would require packaging it (perhaps in a modular way: non-GUI CLI stuff in one package, the desktop app in another, maybe a server in yet another, etc). I'm a Debian Developer, so would be happy to help facilitate this if y'all think it's

1. a good idea in principle, and
2. makes sense technically.

Maybe there's too much churn, so it's not feasible yet, but might become feasible in the future? If so, a bit of planning now might make it easier to do this sort of packaging later.

**Comment by diederikdehaas** [comment]
I'd love to have a Debian package!

I'm also in favor of modularity, f.e. I'd prefer to have the server part running on a (headless) Raspberry Pi (f.e. which is on 24/7) and then have a client (GUI and/or CLI) which can connect/interact with that.
Kind of like I now do/have with deluge(d). I don't know whether deluge(d)'s design itself is good, but thought about it as it's a bittorrent client.

Modularity/separation of concerns could also (partly?) address the concerns raised in #1469 (I'd used different wording, but agree ~ with the sentiment) as I wouldn't feel comfortable having a device (RPi) meant to run 24/7 to talk to the outside world, running JavaScript with nodejs+npm and Electron
