### ISSUE TITLE
Network integration testing

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1475]
## Rationale

To increase confidence in our release process and avoid wasting time performing manual QA, we want to have test coverage for most of the features in Upstream. However, currently we don't have a way to test any of the networking related features, e.g.:
  - peer selector
  - adding/removing remotes
  - network activity indicator
  - searching/following projects
  - fetching project changes
  - replication/syncing
  - etc.

See https://github.com/radicle-dev/radicle-upstream/issues/1345 and [QA.md](https://github.com/radicle-dev/radicle-upstream/blob/master/QA.md) for an exhaustive list of what needs to be automated.

## Requirements

Ideally we would have something that can:
  - simulate a swarm of nodes/seeds
    - in many different network configurations (e.g. 2 isolated nodes connecting to 1 seed; 3 nodes on the same LAN, etc)
  - run on CI
  - run on local **Linux** and **macOS** dev machines natively
  - run from the proxy rust test suite
  - run from the UI cypress test suite

### Docker
This would allow us to create different network configurations with `docker-compose`. Possibly also allow us to isolate nodes on a network level from one another. This way we could do proper integration tests where we don't have to modify `proxy` at all.

Drawbacks:
  - our current CI setup already runs in a container and running docker within docker [might be messy](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)
  - multicast UDP between containers might be difficult or impossible to set up
  - we would also have to re-configure our buildkite nodes to support that

### Bake in test harnesses into proxy
In this scenario we would change `proxy` in such a way that we can run multiple `proxy` binaries on the same host (or container). Then we could control the additional `proxy` processes via their HTTP APIs from cypress or rust tests to set up different network configurations for each test.

For this to work, we would need to add a couple of additional CLI options to the binary, so that we can:
  - bind to a specific `interface:port` for incoming data connections (we already allow specifying a port for the HTTP API)
  - specify a custom data directory (similar to how we do it on the seed node via `--root`): https://github.com/radicle-dev/radicle-upstream/issues/1199
  - specify allow/deny lists of peers/seeds the process is allowed to connect to directly, to simulate different network configurations

Drawbacks:
  - different network configurations are only simulated, this might work differently when clients talk to each other in the real world over the wire

Open questions:
  - can two processes bound to the same interface, but different ports discover each other over mDNS?

To me it seems like the proxy harness approach covers most of our requirements and is the least effort to implement.

**Comment by geigerzaehler** [comment]
> run from the proxy rust test suite

We’re already effectively doing that. We’re not running processes but part of the coco stack (without the API) natively in Rust. I think this is the right approach for the rust test suite for now and it should be ok to drop this from the requirements.

> To me it seems like the proxy harness approach covers most of our requirements and is the least effort to implement.

I agree. In addition to the arguments you provided I’d like to point out that the most complexity will probably lie in the orchestration of different peers. For example the UI test suite will need to start a specific configuration of peers and know how to interact with them, then tear them down. This will, I believe, be harder with the docker/docker-compose approach.

**Comment by xla** [comment]
> bind to a specific `interface:port` for incoming data connections (we already allow specifying a port for the HTTP API)

Currently the peer API binds to a random port, which means there is no chance of collision, if that is the issue we want to address with this. If it is to make them configurable, reaching for the recently landed mDNS might be a more effective way, as it doesn't depend on synchronisations of configurations.

> specify allow/deny lists of peers/seeds the process is allowed to connect to directly, to simulate different network configurations

As the declared goal is to enable testing which depends on state from different peers I see this as potentially out-of-scope. Focusing on network/NAT scenarios in isolation might be beneficial to driving this issue to completion faster.

**Comment by kim** [comment]
I also think that in-process orchestration is preferable for automated e2e testing. Process isolation and knobs to simulate different network conditions are useful in other contexts (which are hard to completely automate).

_However_, I think what would be useful in any case would be to be able to script `proxy` API interactions, without having to go through the UI. While an OpenAPI spec would be cool, it would probably add additional maintenance burden (I don't think `warp` has any facilities to generate it automatically). As the frontend is maintaining API bindings anyway, perhaps there's a way to make those usable standalone?

**Comment by xla** [comment]
> While an OpenAPI spec would be cool, it would probably add additional maintenance burden (I don't think `warp` has any facilities to generate it automatically). As the frontend is maintaining API bindings anyway, perhaps there's a way to make those usable standalone?

We started of having OpenAPI support for a while. Turned out that it required too much manual bookkeeping to not have it go out of sync with the actual implementation. Here is the [fork](https://github.com/radicle-dev/warp/tree/openapi).

I agree a scriptable proxy is worthwhile outcome, maybe we could have one of these CLIs things.
