### ISSUE TITLE
Fix double layout bug on NotFound

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#148]
Talk to the product team how we should handle generic error cases (including routing errors), showing a "page not found" is not what I would normally expect on a desktop app.

To reproduce:

1. pick a project
2. click "Source"
3. click on a commit SHA

<img width="1050" alt="double-sidebar" src="https://user-images.githubusercontent.com/158411/74134507-fac70980-4bea-11ea-8526-c6b3de4d4331.png">

**Comment by sarahscott** [comment]
@rudolfs status on this one? I'm able to reproduce the Not Found state by pushing corrupted paths but they aren't nested like that anymore:
![Screen Shot 2020-05-11 at 3 18 38 PM](https://user-images.githubusercontent.com/2712962/81617710-ceae5680-939a-11ea-8ea1-bf0325c171e3.png)

**Comment by rudolfs** [comment]
This happens whenever because we're using the `NotFound.svelte` screen for the catch-all route for sub-pages. And the contents of `NotFound.svelte` are wrapped in `<SidebarLayout>`.

For example the `Profile.svelte` screen:
```
  const screenRoutes = {
    "/profile/": Projects,
    "/profile/onboard/": Onboard,
    "*": NotFound,
  };
```

`<a href="/profile/this-does-not-exist" use:link>bla</a>`

<img width="50%" alt="Screenshot 2020-05-12 at 07 32 01" src="https://user-images.githubusercontent.com/158411/81642135-fc3ee280-9422-11ea-9fea-0e4462a7e017.png">

There's a couple of ways we could go about fixing this:

1) the easiest would be to keep the existing `NotFound.svelte` screen as the top-level catch-all route and define one or multiple custom NotFound screens for the sub-routes (without wrapping their contents in a layout).

2) talk to the design team and come up with a UX that feels more like an actual desktop app where catch-all error handling is done in a way that guides the user to recover from whatever error state they're in. An example could be a catch-all page with some nice wording and maybe give a copyable chunk of trace that a user can report to us + a link to get back to the previous page they were on. Instead of a whole screen, it could also be just a notification or modal box that pops up...
