### ISSUE TITLE
Support IPv6 alongside IPv4

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1480]
Currently we bind exclusively to IPv4. It should also be possible to bind to IPv6 and ideally both, so we peers can connect with either of these.

https://github.com/radicle-dev/radicle-upstream/blob/c111d6eaa7963bac9d30ad0708115103d8267d61/proxy/coco/src/config.rs#L22

**Comment by xla** [comment]
Ref. radicle-dev/radicle-link#472

**Comment by juliendonck** [comment]
@xla is this issue still relevant in this repo with most proxy code in link now?

**Comment by geigerzaehler** [comment]
This will be tackled as part of the new [application architecture](https://github.com/radicle-dev/radicle-link/blob/f583f7b1de41ef91f7d3d3e161ec3b73eb0202cb/docs/rfc/0682-application-architecture.adoc).
