### ISSUE TITLE
Is Windows support planned?

### ISSUE THREAD

**Issue by DiegoMagdaleno** [radicle-dev/radicle-upstream#1486]
Hi, im a Windows user and I would love to use this project, sadly it doesn't look like it supports Windows.

Is Windows support planned in the future?

**Comment by xla** [comment]
Hej @DiegoMagdaleno - thanks for reaching out. We are planning to support all major platforms. We got a lot of requests for Windows through other channels already. When that will land is unclear at this point but keeping an eye on this repository or the Development section over at radicle.community will help you not miss it.

@abbey-titcomb Can we funnel this into the user feedback board?

**Comment by rudolfs** [comment]
We've heard people having success running Upstream via WSL2 on Windows, might be worth a try in the meantime. There's also some [community effort](https://github.com/radicle-dev/twemoji-svg-assets/pull/3) going on in this regard. Maybe @bltavares can chime in on how that is going?

**Comment by voronoipotato** [comment]
It's kinda wild that this doesn't currently just work on windows, rust, typescript, svelte etc should all be cross platform. Obviously there's still testing for edgecases but I don't yet see anything that is linux specific. Even the shell scripts likely would run on git-bash.

**Comment by rudolfs** [comment]
@voronoipotato that's correct, we just didn't have the capacity to test it on that platform, but in theory there shouldn't be anything major preventing it from working on Windows.

**Comment by xla** [comment]
Tracked in #1488
