### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-upstream#1488]
We've gotten a lot of requests for Windows support since launching Beta. They have come through Twitter, Matrix, Hacker News, and issues on radicle-upstream. See #1486 and #1462 

We've even seen a community effort go into getting it working on Windows. See [#3](https://github.com/radicle-dev/twemoji-svg-assets/pull/3) and [#468](https://github.com/radicle-dev/radicle-link/pull/468).

Personally, I've seen at least 10 asks for Windows support via tweets or messages in #support.

**Comment by kim** [comment]
If we are to maintain Windows compatibility, the first thing to invest in is to set up CI on that platform, which will also define which exact versions we support.

**Comment by bltavares** [comment]
I've been able to get the Electron part fixed and running on windows.

Unfortunately the `radicle-proxy` has lot's of moving parts and is not up-dated to use the latest changes from `radicle-link` with the patches that make it compile on Windows.

Pending updates to `radicle-proxy`:
- https://github.com/radicle-dev/radicle-upstream/pull/1463 [probably needs another attempt to update]
- https://github.com/radicle-dev/radicle-link/pull/515

I'll try again when those updates land.

**Comment by Xiamuf** [comment]
要求Windows支持

**Comment by Aeroxander** [comment]
Hey, I see this is getting pretty close but I've been trying to run Radicle in WSL2 with the new GUI update https://devblogs.microsoft.com/commandline/the-initial-preview-of-gui-app-support-is-now-available-for-the-windows-subsystem-for-linux-2/

I got pretty close but I'm stuck at: 
```
~/squashfs-root$ ./AppRun --no-sandbox
./AppRun: line 45: /radicle-upstream: No such file or directory
```

If I run it with sandbox I get:

```
~/squashfs-root$ ./AppRun
[8570:0510/012725.446628:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/alex/squashfs-root/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

**Comment by geigerzaehler** [comment]
Thanks for trying this out @Aeroxander! I’m not familiar with WSL. Could you elaborate what `./AppRun` is? You may also want to check running the branch from #1623 from source to see if it works.

The SUID sandbox helper seems to be an [Electron problem](https://github.com/electron/electron/issues/17972). Looks like WSL doesn’t provide the right environment

**Comment by Aeroxander** [comment]
@geigerzaehler I was running on WSL1 without the Windows insider so that's why it didn't work, it's running now! I just needed to install some libs, running very smooth now :D
![image](https://user-images.githubusercontent.com/11189629/117715477-f1d23880-b19d-11eb-8ad5-4bd9c427ec40.png)

**Comment by rudolfs** [comment]
We have experimental Windows support since:
https://github.com/radicle-dev/radicle-upstream/commit/dd1eedadebfb17b1e3dbfe313c49bff26592a300
https://github.com/radicle-dev/radicle-upstream/commit/98030f35f88629116ff4fe73e30cac3e3d572a60

**Comment by freddi301** [comment]
What about adding binaries for windows? (maybe wiht a big red disclaimer)
It could help with adoption!

**Comment by unioneoks** [comment]
Yes, we need windows
