### ISSUE TITLE
Announcement Sync

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1490]
If we're in a situation where a project was created but a seed failed to apply the announcement of that project then the seed will never hear about that project again until another announcement is made -- via a commit for example.

One solution to this is that we could announce the tip of all projects' default branches to the network upon startup. This is similar to the way we try to run a fetch for every project upon startup.

**Comment by viraptor** [comment]
Would it be a problem to do this in a new connection matching a seed as well? I'm thinking of situations where the app starts when the seed is not available, or the app started before the network connection is up.

If the proxy reannounced all tips on a new connection, it could recover from a few weird situations.

**Comment by FintanH** [comment]
Grafting will solve this
