### ISSUE TITLE
error: Cannot determine remote HEAD

### ISSUE THREAD

**Issue by Nemo157** [radicle-dev/radicle-upstream#1494]
I like to avoid remembering the primary branch name by using `<remote>/HEAD` instead. Unfortunately this doesn't appear to work with a `rad` remote:

```console
> git checkout rad/HEAD
error: pathspec 'rad/HEAD' did not match any file(s) known to git

> git remote set-head rad -a
Password for 'rad://radicle@hwd1yre85oenojqfpzt1ihd36enmupg4dnb1o78rsos8h957bpxxbzn5g4a.git':
error: Cannot determine remote HEAD

> git remote -v
rad     rad://hyy7poyurp67tb14oa17e7d3wn4ieg4yg1r3h3q8kkc3prc7ux4hpy@hwd1yre85oenojqfpzt1ihd36enmupg4dnb1o78rsos8h957bpxxbzn5g4a.git (fetch)
rad     rad://hyy7poyurp67tb14oa17e7d3wn4ieg4yg1r3h3q8kkc3prc7ux4hpy@hwd1yre85oenojqfpzt1ihd36enmupg4dnb1o78rsos8h957bpxxbzn5g4a.git (push)
```

**Comment by FintanH** [comment]
If I'm understanding correctly, this is just a symbolic ref to the default branch. If that's the case it would be easy enough to create the symbolic ref at this point https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/coco/src/project.rs#L20

**Comment by kim** [comment]
The first two commands expect that the remote end has advertised `HEAD`, which we don't at the moment. The problem being that there are ambiguous cases which _someone_ needs to take the time to sort out. See also: https://github.com/radicle-dev/radicle-link/issues/234

**Comment by Nemo157** [comment]
> If the logical repo does have a `default_branch`, we still need to decide which peer's view of it it shall be, and handle the case when they are diverging.

If my understanding is correct, this is if tracked peers have changed the `default_branch` in their fork of the project? In that case it seems that each remote should just have its own HEAD symbolic ref, set to whatever `default_branch` setting they are using (and in fact, without really knowing much about how metadata storage is done currently, it seems like this symbolic ref could _be_ the storage for the `default_branch` setting).

**Comment by Kaihuang724** [comment]
Closing this for now
