### ISSUE TITLE
Register url scheme handler

### ISSUE THREAD

**Issue by Nemo157** [radicle-dev/radicle-upstream#1498]
It would be nice if Radicle Upstream would register itself as the `rad:` URL scheme handler so that creating links like <rad:git:hwd1yre85oenojqfpzt1ihd36enmupg4dnb1o78rsos8h957bpxxbzn5g4a> would just work and navigate to the project (though, seems that github filters out non-http links...).

**Comment by dragon788** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

**Comment by NunoAlexandre** [comment]
Thanks for opening this up, @Nemo157. I am closing it since it is already captured in https://github.com/radicle-dev/radicle-upstream/issues/1512 :raised_hands:
