### ISSUE TITLE
Browsing git tags (feature request)

### ISSUE THREAD

**Issue by laanwj** [radicle-dev/radicle-upstream#1513]
The repository browser allows looking at branches, it would be nice to also be able to see the tags.
(as these are generally what one'd want the user to check out for production use)

**Comment by rudolfs** [comment]
Currently tags are hidden behind a feature flag in development mode.

See https://github.com/radicle-dev/radicle-link/issues/145 for more context on why git tags are not yet available.
And https://github.com/radicle-dev/radicle-upstream/blob/master/DEVELOPMENT.md#feature-flagging for how to enable experimental mode.
