### ISSUE TITLE
Dismissing the hint in the New Project modal breaks the modal layout

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1515]
Close the hint about adding to your shell configuration to see the modal's layout break.

![image](https://user-images.githubusercontent.com/4406983/104299959-23741500-54c6-11eb-8ee7-ed1dd07824ba.png)

**Comment by juliendonck** [comment]
Closed by https://github.com/radicle-dev/radicle-upstream/pull/1523
