### ISSUE TITLE
Race condition during app start

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1516]
There are cases where the `activate` event is fired before the `ready` event. this leads to Electron showing an error message.
https://github.com/radicle-dev/radicle-upstream/blob/2224157f952ef2a5dcaf246602987eb345a6875f/native/main.ts#L195

Steps to repro on macOS: click the dock icon rapidly when opening Upstream. Users also have reported that it also happens on random app starts without clicking the icon.

See: https://www.electronjs.org/docs/api/app#event-activate-macos and https://github.com/electron/electron/issues/5272 for hints on how to fix this.

<img width="372" alt="Screenshot 2021-01-12 at 14 21 23" src="https://user-images.githubusercontent.com/158411/104319654-74ddcd80-54e1-11eb-9a53-7760a2b0fa77.png">

https://user-images.githubusercontent.com/158411/104319763-9dfe5e00-54e1-11eb-93ff-b63dff281fc6.mov

**Comment by rudolfs** [comment]
\cc @geigerzaehler

**Comment by geigerzaehler** [comment]
I assume this is fixed by #1517?

**Comment by rudolfs** [comment]
Correct.
