### ISSUE TITLE
Move from using dispatch to passing functions as parameters 

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#1521]
Currently, we use [Svelte's event system](https://svelte.dev/tutorial/component-events) as the way to configure a (component's behaviour upon some event, e.g., what do when a user clicks a button.  

By reading this [SO thread](https://stackoverflow.com/questions/61569655/svelte-event-forwarding-with-dispatcher-vs-passing-in-handling-function-which) I understand that `dispatch` is the only way to achieve this with native components. However, I find it a bad deal to, therefore, breach it out across the whole codebase for three main reasons:

1. it makes the code highly implicit and difficult to follow
2. the events are dynamically checked, resulting in the whole flow only being checked on runtime
3. no type-checking, one can call the wrong event or pass unfitting arguments and - again - only see it fail on runtime 

My suggestion is to move from using `dispatch` to passing functions as parameters instead, which resolves the 3 issues raised above.

_context: https://github.com/radicle-dev/radicle-upstream/pull/975#issuecomment-759353567 + https://github.com/radicle-dev/radicle-upstream/pull/975#issuecomment-759391371_

**Comment by geigerzaehler** [comment]
@MeBrei, @xla: Do you agree with this approach? If so we don’t want to tackle this all at once but incrementally as we go.

**Comment by xla** [comment]
The alternative needs more realistic scrutiny, as the perceived gains from type-safety needs to be measured against the not insignificant overhead when a component at the bottom of a deep component hierarchy changes its interface. Such a change would necessitate refactoring to all dependent components. Furthermore there should be a proposal for how to capture optionality when binding, something that the current dispatch approach allows. Generally I'm not against improvements which make public APIs more explicit, I'd be sceptical that the implications are clear.

**Comment by geigerzaehler** [comment]
Thanks for the input, @xla. With your comments in mind, I think it’s reasonable to chose a mechanism on a case-by-case basis where we can weigh the pros and cons.

Since we don’t intend to migrate everything to one approach anyway, I suggest we close this issue.

**Comment by NunoAlexandre** [comment]
> The alternative needs more realistic scrutiny, as the perceived gains from type-safety needs to be measured against the not insignificant overhead when a component at the bottom of a deep component hierarchy changes its interface. Such a change would necessitate refactoring to all dependent components.

Having a type-safe setup is particularly helpful in such scenarios tho. The _overhead_ is the compiler specifically pointing out where a change caused a break that needs fixing. I'd take that any day over having the app malfunction at runtime or having to lookup strings and match value types across files. Note that this is exactly what we do for any non-function parameters.

>  Furthermore there should be a proposal for how to capture optionality when binding, something that the current dispatch approach allows. 

I assume you refer to a function parameter being optional. If so, good point. I faced such a necessity in the funding feature and having it as a union type of `<fn type> | undefined>` worked seamlessly. Perhaps using `?`, as in `<fn type>?` could be a more idiomatic way. Good stuff to explore.

> I'd be sceptical that the implications are clear.

What makes you sceptical? Is it regarding your first point or something else?

**Comment by NunoAlexandre** [comment]
> Since we don’t intend to migrate everything to one approach anyway, I suggest we close this issue.
