### ISSUE TITLE
Automate Apple dmg notarisation

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1530]
When doing a release we have to build the app locally and run the [notarisation step](https://github.com/radicle-dev/radicle-upstream/blob/master/DEVELOPMENT.md#publishing-a-release) manually. This takes around 10-20 mins of developer time for every weekly release. Additionally this prevents us from delegating the release procedure to people without Apple hardware. Therefore it would be great if we could automate this step.

Technically there is nothing preventing us from automating this step.

We would have to:
  - set up a developer certificate on our macOS build host _mac-n-cheese_
  - add an additional build step targeting only this machine which runs:
```
CSC_NAME="Monadic GmbH (XXXXXXXXXX)" \
APPLE_ID="XXXXXXX@monadic.xyz" \
APPLE_ID_PASSWORD="XXXX-XXXX-XXXX-XXXX" \
NOTARIZE=true \
yarn dist
```

However, before we dive into implementation, we should discuss whether we are okay with the security implications.

**Comment by rudolfs** [comment]
@kim would love to hear your thoughts on this.

**Comment by kim** [comment]
Sounds good. Found some hints [here](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow), which suggest that the `xcode` cli tools can read the necessary credentials from the local keychain.

**Comment by rudolfs** [comment]
I got this working on our `mac-n-cheese` build host, but before we can close this issue we still should:
  - [ ] create a new Apple account which uses our dev email address
  - [ ] generate a new developer certificate for that Apple ID, and use it on our build host, so everybody gets emails about successful notarisations
  - [ ] set up a separate keychain for the dev cert on `mac-n-cheese`
  - [ ] update https://github.com/radicle-dev/infra/blob/master/ci/macos/usr/local/etc/buildkite-agent/hooks/environment to reflect latest changes
