### ISSUE TITLE
How can I delete a project that could not be loaded?

### ISSUE THREAD

**Issue by bbigras** [radicle-dev/radicle-upstream#1532]
I had a problem while creating a project a while ago. I think my internet connection dropped. Now when I start radicle-upstream I got an error and I can't figure out how to delete the project so I can create it again.

Here's the error:

```json
{
  "code": "ProjectRequestFailure",
  "message": "The project rotp-public could not be loaded",
  "details": {
    "type": "defaultBranch",
    "urn": "rad:git:hwd1yrebc3yfwk8m4tw6a6a9mbpo8xgxpxj4jnr74wpus66axhj19thnfmy",
    "shareableEntityIdentifier": "%rad:git:hwd1yrebc3yfwk8m4tw6a6a9mbpo8xgxpxj4jnr74wpus66axhj19thnfmy",
    "metadata": {
      "name": "rotp-public",
      "description": "mirror of rotp-public",
      "defaultBranch": "master",
      "maintainers": [
        "rad:git:hwd1yrer9x3aup14yfbacp75mc5dwme5oh6z16f5c9xhdcpjczyfqp7k9wr"
      ]
    },
    "stats": null
  }
}
```

**Comment by FintanH** [comment]
Deleting data is unsafe at the moment until we solve https://github.com/radicle-dev/radicle-link/issues/398.

:construction:  **Use at your own risk** :construction: 

However, if you want to try to remove the reference manually you can navigate to the directory where your monorepo lives. On any machine it lives under `XDG_DATA` I believe, so specifically for my linux machine it's under `~/.local/share/radicle/git`, and on MacOS it's somewhere under `~/Library/Application Data` I think.

Once you're there you can `ls refs/namespaces/hwd1yrebc3yfwk8m4tw6a6a9mbpo8xgxpxj4jnr74wpus66axhj19thnfmy` to first check the project is there (it should be). Then you can `rm -r refs/namespaces/hwd1yrebc3yfwk8m4tw6a6a9mbpo8xgxpxj4jnr74wpus66axhj19thnfmy`. This is not a great solution but should do the job.

**Comment by bbigras** [comment]
It seems to have worked (I made a backup first). Thanks!
