### ISSUE TITLE
Radicle doesn't detect/honor gitconfig include files/directories?

### ISSUE THREAD

**Issue by dragon788** [radicle-dev/radicle-upstream#1538]
Radicle apparently doesn't understand git include directives or check the current path against those paths.

I prefer not to set a GLOBAL user.name or user.email because it leads to accidentally committing to projects with a personal email when it should be my work email or vice versa. I have specific `include` and `includeif` settings to manage my identities based on the path where I've checked out the project, allowing me to easily use one identity for FOSS projects and another for one client's projects and another for a different client.

A simple workaround/test is to do a `git init` and then check for `git config user.name` and `git config user.email` before complaining that there is no author since git itself can find/resolve the `include` and `includeif` directives.

I received this error message.

```
{
  "code": "ProjectCreationFailure",
  "message": "Could not create project: the author name for creating the project could not be found - have you configured your git config?",
  "source": {
    "response": {}
  }
}
```

The first time I got the error, it was correct, I hadn't copied my gitconfig from my dotfiles yet, but after I did that, it was still complaining.

Doing the workaround described above of `git init` in an empty directory right next to where I expected Radicle to create a repository (does that create the folder for the repository, or just `git init` inside the directory selected, that is unclear from the wording?) and I was able to run `git config user.name` and `git config user.email` in this fresh repository and see my expected values without needing to set a default/global user.name or user.email.

`~/.gitconfig`

```
[include]
        path = ~/.gitconfig.alias
        path = ~/.gitconfig.default
# If using multiple identities can use per path user/email
[includeIf "gitdir:~/projects/"]
        path = ~/.gitconfig.dragon788
```

Path I was attempting to have Radicle create a new repository in:

`~/projects/radicle-projects/`

I created a `radicle-test` folder which is where I did the `git init` and subsequent `git config user.name` and `git config user.email` and saw the correct author information.
`

**Comment by dragon788** [comment]
The other option since I can't add a "New repository" due to the gitconfig issue was to add an existing repository, so while doing that I expanded my `~/.gitconfig` to include the Radicle gitconfig `~/.local/share/radicle/git/config` for the folder I designated for my radicle projects and then did a `git init` and `touch touchme.md` and then `git add touchme.md` and `git commit -m "TouchMe"` and then I could add the "Existing project" to Radicle and I confirmed that the commit that shows up in Radicle shows my username@nodeID, which makes sense since I wasn't using Radicle to create the project, and git knows how to handle its includes.

**Comment by FintanH** [comment]
You're right, we're using this [open_default](https://docs.rs/git2/0.13.15/git2/struct.Config.html#method.open_default) to get at the `Signature` for creating the initial commit.

Since this commit is automated by us, maybe it would suffice to use the `PeerId` information for this initial signature. Then it's up to the person to configure their working copy as they please, whether through includes or the global config.

How does that sound to you @dragon788?
