### ISSUE TITLE
Seed node infrastructure

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1543]
As I'm going to be the one looking into deploying a dev seed node, I wanted to have a place to gather questions, thoughts, and answers on how to make this a more automated process and see what portions of the process will be manual.

I came up with a list of things that I thought would be involved in setting up the dev seed node, which I passed on to @xla to get his input. At this point, he brought up the question of automation and devoops.

My initial thoughts were:
```
# Setup VM Instance

Create a new instance on gcloud
- name: setzling
- type: e2-standard
- image: ubuntu minimal
- disk: seedling-state /state 1000GB

## Questions

1. Do I need to notify anyone about adding an instance, since it probably costs 
money?
2. Is there any kind of load balancer needed?
3. Do I need to expose the IPs in anyway?

# Setup Disk

- clone radicle-bins
- clone radicle-link? # don't think we need this because we don't need custom branch
- generate private key
- copy run-seed.sh script from seedling # we could commit this to the radicle-bi
ns repo
- change run-seed.sh to setzling specific details
```

And @xla's answers:
```
# Setup VM Instance

Create a new instance on gcloud
- name: setzling
- type: e2-standard
- image: ubuntu minimal
- disk: seedling-state /state 1000GB
  * Could be reduced in size for the dev needs

## Questions
1. Do I need to notify anyone about adding an instance, since it probably costs 
money?
  * No
2. Is there any kind of load balancer needed?
  * There is no load balancer in the mix of know, the firewall rules have been
    carefully tuned
3. Do I need to expose the IPs in anyway?
  * On instance creation you want to allocate an external IP, which is used in
    CLOUD DNS to route the public domain to. i.e.: setzling.radicle.xyz

# Setup Disk

- clone radicle-bins
- clone radicle-link? # don't think we need this because we don't need custom br
anch
- generate private key
- copy run-seed.sh script from seedling # we could commit this to the radicle-bi
ns repo
- change run-seed.sh to setzling specific details

***

Instead of doing all these steps again, there should be either an instance
template which can be generated for a version of the seed. Generally there are
a lot of unanswered questions how to operate more than 1 seed and equally
important what the upgrade path looks like.

* how to spin up a seed without manual labour?
* how to operate different versions of the seed?
* how to upgrade the seed binary on an instance?
* how to ensure the OS level process/service is ran/kept running?
* how to monitor primitive operations?
* how to monitor domain correct operations? (does replicate properly)
* who gets notified when service is degraded?
* who operates seed(s)? (Monadic, Foundation)
* how to enable logical seed sets? (translate SRV to multiple entries)
```

This ticket can serve as a discussion as we break out the individual questions into direct issues that we can solve.

**Comment by geigerzaehler** [comment]
I’d be interested in contributing to this discussion. Keep my posted, @FintanH, how you intend to proceed.

**Comment by FintanH** [comment]
Thanks @geigerzaehler :grin: The first thing I'm going to be looking into is the template since it seems like it's nice, low-hanging fruit -- and probably easy to iterate on.

**Comment by FintanH** [comment]
I've reviewed the template options and picked which options that I think make sense. I'm nowhere near experienced with these things so would appreciate input from @xla, @geigerzaehler, @kim, and anyone else who might have an idea on this stuff.

**Name**: `seedling`

**Machine Configuration**: e2-standard (4 CPU, 16GB)

**Container**: We could set up a container with the radicle-bins binary in it I
believe

**Boot disk**: Ubuntu 20.10 # Just choosing this because it's the latest.

**Firewall**:
  - I'm thinking we need to allow both but advice here would be appreciated
  - [x] Allow HTTP traffic
  - [x] Allow HTTPS traffic
  
**Management**:
    - **Description**: Template for our garden of seedlings
    - **Labels**: None
    - **Reservations**: use default
    - **Startup script**: I think it could be useful to have a startup script
      that checks if a key needs generating, followed by the run-script.sh
    - **Metadata**: None
    - **Availability**: Use defaults
    
**Security**: Use defaults

**Boot distk**:
    - **Delete on instance delete**: Might be a good idea to turn this off so we
      have a second chance to migrate data if needed; thoughts?
    - **Encryption**:
        - Google-managed vs Customer-managed -- not sure what we want here or
          what the trade-offs are
    - **Device name**:
        - We currently use `state` on seedling, I think it makes sense to stick
          with that.
        - New disk of 500GB SSD
        - We have a choice of Blank vs Image vs Snapshot. Wondering is _here_ is
          where we can have an image of our repo state instead of the container.
          Not sure what the difference is.
          
**Network**:
    - **Network**: `defualt` # only option
    - **Subnet**: `Auto subnet` # or should we choose eu specifically?
    - **Network tags**: None
    - **External IP**: `Ephemeral`
    - **IP forwarding**: `Off` # or do we need this On for seed ops?
    
**Sole Tenancy**: Use defaults

## Option to use Confidential VM Service
- This means that data in-use is encrypted with keys that not even Google is
  privy to
- Would need N2D machine config
- Region supporting n2d (haven't checked if Europe is one of them)
- Boot disk must be Confidential OS image
- Host maintenance must be set to "Terminate VM instance"

**Comment by geigerzaehler** [comment]
> **Machine Configuration**: e2-standard (4 CPU, 16GB)

I took a look at monitoring data from the last 30 days of the current instance. CPU usage never exceeds 10% and we are currently using 640MiB of memory. I think 2CPU/8GB should be more than enough.

> Might be a good idea to turn this off so we have a second chance to migrate data if needed; thoughts?

If we setup the VM correctly, then all essential data is stored on the attached disk and the boot disk is automatically provisioned. This means that we can delete the VM, re-create it, and attach the the old disk and everything works as expected. If this is the case we don’t need that option. That being said, we’re also not dealing with a huge automated fleet of VMs so keeping it around might be safer.

> - **External IP**: `Ephemeral`

We need to use a static IP that we connect to the DNS record. IIRC ephemeral don’t survive VM restarts.

> **Container**: We could set up a container with the radicle-bins binary in it I believe

You suggest using container images to distribute `radicle-bins` and `docker` on the VM to run the seed? I think that makes a lot of sense.

I’ll follow up with more comments later

**Comment by FintanH** [comment]
> I took a look at monitoring data from the last 30 days of the current instance. CPU usage never exceeds 10% and we are currently using 640MiB of memory. I think 2CPU/8GB should be more than enough.

Ah, great thinking! Appreciate that :)

> If we setup the VM correctly, then all essential data is stored on the attached disk and the boot disk is automatically provisioned. This means that we can delete the VM, re-create it, and attach the the old disk and everything works as expected. If this is the case we don’t need that option. That being said, we’re also not dealing with a huge automated fleet of VMs so keeping it around might be safer.

Ya, my thoughts are that it's safer to perform two deletes rather than one since one will mean losing everything in one fell swoop :sweat_smile: 

> We need to use a static IP that we connect to the DNS record. IIRC ephemeral don’t survive VM restarts.

Thanks for the catch! I misremembered what ephemeral meant.

> You suggest using container images to distribute radicle-bins and docker on the VM to run the seed? I think that makes a lot of sense.

Great! I could use a hand with how to do that, whether it's information or existing ways we do this -- so not necessarily someone holding my hand :innocent:

**Comment by FintanH** [comment]
(Sort of) being done here https://github.com/radicle-dev/radicle-bins/pull/61 and gcloud commands added to monadic-xyz repo.
