### ISSUE TITLE
Improve error text with `next`-upgrade in mind

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1560]
With the `next`-update being a breaking change there are a few experiences where we expect errors and that we could guardrail by linking to some troubleshooting text in the docs

The places we've discovered are:
- when re-adding a project that was managed by your old (pre next) identity, you'll have to remove the remotes before adding the project.
  -> `You're adding a project that is already managed by a rad id, click here to read more about how to fix this.`
- when pasting a project ID in search you got from the old (pre next) seed node, it won't be able to resolve that urn.
  -> `This project ID doesn't exist, is it possible you copied it from an old seed node? See the new seed node.`

Any other places that we might run into problems?

**Comment by juliendonck** [comment]
@cloudhead @FintanH @MeBrei @abbey-titcomb here's the issue we talked about today.

**Comment by FintanH** [comment]
> Any other places that we might run into problems?

Not that I can think of, but I'm sure we'll find out ;)
