### ISSUE TITLE
Notifications and Transaction Center overlap

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#1568]
In last week's Funding demo on the testnet, one of the most experienced issues was related to not being able to close the Transaction Center. That bug had two parts: one caused by the TS code, fixed in 08051efc75fb25cf0100177cf61ed52e181f5276; the other caused by an overlap between the notification faucet and the transaction center as you can see here:

![overlap](https://user-images.githubusercontent.com/7075260/106485733-366c7a80-64b1-11eb-9d0c-3431552a2060.png)

There are a couple of solutions we can consider:

1. Have the Transaction Center's `z-index` higher than the notification faucet
    That solves one issue and creates another, _unless_ if we set a minimum width for the whole app.

2. Set the width of the notifications faucet to be  `100vw - var(--sidebar-width) - var(--transaction-center-width) - var(--transaction-center-right-margin)` (pseudo-code).
   That would mean that the transactions would sit between the sidebar and the transaction center.
    However, for users who don't use the funding feature, the transactions would look off-place.

3. We move the transaction centre somewhere else

4. We gather the two elements in a common `div` and have them share the space appropriately.
    This seems to be the best approach. However, setting a minimum width for the whole app would
    still be relevant as having both elements in a small viewport would not work anyways. That can
    be treated as a separate issue, though.

**Comment by NunoAlexandre** [comment]
@juliendonck @brandonhaslegs would be great to get your eyes on this :eyes: :art:

**Comment by NunoAlexandre** [comment]
I'm giving option 4 a try.

**Comment by geigerzaehler** [comment]
@NunoAlexandre: My preferred option would be for the notification faucet to only be as wide as its content. I think there are more issues where the notification faucet covers clickable areas and this would fix this once and for all. (Check out `margin: auto` for a nice way to center things.)

**Comment by NunoAlexandre** [comment]
> @NunoAlexandre: My preferred option would be for the notification faucet to only be as wide as its content. I think there are more issues where the notification faucet covers clickable areas and this would fix this once and for all. (Check out `margin: auto` for a nice way to center things.)

@geigerzaehler the `margin: auto` trick only works if you have a defined area. So that wouldn't work if we need to be responsive regarding the optional presence of the Transaction Center. In any case, your suggestion would only accidentally/optimistically improve things for the end-user, as its effectiveness would depend on the size of the displayed notification, no? The solution really seems to be to have a min screen height so that all the content displayed on the screen are reachable.

I have implemented option 4 in https://github.com/radicle-dev/radicle-upstream/pull/1573.

**Comment by geigerzaehler** [comment]
>  In any case, your suggestion would only accidentally/optimistically improve things for the end-user, as its effectiveness would depend on the size of the displayed notification, no?

To some extent yes. But I don’t think it is an issue for the notifications to cover the transaction center if the notification is visible and the user can easily dismiss it.

**Comment by NunoAlexandre** [comment]
> To some extent yes. But I don’t think it is an issue for the notifications to cover the transaction center if the notification is visible and the user can easily dismiss it.

That only holds true if the displayed notification offers a "Dismiss" action though. And it's no good looking in any case.
