### ISSUE TITLE
Test "own" profile screen 

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1576]
- [ ] header contents
  - [ ] user handle
  - [ ] copyable PeerId
  - [x] new project button
- [ ] sidebar avatar
- [ ] `Projects` tab
  - [ ] there is a placeholder when no projects have been created
  - [ ] project list
    - [ ] for each project: project metadata (branch, commit, contributor counts)
- [ ] `Following` tab
  - [ ] placeholder when there are no projects
  - [ ] project list
    - [ ] for each project: project metadata (commit, contributor counts)

<img width="1552" alt="Screenshot 2021-02-02 at 13 27 41" src="https://user-images.githubusercontent.com/158411/106600255-70458b80-655a-11eb-8561-b81f8fad517b.png">

**Comment by geigerzaehler** [comment]
Tasks

- [ ] Project tests should be part of project creation test suite
- [ ] Tests for the following tab should be part of a following test suite (to be created)
- [ ] The rest should be added to the user profile test suite.

**Comment by rudolfs** [comment]
There's not much value in this at the moment.
