### ISSUE TITLE
Test Project screen header

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1577]
- projects where I'm the maintaintainer
  - [x] project title
  - [x] project description
  - [x] project ID
  - [ ] branch count
  - [ ] contributor count
  - [x] in peer selector I'm shown as the maintainer and selected by default (#1589)
<img width="1440" alt="Screenshot 2021-02-02 at 13 39 08" src="https://user-images.githubusercontent.com/158411/106601559-15149880-655c-11eb-9ef5-cf874aa6c538.png">

- projects I follow
  - [ ] project title
  - [ ] project description
  - [ ] project ID
  - [ ] contributor count
  - [x] in peer selector the original maintainer is shown and selected by default (#1589)
<img width="1440" alt="Screenshot 2021-02-02 at 13 39 21" src="https://user-images.githubusercontent.com/158411/106601564-1645c580-655c-11eb-944f-af0b290fb061.png">

**Comment by geigerzaehler** [comment]
Tasks
- [ ] Add branch and contributor count assertion to project creation test case
- [ ] On the follower side we need to create a dedicated test case for the following flow and add the assertions
