### ISSUE TITLE
Make project title clickable as a way to go back to the readme view

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1612]
Currently the only way to "reset" the project view is by clicking on "Files" in the tabs. That's not always clear as it's already selected. @cloudhead suggested we used the project title to also do this:
<img alt="Screen Shot 2021-02-10 at 16 47 03" width="611" src="https://user-images.githubusercontent.com/2326909/107533836-a371c580-6bbf-11eb-8df5-b6c5e51e11ef.png">

**Comment by NunoAlexandre** [comment]
This is low-hanging fruit, I will tackle it.
