### ISSUE TITLE
Fast file keystore for development

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1614]
When the proxy and `git-remote-rad` are build without optimization, then decrypting the keys stored in a file takes quite some time (20 seconds on my machine). This slows down development and is a particular problem when running tests since every test case that does not use the in-memory key store requires unlocking which in turn decrypts the key. A workaround is to compile with the `--release` flag and use the release build to test and develop against. However compilation with the release profile takes quite some time too, slowing down development again.

`radicle-keystore` provides a set of [test parameters](https://github.com/radicle-dev/radicle-keystore/blob/e8bfc0052c5cd2d6a68f1c69fcbc74149b9d82ac/src/crypto.rs#L44) for the key derivation function that make the encryption insecure but fast. I suggest we use that for development builds. We would need to ensure that this does not mess with production values.

**Comment by kim** [comment]
I had experimented with the trick of introducing a `test` feature, because `cfg(test)` doesn't propagate where we need it. Unfortunately, this didn't work out, because the cargo workspace solver would _always_ enable the feature as being the largest common denominator (ie. we end up with test parameters even in release builds).

It might be that the `upstream` build could be tweaked to avoid this problem, but otherwise I can't really see how to make this _safe_ -- if people build from source, there's always a chance that they accidentally initialise their keystore with the unsafe parameters. Perhaps we should thus just allow runtime selection of the parameters (via env variables)? The default would be sane, but if You Know What You're Doing(tm)...

**Comment by geigerzaehler** [comment]
I have the following concrete proposal to tackle this issue.

We want to guard usage of the test keystore by both a runtime variable (`RADICLE_UNSAFE_TEST_KEYSTORE=true`) and a compiler feature (`unsafe-test-keystore`) in Upstream. (I don’t think either one alone is enough to prevent misuse.)

To enable the test key store we need to instantiate [`FileStorage`](https://github.com/radicle-dev/radicle-keystore/blob/e8bfc0052c5cd2d6a68f1c69fcbc74149b9d82ac/src/file.rs#L46) from `radicle-keystore` with the [test crypto parameters](https://github.com/radicle-dev/radicle-keystore/blob/e8bfc0052c5cd2d6a68f1c69fcbc74149b9d82ac/src/crypto.rs#L44). This requires a change in Upstream [here](https://github.com/radicle-dev/radicle-upstream/blob/e483582a7da637d02f8e8c015ed8e4a5d53ac8f7/proxy/coco/src/keystore.rs#L63-L64) and the ability to configure the keystore of `git-remote-rad` [here](https://github.com/radicle-dev/radicle-link/blob/f916d1cde8632bb4ed87e50b03c599f6d15fcb95/git-helpers/src/remote_helper.rs#L83-L84). The change in Upstream should be straight forward.

For `git-remote-rad` I propose that [`run`](https://github.com/radicle-dev/radicle-link/blob/f916d1cde8632bb4ed87e50b03c599f6d15fcb95/git-helpers/src/remote_helper.rs#L31) accepts a configuration object which allows the caller to pass an optional `BoxedSigner`. If the signer is not provided, the current [default signer](https://github.com/radicle-dev/radicle-link/blob/f916d1cde8632bb4ed87e50b03c599f6d15fcb95/git-helpers/src/remote_helper.rs#L80-L88) is used.

An alternative to this approach would be to have the `git-remote-rad` code in `radicle-link` do the keystore selection based on the environment variable and the feature flag. This would however be less flexible for other use cases and would require us to duplicate the selection logic (environment var and feature flag) in `git-remote-rad`. This would open the possibility of the logic diverging and things breaking.

@kim: I would appreciate your feedback on this

**Comment by kim** [comment]
I don’t quite understand where the remote helper binary would evaluate the
environment variable. For some reason, we build it multiple times, both in
upstream and in link (for testing), so the logic would be duplicated either
way?

Perhaps with the global daemon model we can just teach that to accept
pushes over HTTP, so we can deprecate the remote helper anyway.

**Comment by geigerzaehler** [comment]
radicle_git_helpers::remote_helper> I don’t quite understand where the remote helper binary would evaluate the environment variable. 

Handling of the environment variable (as well as guarding it with a feature flag) would happen in the [Upstream wrapper](https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/api/src/bin/git-remote-rad.rs) for `git-remote-rad`. The boxed signer would be created there and passed as a configuration parameter to `radicle_git_helpers::remote_helper::run`.

> For some reason, we build it multiple times, both in upstream and in link (for testing), so the logic would be duplicated either way?

That’s possible and an argument for keeping the logic in `radicle_git_helpers::remote_helper`. On the other hand, if we duplicate the selection logic only for tests in radicle link this wouldn’t mean that differences will break the tests in upstream. This would however be the case if upstream _relies_ on the selection logic that is provided by `radicle_git_helpers::remote_helper`. Taking this into account I’d still prefer to have the flexibility of configuring the `BoxedSigner`.

**Comment by kim** [comment]
Makes sense. We don't even _need_ config selection in link, because it should
always be the fast settings.
