### ISSUE TITLE
Feature request: peer status screen

### ISSUE THREAD

**Issue by viraptor** [radicle-dev/radicle-upstream#1626]
Sometimes it's hard to tell if the client is connected to the seed / anyone.

The hover text over the icon says only "You're connected to 2 peers.", but it seems to count also attempted connections which keep timing out (or maybe I'm mistaken?)

It would be great if clicking the peers/network icon provided a screen with information like:

- address of peer
- connection state (connecting, established, etc.)
- is it a seed?

(the manually configured seeds should be visible all the time so it's easy to see when they're disconnected)

**Comment by rudolfs** [comment]
Does the [network diagnostics screen](https://github.com/radicle-dev/radicle-upstream/pull/1758) resolve this issue?
You can access it via <kbd>⌘</kbd>+<kbd>1</kbd> in `v0.2.6`.

**Comment by juliendonck** [comment]
related to #1066

**Comment by rudolfs** [comment]
Feel free to reopen the issue, if you think it's not covered by: https://github.com/radicle-dev/radicle-upstream/issues/1626#issuecomment-865162931.
