### ISSUE TITLE
refactor(ui): support dependency-injection in modals

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#1629]
### The problem

The current setup for modals requires the use of svelte stores as the means to pass data to a modal instance.
Opening a modal, thus, usually looks something like this:

```
Screen:
   function openModal() {
      someStore.set(someDataTheModalNeeds);
      modal.toggle(path.modal())
   }

Modal:
  import { someStore } from "some-module";
  
  // check if `someStore` is set and handle it accordingly if not
```

For some cases, we can be sure - at compile and at runtime - that the value the store holds is always set.
For example, if the store holds a string and the default value is the empty string, `""`, the modal 
can operate independently of that value.

Things get more complicated to guarantee in scenarios. For example, in the Funding Pool modals
we need to access the `pool` instance. 

Again, the whole way to pass this instance onto the modals is by setting it in a store. Because the 
pool is only instantiated once there is a connected wallet, we need to consider that there might be no 
pool instance at all, at least at the type level. That results in the specific store being of type `Pool | undefined`. 

Now, in the modals that make use of said pool instance, they are left with that uncertainty: is there a pool instance, or not?

In sum, this setup creates undesired boilerplate by requiring the usage of stores to pass values to modals which, in turn, creates an undesired level of complexity on the modals to handle stores being possibly not set.

### Proposal

Ideally, we would pass arguments to modals the same we do with screens: through dependency injection.
That would mean that the snippet above would look like:

```
Screen:
   <Modal data={someDataTheModalNeeds}/>

Modal:
   export let data: T;

  // There is no way but for `data` to be defined;
```

This pseudo-code/example is obviously naive. For instance, it raises the question of how we could open modals when a button is clicked, or how we would control/avoid having stacked modals. That is something we need to define as a requirement for this exploration.

### Requirements

- Allow for dependency injection of arguments to modals
- Allow for control of having a single modal open at a time
- Allow for modals to be open on click events and/or from plain javascript code (i.e, not only within a svelte block)

**Comment by NunoAlexandre** [comment]
Regarding prioritization, I find that we have bigger fish to fish. However, shall we have some slack or headspace to work on something of this nature that would cut down some complexity and boilerplate, I'd be eager to explore this or invite someone else to.

**Comment by geigerzaehler** [comment]
Thanks for the writeup @NunoAlexandre. 

As an alternative to opening the modal declaritively with a `Modal` component we should consider opening the modal with a function call like `myModal.open(someData)`. This would satisfy the third requirement you mentioned.

Another requirement to consider is that often modals also return values, for example if you prompt for an input. (I don’t know if there’s a concrete case of this in the app though.) This is something that we should consider in the design but don’t need solve immediately.
