### ISSUE TITLE
Unclear Following UX

### ISSUE THREAD

**Issue by BogdanDidenko** [radicle-dev/radicle-upstream#1640]
After following the first project on Following Tab, I lost the ability to follow other projects from this Tab.

**Comment by FintanH** [comment]
Can you clarify what you mean? What were the steps you took within the client?

Thanks

**Comment by BogdanDidenko** [comment]
> Can you clarify what you mean? What were the steps you took within the client?
> 
> Thanks

The first time I interacted with this tab, there was a "Look for a project" button. 


![image](https://user-images.githubusercontent.com/11133686/109438329-328d3300-7a32-11eb-8283-ea7b47370274.png)

After adding the first project, there is no way to add new projects to the following projects list.


![image](https://user-images.githubusercontent.com/11133686/109437959-4e8fd500-7a30-11eb-87c7-fb26d9fa1f14.png)

**Comment by rudolfs** [comment]
> After adding the first project, there is no way to add new projects to the following projects list.

Right. After adding the first project, subsequent ones can be added by opening the "Navigate to a project" sidebar item (magnifying glass icon). Or via the <kbd>⌘</kbd>+<kbd>p</kbd> shortcut.

Probably something @juliendonck & @brandonhaslegs should look into.

**Comment by BogdanDidenko** [comment]
> > After adding the first project, there is no way to add new projects to the following projects list.
> 
> Right. After adding the first project, subsequent ones can be added by opening the "Navigate to a project" sidebar item (magnifying glass icon). Or via the ⌘+p shortcut.
> 
> Probably something @juliendonck & @brandonhaslegs should look into.

Yes, I eventually came to this approach) But it was not intuitive, and I found the solution almost at random.

**Comment by brandonhaslegs** [comment]
How about adding this bit of text and button at the end of the list?

The button would just open the search modal (same as clicking the pink "Look for a project" button, or clicking the 🔍 icon in the sidebar) 

![image](https://user-images.githubusercontent.com/4406983/110779915-66532e80-8264-11eb-8eb5-1d6d26b927f3.png)
