### ISSUE TITLE
Unable to checksum the downloaded release

### ISSUE THREAD

**Issue by ltfschoen** [radicle-dev/radicle-upstream#1643]
i'd like to start using radicle, but first i'd like to be able to validate the checksum of the latest release (i.e. `shasum -a 256 filename.dmg`, and it should match a checksum) to ensure that a hacker hasn't intercepted the download

**Comment by geigerzaehler** [comment]
Hey @ltfschoen :wave:. Seems very reasonable to also provide checksums. I suggest we post them as part of the release announcements on radicle.community and also add them to https://radicle.xyz/downloads.html.
