### ISSUE TITLE
Debug console in Radicle Client

### ISSUE THREAD

**Issue by abarmat** [radicle-dev/radicle-upstream#1645]
I'm having some issues now where a project is not being synced and I wonder what the real reason is. I find it hard to debug as I don't have a debug console to see if it is a connection issue, or any other error.

I think including a debug console could help people debugging some issues or report them easily.

I'm using the Mac version of the Radicle client.

**Comment by rudolfs** [comment]
Hey @abarmat. You can get all the backend debug logs by running the application from a terminal, like so:
```
/Applications/Radicle\ Upstream.app/Contents/MacOS/Radicle\ Upstream
```
They'll be logged to STDOUT and STDERR in the terminal.

There's also a console where you can look at the UI logs, you can see it via <kbd>⌘</kbd>+<kbd>i</kbd>.

**Comment by abarmat** [comment]
Good to know, thank you. command+i is not working for me but I can see the logs from the terminal.

**Comment by rudolfs** [comment]
> Good to know, thank you. command+i is not working for me but I can see the logs from the terminal.

Oops, I meant <kbd>command</kbd>+<kbd>option</kbd>+<kbd>i</kbd>.

**Comment by abarmat** [comment]
That works :)
