### ISSUE TITLE
Release process suggestions

### ISSUE THREAD

**Issue by bzz** [radicle-dev/radicle-upstream#1654]
Thank you for documenting the [CI and development process](https://github.com/radicle-dev/radicle-upstream/blob/master/DEVELOPMENT.md) in great detail!

It would be absolutely amazing not only to do #1643 but also to:
 - [x] include updates of the [brew cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/radicle-upstream.rb#L3) (#1671)
 - [ ] attach checksums and DMGs on Github as release artefacts
 - [ ] provide a simple way of finding radicle-upstream project (a RadicleID?) from it's description on Github, inside the upstream app itself to simplify the onboarding/discovering (ideally, that will eventually be replaced by the special [links on the web](https://radicle.community/t/opening-upstream-via-links-on-the-web/1856))

All that would allow new users to gain credibility and try out the project even faster.

I will be happy to contribute some of the above if you think it is worth looking into and point me to the right direction for CI the current release process automation.

Thanks again!

**Comment by geigerzaehler** [comment]
Thanks for the input @bzz! 

> provide a simple way of finding radicle-upstream project (a RadicleID?) from it's description on Github, inside the upstream app itself to simplify the onboarding/discovering (ideally, that will eventually be replaced by the special [links on the web](https://radicle.community/t/opening-upstream-via-links-on-the-web/1856))

Work on links on the web is progressing nicely so I think this point is covered there.



> attach checksums and DMGs on Github as release artefacts

As you mentioned, checksums are already covered by #1643. We already upload the release artifacts to a `releases.radicle.xyz` so for us there’s no real need at the moment to also upload it to Github. That being said, if the process is mostly automated we would definitely included it.





> include updates of the [brew cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/radicle-upstream.rb#L3)

That sounds like a great idea!

If you want to contribute, you can start by adding instructions for calculating checksums and updating the brew cask to our [release script](https://github.com/radicle-dev/radicle-upstream/blob/master/scripts/release.ts#L139-L182). Uploading releases to Github should be fully automated through a script. You can also build on some of the code in our release script.

**Comment by bzz** [comment]
Thanks for you kind explanations, @geigerzaehler !

>> provide a simple way of finding radicle-upstream project from it's description on Github
>
> Work on links on the web is progressing nicely so I think this point is covered there.

Makes sense. Could you help me understand if there any obvious downsides of adding a RadicleID to the README in the meanwhile? 


>> include updates of the brew cask
>
> ... adding instructions for calculating checksums and updating the brew cask to our release script. 

Added in #1671.

**Comment by geigerzaehler** [comment]
> Makes sense. Could you help me understand if there any obvious downsides of adding a RadicleID to the README in the meanwhile?

I may have misunderstood you. Are you suggesting to put the Radicle URN of the `radicle-upstream` repo (the mirror of this repo) into the README so that you can find this repo on Radicle itself?

**Comment by bzz** [comment]
> > Makes sense. Could you help me understand if there any obvious downsides of adding a RadicleID to the README in the meanwhile?
> 
> I may have misunderstood you. Are you suggesting to put the Radicle URN of the `radicle-upstream` repo (the mirror of this repo) into the README so that you can find this repo on Radicle itself?

I'm sorry for confusing explanation! Yes, that's what I had in mind.

The motivation behind was to improve the onboarding experience to the Radicle platform for a new user. After discovering the project, checking it's status on the popular code forge (e.g. github) and installing the Upstream client - it would be really nice to allow for something useful to happen when user launches the Upstream client for the first time, e.g. to open radicle-upstream project itself, thus motivating user to spend time with the project and hopefully, eventually, contribute.

Right now doing that is not trivial - visiting http://seedling.radicle.xyz/ and filtering for `upstream` results in at least 8 projects, all with the same name and without a clear path towards understand which one of those tracks the state of official Github.
