### ISSUE TITLE
111

### ISSUE THREAD

**Issue by hugdag11** [radicle-dev/radicle-upstream#1655]
import hashlib as hasher
 
class Block:
  def __init__(self, index, timestamp, data, previous_hash):
    self.index = index
    self.timestamp = timestamp
    self.data = data
    self.previous_hash = previous_hash
    self.hash = self.hash_block()
  
  def hash_block(self):
    sha = hasher.sha256()
    sha.update(str(self.index) + 
               str(self.timestamp) + 
               str(self.data) + 
               str(self.previous_hash))
    return sha.hexdigest()

**Comment by FintanH** [comment]
Not sure what you're trying to convey here, so I'm going to close this ticket. Feel free to re-open with clearer information.
