### ISSUE TITLE
Support importing/exporting seed list for reusing

### ISSUE THREAD

**Issue by clearloop** [radicle-dev/radicle-upstream#1656]
I'm not familiar with p2p, but it seems more seeds we have connected, the network comes more stable, it would be nice to have a button on upstream or some shell scripts that can help users sharing seed lists with each other.

https://github.com/radicle-dev/radicle-upstream/blob/9770b08a5c0df7738702db96caae07b9c34a4f5a/proxy/api/src/session.rs#L32

Or some rust binary tools since radicle stores seeds using `rust-kv`?

Or store the list into a file, that easy to replace?

**Comment by rudolfs** [comment]
Does the [network diagnostics screen](https://github.com/radicle-dev/radicle-upstream/pull/1758) resolve this issue?
You can access it via <kbd>⌘</kbd>+<kbd>1</kbd> in `v0.2.6`.

**Comment by rudolfs** [comment]
At the moment we don't support gossip seeds. We'll re-evaluate the import/export once we implement the gossip transport.
