### ISSUE TITLE
Some tools for checking or logging the p2p status of the upstream

### ISSUE THREAD

**Issue by clearloop** [radicle-dev/radicle-upstream#1657]
I've set up my seed node and wrote it (and the official seed) into the seed list of my radicle-upstream for 3 days, the UI popups `You're not connected to any peers` all the time.

I need to find out what happened to my rad-upstream but don't know how to start it.

**Comment by rudolfs** [comment]
Does the [network diagnostics screen](https://github.com/radicle-dev/radicle-upstream/pull/1758) resolve this issue?
You can access it via <kbd>⌘</kbd>+<kbd>1</kbd> in `v0.2.6`.

**Comment by rudolfs** [comment]
Feel free to reopen the issue, if you think it's not covered by: https://github.com/radicle-dev/radicle-upstream/issues/1657#issuecomment-865164711.
