### ISSUE TITLE
Consistent validations

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#166]
Follow up issue of #119 

We currently use `validate.js` for validations in ui. The same logic has to be repeated in each component where it is used and custom validation and error handling add to its complexity. At the time of closing #119 there was no svelte library that would be feasible to use.

- [ ] investigate validation libraries
- [ ] extract ui validation logic as much as possible
- [ ] avoid mismatched validations and define authorities of validation between ui and API

**Comment by sarahscott** [comment]
We should think about validating with respect to the needs of the registry, as transactions will fail if certain constraints aren't met. Ideally we would have one source of truth for what registry-legible data looks like (e.g. instead of having regular expressions defined all over the app, we would pull them from proxy as-needed).

We already have [specs for registry data](https://github.com/radicle-dev/registry-spec/), so this might be a good place to start.

Also, we copy & paste a lot of validation code in our components. Here's an overview of what validation looks like app-wide:

![Screen Shot 2020-04-22 at 3 30 23 PM](https://user-images.githubusercontent.com/2712962/80042379-ab873a00-84b3-11ea-85ea-76bc51e04e4d.png)

Perhaps a reactive `validations` store would be a better approach?

**Comment by MeBrei** [comment]
### Idea for moving the validations into the proxy

Currently most validations live in the ui and some of them have diverged from those in the protocol. In the proxy, before transactions are sent to the registry, little validations happen so that the api relies on the ui to provide the correct data. This concepts aim is to consolidate the validations in the proxy and provide an endpoint for the ui to consume the validations. This will prepare for eventually deriving validations from the protocols. 

Idea: A path prefix `validations` is introduced that would be prepended to each post request we need validations for in the ui. Similar like the current `control` prefix, but the `filters` of the original post requests should be used to not add duplication and diverging paths. Validations are added to the original post request handlers. Whenever the request goes over the `validations` path, only the validations are executed (not the actual sending of the transaction), by for example passing a validation flag. Failing validations would return a validation error with a message that could be consumed in the ui to display the error message in forms.  Some validations could still remain in the ui (like input presence)

**Comment by rudolfs** [comment]
Not sure if pushing validations back to the proxy is worth the effort right now. It seems to me that it would only pay off if we did all validations for every field in one place and not validate some things in the proxy and others in the UI.

Would we provide the validation messages via the API then as well?

I also wonder how we would handle more complex validations for forms where the fields depend on each other, like in project creation where the form is only valid if the project name is valid and the chosen repository exists and is not already managed by radicle?

**Comment by MeBrei** [comment]
> Not sure if pushing validations back to the proxy is worth the effort right now. It seems to me that it would only pay off if we did all validations for every field in one place and not validate some things in the proxy and others in the UI.

Yes, I think it only makes sense if we move all validations to the proxy. My last comment was more referring to hold off querying the validations if eg the form is empty and thus the ui validating that the appropriate fields are filled out.

> Would we provide the validation messages via the API then as well?

yes, the validation message would be directly taken from the error message.
> I also wonder how we would handle more complex validations for forms where the fields depend on each other, like in project creation where the form is only valid if the project name is valid and the chosen repository exists and is not already managed by radicle?

For that particular validation, we might keep the request that validate the repository, the project name could have the validations as described above. But I see your point that a more complex form might require multiple validation error messages.

**Comment by FintanH** [comment]
One pro of having validation happening in one place is that you could gather as many as possible using something like https://github.com/Keats/validator. So at least when errors happen you get back a list of the errors that happen.

Also, proxy will have to validate input into domain types to pass them along regardless so it seems like a good place for doing this logic.

**Comment by sarahscott** [comment]
I think we should figure out a solid approach to validation and this seems like a step in the right direction. As @FintanH suggested, we could implement something that allows for multiple error states for our more complex forms.

**Comment by geigerzaehler** [comment]
@MeBrei: Could you review this again and determine what remains to be done?

**Comment by rudolfs** [comment]
@geigerzaehler should we close this one and revisit the topic next time we touch the validation code?

**Comment by geigerzaehler** [comment]
Sounds good. I know very little about the validation logic.
