### ISSUE TITLE
Register project mutation regression

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#167]
To reproduce:
```sh
yarn start
yarn graphiql
```

Request:
```graphql
mutation MyMutation {
  registerProject(orgId: "test", projectName: "test") {
    id
    timestamp
    messages {
      ... on ProjectRegistration {
        projectName
        orgId
      }
    }
    state {
      ... on Applied {
        block
      }
    }
  }
}
```

Response:
```json
{
  "data": null,
  "errors": [
    {
      "message": "watch_extrinsic stream terminated",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "registerProject"
      ],
      "extensions": {
        "type": "RADICLE_PROTOCOL"
      }
    }
  ]
}
```

Proxy log:
```
 WARN  jsonrpc_client_transports::transports::duplex > The response does not have expected subscription id in response: Num(8) ("author_extrinsicUpdate"): Err(JsonRpcError(Error { code: ServerError(1002), message: "Verification Error: Execution(ApiError(\"Could not convert parameter `tx` between node and runtime: No such variant in enum Call\"))", data: Some(String("RuntimeApi(\"Execution(ApiError(\\\"Could not convert parameter `tx` between node and runtime: No such variant in enum Call\\\"))\")")) }))
```

**Comment by NunoAlexandre** [comment]
@rudolfs @xla I'm hoping to understand what is going on here. I'm new to graphql and read some docs to get an idea of what this is doing.

The `proxy > tests > graphql_mutation.rs > register_project` test works correctly and it issues the following query mutation:

```
let query = "mutation($projectName: String!, $orgId: String!) {
                        registerProject(projectName: $projectName, orgId: $orgId) {
                            messages {
                                ... on ProjectRegistration {
                                    projectName,
                                    orgId
                                }
                            },
                        }
                    }";
```

The query looks good, so this tells _me_ that the registry client is working correctly.

No `id` or `timestamp` is passed here, contrary to the one issued in the description of this issue. Why is that nuance? What's the difference between the two queries to have those two params in one and not in the other?

**Comment by xla** [comment]
> No `id` or `timestamp` is passed here, contrary to the one issued in the description of this issue. Why is that nuance? What's the difference between the two queries to have those two params in one and not in the other?

That's a good find. The reason we don't pass these in the tests is, that they are vairable and can't be easily asserted. I added it in the test to see if it produces the same behaviour but it doesn't seem to do so.

**Comment by xla** [comment]
To complete that statement, the tests fail, but only because we don't expect `id`, `timestamp` and `state` to be in the response.

**Comment by rudolfs** [comment]
Running this mutation via GraphiQL without `id` and `timestamp` also gives me the same error.

**Comment by NunoAlexandre** [comment]
@rudolfs I just ran the mutation tests with the `id` and `timestamp` params and it did not fail to process the transaction, it just failed due to the expected result being different:

```

Diff < left / right > :
 Object(
     Object {
         key_value_list: [
             (
                 "registerProject",
                 Object(
                     Object {
                         key_value_list: [
                             (
<                                "id",
<                                Scalar(
<                                    String(
<                                        "0x9304…8972",
<                                    ),
<                                ),
<                            ),
<                            (
<                                "timestamp",
<                                Scalar(
<                                    String(
<                                        "1582186221",
<                                    ),
<                                ),
<                            ),
<                            (
                                 "messages",
                                 List(
                                     [
                                         Object(
                                             Object {
                                                 key_value_list: [
                                                     (
                                                         "projectName",
                                                         Scalar(
                                                             String(
                                                                 "upstream",
                                                             ),
                                                         ),
                                                     ),
                                                     (
                                                         "orgId",
                                                         Scalar(
                                                             String(
                                                                 "monadic",
                                                             ),
                                                         ),
                                                     ),
                                                 ],
                                             },
                                         ),
                                     ],
                                 ),
                             ),
                         ],
                     },
                 ),
             ),
         ],
     },
 )
```


The query being

``` rust
let query = "mutation($projectName: String!, $orgId: String!) {
                        registerProject(projectName: $projectName, orgId: $orgId) {
                            id
                            timestamp
                            messages {
                                ... on ProjectRegistration {
                                    projectName,
                                    orgId
                                }
                            },
                        }
                    }";
```

**Comment by xla** [comment]
> That's a good find. The reason we don't pass these in the tests is, that they are vairable and can't be easily asserted. I added it in the test to see if it produces the same behaviour but it doesn't seem to do so.

@NunoAlexandre My find as wel --^

**Comment by NunoAlexandre** [comment]
I was curious whether this error was thrown because we are trying to register a project under an org that doesn't yet exist but it doesn't seem to be the case.

I am implementing a `register_org` mutation to see what happens if we try to just register an org, given that there are fewer pieces involved in that transaction.

**Comment by NunoAlexandre** [comment]
Doesn't work either. I will run some tests on the registry side and get back to you asap.

**Comment by xla** [comment]
@NunoAlexandre Thanks for the update, lemme know if you need assistance.

**Comment by NunoAlexandre** [comment]
Everything appears fine on the registry side. The error message is related to `jsonrpc`, and so it seems that's really the layer where the issue is taking place.

I found that Thomas faced a [similar issue](https://github.com/paritytech/substrate/issues/3849) a few months back. @geigerzaehler, do you remember how you fixed that? or do you have any clue as to why we are facing this one and what we can do? I'm running out of ideas.

**Comment by geigerzaehler** [comment]
I believe that the issue is that the client version used in upstream is not compatible with the most recent runtime that is deployed on the devnet

**Comment by NunoAlexandre** [comment]
Is the upstream using the devnet? That surprises me but brings sense to this issue.

> Simply updating the client here should fix the issue. 

Not sure if you mean to update the version of the registry client that `upstream` is using or updating the registry `client` to use the latest runtime?

**Comment by NunoAlexandre** [comment]
It works after bumping the `radicle-registry-client` 👌 @rudolfs @xla, I will raise a PR in a moment.
