### ISSUE TITLE
org-mode support in readmes

### ISSUE THREAD

**Issue by slondr** [radicle-dev/radicle-upstream#1670]
Feature request: GitLab etc supports org-mode in Readmes, currently Upstream doesn't so readmes look kinda weird.

**Comment by NunoAlexandre** [comment]
@slondr could you paste an example of a project that I could look into?

**Comment by slondr** [comment]
Yes I'm referring to that org-mode. By example do you mean a project which uses org-mode for a readme, or a project that could parse org-mode and display it in an html context?
