### ISSUE TITLE
Move Network settings to Network page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1696]
Task:
Simply move the settings to their own page. Nothing else (for now).

Reasoning:
- When you are connected to a lot of seeds, the list of seeds is very long and hides other settings below and generally just takes up a ton of space
- The network icon in the sidebar looks like a page because it's in the navigation, but is just a status indicator
- If we put it on it's own page now, we can develop the Network page later into something more robust (health indicator, projects list, connected peers, whatever)

**Comment by rudolfs** [comment]
A follow-up here should be to update the docs as well: https://docs.radicle.xyz/docs/using-radicle/adding-a-seed-node.
