### ISSUE TITLE
Orgs I & Identities I feature scoping

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#171]
Let's collectively review the `Orgs I` and `Identities I` spec and UX flows.
- [Basic User Identity](https://www.notion.so/monadic/Basic-User-Identity-0688a802e65040778a459892d6922919)
  - [Shareable Entity Identifiers](https://www.notion.so/monadic/Shareable-Entity-Identifiers-406a170c78f241238caef9affa11b4f1)
  - [User Registration](https://www.notion.so/monadic/User-Registration-6bcb1ebd6f334d0290c95c5a05f54649)
- [Org Overview](https://www.notion.so/monadic/Overview-adab284a260c408a9332e0ea2866b505)
  - [Org Registration](https://www.notion.so/monadic/Org-Registration-63b114e42b04468b9d4c30bf01f3cfc3)
  - [Org Profile](https://www.notion.so/monadic/Org-Profile-99f510b140034ca1895bf9d97f347588)
  - [Shareable Org IDs](https://www.notion.so/monadic/Shareable-Org-IDs-b164a64abe674c268368fececa9025c4)
  - [Project Registration](https://www.notion.so/monadic/Project-Registration-a8e8125af6654ee28655c0af80254c4d)
  - [Member Registration](https://www.notion.so/monadic/Member-Registration-4358e742c9d446c18eb9ec67dc858884)

Please add your collected questions around this feature as comments to this issue.

**Comment by MeBrei** [comment]
On **Org-Registration**
- [basic user identity](https://www.notion.so/monadic/Basic-User-Identity-0688a802e65040778a459892d6922919) is a preliminary of this
- regarding error conditions
   - will they only be checked after initiating the registration process, or should they be checked, when entering the org name?
   - if I only learn about the error after the modal is closed, do I have to start the registration process again from the beginning, or do I get directly to the enter-name modal?

On **Org Profile**
- is the `fund` page part of the beta release? Do I register an org from my own funds, but then the org has separate funds (to register a project for example)?

On **Shareable Org IDs**
- is there a figma screen for the "designated place" for entering a org id?
- Where do I copy the user/org ids from (couldn't find them in figma)

On **Project Registration**
- Does this mean that for now I can only register a project if I am a member of an org?

On  **Member Registration**
- only "registered" users can be added. Is there a flow for registering as a user?

**Misc**
- What is now shown in the sidebar? myself (leading to my projects or my profile?) & orgs that  am a member of?
- Do the views for user profiles now change, showing which orgs they are a member of etc.?

**Comment by rudolfs** [comment]
> basic user identity is a preliminary of this

Yes, added it to the issue description.

> will they only be checked after initiating the registration process, or should they be checked, when entering the org name?

As I understand it, we can query the registry for existing names already before initiating the transaction. But we don't have a guarantee that the transaction will succeed in the case when two different people request the same name at the same time. In this case one of the requests will fail, and the other succeed.

**Comment by rudolfs** [comment]
> basic user identity is a preliminary of this

Yes, added it to the issue description.

> will they only be checked after initiating the registration process, or should they be checked, when entering the org name?

As I understand it, we can query the registry for existing names already before initiating the transaction. But we don't have a guarantee that the transaction will succeed in the case when two different people request the same name at the same time. In this case one of the requests will fail, and the other succeed.

**Comment by MeBrei** [comment]
early issue idea: 

As the layout and functionality of the current `ProjectTopbar` will also be used for Orgs, we should abstract the layout (currently defined in `Project` directly) and the topbar components.

**Comment by juliendonck** [comment]
> As the layout and functionality of the current ProjectTopbar will also be used for Orgs, we should abstract the layout (currently defined in Project directly) and the topbar components.

Yes and also on the profile page for that matter. But I do think in the long run, we will probably have a more expanded topbar for orgs and profiles (see image below), but maybe not for projects.

<img width="1508" alt="Screenshot 2020-02-20 at 17 14 39" src="https://user-images.githubusercontent.com/2326909/74955200-92ef9a80-5404-11ea-88aa-71d0e7a20b2e.png">

**Comment by rudolfs** [comment]
### Basic User Identity
  - where is the handle, display name and avatar url stored until we're registered on chain?
  - the create identity modal has a "x" and "cancel" buttons, what happens if we don't have an identity and skip creating it on app start?
  - is there a visual distinction between a registered and unregistered user identity?
  - what creates the identity, registry or coco or something else?
  - can we change the handle before registering on chain (if it is not available for example)?
  - it looks like we'll have a chance re-thing how we do routing in the UI because of the new identifiers: https://www.notion.so/monadic/Shareable-Entity-Identifiers-406a170c78f241238caef9affa11b4f1, it was already on my todo-list to write an issue about the shortcomings of the existing router. Would be cool if we had a dedicated parser for this.

### Orgs
#### Overview
  - there was a discussion about registering a project separately from registering it on an org, how was that resolved?
  - can you change the locked amount on the fly? for example if I want to register more projects than I anticipated when I created the org
  - is there a spec on how to generate the placeholder avatars?
  - how much of the wallet functionality do we need to implement this quarter? Or do we still just mock it all out?

#### Org Registration
  - UX: when typing in the name for an org, at what point should we run the validation to check if it exists?
  - UX: what visual feedback can we give the user to show that we're checking if a name exists already (this probably isn't instantaneous)?
  - UX: the step counter is confusing as there are 3 steps in total, but the counter only shows "prepare" and "submit"
  - UX: can I only add myself as the org member?
  - UX: what does that green checkmark mean?
  - UX: once we leave the transaction summary screen, we directly land in the project screen, I assume we just use the cached data while the transaction is being validated. What happens if the user closes and opens the app before the transaction has been validated? Do we need to cache the org data in the meantime?

#### Shareable Org IDs
  - at what point in time after registering an org can we get the sharable ID and when can another user on another machine query for it in the registry?
  - UX: missing the flow (where do we paste the link, etc?)


#### Org Profile
  - where do we store the list of all branches for a registered project?
  - when does checkpointing happen (to update the number of commits on the default branch)?
  - what do we show if the org profile is not available (can't connect to the network for example)?
  - can we get all the data that is required to show the profile (including all registered projects) in one go?
  - UX: how does the "..." menu for the org list item look like?
  - UX: why do we have "+ New project" and the same functionality under "..." duplicated in the topbar?

#### Project Creation
  - note: looks like most of the flow is already implemented (we still don't display the project ID anywhere in the UI)
  - UX: is there a visual difference between new locally created project and a registered one?

#### Project Registration
  - when registering a new repo, how do we do roll-backs in coco when registry fails?
  - UX: what does the visual feedback look like for when we check availability of the name?

#### Member Registration
  - UX: is there visual feedback in the input field when entering a member name and the system is searching for the member in the background? At what point does the UI know to check?

**Comment by rudolfs** [comment]
@MeBrei and I just sat down for a spec-breakdown session. We figured out a nice way to isolate individual work packages. And we're in the process of writing everything down into issues. The issues should be ready by Tuesday the 3rd of March.

Here's a photo of our process:
![IMG_6793](https://user-images.githubusercontent.com/158411/75051463-348eee80-54ce-11ea-8379-be066776c6d4.jpg)

The work will be roughly split up into API definition, business logic modules and visuals. This is only work for the UI side of things.

Here's some additional questions we came up with for @juliendonck:
   - what does the hover state in the new sidebar look like?
   - how does avatar hover state look like?
   - animation visuals for user handle avatar generation and availability check, what does the user handle is unavailable state look like?
   - what do the animation visuals for avatar generation look like?
   - does my user profile look different from another user's profile? what does the menu bar look like on another user's profile?
  - is the top bar always present in all layouts across the app?
  - what do the animations for transaction state changes look like?
  - what do the `...` button menu hover states and animation look like?
  - do we have something like breadcrumbs or visual "back" buttons for navigation?
  - what happens when a transaction succeeds but I'm not on a page that is displaying the data related to that transaction?
    - maybe the transaction floater turns green? and offers a link to the updated page?

**Comment by juliendonck** [comment]
> - what does the hover state in the new sidebar look like?

It's illustrated [here](https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=3346%3A202)

> - how does avatar hover state look like?

Also on the same page as above

> - animation visuals for user handle avatar generation and availability check, what does the user handle is unavailable state look like?

Illustrated [here](https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=3485%3A21067)

> - what do the animation visuals for avatar generation look like?

this will depend on how and when we generate these, @cloudhead was gonna figure this out.

> - does my user profile look different from another user's profile? what does the menu bar look like on another user's profile?

I think for now yes, but these two will converge. So if you want to plan ahead I would plan on them being different.

> - is the top bar always present in all layouts across the app?

No, the search results page and network tab will not have a topbar.

> - what do the animations for transaction state changes look like?

[This page](https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=3346%3A202) shows you the different states, I can make a little prototype on how this will animate or we can just chat about it.

> - what do the ... button menu hover states and animation look like?

Is illustrated [here](https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=3340%3A2), can go into more detail if necessary.

> - do we have something like breadcrumbs or visual "back" buttons for navigation?

Right now I don't think so, I would love for the typical back button (mousepad swipes, mouse button, etc) to work. we can think of breadcrumbs/back buttons when we need to.

> - what happens when a transaction succeeds but I'm not on a page that is displaying the data related to that transaction? maybe the transaction floater turns green? and offers a link to the updated page?

The "floater" should direct you to the transaction, since that's what's succeeding or failing.

**Comment by rudolfs** [comment]
> Right now I don't think so, I would love for the typical back button (mousepad swipes, mouse button, etc) to work. we can think of breadcrumbs/back buttons when we need to.

Cool, we already have an issue for it: https://github.com/radicle-dev/radicle-upstream/issues/140, will prioritise it accordingly.

**Comment by rudolfs** [comment]
Closing this issue, as it is mostly notes of the requirements engineering process and the remaining tasks are tracked in: https://github.com/radicle-dev/radicle-upstream/issues/277.
