### ISSUE TITLE
Can't change default branch for a project

### ISSUE THREAD

**Issue by smartcontracts** [radicle-dev/radicle-upstream#1725]
I can't seem to find any way to change the default branch for a project. I accidentally set the wrong default branch and seem to be stuck with this branch now. I saw that https://github.com/radicle-dev/radicle-upstream/issues/1058 exists but it seems that's more w.r.t. renaming the default branch and not changing it entirely.

Specs:
- `radicle-upstream@0.1.13`
- macOS 11.2.1

**Comment by FintanH** [comment]
Hey @smartcontracts, sorry to be the bringer of bad news but this is currently not supported. The changing of a document, which changing the default branch counts as a change, requires the signing and verification of the changes. This is only properly done in the upcoming changes and will need adding to the API for Upstream to call.

**Comment by smartcontracts** [comment]
Some other UI notes:
- I can't seem to remove a project from the UI. Not sure if that's intentional or not but it's a bit confusing.
- Project discoverability needs some work but I think I've seen others make issues about it.
- The `light` theme is a bit hard on the eyes. It's quite bright. Dark theme is somewhat difficult to navigate too.

**Comment by FintanH** [comment]
> I can't seem to remove a project from the UI. Not sure if that's intentional or not but it's a bit confusing.

Deletion is a bit tricky because we're using git as the data storage. You can see this ticket for more info: https://github.com/radicle-dev/radicle-link/issues/398

**Comment by smartcontracts** [comment]
> Deletion is a bit tricky because we're using git as the data storage. 

Honestly even the option to "hide" a project from the main view would be useful. No need to actually delete anything.

**Comment by juliendonck** [comment]
> Some other UI notes:
> 
>     * I can't seem to remove a project from the UI. Not sure if that's intentional or not but it's a bit confusing.
> 
>     * Project discoverability needs some work but I think I've seen others make issues about it.
 
Yes it's on the list :)

>     * The `light` theme is a bit hard on the eyes. It's quite bright. Dark theme is somewhat difficult to navigate too.

I'd be curious what you mean here. We are planning on tweaking the themes a bit, so if you have any specific concerns, we'd be happy to hear them (cc: @brandonhaslegs)

**Comment by smartcontracts** [comment]
> I'd be curious what you mean here.

Mainly I think the colors could contrast a bit more. The font colors here are a bit too light IMO, I end up squinting to see the words. But maybe my eyes just aren't what they used to be 😄.

<img width="732" alt="Screen Shot 2021-04-07 at 8 07 00 PM" src="https://user-images.githubusercontent.com/14298799/113962625-eb3a5500-97dc-11eb-945d-75416fbd9e57.png">

I also think the projects list could use a slightly different background color to make it stand out more against the very bright background. Or maybe just make the borders between each project a little more visible.

**Comment by brandonhaslegs** [comment]
All fair points, will look into the contrast issues. In the meantime, maybe you'd like the new color theme we just merged in on #1724. 😂

**Comment by smartcontracts** [comment]
> All fair points, will look into the contrast issues. In the meantime, maybe you'd like the new color theme we just merged in on #1724. 😂

I can finally hack the mainframe!
