### ISSUE TITLE
Drop usage of the devnet for local development

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#173]
Currently, the upstream connects (its version of) the `radicle-registry-client` to the registry devnet:
 
https://github.com/radicle-dev/radicle-upstream/blob/518b2b2f2a32c834168900dab77d84738e54caa0/proxy/src/main.rs#L57-L63

This causes unpredictable runs such as https://github.com/radicle-dev/radicle-upstream/issues/167, since the devnet might be updated in the meantime, running a different and incompatible version of the runtime that the upstream registry client can't interact with.

By running a local development with a locked version of the runtime, we safely fix such scenario.

**Comment by xla** [comment]
This is a regression from the rush to demos, the flags we used to determine if the emeluator should be used or not is ignored. Good find.
