### ISSUE TITLE
Commits endpoint accepts general git revisions

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1737]
At the moment, the `source/commits` endpoint can only be used to list all ancestors of a commit identified by a SHA, branch name, or tag name. We have already seen the limitation of that when [trying](https://github.com/radicle-dev/radicle-upstream/pull/1686#issuecomment-803863640) to list commits for merge requests. To tackle this and other use cases it would be great if `source/commits` would behave like the [`git rev-list`](https://git-scm.com/docs/git-rev-list) command and accept arbitrary [git revisions](https://git-scm.com/docs/gitrevisions).

**Comment by FintanH** [comment]
Maybe this issue would be better lived in `radicle-surf`?
