### ISSUE TITLE
Fix flaky track_peer spec

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1749]
https://buildkite.com/monadic/radicle-upstream/builds/8374#a34cafd8-db23-47d6-b52c-571faec2e39c/473-816
https://buildkite.com/monadic/radicle-upstream/builds/8597#9189010d-0304-446e-b778-12ffbbf6a6a1

**Comment by xla** [comment]
Are their steps to reproduce this locally? Or can it be reproduce by running it multiple times?

**Comment by rudolfs** [comment]
I've only seen this happen on CI between multiple runs.

**Comment by geigerzaehler** [comment]
This happens to my locally if I put all my CPU cores under stress

**Comment by xla** [comment]
> This happens to my locally if I put all my CPU cores under stress

Can you share what your method for that is?

**Comment by geigerzaehler** [comment]
> > 
> 
> Can you share what your method for that is?

I’m run [`stress`](https://archlinux.org/packages/community/x86_64/stress/) with one thread per core simultaneously to `cargo test`.

**Comment by geigerzaehler** [comment]
These tests have been moved to radicle-link
