### ISSUE TITLE
Disappearing remotes

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1763]
We've observed remotes randomly disappearing from projects during testing.
In some cases this would lead to the UI throwing an error and leaving the user in a stuck state.

<img width="70%" alt="Screenshot 2021-04-08 at 18 57 32" src="https://user-images.githubusercontent.com/158411/114159582-3a3fd180-9926-11eb-982e-4efcacabec62.png">

The blocking UI issue has been addressed with [a workaround](https://github.com/radicle-dev/radicle-upstream/pull/1762).
This issue is about fixing the root cause.

**Comment by xla** [comment]
Behaviour captured in radicle-dev/radicle-link#596
