### ISSUE TITLE
Cannot deserialize previous settings JSON object

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1775]
When using the app with  #1754 on a state that was created by a previous version it shows the blue screen of death.

This is caused by a 400 response from the `GET /session` endpoint. This is caused by `api::session::get_current` because we fail to deserialize the JSON value of that is stored on disk (in the KV store) into `Session`. The reason for this is that the JSON value stored before #1754 does not include the key `settings.uiFont` while the `Session` deserializer after #1754 requires that key.

There’s a couple of things we can do
* Wrap the new settings in an `Option` and verify that this works.
* Write a custom deserializer that adds the new default values
* Move these setting to electron storage to decouple them from the proxy and make them easier to upgrade
* Add some tests to ensure backwards compatibility
* Add a versioning scheme to the settings to help with upgrades

**Comment by xla** [comment]
> Move these setting to electron storage to decouple them from the proxy and make them easier to upgrade

Highly encouraged given the direction of the proxy code.

**Comment by rudolfs** [comment]
Can we close this? All settings except for the seed list are now stored on the front-end since be05d080c4b3b3e52070583a8bbce4984627b50e.
