### ISSUE TITLE
Navigation breaks after refresh

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1778]
When going to a full screen modal and refreshing the app, the routing breaks and I can't leave the screen by pressing the `X` or by typing the shortcut again. 

Only workaround atm is to go to the settings screen with the shortcut `cmd + ,` and then you can continue using the app

**Comment by geigerzaehler** [comment]
> When going to a full screen modal and refreshing the app,

I guess you’re referring to the design system modal. I was only able to reproduce the issue with that dialog. The problem seems to be caused by an [issue in Electron](https://github.com/electron/electron/issues/16306) which does not retain the History API information after a refresh.

**Comment by juliendonck** [comment]
It's also when you go to a commit detail page and then refresh. The `.pop()` doesn't know where to pop to anymore.

**Comment by rudolfs** [comment]
We'll fix this in https://github.com/radicle-dev/radicle-upstream/pull/1876.
