### ISSUE TITLE
Set up unit tests for lib code in UI

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#178]
Some of our business-logic modules might lend themselves to unit testing.
Set up Jest, so we can write unit tests and run them locally as well as automatically on CI.

https://jestjs.io/

**Comment by xla** [comment]
I recently was exposde [ava](https://github.com/avajs/ava) which seemed low touch and approachable.

**Comment by sarahscott** [comment]
Closed by #413
