### ISSUE TITLE
Customize the app icon to your favorite color 🎨

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1789]
![image](https://user-images.githubusercontent.com/4406983/114760751-f43ca080-9d5f-11eb-8474-8c012885ce51.png)

Here's all the assets for this:
[app icon.zip](https://github.com/radicle-dev/radicle-upstream/files/6313001/app.icon.zip)

**Comment by rudolfs** [comment]
Currently we are [setting the icon at build time](https://www.electron.build/icons.html). AFAIK it's not possible to change the app icon at runtime on macOS in electron. On Linux and Windows it's supposedly possible.

https://github.com/electron/electron/issues/3839
https://stackoverflow.com/a/31538436

**Comment by cloudhead** [comment]
Maybe we have a different icon for dev builds? :paintbrush:
