### ISSUE TITLE
Shareable entity identity parser module

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#179]
Write a JavaScript module for parsing identifiers based on the [Shareable Entity Identifier spec](https://www.notion.so/monadic/Shareable-Entity-Identifiers-406a170c78f241238caef9affa11b4f1).

This module should have a parse function which accepts a string of an identfier and returns a structured object with all the parsed metadata (user, organisation, repository, etc).

- [ ] figure out the interface for the module
- [ ] implement the functionality
- [ ] write unit tests (depends on: #178)

This module will be used in various places throughout the UI:
  - to visually show an identifier (or maybe just parts of it)
  - for navigation and routing
    - opening a specific org or project screen when pasting an identifier in the app
    - deep-linking to a specific revision and file in a repository

For reference, here are all the possible identifiers:
```
%monadic/radicle-link
%73f26c2b0b5c216caba8b049e478e5f02e7923f8.git
radicle-link%2fFdyRzay2Rew9CpjEunPLp2PWe7HSvXWB3AJ.git
%monadic
@cloudhead
@ViJQHAdeZoiEbaE5vv83dpjEun.rad
cloudhead@ViJQHAdeZoiEbaE5vv83dpjEun.rad
%73f26c2b0b5c216caba8b049e478e5f02e7923f8.git/@ViJQHAdeZoiEbaE5vv83dpjEun.rad
%73f26c2b0b5c216caba8b049e478e5f02e7923f8.git/@cloudhead
%monadic/radicle-link/@cloudhead
%monadic/radicle-link/@ViJQHAdeZoiEbaE5vv83dpjEun.rad
%73f26c2b0b5c216caba8b049e478e5f02e7923f8.git/@cloudhead/tree/master
%73f26c2b0b5c216caba8b049e478e5f02e7923f8.git/@cloudhead/4235af8559d70b6a09a952932abda63362c4ff51
%73f26c2b0b5c216caba8b049e478e5f02e7923f8.git/@cloudhead/tags/v1.0
```

**Comment by xla** [comment]
It doesn't seem like this logic should live in the ui. We need to handle these identity references consistently in the proxy regardless. Instead we should strive to define a well-formed and robust data shape that the will be served through the API and expect that there is a string representation that is url safe to be used in routes and shareable URIs. The ui ought to know if somehting is an identifier from the response of a query.

Mostly to avoid duplication of efforts and strive for a single source of truth for consistent handling. I'd therefore propose to reframe this issue to be about arriving on a robust shape for how the identifiers are served and implementing them across the stack.

**Comment by rudolfs** [comment]
I think we'll still need to be able to parse these strings in the UI, as a user could paste any type of identifier into the search bar and we would like for the UI to open the right screen be it profile, org, a file somewhere deep in a repository or anything else.

**Comment by xla** [comment]
> I think we'll still need to be able to parse these strings in the UI, as a user could paste any type of identifier into the search bar and we would like for the UI to open the right screen be it profile, org, a file somewhere deep in a repository or anything else.

It can also be solved by firing a query for that. Otherwise if what is copy-pastad is always a well-formed URI then this unabmbiguous and just a routing concern.

**Comment by rudolfs** [comment]
This will be done in the proxy.
