### ISSUE TITLE
Adjust the global font size

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1790]
![image](https://user-images.githubusercontent.com/4406983/114761875-5cd84d00-9d61-11eb-81a1-00f9e2e4ae16.png)

Not exactly sure how the interaction will work here, still thinking about it. Probably just make the circles slightly bigger on hover, then the font size number appears when you click on it.

**Comment by brandonhaslegs** [comment]
I just meant the global font size here. What you mean is just that the screen looks better when everything is smaller?

**Comment by rudolfs** [comment]
> What you mean is just that the screen looks better when everything is smaller?

Yes. I can see more of the diff, which let's me do the code review more efficiently.

**Comment by brandonhaslegs** [comment]
Is it even possible to scale the whole UI with a user setting?
