### ISSUE TITLE
Branch name is undefined in commit view

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#1793]
![2021-04-15_14-52](https://user-images.githubusercontent.com/40774/114872177-5a760180-9dfa-11eb-9dc0-1a41ec6c2860.png)

**Comment by rudolfs** [comment]
It looks like this regression was introduced in 82f46fa5ec12264328b1fa2e433c44c6a3e94501.
\cc @geigerzaehler
