### ISSUE TITLE
Customize the primary UI color to your favorite color ❤️💚💙

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1803]
![image](https://user-images.githubusercontent.com/4406983/115257063-0c316d00-a130-11eb-903b-fca1f7061c1f.png)

- [x] offer Blue (#5555FF), Pink (#FF55FF), and Orange (#FF7700) as options for primary colors -> #2380
- [ ] a text field for a hex code or RGB.
- [ ] Support for Standard [HTML color names](https://www.w3schools.com/tags/ref_colornames.asp)
- [ ] Error when user inputs something that isn't a color code

- [x] translate the current "level system" of the primary color (primary-level1, primary-level-2, etc…) into an RGBA solution using opacities

**Comment by juliendonck** [comment]
@brandonhaslegs what happens if I'm in hacker theme? Should it overwrite the orange with blue? The theme and font color kind of collide as separate options, no?

**Comment by juliendonck** [comment]
Also, could you give me the rgba values for the `pink` please

**Comment by juliendonck** [comment]
Also, could you give me the rgba values for the `pink` please

**Comment by juliendonck** [comment]
Also, could you give me the rgba values for the `pink` please

**Comment by brandonhaslegs** [comment]
> Also, could you give me the rgba values for the `pink` please

The pink is `255, 85, 255`

**Comment by brandonhaslegs** [comment]
> @brandonhaslegs what happens if I'm in hacker theme? Should it overwrite the orange with blue?

Yes.

---

> The theme and font color kind of collide as separate options, no?

Don't know what this means.
