### ISSUE TITLE
Emojicon generation module

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#181]
This module will be used whenever we have to show an avatar for a user or org, but no avatar image url is provided. This could simply be a function that, given a user/project name, returns an object:
```
{
  emoji: "👹"
  color: "#D976E3"
}
```

The mapping should always be the same, meaning a given user/project name will always return the same emoji/color combination.

User emojicons always return "🙂", only the background color differs depending on the id.
<img width="101" alt="Screenshot 2020-02-25 at 08 53 03" src="https://user-images.githubusercontent.com/158411/75226528-c9cf0300-57ac-11ea-91b3-a63880957804.png">

For orgs we pick from a pre-defined set of emojis and colors.
<img width="83" alt="Screenshot 2020-02-25 at 08 53 28" src="https://user-images.githubusercontent.com/158411/75226534-cc315d00-57ac-11ea-8214-6ef25ac934f3.png">

The org emoji set is TBD: @juliendonck.

Requires: #179.

**Comment by rudolfs** [comment]
@cloudhead you mentioned that you might already have some code for this?

**Comment by cloudhead** [comment]
Here's a working prototype: https://gist.github.com/cloudhead/545fd3fd9f89070672375eda75ab1093

* We need to choose an emoji font for Linux (as macOS/windows have one already)
* UTF-8 charset is required everywhere, for this to work.

**Comment by cloudhead** [comment]
Example output:

![2020-02-25-123817_1184x104_scrot](https://user-images.githubusercontent.com/40774/75244174-9e0f4580-57cb-11ea-8cf3-b80ca6f2447d.png)

**Comment by cloudhead** [comment]
Possible font candidate: https://github.com/MorbZ/OpenSansEmoji

**Comment by xla** [comment]
Similar to #179 this information should come through the proxy API as part of the response for a proejct/org.

**Comment by xla** [comment]
@cloudhead Can you port this to a cute little Rust module in the proxy source? PRs are open.

**Comment by juliendonck** [comment]
Do I still need to make an emoji selection for this?

**Comment by xla** [comment]
> Do I still need to make an emoji selection for this?

@cloudhead @rudolfs Maybe you can answer this.
