### ISSUE TITLE
Detect circular dependencies

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-upstream#1818]
Circular dependencies between modules are valid in TypeScript, but the sometimes cause problems in our toolchain. An existence of a circular dependency sometimes silently crashes the build process and makes the app default to the old, cached version of the code. It's confusing, hard to debug, but worst of all hard to notice.

Fortunately it's a common problem and there are tools detecting circular dependencies. One of them is [Madge](https://www.npmjs.com/package/madge), which we could add to our build chain and explicitly crash builds if circular dependencies are found.

**Comment by geigerzaehler** [comment]
I agree, we should avoid circular dependencies in modules. In the past I have used [`circular-dependency-plugin`](https://github.com/aackerman/circular-dependency-plugin) for webpack with good results.
