### ISSUE TITLE
Wire up screens with app boot logic

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#183]
The app boot logic should check:
- [x] if a user identity exists -> show the user profile
- [x] if no identity exists -> show user identity creation welcome screen
- [x] add error handling for fetch identity queries and surface them to the user

**Comment by nassarhayat** [comment]
Hi. I'm a frontend dev interested in contributing. Is anyone already working on this issue?

**Comment by rudolfs** [comment]
Hey @nassarhayat! Happy to hear you want to get involved. I'd recommend starting on something more isolated first, as this issue depends on a bunch of stuff that is not yet implemented.

Here are a couple of smaller and more isolated things, which would be more suitable as a first issue:
- https://github.com/radicle-dev/radicle-upstream/issues/131
- https://github.com/radicle-dev/radicle-upstream/issues/140
- https://github.com/radicle-dev/radicle-upstream/issues/180

Make sure to read through [`DEVELOPMENT.md`](https://github.com/radicle-dev/radicle-upstream/blob/master/DEVELOPMENT.md) before contributing!

**Comment by nassarhayat** [comment]
cool. thanks @rudolfs will have a look through and pick one.

**Comment by rudolfs** [comment]
Notes from check-in with @xla:
  - we'll have a `session` endpoint which will expose the current identity
  - the identity endpoint gives back any identity by id (shouldn't be used by book logic directly)
  - the test-api endpoints will be extended
