### ISSUE TITLE
Homebrew picks up Upstream releases from tags before we officially announce them

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1833]
This is a problem especially when we push out breaking changes, since we tag releases before officially announcing them to the public.

**Comment by geigerzaehler** [comment]
How does Homebrew pick up the tags? Do you know whether we can work around this?

**Comment by rudolfs** [comment]
I believe someone from the community runs `brew tap homebrew/cask`.
https://github.com/Homebrew/homebrew-cask/pull/103697

**Comment by rudolfs** [comment]
The underlying issue is that we tag the release (and push the tag to github) before we do QA as @xla pointed out. We should change the release procedure.

**Comment by rudolfs** [comment]
I wonder whether we should not remove Upstream from brew/cask entirely and stop tagging releases on GitHub?

The reason being security (as @kim pointed out in the past) -- we don't have any control over this distribution channel. One attack vector I see here is somebody switching out [the url in the tap](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/radicle-upstream.rb#L5) file with something that has malicious code in it.

On the other hand, once Upstream becomes popular there won't be any way to control whether a distribution channel picks up our software or not. So maybe this point is moot?

\cc @cloudhead

**Comment by kim** [comment]
What’s the reason for tagging releases before actually releasing? What else
would a package maintainer refer to for upgrading?

Perhaps this could be changed such that those tags are labelled in a
special way, like -rc{number}, and only after the QA procedure the release
tag is pushed?

**Comment by rudolfs** [comment]
> What’s the reason for tagging releases before actually releasing? 

The initial idea was to make sure we QA the same binary that we publish. To avoid QAing one thing but publishing another. But yeah, I think that's overkill and we can move the tagging to the very end of the process.

**Comment by rudolfs** [comment]
This should be fixed via https://github.com/radicle-dev/radicle-upstream/pull/1929.
