### ISSUE TITLE
Integrate Registry user registration

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#185]
The user registration flow as outlined in #202 requires the integration with the user registration provided by radicle-dev/radicle-registry.

- [x] integrate registry client user registration in `regisry.rs`
- [x] integrate user registration in graphql schema

**Comment by xla** [comment]
The first step on the Registry side is under way with the extension and adjustment to the spec in radice-dev/regisry-spec#11

**Comment by xla** [comment]
The foundational work that will lead up to the actual user implementation has been started in radicle-dev/radicle-registry#246
