### ISSUE TITLE
Add more Ethereum client honesty checks when verifying attestations

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-upstream#1853]
The Ethereum attestations are a potential attack vector and we need to be extra careful when querying Ethereum clients. We need more client honesty checks when reading the transactions:
- Check if the transaction signature matches the attested address
- Check if the network matches the connected network
- Possibly more?

**Comment by Kaihuang724** [comment]
Closing for now until we decide to implement blockchain features.
