### ISSUE TITLE
Request amplification bug

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1855]
Upstream generates a lot of requests and becomes unusable.
I've noticed this bug a couple of times since we released 0.2.

https://user-images.githubusercontent.com/158411/117018284-a7137500-acf4-11eb-8010-d6e0619b1e3f.mov

Haven't worked out reliable steps to reproduce, but it usually happens when adding a new remote to a project.

**Comment by rudolfs** [comment]
Still happening on master at c3f140fa08607d2d136eeefdec1c435ab7fd530b.

**Comment by geigerzaehler** [comment]
I think I’ve identified the cause and created [an issue](https://github.com/radicle-dev/radicle-link/issues/734) on radicle link.

**Comment by geigerzaehler** [comment]
Let’s see if this is solved by https://github.com/radicle-dev/radicle-link/pull/773

**Comment by rudolfs** [comment]
I think this isn't happening anymore.
