### ISSUE TITLE
Web Native Upstream

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1868]
# Basically
People want to run Radicle Upstream in their browser instead of opening an electron app. How can we do this?

# Notes
- So we want to run Upstream's front end in a browser tab and connect to your local host instead of having electron wrapper
- Users will need to install a daemon first (not having to install a daemon is second priority)
- A read only app that has some actions. When you click something, it checks if the daemon is running.
- The web app would get its data from a web API mirror, similar to how Ethereum works
- First step is moving to a daemon.
- It would require a lot of changes to Upstream because the current experience is based around a user's session. The user is logged in and everything is built around that. A read only experience wouldn't have you be in a session. So it wouldn't just be moving the app onto the web.
- Maybe with a browser extension you could replicate everything but that requires more exploration.
- The daemon is there now but it can't be launched on it's own. There is work to do first.
- If we have specific requirements from the backend, we may need a proxy. Maybe put a web server proxy on top of the daemon. Maybe it's a library or there's two processes and they communicate?
- We could serve Upstream from radicle.xyz and have it connect to your local host. There are security concerns here but we could try it.
- We would need to get rid of directory creation in the app, and rely on a CLI to do this, which is fine because this is how GitHub works. People expect this.

# Problems
- We're relying on a middle layer that is not yet done by the Link Team (so we should expect to spec and build this ourselves)
- We have no idea what the progress is on middle layer developments from the Link Team
- If the middle layer is 6-12 month out then it might sense to built it ourselves, but if it's sooner it doesn't make sense, we can wait.
- If we decide to build and control the distribution of our own, it could work, but that's not a long term solution because it doesn't allow other people to work with it.
- If we move forward with our own daemon, and make a bunch of assumptions on how they're gonna build things, we'd have to do a lot of work to integrate with them after they have their own. It'd just be a side step.

#  Actions
- [ ] Map out a path for the middle layer/daemon and reach out the Link team to plan this work. Expect to contribute to get this done, aka… do it yourself
- [ ] Map out a path for the CLI features we'd need, like directory creation and checking out repos.
- [ ] Talk to Link team about a proxy on top of the daemon
- [ ] Parity does a lot of this stuff. Look into how they do it.
- [ ] If we split out the proxy as it is now and figure out how to serve it through the UI, we'd need to think about distribution (could be solved with static Rust binaries for example) — but again, doing this might just be a side step that wastes our time.
- [ ] Optimize for moving independently as much as possible but at least create shared assumptions with other teams regarding CLI and middle layer features.

🌠 Teamwork makes the dream work.

**Comment by rudolfs** [comment]
We'll stick with electron for now until we see a clear path to get rid of it.
