### ISSUE TITLE
Expand the Network tab

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1871]
- Show what seeds you're connected to
- Show what specific peers I'm connected to
  - If you are following one of the peers, you can click on their profile to view their projects
- Click on a seed to explore more about that seed
- Discover users and projects on that seed
- Check the status of the network
- Show how much storage the app is using. Like you're replicating 30 projects using 30MB of data on your computer.
- Maybe show users and projects in the same feed
- Show activity on the network like "user x followed user y"

**Comment by juliendonck** [comment]
related to #1696
