### ISSUE TITLE
Port radicle-avatar to Typescript

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1878]
We'll need the [radicle-avatar](https://github.com/radicle-dev/radicle-avatar) functionality in the front-end for orgs and other Ethereum functionality. At the moment this functionality is provided by the proxy, but it [will soon be removed](https://github.com/radicle-dev/radicle-upstream/pull/1862#discussion_r629302211).

**Comment by juliendonck** [comment]
@rudolfs isn't this done?

**Comment by rudolfs** [comment]
@juliendonck we still use the avatars provided by the proxy for the p2p identity and peers. For Ethereum related stuff (i.e. orgs) we already use the typescript lib.

**Comment by rudolfs** [comment]
Correct.
