### ISSUE TITLE
Solve truncation globally

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1880]
- We are discussing Upstream on the web (so the app needs to work well on small screens)
- The desktop app should also just be more flexible and responsive
- It's just good to have a more automatic and reliable solution for truncation

**Comment by rudolfs** [comment]
I think this got solved in https://github.com/radicle-dev/radicle-upstream/pull/2274.

**Comment by brandonhaslegs** [comment]
It was also just an outdated issue. Will revisit this when we attempt to do better responsiveness.
