### ISSUE TITLE
GitHub to Radicle importer

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1881]
- Import projects, stars, comments, code reviews (whatever could be possible) to Radicle.
- Importer feature should grow in scope to import future features (like issues) later

**Comment by juliendonck** [comment]
Maybe a first step for this is to improve documentation to import your code by just pushing to the rad remote

**Comment by Kaihuang724** [comment]
This would be a good issue to tackle once we have issue management features up and running. We can allow users to import their entire GitHub project over to Radicle, including issues, comments, etc.
