### ISSUE TITLE
Update Application folder window on macOS

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1882]
This is ugly. Would be nice to make it better. Is it possible to customize it?

![image](https://user-images.githubusercontent.com/4406983/117712738-fe25b800-b1d4-11eb-8c37-bf556b3a5295.png)

**Comment by juliendonck** [comment]
Look into electron builder

**Comment by rudolfs** [comment]
https://www.electron.build/configuration/dmg
