### ISSUE TITLE
Project deletion

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1884]
- Allow users to delete projects (aka disassociate projects from themselves)
- Explain that because of the nature of P2P, someone may have already replicated the project, which you can't control
- Maybe start with just hiding projects from my profile

**Comment by brandonhaslegs** [comment]
We could add an overflow menu in the project nav, that includes various quick actions including removing the project from the user's profile (if the user viewing this project is the creator).

![image](https://user-images.githubusercontent.com/4406983/118499475-42f6a500-b727-11eb-86d6-0d066ea6f7b9.png)

And then a standard modal that explains more about what "removing" a project from your profile actually does (text is just my quick pass at it).

![image](https://user-images.githubusercontent.com/4406983/118499640-6c173580-b727-11eb-84b5-40dc149eb4ef.png)

**Comment by juliendonck** [comment]
We should think about this in the context of unfollowing any project.

**Comment by geigerzaehler** [comment]
This is something we may want to implement in the UI, too. So I’d leave this open for now.
