### ISSUE TITLE
Show following and your projects on the same page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1887]
![](https://user-images.githubusercontent.com/4406983/123997806-1219b900-d9d1-11eb-8800-95687227d5bc.png)

We're interested in "Your projects" and "Followed projects" being on the same page, since they're so similar and since projects regularly move between the two pages.

**Comment by brandonhaslegs** [comment]
Here's what I'm thinking for the new projects layout on profiles. If a project is one that you're following, the only difference is we show the creator/maintainer's avatar in the corner. Projects that are not found yet are hidden behind a "Still looking" block which you can click on to expand to see the projects that haven't been found yet. All the various states I could imagine are [here in Figma](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=9402%3A142430).

![image](https://user-images.githubusercontent.com/4406983/123994232-75095100-d9cd-11eb-9124-dd5225d88dcb.png)

**Comment by juliendonck** [comment]
How do I know here if I follow it or own it?

**Comment by brandonhaslegs** [comment]
> How do I know here if I follow it or own it?

I explained some of my thinking in the comment above.
