### ISSUE TITLE
Don’t poll Ethereum account data

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1916]
At the moment we [poll](https://github.com/radicle-dev/radicle-upstream/blob/dbf9d1b81dfae4b71fe308f4109c9e03bee98e7b/ui/src/wallet.ts#L189-L194) the Ethereum provider every three seconds to update the account data for the wallet. This quickly exhausts our rate limits for Infura APIs.

To address this we should use event APIs to only update the data when we are notified of a change.

**Comment by Kaihuang724** [comment]
Closing for now until we decide to implement blockchain features.
