### ISSUE TITLE
Show cost of transactions in the transaction list of the wallet.

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1918]
We'd like to show the impact a certain transaction had on your wallet, by showing an aggregate of the txfee as well as the amount that might have been debited or credited to your wallet.

<img width="812" alt="Screenshot 2021-05-31 at 12 15 21" src="https://user-images.githubusercontent.com/2326909/120178533-39614880-c1cf-11eb-9419-4f2035a8a80e.png">

**Comment by CodeSandwich** [comment]
What's the use for displaying old TX fees? Shouldn't it be displayed for all operations, including the ones involving moving around DAI?

**Comment by geigerzaehler** [comment]
Something we need to consider in the design is that for token transfers (e.g. when you receive DAI) there’s both a change to the DAI balance as well as some transactions fees in ETH.

**Comment by juliendonck** [comment]
> What's the use for displaying old TX fees? Shouldn't it be displayed for all operations, including the ones involving moving around DAI?

I'm not sure I follow. Are you arguing it doesn't make sense to show gasFees of transactions? You might be right, that information is available on etherscan and maybe we can just link from the transaction detail screen to there so people can actually get that information. 
- It could make sense to just show when you are moving amounts around in DAI for the token streams or burning RAD for registration.

**Comment by juliendonck** [comment]
> Something we need to consider in the design is that for token transfers (e.g. when you receive DAI) there’s both a change to the DAI balance as well as some transactions fees in ETH.

Yes, as i mentioned to @CodeSandwich maybe it's only worth showing the DAI amount or RAD burn
