### ISSUE TITLE
Show if user has attested Radicle ID on Ethereum and vice versa

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1920]
We want to show if a user is attested by adding an icon to the end of their avatar/username.
<img width="535" alt="Screenshot 2021-05-31 at 13 50 41" src="https://user-images.githubusercontent.com/2326909/120189160-9a434d80-c1dc-11eb-92bf-28e127ccd5db.png">

**Comment by rudolfs** [comment]
Have a look [here]( https://github.com/radicle-dev/radicle-upstream/blob/cloudhead/orgs/ui/DesignSystem/Component/AnchorMetadataModal.svelte) for some inspiration on how to get the floating modal working.
<img width="568" alt="Screenshot 2021-05-31 at 14 11 15" src="https://user-images.githubusercontent.com/158411/120191305-114b0700-c21a-11eb-9799-a8849fb35e27.png">

**Comment by Kaihuang724** [comment]
Closing for now until we decide to implement blockchain features.
