### ISSUE TITLE
Introduce Overflow button on Project page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1936]
- [x] Change the global Following button back to rendering as icon + text. instead of just an icon in a button
- [x] Move Following button on the project page to a button accessible under a `•••` overflow button (until the following button actually does something, it's totally fine to hide it)
- [x] Change following button under the overflow button to "Unfollow" instead of being a Follow/Unfollow toggle button
- [x] Add other quick actions under the overflow button
   - [x] Copy Radicle ID
   - [ ] Checkout (or Fork… depending on the situation?)
   - [ ] New Patch

![image](https://user-images.githubusercontent.com/4406983/120509186-93792e00-c3c8-11eb-8a41-4f19ed6936d5.png)

**Comment by juliendonck** [comment]
Nice. I like this approach. A few notes:
- Should the `Add Remotes` not just be a pencil, I think after clicking it once you'd know and I find it quite busy having 2,5 buttons up there.
- Checkout and New patch open modals, not sure how that would look to open a dropdown from a dropdown.

**Comment by juliendonck** [comment]
>     * Should the `Add Remotes` not just be a pencil, I think after clicking it once you'd know and I find it quite busy having 2,5 buttons up there.

Maybe the pencil would be to generic, maybe it would be nice to have a pencil over a "remotes icon" or something, making it a bit clearer it's not just an "edit" icon

**Comment by brandonhaslegs** [comment]
> * Should the `Add Remotes` not just be a pencil, I think after clicking it once you'd know and I find it quite busy having 2,5 buttons up there.
Maybe could do a + button that is more attached to the remotes dropdown.

> * Checkout and New patch open modals, not sure how that would look to open a dropdown from a dropdown.
Yeah this could be weird… I just like the idea of quick actions being there. If it's not too much work to try it out then it would be cool to see what it feels like. If it's too much work just remove Checkout and New Patch out of it.
