### ISSUE TITLE
Wallet UX review

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1937]
- [x] In this empty state text, is it necessary to have the words "you own" … like can't I connect it to a wallet I don't own but just have access to? Makes it seem like legally this must be my wallet, whereas I can imagine someone is setting up their Radicle account and connecting their company wallet, which they don't own.
![image](https://user-images.githubusercontent.com/4406983/120511962-316df800-c3cb-11eb-8007-8167e9b04b0d.png)

---

- [x] There's a spinner when you're first connecting your wallet that's really huge but I didn't get a screenshot of it

**Comment by juliendonck** [comment]
I've tackled some of these in #1930

**Comment by juliendonck** [comment]
The ones that are left we'll review when we release token streams, which will be later on. We'll need to review that whole flow at some point

**Comment by brandonhaslegs** [comment]
I'll close this and add a new issue for Token Streams UX review
