### ISSUE TITLE
Token Streams UX Review

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1943]
- [ ] When I try to set up Token Streams, the transaction goes through normally, but when it's done, Token Streams still has an empty state. If there's something else going on that I'm waiting on, the UI should tell me about it. It seems like if Token Streams is still being set up but the transaction has been sent and confirmed, there should be some change to this empty state. Also is it expected that it says "n/a" under Radicle Pool?
![image](https://user-images.githubusercontent.com/4406983/120783023-e834ba00-c52a-11eb-8169-7f87c4a883ef.png)

I've already pressed this button and confirmed the transaction in my wallet and i still see this
![image](https://user-images.githubusercontent.com/4406983/120783072-f4207c00-c52a-11eb-81dd-7257a9c981b2.png)

---

- [ ] This form shouldn't be in an error state when there's nothing in it. forms should only error when the user has expressed interest in continuing.

![image](https://user-images.githubusercontent.com/4406983/120783101-faaef380-c52a-11eb-8399-584fef94de49.png)

---

- [ ] hover states on the transaction rows should look like the hover state on the projects on the profile. So on hover a background of `--color-foreground-level-1`
![image](https://user-images.githubusercontent.com/4406983/120794154-2684a600-c538-11eb-8cca-dc1be6ed1be1.png)

---

- [ ] The DAI amount should always have two decimals
![image](https://user-images.githubusercontent.com/4406983/121361279-6e8b3a80-c935-11eb-9087-e29358ebd395.png)

---
<img width="711" alt="image" src="https://user-images.githubusercontent.com/4406983/123253013-3ebf6380-d4ed-11eb-9767-0936a1358e41.png">
- [ ] The notification that the app is waiting on your wallet to confirm a transaction should be a persistent notification that has no close button

---

- [ ] <img width="492" alt="image" src="https://user-images.githubusercontent.com/4406983/123250952-f141f700-d4ea-11eb-949a-c9053123a156.png">
These things say the same thing

---

- [ ] `Tip: You can also add new receivers later on by clicking on “Support” on their profile.`
This isn't true yet. But I guess profiles are a requirement for launching token streams?

---

<img width="529" alt="image" src="https://user-images.githubusercontent.com/4406983/123252521-a88b3d80-d4ec-11eb-8ab3-9ac006b35d8f.png">

- [ ] right now, it doesn't add the address to the list when you press continue. you MUST press the + button to add an address. when you enter an address in this box, and just press continue, we should add that address to the list of receivers.

---

<img width="407" alt="image" src="https://user-images.githubusercontent.com/4406983/123252774-ef793300-d4ec-11eb-8a59-36555deff457.png">

- [ ] when you hover over an address it turns grey. these need normal button hover/active states.

---

<img width="522" alt="image" src="https://user-images.githubusercontent.com/4406983/123252951-25b6b280-d4ed-11eb-90ef-1654cb34d830.png">

- [ ] For the confirmation screen, we should update this text to something more "CONFIRM THIS IS RIGHT"ish.

---

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/4406983/123255728-77ad0780-d4f0-11eb-9b1a-6268c247704a.png">

- [ ] It says my support is paused at the moment, but it is not paused.

---

<img width="991" alt="image" src="https://user-images.githubusercontent.com/4406983/123394294-463f4500-d59f-11eb-8d5f-5d3c378ac78a.png">

- [ ] I shouldn't be able to have a negative remaining balance. it should just pause the stream when it's empty

---

- [ ] seems like we could add some more info to these rows. maybe the timestamp? or some more details somehow?
<img width="985" alt="image" src="https://user-images.githubusercontent.com/4406983/123410878-177d9a80-d5b0-11eb-9b93-b52db55e1f13.png">

**Comment by brandonhaslegs** [comment]
Hey is this feature officially cancelled? For the record I'd like to finish these last few things and launch it! It was basically done…

**Comment by rudolfs** [comment]
If it is, we should delete the code, because it's a lot of extra work to maintain. \cc @geigerzaehler @juliendonck

**Comment by juliendonck** [comment]
Where we left it off in the end of July is that we'd not implement it in this form. If this would come back it would be under orgs, for this reason I think we should kill this and remove the code. We can always come back to it when we need to.
