### ISSUE TITLE
Replace Radicle ID with Project Name in "found and cloned" notification

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1957]
![image](https://user-images.githubusercontent.com/4406983/121183789-ba21e380-c864-11eb-9ca4-62bcb45a4711.png)

So instead of `Project for "rad:git:hilfug89423hgfiwuelg723gfliu.248o2yo1y2whiudgho" found and cloned. | Show Project` the notification should say `The project **Test-Project** has been found and cloned. | Go to project`

**Comment by nishit-prasad** [comment]
I can take this up if it's available. All I need are the steps to reproduce this.

**Comment by brandonhaslegs** [comment]
This notification is shown when a project is successfully cloned. So just clone any project, and wait for it to be successfully cloned, and it appears.
