### ISSUE TITLE
Bold project name in project creation notification

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1960]
![image](https://user-images.githubusercontent.com/4406983/121184847-c8243400-c865-11eb-9b30-ccbd42ad467e.png)
In this notification "berghain.de" should be bold.

**Comment by nishit-prasad** [comment]
Hello! I am new to open source and would like to work on this. Can I take this up?

Currently, I am reviewing the docs/guidelines to understand and set up.

**Comment by rudolfs** [comment]
At the moment our notifications only support plain-text, we'd have to figure out how to pass in arbitrary content for this to work, hence it might not be a `good-first-issue`.
