### ISSUE TITLE
center the navigation in onboarding

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1962]
In the recent modal update, the last step in onboarding is looking funny. I guess this happened since this is technically using the modal component.

![image](https://user-images.githubusercontent.com/4406983/121187449-5bf6ff80-c868-11eb-842a-d9c1e2c86e1e.png)

**Comment by juliendonck** [comment]
Wanted to improve the modal component, it could be DRY'er. Related to #2037

**Comment by juliendonck** [comment]
@brandonhaslegs this doesn't use the modal component. All we need to do to center these buttons is to change this to `center`: https://github.com/radicle-dev/radicle-upstream/blob/master/ui/Screen/Onboarding/Success.svelte#L55

**Comment by brandonhaslegs** [comment]
Ah okay, I just assumed because it happened around the time the modal PR went through.
