### ISSUE TITLE
Restyle commit hashes

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1968]
Hashes are inconsistently formatted (sometimes in monospace, sometimes in normal font). Since we have the Inter alternates on that differentiate properly between characters, I see no reason to use a monospace font for hashes. Can reserve the monospace font purely for displaying code I think.

**Comment by rudolfs** [comment]
@brandonhaslegs is this still relevant after we got https://github.com/radicle-dev/radicle-upstream/pull/2354 merged?

Here's what all the commit hashes look currently:

<img width="1552" alt="Screenshot 2021-09-10 at 16 06 28" src="https://user-images.githubusercontent.com/158411/132866659-79e50591-b619-41d4-9daa-02387453fdf9.png">
<img width="1552" alt="Screenshot 2021-09-10 at 16 06 33" src="https://user-images.githubusercontent.com/158411/132866680-958a8d90-6d50-4314-bc5a-df3700705f66.png">
<img width="1552" alt="Screenshot 2021-09-10 at 16 06 39" src="https://user-images.githubusercontent.com/158411/132866685-2d8cc53c-a429-48a3-87bd-1b0b05b93039.png">
<img width="1552" alt="Screenshot 2021-09-10 at 16 06 43" src="https://user-images.githubusercontent.com/158411/132866691-cd808fb4-efb0-4ce7-b71e-0b3436550896.png">
<img width="1552" alt="Screenshot 2021-09-10 at 16 06 54" src="https://user-images.githubusercontent.com/158411/132866694-225b2a8b-9197-4960-9f46-cd8c11d512ec.png">
<img width="1552" alt="Screenshot 2021-09-10 at 16 07 39" src="https://user-images.githubusercontent.com/158411/132866699-4051d6e6-9214-462b-9c01-e67cd5d73001.png">
<img width="1552" alt="Screenshot 2021-09-10 at 16 07 54" src="https://user-images.githubusercontent.com/158411/132866704-bb70789d-6d5b-44a6-b459-8addb5c308d4.png">
