### ISSUE TITLE
Remove Network Diagnostics from the keyboard shortcuts modal

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1973]
Network Diagnostics keyboard shortcut is appearing in the public, non developer, build. It should only appear when you build from source.

![image](https://user-images.githubusercontent.com/4406983/121330663-81dadd80-c916-11eb-90eb-d41dda61cee6.png)

**Comment by xla** [comment]
Why? This is a helpful tool, esp. important when you encounter issues when operating from a packaged release.

**Comment by rudolfs** [comment]
I think the intention is to only remove the shortcut hint from the modal, but keep the shortcut itself working in production builds, correct @brandonhaslegs?

**Comment by brandonhaslegs** [comment]
Yes, that's what we agreed to do.
