### ISSUE TITLE
Replace check icon in transaction details modal

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1974]
![image](https://user-images.githubusercontent.com/4406983/121346204-1ac52500-c926-11eb-853f-59d56f9bae73.png)

The icon next to "Included" is a legacy icon. Should be `checkCircle` from [the icons file](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=3666%3A13).

**Comment by nishit-prasad** [comment]
Hello! I am new to open source and would like to work on this. Can I take this up?

Currently, I am reviewing the docs/guidelines to understand and set up.

**Comment by geigerzaehler** [comment]
Of course, @nishit-prasad. Feel free to tackle this and reach out to us if you need support.

**Comment by nishit-prasad** [comment]
@geigerzaehler Thank you! Can this be assigned to me, if applicable?

**Comment by nishit-prasad** [comment]
@geigerzaehler 
Apologies as I got caught up with work.

How can I see this pop-up? By linking my wallet and completing a transaction? For that to work, I need to have some cash balance in any of the supported crypto wallet?

Do you have any suggestions/alternatives?

**Comment by brandonhaslegs** [comment]
If you have a wallet connected to the Ropsten network, I can send you Ropsten Eth.

**Comment by nishit-prasad** [comment]
Sure. Let me set it up and I'll post it here. Thank you!

**Comment by brandonhaslegs** [comment]
I use the Rainbow wallet. Seems to work fine there!

**Comment by nishit-prasad** [comment]
Okay. Seems like Rainbow works (I think). How would you like me to share my wallet address? Over discord DM?
