### ISSUE TITLE
Show anchored state of the project

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1976]
Maybe in the peer selector or revision selector on the project page

**Comment by rudolfs** [comment]
I think it would make more sense in the revision selector.

**Comment by brandonhaslegs** [comment]
So the two options would be either showing the anchor next to the anchored branch
![image](https://user-images.githubusercontent.com/4406983/122215510-98031380-ceab-11eb-8fa5-16d045cbd441.png)

…or showing it next to the org that has anchored the project
![image](https://user-images.githubusercontent.com/4406983/122215576-a94c2000-ceab-11eb-9868-8fda2c09e120.png)

I think the first one makes more sense?

**Comment by rudolfs** [comment]
Hm, but the actual object that is being anchored is a commit.

A branch contains many commits and a peer contains many
branches and commits, so to me it doesn't make sense to
show the anchor on a branch or a peer. Besides, a branch always
points to the latest commit of that branch, but an anchored commit
could be somewhere in that branch but earlier than the latest commit.

To me an anchor is similar to a branch or a tag. I think we should
show it in the revision (aka branch) selector as the shortened
commit SHA + anchor like this:

```
<branch icon> main
<branch icon> feature/bla
<anchor icon> f4c7697
<anchor icon> a89834

**Comment by brandonhaslegs** [comment]
![image](https://user-images.githubusercontent.com/4406983/122225175-216b1380-ceb5-11eb-94a2-decb9be4d90c.png)

**Comment by rudolfs** [comment]
Hmm, now after reflecting a bit more on this and talking to @geigerzaehler I think that you were right after all -- orgs belong in the peer selector. 😬 🤷 

If we have the org in the revision selector then we'd still have to figure out which peer to select in the peer selector. And it's not guaranteed that every peer will have this specific anchored project, which might make this selection heuristic complicated.

Now, if we put the org that the anchor belongs to in the peer selector we've solved the peer pre-selection problem. And for that org we'd show the latest anchor in the revision selector -- which might make that list rather short and boring. To remedy that, we could also show all the historical anchors for that org _and_ mark the latest anchor in some special way.

**Comment by brandonhaslegs** [comment]
Yeah I like it. Makes the most sense to me too. So this?

![image](https://user-images.githubusercontent.com/4406983/122231362-aefd3200-ceba-11eb-88e9-f6d56c113780.png)

**Comment by juliendonck** [comment]
I'm not sure this will be clear tbh, I think users expect to see `main` or `master` in the revision selector. And if that happens to be an anchored one, we could show the anchor symbol next to it that you can hover on. 

To show all anchors of that project, either we add a `anchors` tab next to commits or we do it the way github does tags:
<img width="374" alt="Screenshot 2021-06-21 at 11 59 57" src="https://user-images.githubusercontent.com/2326909/122744385-89bb4b80-d24d-11eb-818c-a23190415f76.png">

**Comment by rudolfs** [comment]
> To show all anchors of that project, either we add a anchors tab next to commits or we do it the way github does tags:

Yeah, I agree, both of these options would be less confusing than the one I proposed.

**Comment by brandonhaslegs** [comment]
They expect to see main or master in there, but that's because that's the canonical version. In our case, main and master aren't the canonical version, the latest anchored commit is. Not totally sure this is resolved. Maybe we should discuss it together in a meeting.

**Comment by juliendonck** [comment]
> They expect to see main or master in there, but that's because that's the canonical version. In our case, main and master aren't the canonical version, the latest anchored commit is. Not totally sure this is resolved. Maybe we should discuss it together in a meeting.

I mean there's a difference between a release and the latest version on master, this is how we use tags in this repo. Even though the tag shows you which commit is which release, I still want to see the latest master by default.

**Comment by juliendonck** [comment]
Down to discuss in a meeting

**Comment by brandonhaslegs** [comment]
Based on our discussion today.

![image](https://user-images.githubusercontent.com/4406983/122985031-fcd3d780-d39d-11eb-902d-a9b738d5572d.png)
