### ISSUE TITLE
Define GraphQL schema for User Registration

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#198]
### ~~Registered user handle query~~ Already done in #199 
~~To check whether a handle is already registered.~~
- ~~given: user handle~~
- ~~return: Option(registered user)~~

### User registration transaction cost query *
- given: transaction message (UserRegistration)
- return:
  - user registration cost or deposit
  - transaction fee
  - total

\* low prio (as we're not doing real wallet stuff this quarter)

### ~~Register user handle mutation~~ Already done in #199 
- ~~given: user handle~~
- ~~return: transaction~~

### Transaction query
- given: transaction id
- return: transaction

**Comment by xla** [comment]
Follow ups in #212
