### ISSUE TITLE
Redesign initial onboarding screen

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1982]
There's gotta be something way cooler we can do here. Something with illustrations could be cool.

![image](https://user-images.githubusercontent.com/4406983/121678739-d8335200-cab7-11eb-8dcf-f7452451ab05.png)

**Comment by rudolfs** [comment]
Superseded by https://github.com/radicle-dev/radicle-upstream/issues/2802.
