### ISSUE TITLE
Update copy in passphrase onboarding step

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1984]
I feel like this copy is super weird but I know it's technically what's happening. Would love to hear some other suggestions for how we might be able to improve it or make it more casual. I mean this is essentially just setting an app unlock password, but referencing your keys seems super unnecessary. I wonder how we can reference it in a more lightweight way (and then maybe link to a docs article about security on Radicle where we can really go into it).

![image](https://user-images.githubusercontent.com/4406983/121697755-a5945400-cacd-11eb-8406-00c2f85635cb.png)

**Comment by rudolfs** [comment]
Superseded by https://github.com/radicle-dev/radicle-upstream/issues/2802.
