### ISSUE TITLE
Dependency License Audit

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2024]
Audit the licenses of all dependencies so that they are compatible with our [licensing model](https://radicle.community/t/radicle-licensing-model/282). This task should be automated and part of CI. [Here](http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses) is an overview of GPL-compatible licenses

**Comment by geigerzaehler** [comment]
[`license-checker`](https://www.npmjs.com/package/license-checker) is a widely used tool for NPM.

**Comment by geigerzaehler** [comment]
We should also include license header (and again automatically check this) in all source files.

**Comment by rudolfs** [comment]
Can this be closed now?
