### ISSUE TITLE
Fix hover and click states of buttons and links

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2031]
These have always looked bad. They should just work with opacities or transforms instead of jumping around to different color styles. Just weird overall!

**Comment by juliendonck** [comment]
Let me know if you want to pair on this. Have some ideas on how to improve buttons.

**Comment by brandonhaslegs** [comment]
I'm working on this right now. Should have something to look at by tomorrow, can pair tomorrow or Wednesday.
