### ISSUE TITLE
Anchor project dropdown empty state is weird

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2035]
When clicking on the project selector to anchor it, when you have no projects it shows an empty box with an outline. 

![org-no-project-anchor](https://user-images.githubusercontent.com/2326909/122727540-bfa40400-d23c-11eb-820d-b8740697d48f.gif)

_Proposed:_ Add a disables item that says "you have no projects."

**Comment by rudolfs** [comment]
Fixed in: https://github.com/radicle-dev/radicle-upstream/blob/master/ui/Screen/Org/ProjectsMenu.svelte#L11.
