### ISSUE TITLE
Intermittent connectivity problems in wallet

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2048]
When I try to scan the walletconnect code to connect my wallet in the app, I sometimes get this error in the console:

Error code : `429`.
```
WebSocket connection to 'wss://bridge.walletconnect.org/?env=browser&host=&protocol=wc&version=1' failed: Error during WebSocket handshake: Unexpected response code: 429
```

Error code : `403`.
```
index.js?ecbf:84 WebSocket connection to 'wss://bridge.walletconnect.org/?env=browser&host=&protocol=wc&version=1' failed: Error during WebSocket handshake: Unexpected response code: 403
```

Error code: `502`.
```
WebSocket connection to 'wss://bridge.walletconnect.org/?env=browser&host=&protocol=wc&version=1' failed: Error during WebSocket handshake: Unexpected response code: 502
```

Usually when this error shows up connecting the wallet is not possible or makes the wallet respond very slowly. Sometimes it takes 2-3 minutes to scan and connect a wallet. And over a minute to get a signing request show up in the wallet.

Restarting the wallet and refreshing the app gets rid of it. 

<img width="2032" alt="Screenshot 2021-06-22 at 09 41 05" src="https://user-images.githubusercontent.com/158411/122883984-f9a8ff00-d33d-11eb-8b80-dfcc0e7ad0b9.png">

<img width="2032" alt="Screenshot 2021-06-22 at 09 49 04" src="https://user-images.githubusercontent.com/158411/122885140-16920200-d33f-11eb-9888-6f4fe5b33bda.png">

Possibly related: https://github.com/WalletConnect/walletconnect-monorepo/issues/535.

**Comment by rudolfs** [comment]
Turns out this is related to problems on the official walletconnect infra: https://twitter.com/WalletConnect/status/1407279853943001088.

**Comment by geigerzaehler** [comment]
Shall we close this then?

**Comment by 0x0-emg** [comment]
Is this why Uniswap runs its own Bridge? Is it advisable for services to run their own bridge as well?

It would be great if someone could link me to relevant documentation on this, thanks

**Comment by rudolfs** [comment]
@0x0-emg yes, at least that's what I read in the walletconnect discord #developers channel during their outage. Gnosis also runs their own walletconnect bridge btw.
