### ISSUE TITLE
Deploy and use our own walletconnect bridge

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2052]
The official walletconnect bridge is [often flaky and unreliable](https://github.com/radicle-dev/radicle-upstream/issues/2048#issuecomment-865916258). We want to provide a solid service to anyone opting-in to our Ethereum features, therefore we should run our own service.

The [2.0 version relay service](https://github.com/WalletConnect/walletconnect-monorepo/tree/v2.0/servers/relay) is backwards compatible with 1.x clients, we should use that.

From the walletconnect discord in #general and #developers:

> xingxing — Today at 11:05 AM
> https://github.com/WalletConnect/node-walletconnect-bridge

> xingxing — Today at 2:08 PM
> Yes. the bridge is very simple and lightweight.
> git clone
> npm install
> npm start
> oh you also need redis so for me, it is apt-get install redis
> then put apache2/nginx in front as a proxy server, use letsencrypt to have TLS
> a 1-2 hours work I would say. I just slap it on to my existing AWS server and create a CNAME for it. can also use elastic beanstalk of AWS(or whatever provider you prefer).

> pedrouid — Today at 2:18 PM
> Here is quick description of the limitations of the v1.0 clients:
> - no message acknowledgement (server needs to ensure that it only delivers the message to the client once)
> - same server as peer (server can't peer with other servers and needs both sender and recipient connected)
> - one session per websocket (every time you connect a new session it requires a new websocket)

> These 3 issues are fixed with v2.0 which means that servers can be load balanced and the client-server relationship is not as tightly coupled

> We would need to break compatibility with  v1.0 clients to fix these issues therefore it's more reasonable to introduce a complete new protocol that adds other benefits besides these such as:
> - session-pairing decoupling
> - multi-chain and chain-agnostic APIs
> - improved session management and permissions

> Although that's for v2, wonder what one would use for v1.4.1?
> pedrouid — Today at 1:44 PM
> they are the same
> the server supports both clients

**Comment by rudolfs** [comment]
We should probably also make the bridge user configurable.

**Comment by pedrouid** [comment]
We've deployed a bridge for you guys 🙌  Looking forward to see the WalletConnect integration in production

New Bridge: https://radicle.bridge.walletconnect.org/
