### ISSUE TITLE
Fix wallet issues when offline

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2053]
When the user is offline, how should we show orgs and anchored states in projects? So far, everything in the app is p2p replicated data and is thus still available when offline. We've talked about having an offline mode, or Ethereum-free mode in Settings. Maybe we could introduce a flag that doesn't show or disables certain features.

When offline:
- [ ] when wallet is connected, the wallet page is broken
- [ ] when wallet is connected, replicated projects cannot be loaded
- [ ] Org profile
- [ ] org profile i'm a member of

**Comment by geigerzaehler** [comment]
Offline and ethereum-free are two different things. To proceed with this we should separate the issues and list the concrete issues. E.g. what happens when the app is offline and what we concretely want to make less visible with respect to Ethereum features.

**Comment by juliendonck** [comment]
@brandonhaslegs could you go through the app offline and add what breaks?

**Comment by Kaihuang724** [comment]
Closing for now until we decide to implement blockchain features.
