### ISSUE TITLE
Expose all Ethereum related endpoints in settings

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2054]
So far we rely on some 3rd parties to provide gateway and other infrastructure that allows our Ethereum features to work. Some of this infrastructure is unreliable, in which case we should run our own.

We should, however allow the users to freely choose which API endpoints to use in case our or the 3rd party infrastructure is experiencing problems.

We should make these configurable in the Settings page:
  - walletconnect bridge (`https://bridge.walletconnect.org`)
  - infura project key (network: `mainnet` api-key: `7a19a4bf0af84fcc86ffb693a257fad4`)
  - orgs the graph index endpoint (`https://api.thegraph.com/subgraphs/name/radicle-dev/radicle-orgs`)
  - gnosis safe the graph index endpoint (`https://api.thegraph.com/subgraphs/name/radicle-dev/gnosis-safe`)

This could be hidden under "Advanced settings" or something like that, with a warning "better know what you're doing", etc.

**Comment by brandonhaslegs** [comment]
> with a warning "better know what you're doing"

Is it the end of the world if a user turns these things off though? Should be a normal setting I think.

**Comment by rudolfs** [comment]
> Is it the end of the world if a user turns these things off though? Should be a normal setting I think.

If they mess the settings up and point to endpoints that don't work, then the Ethereum related features will show errors. But the app still should work. We could put this below the "Turn Eth features off switch" https://github.com/radicle-dev/radicle-upstream/issues/2053.

**Comment by brandonhaslegs** [comment]
I _think_ we should plan for the case where a user has Ethereum features turned on, then wants to use the app purely in P2P mode and wants to turn them off. So not showing errors necessarily, but showing the features in "offline mode" basically.

**Comment by rudolfs** [comment]
Gotcha, so `Off` | `On` | `Flight mode`

**Comment by brandonhaslegs** [comment]
Is it possible to have just `On` and `Flight mode`? What's the purpose of Off?

**Comment by rudolfs** [comment]
Because we're saying that blockchain is "opt-in" on our website, so I'd expect people might want to turn it off completely.
<img width="587" alt="Screenshot 2021-06-23 at 10 22 39" src="https://user-images.githubusercontent.com/158411/123062649-05172b80-d40d-11eb-9769-3fdaaa360911.png">

I imagine that `Flight mode` could be set automatically if the network is down, so it might not be switchable by the user. 🤷

**Comment by brandonhaslegs** [comment]
I'm just wondering what the difference would be between `Flight mode` and `Off`

**Comment by rudolfs** [comment]
`Flight mode` would still show you your cached orgs and wallet in the sidebar, but you wouldn't be allowed to interact with them. In `Off` mode we wouldn't show any Ethereum related stuff in the app at all.

**Comment by brandonhaslegs** [comment]
Settings view:
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/4406983/123997882-28277980-d9d1-11eb-9505-26500816010a.png">

I think when Ethereum is turned off, adding orgs should go away, but any orgs the user has already replicated should hopefully stay accessible. The wallet icon in the sidebar should also be removed when Ethereum is turned off.

**Comment by Kaihuang724** [comment]
Closing for now until we decide to implement blockchain features.
