### ISSUE TITLE
Settings screen loads slower than all other screens

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2065]
All other screens load instantly but the settings screen is a few milliseconds off.

![settings is slow](https://user-images.githubusercontent.com/4406983/123128281-4e866b80-d44b-11eb-974f-6ac0227e36bc.gif)

**Comment by geigerzaehler** [comment]
I can’t reproduce this. This is probably a symptom of #1975

**Comment by geigerzaehler** [comment]
Closing this in favor of #1975.

**Comment by brandonhaslegs** [comment]
You definitely sure this is the same issue? It only happens on the settings screen. Maybe @rudolfs or @juliendonck can reproduce it?

**Comment by geigerzaehler** [comment]
@brandonhaslegs reported that this is not an issue anymore. Keeping this closed.
