### ISSUE TITLE
Truncate the Device ID in settings just like it is on the profile

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2067]
So this device ID:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/4406983/123131469-03218c80-d44e-11eb-80e3-733b14b843a0.png">

Should look like this one (but doesn't need the expand on hover):
<img width="413" alt="image" src="https://user-images.githubusercontent.com/4406983/123131590-1df40100-d44e-11eb-986f-c4f645d09173.png">

**Comment by nishit-prasad** [comment]
I can take this up if it's available, since I am working on something similar (Issue 2068) already.

**Comment by brandonhaslegs** [comment]
Sure thing, I've assigned it to you. 💪

**Comment by nishit-prasad** [comment]
PR is up and ready! 😄

**Comment by nishit-prasad** [comment]
@geigerzaehler thank you for the merge. However, I see the most recent update on the master has replaced my changes for this issue. Am I missing something here?

https://github.com/radicle-dev/radicle-upstream/commit/472d1fe91cf366f22c62427e33f36b3352d859a5#diff-8eb57a3f3cdf09e8833ed4474cf17539c962b195b7a76a9b1cc7733f69385a82

**Comment by geigerzaehler** [comment]
Oh no :see_no_evil:, you’re right. This came from a bad rebase I did on #2087. I’ll fix this tomorrow.

**Comment by nishit-prasad** [comment]
Can this issue be closed?
