### ISSUE TITLE
Implement single-sig backed orgs

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2084]
- [x] redesign org creation modal
  - let the user choose whether they want a single or multi-sig backed org
  - pre-fill the org owner input with the wallet address for single-sig
  - pre-fill the org first member input with the walled address for multi-sig
- [x] implement single-sig org creation flow
- [x] differentiate single-sig in Org screen -> query `/safes/{address}` on https://safe-transaction.gnosis.io
  - no gnosis safe icon for owner address
  - remove quorum info
  - no members tab
  - different context menu contents
- [x] implement project anchor flow for single-sig orgs
  - pending anchors might just be pending tx in the wallet?

**Comment by juliendonck** [comment]
@rudolfs https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=9370%3A142886
