### ISSUE TITLE
Whole option animated instead of just its contents

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2086]
In the new project form clicking elements within an option will animate the entire option instead of just the clicked button or dropdown.

https://user-images.githubusercontent.com/158411/123921850-bd9e1b80-d987-11eb-958f-61bd94153c4b.mov

**Comment by brandonhaslegs** [comment]
Yeah I couldn't figure out how to turn the `:active` transition off when it was open.

**Comment by juliendonck** [comment]
> Yeah I couldn't figure out how to turn the `:active` transition off when it was open.

Will you fix it or want me to take a look at it?

**Comment by brandonhaslegs** [comment]
I can't figure it out, so go for it!
