### ISSUE TITLE
Merge unreplicated and replicated project cards in orgs

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2089]
Right now we split the projects lists into the projects you have replicated and the ones you don't. I think we should merge the lists. We can indicate to the user that it's not replicated on hover.

<img width="954" alt="Screenshot 2021-06-30 at 11 56 32" src="https://user-images.githubusercontent.com/2326909/123941203-8b78c380-d95f-11eb-8aa8-81091e4ca023.png">

**Comment by juliendonck** [comment]
@rudolfs how hard would this be? I know that the data is slightly different.

**Comment by rudolfs** [comment]
Shouldn't be too hard. Initially I went for splitting the lists up to save some time while implementing orgs.

Now that orgs are done, we should refactor and clean up the `ProjectList` component and the components it uses.
`ProjectList` used in various contexts:
  - `ui/Screen/UserProfile/Projects.svelte`
  - `ui/Screen/Profile/Projects.svelte`
  - `ui/Screen/Profile/Following.svelte`
  - `ui/Screen/Org/Projects.svelte`

It would also make sense to first think on how we can prepare the data that goes into it better on the org side.

**Comment by juliendonck** [comment]
> It would also make sense to first think on how we can prepare the data that goes into it better on the org side.

What do you mean with this?

**Comment by rudolfs** [comment]
We could split the data differently in the resolver function, so that you get what you need in the view and don't have to do a lot of branching: https://github.com/radicle-dev/radicle-upstream/blob/master/ui/src/org.ts#L330.

**Comment by juliendonck** [comment]
Should also use the <squareprojectcard /> component

**Comment by juliendonck** [comment]
![image](https://user-images.githubusercontent.com/2326909/143053239-d1c2bd9d-b103-4f2e-9930-6941e1e84cdf.png)

**Comment by Kaihuang724** [comment]
Closing this as orgs will not be implemented for MVP
