### ISSUE TITLE
Show Ethereum address on profile after attested

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2091]
- [ ] add check next to name
- [ ] add popover when hovering check
- [ ] add eth address next to device id
- [x] remove expanding device id (if the user needs to look at the full device id, they can copy and paste it somewhere, the use case of looking at a full 64-digit device ID is not strong enough to keep it expanding on hover. most users are just copying it and pasting it somewhere.)
- [ ] add tooltip on eth address "Verified Ethereum address"
- [x] add tooltip on Device ID "Device ID"
- [x] #2271

![image](https://user-images.githubusercontent.com/4406983/124122245-2b287580-da76-11eb-91ee-ea000e13f00c.png)

**Comment by nishit-prasad** [comment]
I understand most but not all of it. I can take this up if it's up for grab and maybe connect to understand the missing pieces of my knowledge.

**Comment by brandonhaslegs** [comment]
I'm not sure this is ready to be worked on yet. @rudolfs @juliendonck can confirm…

**Comment by rudolfs** [comment]
I _think_ it should be possible to start working on this. We already check the attestation status on the wallet page: https://github.com/radicle-dev/radicle-upstream/blob/master/ui/Screen/Wallet.svelte#L107, so it should be possible to adapt that to the profile page too.

**Comment by rudolfs** [comment]
On second thought, it might require some more work to refactor the way we fetch the attestation status though: https://github.com/radicle-dev/radicle-upstream/blob/master/ui/src/attestation/status.ts#L47.

**Comment by juliendonck** [comment]
This should probably be shown in the sidebar
