### ISSUE TITLE
Make Copy Icon not part of Hoverable

### ISSUE THREAD

**Issue by nishit-prasad** [radicle-dev/radicle-upstream#2098]
Per below gif, the `<Hoverable />` element is wrapped around `<Copyable />` (where the copy icon exists) which makes the Icon part of hover event which makes it a sort of annoying when you just want to hover towards the copy icon (in case when you don't want to see the whole Id). [Reference](https://github.com/radicle-dev/radicle-upstream/blob/master/ui/DesignSystem/StyledCopyable.svelte#L33)

![ScreenRecord](https://user-images.githubusercontent.com/64563418/124362795-d42cc700-dc54-11eb-8379-03d1ab2b6108.gif)
 
Feel free to close this if this doesn't qualify as an issue.

**Comment by nishit-prasad** [comment]
I can work on fixing this. The change would mostly be:
- To wrap `<Hoverable />` inside the `<Copyable />` around the paragraph tags. This way only when you hover around the id text, the hover event gets triggered leaving out the copy icon.

**Comment by geigerzaehler** [comment]
Sounds reasonable to me. @brandonhaslegs @juliendonck: is this ok from a design perspective?

**Comment by brandonhaslegs** [comment]
Fine with me yes. Although I'm thinking we should stop this thing from expanding at all. The use case for seeing the full ID is so small that we don't need to expand it. If the user really needs to see the full Device ID, they can copy it and paste it somewhere.

**Comment by nishit-prasad** [comment]
Since I have a PR ready that disables expansion of Device ID on profile screen, shall I go ahead with the change as per this posted issue?

**Comment by brandonhaslegs** [comment]
I don't think this really needs to be done anymore. Probably can be closed.
