### ISSUE TITLE
Improve performance of orgs

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2099]
My org took 7 minutes to load, then about 30 seconds to load the members page once I got to the org page. In the time when it is loading, the app is unresponsive and there's no way to get out of it besides refreshing. We should at least allow the user to click something else while org is loading (This would cancel the request for the org page).

It would be great if we could store all org data locally and only fetch updates instead of fetching it every time it's clicked on.

**Comment by geigerzaehler** [comment]
> We should at least allow the user to click something else while org is loading (This would cancel the request for the org page).

I’d prefer having the loading time out (#2109). If the user is allowed to click on something else there is the potential to mess up the system state.

> It would be great if we could store all org data locally and only fetch updates instead of fetching it every time it's clicked on.

Created #2108 to track this.

@brandonhaslegs: Mind if we close this in favor of the two issues I created?
