### ISSUE TITLE
Cache org data

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2108]
To get data for displaying orgs we issue a lot of requests which may result and long load times and potentially rate limiting. We can easily cache the following data fetches because the data is immutable`
* `isMultiSig` from `ui/src/org`
* `getOwner` from `ui/src/org`

We should also cache data that is mutable but changes infrequently. Even a max-age of 60 seconds would decrease the number of requests. The only candidate for this is

* `ClaimContract#getClaimed` as used in `getClaimedIdentity` in `ui/src/org`

We should also investigate more candidates for caching.

**Comment by rudolfs** [comment]
> isMultiSig from ui/src/org
> getOwner from ui/src/org

This was already done in https://github.com/radicle-dev/radicle-upstream/pull/2167.
