### ISSUE TITLE
Update copy for wallet connection screen

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2110]
We should update the copy in the wallet connection screen. We should probably not mention a specific feature and mention WalletConnect explicitly.
![Screenshot from 2021-07-08 12-31-33](https://user-images.githubusercontent.com/3919579/124907640-b2329c00-dfe8-11eb-9787-c7830d1e0772.png)

**Comment by brandonhaslegs** [comment]
I do think it's smart to give users a reason why they should connect their wallet. Maybe we can add more reasons, instead of just "funding features."

**Comment by brandonhaslegs** [comment]
Let's just make it generic, "In order to use Ethereum features, you need to connect a wallet."

**Comment by rudolfs** [comment]
@brandonhaslegs we should also somewhere mention WalletConnect, as they're the provider.

**Comment by brandonhaslegs** [comment]
Why do we need to mention it though? Does it help the user at all?

**Comment by rudolfs** [comment]
> Why do we need to mention it though? Does it help the user at all?

Perhaps the link to the supported wallets on the WalletConnect website is enough 🤷 .

**Comment by brandonhaslegs** [comment]
I think the link to compatible wallets is good enough because that affects the user (answers the question "can I use my wallet or not").
