### ISSUE TITLE
Error after resetting state

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2119]
After resetting my state (deleting `sandbox/rad_home`) I refresh and get this error. The first word should be capitalized but also is the error something we need to do something about?

<img width="752" alt="image" src="https://user-images.githubusercontent.com/4406983/125266547-35fcc900-e306-11eb-8cc8-fea6064e94d9.png">

**Comment by brandonhaslegs** [comment]
Also I thought it was strange that after deleting rad_home and refreshing, the screen didn't automatically go to onboarding.

**Comment by geigerzaehler** [comment]
Unfortunately it’s necessary to restart the whole app for resetting to work. The reason is that the proxy is running in the background and doesn’t know that `rad_home` has been deleted. I’m updating the docs to better reflect this in #2120.
