### ISSUE TITLE
Timing mismatch between notification and project showing up in the following list

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2124]
When a project is found and cloned, it takes a while for the project to actually show up in the list, even though the notification has already fired.

Note: see notification has fired, but the project is not yet shown in the list.
![image](https://user-images.githubusercontent.com/4406983/125606495-05e3b0f5-bad8-4d5e-ab6a-55ad04ccba08.png)

**Comment by rudolfs** [comment]
The "projects" and "following" screens got consolidated and the logic has changed. I tried following a project and the notification appeared at the same time as the project card.
