### ISSUE TITLE
Implement Contributors page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2125]
I want to try to clean up the header of the project page, it always seems to look so messy and full of stuff. I think if we remove this though, it will feel more resolved. Let's implement a contributors page on projects, and remove the "X Contributors" stat under the Project ID. Obviously we only have the Git name and Git email address of the contributors, which is fine. At some point we should make this list a list of Radicle identities.

![image](https://user-images.githubusercontent.com/4406983/125609605-5802d84e-79d2-458a-bca5-015860d3dfe1.png)

**Comment by Kaihuang724** [comment]
I really like this idea. Maybe we can expand on it to also show contributors stats.
