### ISSUE TITLE
Expose avatar fallbacks in GraphQL API

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#213]
Pending the implementation in #181 the proxy should expose the generate values for an org and user.

- [x] Extend Org and User entities with avatar fallback information
- [x] Add schema to get avatar info for org id
- [x] Add schema to get avatar info for user handle

**Comment by MeBrei** [comment]
@xla We might need an extra endpoint for this, which returns the avatar fallback for a unregistered ie available org handle. When registering your Org, you choose a org handle and the avatar should be shown in the ui before the org is actually created on the Registry.

**Comment by xla** [comment]
@MeBrei Is this true for identity avatars as well?

**Comment by MeBrei** [comment]
For identity the fallback avatar is only shown after creation (and if no custom avatar was provided). 
For user registration, we also want to show the fallback avatar while changing to a new handle.

**Comment by xla** [comment]
There are currently avatars attached to users (meaning a registered handle on the Registry), so avatars only are important in the context of the identity. Does that change our understanding what endpoints we need? @MeBrei

**Comment by MeBrei** [comment]
@xla My understanding was that there are avatars attached to identity and org. When you first open the app and create your identity, you can provide an avatar or get a fallback one depending on the name you choose. When you register your user, you might or have to change your previously picked name (which will become your user handle) and the fallback avatar has to change accordingly.

**Comment by xla** [comment]
@MeBrei Our understandings match and we should have an endpoint previewing the generated avatar info given a `handle`. Updated the todo list up top.

**Comment by MeBrei** [comment]
Proposal for the schema additions:

```graphql
type UpstreamQuery {
  ...
  avatar(handle: ID!): Avatar!
}

type IdentityMetadata {
  ...
  avatarFallback: Avatar!
}
```
with `Avatar` coming from `proxy/src/avatar.rs`. Currently we don't distinguish between user and org when creating the avatar so that one endpoint is enough.

**Comment by xla** [comment]
@MeBrei Looks guuut, one small addition as we declare our types conversion types explicitely:

``` graphql
type Avatar {
    emoji: String!
    background: String!
}
```
