### ISSUE TITLE
Make lock screen honor theme settings

### ISSUE THREAD

**Issue by nishit-prasad** [radicle-dev/radicle-upstream#2130]
By default, the lock screen is dark-themed.
Currently when you set the theme to a different setting (like Light), the lock screen doesn't take up that preference.

STRs(Steps To Reproduce)
1. Under homepage settings, change the theme to Light.
2. Lock the app or re-launch the app.
3. Notice the lock screen is still dark-themed.

Not a priority but something to look into (which even I can take it up and check it out)

**Comment by geigerzaehler** [comment]
This would be solved by https://github.com/radicle-dev/radicle-upstream/issues/1849
