### ISSUE TITLE
Integrate Blockies

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2141]
Add Blockies to Upstream.

https://github.com/ethereum/blockies

To do:
- [ ] show it on the profile in about section
- [ ] add option in settings to use blockies instead of emoji/colors
- [ ] when blockie avatars are selected in settings, show the upstream icon on the profile in the about section instead of showing the blockie

Profile about section when avatar is selected:
![image](https://user-images.githubusercontent.com/4406983/138081817-4993c1b8-e29a-4c78-a71d-2211b755da41.png)

Profile about section when Blockie is selected (note: blockies and emojis would be mixed in this case, because only ethereum wallet-connected users will have blockie avatars):
![image](https://user-images.githubusercontent.com/4406983/137737110-ce8f883e-636b-4095-98d1-13ddcec0e975.png)

Setting in appearance settings: 
![image](https://user-images.githubusercontent.com/4406983/137728568-9638d4f9-9919-4aff-9c0f-9354ec8b0f17.png)

**Comment by rudolfs** [comment]
Why would we want to do this? Our avatars are based on the Radicle protocol IDs, not Ethereum addresses. Was your intention to show Ethereum addresses as blockies?

**Comment by brandonhaslegs** [comment]
Yeah the idea was to show orgs and users with linked eth addresses as blockies. I still hate the idea, but I got bullied into making this issue! /s

**Comment by brandonhaslegs** [comment]
Ah actually no, this was just the idea to show the blocky pattern _somewhere_. Not to replace the avatars!

**Comment by rudolfs** [comment]
> Ah actually no, this was just the idea to show the blocky pattern somewhere. Not to replace the avatars!

Got it.

**Comment by brandonhaslegs** [comment]
Should be a circle yes. My bad. we do want to keep circle for users and square for orgs, yes.

**Comment by Kaihuang724** [comment]
I believe this is done
