### ISSUE TITLE
Have a show (eye) icon on passphrase fields

### ISSUE THREAD

**Issue by nishit-prasad** [radicle-dev/radicle-upstream#2142]
Currently when you enter a new radicle user details, you get asked to enter new passphrase:
![Screen Shot 2021-07-17 at 12 07 27 PM](https://user-images.githubusercontent.com/64563418/126028466-556f1e80-738e-48ea-bc80-0e47f2576d80.png)

A nice to have feature would be:
- [ ] to have show/eye icon at the end of passphrase input fields (for convenience purposes).
- [ ] the icon displays only when at least one character is entered.
- [ ] when the icon is clicked, the hidden characters are shown to the user.

**Comment by brandonhaslegs** [comment]
There is already an eye icon. 👍 I would just say put the icon in the field on the right side.

**Comment by nishit-prasad** [comment]
Alright! Sounds good. I will go ahead and do that. Thanks!

**Comment by nishit-prasad** [comment]
The PR is up and ready! 😄
