### ISSUE TITLE
Have an option for the app's theme to sync up with OS's theme settings.

### ISSUE THREAD

**Issue by nishit-prasad** [radicle-dev/radicle-upstream#2143]
Currently, we have the following options for changing themes:
![Screen Shot 2021-07-17 at 12 15 08 PM](https://user-images.githubusercontent.com/64563418/126028631-41af1ac4-7d9c-4e06-a4f8-1c90bcc1c238.png)

A nice to have feature would be:
- [ ] To have an additional option called `System`.
- [ ] Once selected, the app will sync based on the OS's theme settings.
- [ ] Whenever the OS's theme changes, the app's theme changes.

**Comment by brandonhaslegs** [comment]
Yes, I have been wanting to do this.

**Comment by nishit-prasad** [comment]
I will start working on this. Can it be assigned to me?
