### ISSUE TITLE
Register, connect and edit an ENS name for an org from upstream

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2147]
- [x] Allow users to register a `<name>.radicle.eth` address
- [x] Allow users to edit the input
  - [x] Allow users to point that ENS address to their org
  - [x] Allow users to add extra metadata
- [x] Allow users to point from their org to the ENS domain
- [x] Show metadata on the org page and sidebar

**Comment by rudolfs** [comment]
Closed via 3fd6112bde2111a723ba478374f78c143df87079.
