### ISSUE TITLE
Patches follow up

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2150]
This is some work that would feature complete the current implementation of patches.

- [ ] Think about how to pull from the maintainer (dropdown) #1842  (@geigerzaehler)
- [ ] Automatic following of peers (@geigerzaehler)

**Comment by rudolfs** [comment]
Closing this as we're already [iterating on the patches feature](https://www.notion.so/radicle-upstream/Upstream-Patch-Collaboration-Workflow-037e8df4be80476d9f22f88431b3b346).
