### ISSUE TITLE
Infura node not working so Ethereum events can`t be fetched

### ISSUE THREAD

**Issue by pimato** [radicle-dev/radicle-upstream#2155]
Hey guys just tried to link my radicle ID with an ethereum address. After signing a transaction I got this error:
<img width="2869" alt="Bildschirmfoto 2021-07-20 um 20 58 18" src="https://user-images.githubusercontent.com/5337809/126380275-7a682c9b-b7cc-4ca0-8c18-28a58b258a9d.png">

Also it seems like your infura node is down because upstream is not able to fetch important data:
<img width="2475" alt="Bildschirmfoto 2021-07-20 um 21 02 51" src="https://user-images.githubusercontent.com/5337809/126381090-8e0510a3-3cf8-4b19-9e14-459631b5cede.png">

```
{
  "stack": "Error: failed response (requestBody=\"{\\\"method\\\":\\\"eth_getLogs\\\",\\\"params\\\":[{\\\"fromBlock\\\":\\\"0x0\\\",\\\"toBlock\\\":\\\"latest\\\",\\\"address\\\":\\\"0x4a7dfda4f2e9f062965cc87f775841fb58aea83e\\\",\\\"topics\\\":[\\\"0xb449c24d261a59627b537c8c41c57ab559f4205c56bea745ff61c5521bece214\\\",\\\"0x000000000000000000000000441428454b614d2bb2782165ef1cee53da79dd93\\\"]}],\\\"id\\\":55,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://mainnet.infura.io/v3/7a19a4bf0af84fcc86ffb693a257fad4\", code=SERVER_ERROR, version=web/5.3.0)\n    at l.makeError (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:82965)\n    at l.throwError (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:83085)\n    at file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:194625\n    at Generator.next (<anonymous>)\n    at a (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:190986)",
  "message": "failed response (requestBody=\"{\\\"method\\\":\\\"eth_getLogs\\\",\\\"params\\\":[{\\\"fromBlock\\\":\\\"0x0\\\",\\\"toBlock\\\":\\\"latest\\\",\\\"address\\\":\\\"0x4a7dfda4f2e9f062965cc87f775841fb58aea83e\\\",\\\"topics\\\":[\\\"0xb449c24d261a59627b537c8c41c57ab559f4205c56bea745ff61c5521bece214\\\",\\\"0x000000000000000000000000441428454b614d2bb2782165ef1cee53da79dd93\\\"]}],\\\"id\\\":55,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://mainnet.infura.io/v3/7a19a4bf0af84fcc86ffb693a257fad4\", code=SERVER_ERROR, version=web/5.3.0)",
  "code": "UnhandledRejection",
  "details": {
    "name": "Error",
    "reason": "failed response",
    "code": "SERVER_ERROR",
    "requestBody": "{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x0\",\"toBlock\":\"latest\",\"address\":\"0x4a7dfda4f2e9f062965cc87f775841fb58aea83e\",\"topics\":[\"0xb449c24d261a59627b537c8c41c57ab559f4205c56bea745ff61c5521bece214\",\"0x000000000000000000000000441428454b614d2bb2782165ef1cee53da79dd93\"]}],\"id\":55,\"jsonrpc\":\"2.0\"}",
    "requestMethod": "POST",
    "url": "https://mainnet.infura.io/v3/7a19a4bf0af84fcc86ffb693a257fad4"
  }
}```

**Comment by rudolfs** [comment]
Indeed, we ran into API limits, we'll try the following:
  - upgrade our infura account to get higher API limits
  - how to reduce the amount of requests https://github.com/radicle-dev/radicle-upstream/issues/1916
  - expose the api endpoints in settings so users can use their own api accounts https://github.com/radicle-dev/radicle-upstream/issues/2054

**Comment by rudolfs** [comment]
With v0.2.9 we released a couple of small improvements that seem to have reduced the request amounts so we don't hit the limits at the moment.

- https://github.com/radicle-dev/radicle-upstream/commit/f50babc192a7bceb96c99620b3490cf8e7f9d76d
- https://github.com/radicle-dev/radicle-upstream/commit/ad3db526eaa0934a02af3b3ccf59aa2ba696018e
- https://github.com/radicle-dev/radicle-upstream/commit/bdbb2f4ad3139fd08a09089ba856dc7b91377894
- https://github.com/radicle-dev/radicle-upstream/commit/669273290057ba28f035e3b4a89b256235b2d842

v0.2.9 was released on the 23rd of July, it seems to align with the drop in requests:
<img width="1314" alt="Screenshot 2021-08-04 at 09 13 32" src="https://user-images.githubusercontent.com/158411/128137928-e0b43ad9-98fb-4321-bfbe-d60a8a62eef4.png">

We'll still do the other improvements mentioned in https://github.com/radicle-dev/radicle-upstream/issues/2155#issuecomment-883961277, but I'll close this issue for now. Please re-open it if it's still a problem.
