### ISSUE TITLE
New version notification (and button in settings) not firing

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2156]
notify me is turned on

![image](https://user-images.githubusercontent.com/4406983/126431929-86961bff-332c-4601-8cbd-36941ad41166.png)

but the button in settings isn't there, and also I didn't get notified of the new version.

![image](https://user-images.githubusercontent.com/4406983/126431943-ac86f71e-386f-4400-9346-c6ac7e4db77b.png)

- [ ] #2157

**Comment by geigerzaehler** [comment]
I forgot to update the notification when doing the release :grimacing:. Is fixed now
