### ISSUE TITLE
Tooltip in New Project modal is mis-aligned

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2161]
It should be centered. It actually is centered in Version 0.2.8-875075639a23b5629e57985c98dc0dd92fc45965, so something was messed up. Probably a result of #1961 

![image](https://user-images.githubusercontent.com/4406983/126474956-df069f04-517e-479b-9ee2-290e1fb37557.png)

**Comment by nishit-prasad** [comment]
I can take a look at this. Kindly assign it to me, if available.

**Comment by nishit-prasad** [comment]
PR is up and ready. Apologies for any delay.

**Comment by rudolfs** [comment]
Fixed via https://github.com/radicle-dev/radicle-upstream/pull/2190.
