### ISSUE TITLE
radicle:// links don't open the repo on Linux

### ISSUE THREAD

**Issue by talentlessguy** [radicle-dev/radicle-upstream#2166]
## Reproduction

- Download Radicle for Linux (AppImage)
- Install AppImage
- Make Upstream executable (if `x` permission not set):

```sh
chmod +x $HOME/Applications/radicle-upstream-0.2.8.AppImage
```

- Create `$HOME/.local/share/applications/radicle-upstream.desktop` file with these contents:

```desktop
[Desktop Entry]
Exec=$HOME/Applications/radicle-upstream-0.2.8.AppImage %U
Terminal=false
Type=Application
MimeType=x-scheme-handler/radicle;
```
- `chmod +x` for that file
- Try to open a link in a browser, it prompts you to use Radicle, follow the prompt
- See Radicle doing nothing

## Info

- Kernel: 5.10.49-1-MANJARO
- Upstream version: 0.2.8

**Comment by rudolfs** [comment]
I just tried to reproduce this on Ubuntu 20.04.2 LTS, following the instructions. I could not reproduce the behaviour you mentioned, when I click on a link, it opens Upstream on the search view with the project URN pre-filled:


https://user-images.githubusercontent.com/158411/128866520-b21bc85e-2b9a-4810-b3dd-991afb374f3d.mov

After you created the `$HOME/.local/share/applications/radicle-upstream.desktop` file, did you also run `update-desktop-database ~/.local/share/applications` as per [the instructions](https://docs.radicle.xyz/docs/understanding-radicle/faq#is-it-possible-to-launch-upstream-via-links-on-the-web)?

What Linux distribution are you using?

**Comment by talentlessguy** [comment]
@rudolfs I use Manjaro Linux and I didn't run `update-desktop-database`

**Comment by rudolfs** [comment]
Could you try that to see if it solves the problem?

**Comment by talentlessguy** [comment]
@rudolfs I tried it an no it nothing still happens

**Comment by rudolfs** [comment]
Could you try running upstream from the console giving the URL as a parameter?
Like so:

```
./radicle-upstream-0.2.9.AppImage radicle://link/v0/rad:git:hnrkmzko1nps1pjogxadcmqipfxpeqn6xbeto
```

**Comment by talentlessguy** [comment]
@rudolfs this works (with CLI)

![image](https://user-images.githubusercontent.com/35937217/128907185-359f53bd-0948-4124-90a4-c3b5821a8764.png)

but through browser it doesn't

**Comment by rudolfs** [comment]
I think this means that the integration on the OS level isn't working. Given that Upstream opens when you click on a link, but doesn't open the search modal means that the URL is not passed along via the `%U` param in:
```
Exec=$HOME/Downloads/radicle-upstream-0.2.1.AppImage %U
```

And opening it via the terminal with:
```
xdg-open "radicle://link/v0/rad:git:hnrkmzko1nps1pjogxadcmqipfxpeqn6xbeto"
```

Doesn't work either, right?

**Comment by talentlessguy** [comment]
@rudolfs yes `xdg-open` doesn't work either

this is what i have in my `.desktop` file rn:

```desktop
[Desktop Entry]
Type=Application
Name=Open Radicle
Exec=/home/v1rtl/Applications/radicle-upstream.AppImage --no-sandbox %U
StartupNotify=false
MimeType=x-scheme-handler/radicle;
```

**Comment by rudolfs** [comment]
Could you try swapping the params around? Like this:
```
Exec=/home/v1rtl/Applications/radicle-upstream.AppImage %U --no-sandbox
```

**Comment by talentlessguy** [comment]
@rudolfs still doesn't work

this is what get's logged btw:

```
Aug 11 10:42:28.504  INFO accept{peer_id=hynuhpwux6h56cokwf6zfbby699m5rf6crhirkgi3chybw9cni3nyc}:disco:discovered{remote_id=hynkyndc6w3p8urucakobzna7sxwgcqny7xxtw88dtx3pkf7m3nrzc}:incoming{remote_id=hynkyndc6w3p8urucakobzna7sxwgcqny7xxtw88dtx3pkf7m3nrzc remote_addr=35.187.60.160:12345}: librad::net::protocol::io::streams: new ingress stream
Aug 11 10:42:28.505  WARN radicle_daemon::peer::run_state::running_waiting_room: waiting room error error=MissingUrn(Urn { id: Oid(8cc143b5b061d9882726564702017b5f94bb0f1a), path: Some(RefLike("rad/id")) })
Aug 11 10:42:28.505  WARN radicle_daemon::peer::run_state::running_waiting_room: waiting room error error=MissingUrn(Urn { id: Oid(8cc143b5b061d9882726564702017b5f94bb0f1a), path: Some(RefLike("rad/id")) })
Aug 11 10:42:28.861  INFO accept{peer_id=hynuhpwux6h56cokwf6zfbby699m5rf6crhirkgi3chybw9cni3nyc}:disco:discovered{remote_id=hynkyndc6w3p8urucakobzna7sxwgcqny7xxtw88dtx3pkf7m3nrzc}:incoming{remote_id=hynkyndc6w3p8urucakobzna7sxwgcqny7xxtw88dtx3pkf7m3nrzc remote_addr=35.187.60.160:12345}: librad::net::protocol::io::streams: new ingress stream
Aug 11 10:42:28.862  WARN radicle_daemon::peer::run_state::running_waiting_room: waiting room error error=MissingUrn(Urn { id: Oid(8cc143b5b061d9882726564702017b5f94bb0f1a), path: Some(RefLike("rad/id")) })
```

**Comment by rudolfs** [comment]
I'm running out of ideas. 🤷 

One last thing you could perhaps check is whether there are any other `.desktop` files that launch Upstream with the wrong params in `$HOME/.local/share/applications`.

**Comment by talentlessguy** [comment]
@rudolfs I don't know what's wrong either, it maybe be a bug in my system which I might not know about

unrelated but IMO Radicle better registers a scheme protocol themself so there's no chance a user fails to setup it themselves

**Comment by rudolfs** [comment]
> unrelated but IMO Radicle better registers a scheme protocol themself so there's no chance a user fails to setup it themselves

We do this on macOS, but I'm not aware of a reliable way to do this on Linux. Let me know if you know how this could be achieved.

**Comment by talentlessguy** [comment]
@rudolfs copying to `$HOME/.local/share/applications/radicle.desktop` maybe 🤔 

it's the default location for desktop files on many distros

**Comment by geigerzaehler** [comment]
@talentlessguy: Could you post the content of `$HOME/.local/share/appliactions/mimeinfo.cache`? It should contain the line
```plain
x-scheme-handler/radicle=radicle-upstream.desktop
```

Could you also try replacing the `Exec` line with this
```plain
Exec=/usr/bin/firefox %U
```
If this doesn’t open firefox there’s probably something wrong with the system configuration. (You can replace `firefox` with a different browser if you don’t have it installed)

Finally, could you run `env | grep XDG_DATA_HOME` in your terminal to see if this variable is set?

**Comment by talentlessguy** [comment]
@geigerzaehler this is what I have:

```
➜ cat ~/.local/share/applications/mimeinfo.cache | grep radicle
x-scheme-handler/radicle=appimagekit_e5c0fcf6b6469090edb6e20393c77581-Radicle_Upstream.desktop;radicle-upstream.desktop;
```

all other `.desktop` files work

**Comment by geigerzaehler** [comment]
It looks like the KDE App Image Kit has already installed a desktop file for upstream. Try removing that file and run `update-desktop-database ~/.local/share/applications` again.

**Comment by talentlessguy** [comment]
@geigerzaehler omg it worked!!!

![image](https://user-images.githubusercontent.com/35937217/129066218-4544e791-e29d-4510-8a60-44a4fc49ffd6.png)


thanks a lot
