### ISSUE TITLE
App refresh navigates away from org

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2168]
If we're on an Org profile screen and refresh the app via <kbd>⌘</kbd>+<kbd>r</kbd>, the app navigates to the user profile screen.
Instead it should stay on the Org profile even after the refresh.

https://user-images.githubusercontent.com/158411/126620171-4a160a7e-64b3-4714-aa34-a4db82c2881f.mov

**Comment by nishit-prasad** [comment]
I can take a look on this, if it's available to work on.

**Comment by rudolfs** [comment]
Yeah, give it a go.

**Comment by nishit-prasad** [comment]
Apologies as I was out for a while. I will start looking into it.

**Comment by Kaihuang724** [comment]
Closing this as orgs will not be implemented for MVP
