### ISSUE TITLE
Show seed phrase to user

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2189]
[Design is here](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/Radicle-Upstream?node-id=9966%3A175486).

I'm not sure why the design is in a modal. My first thought is that it should be in the onboarding, but maybe we put it in a modal after the onboarding for … important reasons? Not sure. I think it could go as an extra step in onboarding.

![image](https://user-images.githubusercontent.com/4406983/127653176-5f60dc80-2cdc-4c32-983d-71e63b8ce895.png)
![image](https://user-images.githubusercontent.com/4406983/127653362-d6faf2ae-9457-4d7a-aa52-cb3284ef363e.png)
![image](https://user-images.githubusercontent.com/4406983/127653376-c9dd7b0a-ff25-4d41-90f2-4172ac2e4532.png)
![image](https://user-images.githubusercontent.com/4406983/127653406-117e3c4c-b522-4828-bce5-3bccd8250e0a.png)

**Comment by juliendonck** [comment]
@geigerzaehler @rudolfs could you explain the flow to back up your identity here? I'll add that to the docs.

**Comment by rudolfs** [comment]
Superseded by https://github.com/radicle-dev/radicle-upstream/issues/2802.
