### ISSUE TITLE
How should we show GitHub and Twitter profiles in Org header?

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2194]
Status quo:
<img width="1151" alt="Screenshot 2021-08-05 at 12 00 47" src="https://user-images.githubusercontent.com/158411/128331870-ccfcd4c9-6632-4594-9bdf-14adddc5db62.png">

We already show the website link in the header, now we also have:
  - Twitter and
  - GitHub links as part of the ENS metadata.

Required by: https://github.com/radicle-dev/radicle-upstream/pull/2191

**Comment by brandonhaslegs** [comment]
Let's do this?
![image](https://user-images.githubusercontent.com/4406983/128506295-6d7390a5-c6d5-475b-8558-8468b3f5951f.png)

Figma design is [here](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/Radicle-Upstream?node-id=8225%3A236).

[Github icon](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/Radicle-Upstream?node-id=10154%3A163726)
[Twitter icon](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/Radicle-Upstream?node-id=10152%3A163541)

**Comment by rudolfs** [comment]
Done in https://github.com/radicle-dev/radicle-upstream/pull/2191.
