### ISSUE TITLE
Fund contributors on Upstream

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2209]
Ideas:
- attest GPG public part to the Rad ID
- lock funds somewhere, pay contributors them out of those funds
- pay maintainers to review or merge your code.
- funding issues

**Comment by rudolfs** [comment]
This seems to be out of scope for Upstream currently. We're [focussing on code collaboration](https://www.notion.so/radicle-upstream/MVP-Launch-5050d7a9833149aa9b4f2ddc013b50c8) for now.

Could be something we could use https://www.drips.network.
