### ISSUE TITLE
CI fails with “Bad file descriptor” error

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2216]
[Occasionally](https://buildkite.com/monadic/radicle-upstream/builds/10146#0028c719-444f-4b00-8e56-8c412df1b313/3184-3323), Buildkite CI fails because the proxy encounters the following error
```plain
Init(Cache(Watch(Notify(Io(Os { code: 9, kind: Other, message: "Bad file descriptor" })))))
```

The error happens when the proxy is initialized after the keystore is unsealed. The error is returned by either of [these calls](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/git/storage/watch.rs#L100-L101) in radicle-link.

It is possible that the [`inotify`](https://docs.rs/inotify/0.9.3/inotify/struct.Inotify.html) is not properly initialized. A potential cause might be https://github.com/radicle-dev/radicle-link/issues/750.

I can’t reproduce this locally.

**Comment by rudolfs** [comment]
We don't have buildkite anymore, can we close this @geigerzaehler?
