### ISSUE TITLE
Handle RAD tokens in Upstream

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2222]
At the moment Upstream only is aware of ETH and DAI tokens.
For [ENS name registration](https://github.com/radicle-dev/radicle-upstream/pull/2191) we'll need to check the RAD balance.

Hide the DAI balance if the token streams feature is not enabled.

<img width="1552" alt="Screenshot 2021-08-12 at 11 27 43" src="https://user-images.githubusercontent.com/158411/129173499-27a511fc-01d3-409d-99d6-485080963ecb.png">

**Comment by geigerzaehler** [comment]
> Hide the DAI balance if the token streams feature is not enabled.

I’d be ok with always hiding the DAI balance since nobody uses the token streams at the moment.

**Comment by rudolfs** [comment]
> I’d be ok with always hiding the DAI balance since nobody uses the token streams at the moment.

To be consistent, I'd rather hide it behind `isDev`, since it belongs to the token streams, which we also hide behind `isDev`. We can remove it entirely if we also remove that feature from the code, otherwise it'll be confusing when somebody will want to test it. 🤷
