### ISSUE TITLE
Anchoring doesn't work with Ledger connected through WalletConnect

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#2226]
I've tried to anchor a project with the Ledger WalletConnect integration, and though it appears to succeed on Upstream, no anchor proposal is created in the Gnosis Safe.

The last thing I see is this message:

![image](https://user-images.githubusercontent.com/40774/129181579-82d08a6d-3898-477e-a047-f67d2c132ced.png)

But nothing happens. Everything else up to that point works as expected.

**Comment by Zerim** [comment]
Also ran into an issue using Ledger Live w/ Radicle Upstream via Wallet Connect.

After digging into Electron dev tools, I see that a network request to ` https://safe-transaction.gnosis.io/api/v1/safes/0xCCCC/multisig-transactions/`:

```
{"nonFieldErrors":["Signer=0xAAAA is not an owner or delegate. Current owners=['0xBBBB']. Delegates=set()"]}
```

Where `0xBBBB` is the account that I'm connected to Radicle Upstream w/ via Ledger Live WalletConnect, and `0xAAAA` is some address that I do not recognize.

A workaround that worked for me is that I just copied the `data` and `to` fields from the request payload that generated that error, and put them directly into the Gnosis Safe UI "Contract Interaction" form w/ "Use custom data (hex encoded)" enabled.

Versions Using
- Ledger Live (2.35.2)
- Ledger Firmware (2.0.0)
- Radicle Upstrea (0.2.11)
