### ISSUE TITLE
Flaky networking test on CI

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2232]
The networking and patches tests sometimes [fail](https://buildkite.com/monadic/radicle-upstream/builds/10197#fd36e975-02b5-4f15-85ab-c8b215f3030f) on CI. The failure is due to data not replicated between the nodes.

**Comment by geigerzaehler** [comment]
In [builds](https://github.com/radicle-dev/radicle-upstream/actions/runs/1139254366) Github Actions we’re seeing the following warning
```plain
recv git error err=Rere(MissingSignedRefs(Urn { id: Oid(c7c303d71b4617696f8eca12b64780c267ad79a8), path: None }))
```
It’s repeated multiple times with the same URN.

**Comment by geigerzaehler** [comment]
Increasing the timeout for tests doesn’t help.

**Comment by geigerzaehler** [comment]
Here’s [another failure](https://buildkite.com/monadic/radicle-upstream/builds/10249#b02a5c84-e5f1-4e2b-b9d2-3e488f7538dc) that doesn’t seem to be caused by a `.lock` file for a reference to exist https://github.com/radicle-dev/radicle-link/issues/758.

**Comment by geigerzaehler** [comment]
Since https://github.com/radicle-dev/radicle-link/pull/777 we’re seeing the following error
```
recv git error err=Rere(Fetcher(Concurrent { urn: Urn { id: Oid(d8fd76b7f3eaecf62a11ead632bd580cca852b30), path: None }, remote_peer: hydkthp9j3ufuzt69nepfzu5x8wcmqmy9ckoi7hythguitfmoee5dh }))
```

https://buildkite.com/monadic/radicle-upstream/builds/10688#f13a8574-97d3-4309-8390-e2c7a4cb350e

**Comment by rudolfs** [comment]
This was fixed, right?

**Comment by geigerzaehler** [comment]
We’ve added some workarounds in #2391 but we should keep this issue open to remind us that we need to fix the underlying cause.

**Comment by rudolfs** [comment]
How about now?

**Comment by geigerzaehler** [comment]
I think we can close this. The tests are still flaky, but the migration to playwright should fix this.
