### ISSUE TITLE
User badges

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2234]
Discussed [here](https://radicle.community/t/user-badges/2453) in the forums.

Design:

![image](https://user-images.githubusercontent.com/4406983/137740184-05e88673-297a-49fc-adf1-38eb32d40bff.png)

Questions:
- How do we save these badges and display them on the profile for others to see? Maybe they are NFTs that Radicle sends to users who have their Rad ID linked, and we display those NFTs on the profile?
- Can we do this with p2p somehow?

Not sure which are easy to just add now, but here are the ideas I had. Open to other ideas for sure!
1. Seed Node operator (don't know how to determine this)
2. Early Adopter (set a join date. any account made before that date gets the badge)
3. Follower - 50 projects followed
4. Radicle Identity linked to Ethereum wallet
5. Builder - 10 projects on Radicle
6. Hacker mode activated (appearance settings are set to h4x0r mode)
7. Shortcut wizard (has used keyboard shortcuts 100 times)

Other ideas:
- every badge could be a NFT that could be minted on a ERC721 contract
- proofs of contribution (e.g. I contributed to radicle-upstream)
- when code is anchored, if you contributed to that release, you are sent an ERC721 that is visible on the UI and proves your contribution
- I would love to hire someone to illustrate these. I'm not that great of an illustrator

**Comment by brandonhaslegs** [comment]
Started a few ideas for badges…

![image](https://user-images.githubusercontent.com/4406983/136585586-506d312d-11d6-450d-bb3f-747fcfdd52ad.png)

**Comment by brandonhaslegs** [comment]
![image](https://user-images.githubusercontent.com/4406983/137622170-34c4a6ca-9bad-4723-80a3-8974c1884397.png)

**Comment by Kaihuang724** [comment]
Closing for now until we decide to implement blockchain features.
