### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2251]
As we add more facts to User and Org profiles, we should introduce an About page on User and Org profiles.

Could add some automated facts on the about page, like date of profile creation, or some other similar easy-to-generate interesting facts.

**Comment by brandonhaslegs** [comment]
Here's an idea

![image](https://user-images.githubusercontent.com/4406983/132087229-55503eb0-f0a5-49fd-9456-7db3adadbf9a.png)

**Comment by juliendonck** [comment]
Hey it's a good idea to move things away from the header but I don't know if it makes sense moving them away from the front page. I think there is value in showing this in the sidebar

**Comment by juliendonck** [comment]
I just feel that otherwise we're hiding the only info that we can rely on to be available:
<img width="1392" alt="Screenshot 2021-09-30 at 16 44 35" src="https://user-images.githubusercontent.com/2326909/135483518-5e78c88d-6a26-4a52-a20d-932bc04f7563.png">

**Comment by brandonhaslegs** [comment]
Ooh! Sidebar! Yes!

**Comment by juliendonck** [comment]
> Ooh! Sidebar! Yes! Like the project page, where the file browser is, except filled with about info.

Lol, Are you being sarcastic?

**Comment by brandonhaslegs** [comment]
Closing because we put this somewhere else.
