### ISSUE TITLE
In-app account switcher

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2261]
Figma design [here](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/Radicle-Upstream?node-id=7052%3A0).

Context:
On MacOS, you can create a new profile by stopping Upstream, deleting the /Users/username/Library/Application Support/xyz.radicle.radicle-link/active_profile file and starting Upstream again. This will create a new identity, you'll have to re-do onboarding again. Your old identity will still be preserved on disk. You can switch between the identities by changing the ID in the active_profile file. The ID is the directory name within the /Users/rudolfs/Library/Application Support/xyz.radicle.radicle-link path. Would be great if this was something you could do in the UI instead of all these manual steps.

More notes:
- Keyboard shortcut ⌘1 - profile 1, ⌘2 - profile 2, ⌘3 - profile 3, etc
- profiles should be drag-n-droppable int he sidebar
- profiles show up in the sidebar just like orgs, except they're fully rounded
- switching to a different profile would take you to the password lock screen where you'd have to enter your password for that profile to access it
- need a new modal that appears and allows the user to select between "new org" and "new user" after clicking on the + button in the sidebar. that's why this issue is marked "design needed"

![image](https://user-images.githubusercontent.com/4406983/130238806-d1fc8027-a7ac-4dcf-a302-8b0ad76139cf.png)

**Comment by juliendonck** [comment]
@juliendonck add this to docs
