### ISSUE TITLE
Avatar generation in handle registration flow

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#230]
@MeBrei ran us through the handle registration flow ( #216 ) and the way that the avatar behaves seems strange to me. 

The way it's implemented here is that it would take the handle that you created in the p2p-identity-creation and prefill this in the app, and this is what we expected. The thing is that right now the avatar is also generated from *just* the p2p-handle, this means that if your p2p-handle is taken in the registry and you change it, your avatar would change as well. This doesn't make sense to me, I would expect that the avatar based on your p2p-handle stays even if your handle is taken in the registry. (I would however expect this behaviour in the org registration). 
A possible solution would be that the avatar is generated not just from the p2p-handle, but the whole handle+public key (e.g.: cloudhead@jdfsfhfhjkshf...) and that one is "unique" and stays with you.

@cloudhead how did you expect this to work?
cc @brandonhaslegs

**Comment by juliendonck** [comment]
Basically, the avatar should be based on handle@<public-key> during the identity creation (if you didn't fill in an avatar_url) and then not change anymore during the handle registration.

**Comment by cloudhead** [comment]
The only way I see this working is that we base the avatar on your radicle-link ID. Not on your handle, because that can change.

When you register your ID, we don't change anything, we still use your radicle-link ID for avatar generation everywhere.

**Comment by juliendonck** [comment]
Yes I agree. @MeBrei that would mean that the avatar should come from the "create identity flow" and not from the "register your handle" flow. Does that make sense?

**Comment by xla** [comment]
@MeBrei @radicle-dev/product Do we need to follow-up/address anything given the latest insights?

**Comment by MeBrei** [comment]
@xla I see the following changes which could be done in PRs connected to this issue:

- proxy: use id to generate the avatar fallback (instead of handle), the endpoint for querying only the avatar of a handle is no longer needed
- ui: remove `avatar` query from the user registration modal, always use the avatar fallback of the identity
