### ISSUE TITLE
Maintainer view is not updated when new patch is discovered

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2308]
The patches count in the maintainer project view is not updated when the maintainer discovers a new patch from a peer. This means the following test fails: https://github.com/radicle-dev/radicle-upstream/blob/f8daaeceef22c2b1c179f7d29feaa7a70b4dbaad/cypress/integration/project/patches.spec.ts#L343

**Comment by rudolfs** [comment]
I believe this is fixed.
