### ISSUE TITLE
Choice of emoji set for avatar generation

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#231]
To guarantee that every user on any OS would get a consistent avatar generated and displayed it would make sense to use a custom emoji set then to rely on the OS's system fonts.

Here are some possible options for that:
- https://twemoji.twitter.com/
- https://www.joypixels.com/

cc @brandonhaslegs @cloudhead

**Comment by juliendonck** [comment]
@cloudhead: @brandonhaslegs mentioned we should also take out 🌱from our icon set, to not create confusion. And we might want to use it in other places... Where can I do this?

**Comment by xla** [comment]
@juliendonck Over here https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/src/avatar.rs#L17.

**Comment by xla** [comment]
@radicle-dev/product What's the status on landing the blessed emoji set in the code?

**Comment by cloudhead** [comment]
The blessed set is already in the code, isn't it? We just want to remove the sproutling?

**Comment by xla** [comment]
Would be good to get a final review of this, so we can close the issue.

**Comment by cloudhead** [comment]
Oh wait I see where the confusion is. This issue isn't about the choice of emojis, it's about the emoji font :smile: 

I think both proposed options are fine. JoyPixels has a bit less of a permissive license it seems, but the emojis look better. I guess we should use the twitter ones.

**Comment by xla** [comment]
Both concerns have been touched in the conversation, happy to break out the font part into a new issue and resolve them both.
