### ISSUE TITLE
Infura websocket-provider exeption breaks navigating to org

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2315]
Symptom: navigating to an org shows a spinner and loads forever until you abort the navigation request via the notification. Other network requests still work, both to the proxy as well as to the internet from the Electron instance. We see an error in the console `websocket-provider.js?7b64:166 WebSocket is already in CLOSING or CLOSED state.`

This happens after a while the app is open.

<img width="1552" alt="Screenshot 2021-09-02 at 16 13 53" src="https://user-images.githubusercontent.com/158411/131859566-f78e5a15-1429-49a9-a03b-1fc52232be3c.png">

<img width="1552" alt="Screenshot 2021-09-02 at 16 20 43" src="https://user-images.githubusercontent.com/158411/131860780-e6f64dd0-884d-4350-9cb4-4f487f2027bc.png">

**Comment by Kaihuang724** [comment]
Closing this as orgs will not be implemented for MVP
