### ISSUE TITLE
Convert Registry validation errors

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#233]
The reason that user input for top level entities (orgs and users) and projects is invalid is more nuanced that just the length since recent additions in radicle-dev/radicle-registry#246, radicle-dev/radicle-registry#247 and radicle-dev/radicle-registry#249. We get back more context which we should propagate up to the user. Addressed leftovers from https://github.com/radicle-dev/radicle-upstream/pull/227#issuecomment-600378189.

**Comment by NunoAlexandre** [comment]
To save you some time, I had already written this:

``` rust

    /// Project names must:
    /// * be at least 1 character and no longer
    /// * be no longer than than 32 characters
    /// * only contain a-z, 0-9 and '-' characters
    /// * not equal '.' or '..'
    InvalidName(String),

    /// Org ids must:
    /// * be at least 1 character
    /// * be no longer than than 32 characters
    /// * only contain a-z, 0-9 and '-' characters
    /// * not start with a '-'
    /// * not end with a '-'
    /// * not contain sequences of more than one '-'
    InvalidOrgId(String),
```
