### ISSUE TITLE
Give visual feedback when orgs are loading

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2344]
We should show some visual feedback while orgs are loading, so users know that something is happening.

Maybe something like this?
<img width="1552" alt="Screenshot 2021-09-07 at 17 59 18" src="https://user-images.githubusercontent.com/158411/132376066-ad1a3cb6-1c5e-4b13-a37d-e2b6fe937a11.png">

https://user-images.githubusercontent.com/158411/132375695-6ee62e3d-63fe-4a23-accb-b47737728049.mov

**Comment by brandonhaslegs** [comment]
I'd be happy to introduce a loading bar, but would like for it to apply to anything loading in the app, not just orgs in the sidebar.

**Comment by brandonhaslegs** [comment]
Also: we don't know how many or even that orgs are loading right? If that's the case, how can we do a loading bar at all?

**Comment by rudolfs** [comment]
We know that orgs are loading. We don't know whether there's more than 0 orgs until after loading is done.

**Comment by brandonhaslegs** [comment]
Why don't we just use the same loading state when the org is being created?

**Comment by rudolfs** [comment]
Sounds good.
