### ISSUE TITLE
Anchoring is broken for multi-sig orgs on wallet account changes

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2346]
Happens when the message signing request is sent to the mobile Metamask wallet.

```
{
  "stack": "Error: undefined is not an object (evaluating 'o.title')\n    at eval (webpack-internal:///./node_modules/@walletconnect/core/dist/esm/events.js:42:31)\n    at Array.forEach (<anonymous>)\n    at EventManager.trigger (webpack-internal:///./node_modules/@walletconnect/core/dist/esm/events.js:40:23)\n    at WalletConnect._handleIncomingMessages (webpack-internal:///./node_modules/@walletconnect/core/dist/esm/index.js:719:32)",
  "message": "undefined is not an object (evaluating 'o.title')",
  "code": "UnhandledRejection",
  "details": {
    "name": "Error"
  }
}
```
<img width="1552" alt="Screenshot 2021-09-07 at 18 25 26" src="https://user-images.githubusercontent.com/158411/132379223-a3dcdade-f6bf-474e-85a6-ed2f00de8afb.png">

**Comment by rudolfs** [comment]
Must have been something transient, it works again.

<img width="1552" alt="Screenshot 2021-09-08 at 07 39 27" src="https://user-images.githubusercontent.com/158411/132452636-15a963cb-6971-467b-99d4-4cc44528c38b.png">

**Comment by rudolfs** [comment]
There's something wrong with switching wallet accounts that causes this. When this happens a workaround is to disconnect and reconnect the wallet.

**Comment by rudolfs** [comment]
This might be due to network switching being generally unreliable because it's broken in certain wallets  https://github.com/radicle-dev/radicle-upstream/issues/2362.

**Comment by sebastinez** [comment]
I'm using Metamask v3.7.0 on my iOS device, and connect through it to upstream.

When the error message appears, I'm able to solve it by force quitting the app and reopen it.
https://support.apple.com/guide/iphone/quit-and-reopen-an-app-iph83bfec492/ios

**Comment by rudolfs** [comment]
This seems to happen here:
https://github.com/radicle-dev/radicle-upstream/blob/main/ui/src/org/safe.ts#L104

It's when the safe sdk is trying to get a signature from the wallet via walletconnect, but fails for some reason. As this is intermittent, it's most likely to do with the walletconnect infrastructure not being reliable.

**Comment by Kaihuang724** [comment]
Closing this as orgs will not be implemented for MVP
