### ISSUE TITLE
Build Standard Layouts for Design System as reusable components

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2348]
Identify the most commonly used layouts in the app and define all their details and parameters.

https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/Radicle-Upstream?node-id=11323%3A171934

![Standard Layouts - Header (Example_ Settings)](https://user-images.githubusercontent.com/4406983/137495036-c2a42b1d-c051-4639-b4ce-176d64f3be5b.png)
![Standard Layouts - Header, nav (Example_ Commits)](https://user-images.githubusercontent.com/4406983/137495040-5225ad1f-ddf7-4fbc-b6b7-7c3f4da3cfbf.png)
![Standard Layouts - Sidebar, big header, nav (Example_ Org)](https://user-images.githubusercontent.com/4406983/137495042-b65c12d4-3db9-4def-95cc-f89c1d01cb93.png)
![Standard Layouts - Sidebar, big header, nav (Example_ Profile)-1](https://user-images.githubusercontent.com/4406983/137495045-63f16589-27e8-476a-91a7-b1d00103047e.png)
![Standard Layouts - Sidebar, big header, nav (Example_ Profile)](https://user-images.githubusercontent.com/4406983/137495049-9e651f72-377f-45a6-99cc-27705703d8e5.png)
![Standard Layouts - Sidebar, big header, nav (Example_ Project)](https://user-images.githubusercontent.com/4406983/137495051-ab8c893f-443f-49d3-aef8-f5dd2c251f48.png)

**Comment by clovelee** [comment]
I reccomend we implement a grid system. 
<img width="918" alt="The Layout 1440 * 900" src="https://user-images.githubusercontent.com/6386945/149615723-f6cde648-84a4-4bc0-b9bb-11b0dcf61d3d.png">

**Comment by Kaihuang724** [comment]
Closing this for now until we're going to focus on UI improvements. Added to a Notion doc.
