### ISSUE TITLE
Update text input component to include explanatory text

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#236]
Spec: 
<img width="641" alt="Screen Shot 2020-03-18 at 8 05 29 PM" src="https://user-images.githubusercontent.com/2712962/77027573-dda4f980-6953-11ea-972b-0a967b4fce0b.png">

**Comment by rudolfs** [comment]
I followed up with #product: for now we should make the input hints part of the placeholder to reduce complexity. They might do some refinements to forms later, then we can revisit this.

![placeholders](https://user-images.githubusercontent.com/158411/77066265-1f30b580-69e3-11ea-90ef-5b86f82b6e58.png)

**Comment by sarahscott** [comment]
@juliendonck can this change be reflected in our figma specs?
