### ISSUE TITLE
Switching Ethereum networks is unreliable

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2362]
Steps to reproduce:

Assuming you've connected your wallet to `Rinkeby` and Upstream is also set to `Rinkeby`. In the sidebar you see your orgs that were registered with your wallet address on `Rinkeby`

1) In Upstream Settings screen switch to `Mainnet`, observe: wallet page notifies about wallet mismatch "Your wallet is on Rinkeby, but Upstream is on Mainnet. Make sure both your wallet and Upstream are set to the same network."
2) Switch your connected mobile wallet to `Mainnet`

Expected: Upstream should be notified of the network change in the wallet and show your `Mainnet` registered orgs in the sidebar and the wallet mismatch notification should be gone.

Actual: Upstream still believes the mobile wallet is not connected to `Mainnet`.

**Comment by rudolfs** [comment]
It's likely a Metamask Mobile issue: https://github.com/MetaMask/metamask-mobile/issues/2927.
Rainbow also has issues with testnets:
 - https://github.com/rainbow-me/rainbow/issues/2333
 - https://github.com/rainbow-me/rainbow/issues/2386

**Comment by Kaihuang724** [comment]
Closing for now until we decide to implement blockchain features.
