### ISSUE TITLE
Fix org navigation edge-case

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2363]
If we're on an org view and switch the wallet account, we still show the old org that belongs to the other wallet. If there is a change to the connected wallet, either network or wallet address, we should navigate away from any org that is shown.

If we don't, this might lead to potential errors when the user tries to interact with the org via a wallet that doesn't control the org.

**Comment by Kaihuang724** [comment]
Closing this as orgs will not be implemented for MVP
