### ISSUE TITLE
Add a lint that prevents checking in non-typescript svelte files

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2364]
We want all our `*.svelte` files to always have the `lang="typescript"` tag, so we get all the benefits of type-checking.

**Comment by geigerzaehler** [comment]
Are there any linters that support this?

**Comment by rudolfs** [comment]
I didn't check. Just thought it'd be a good idea to do this after I went through the codebase and converted the remaining `svelte` files that didn't have the `lang` tag.
