### ISSUE TITLE
🎨  Are you a designer? Our Figma file is also open source!

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2399]
Since Radicle is an open source project, anyone can contribute. This is normal in open source development, but we do it for design too! Here's how you can get started:
- I’d suggest starting by joining our [Discord server](https://discord.gg/HRdnwAwGbG) to chat with me or anyone on the team and ask any questions you have. It’s all public and open for anyone to join and chat in. We even have our “internal” chats public on there where we chat all day about features. The #Upstream channel is an example of that.
- There are also a lot of issues on our GitHub marked as “Design needed” which are open for anyone to grab and submit a solution for. You can find them [here](https://github.com/radicle-dev/radicle-upstream/issues?q=is%3Aopen+is%3Aissue+label%3Adesign-needed). Some are easier than others. Feel free to read through those and ask any questions you have directly on the GitHub issue.
- You can also reach out directly on Discord with any questions you have. If you need any help getting set up with our [Figma file](https://www.figma.com/file/tVqxYmi0YM4TRRebCXWZaF/Radicle-Funding?node-id=393%3A8210) just ask one of the core designers on the team (@brandonhaslegs and @juliendonck)! You’ll need to duplicate the file and make changes in your own private file. If we accept them, we’ll integrate them into the official file.

If you want to submit a design solution on GitHub, just post screenshots of your solution and a description on the issue (see [here](https://github.com/radicle-dev/radicle-upstream/issues/2251) for an example of this in action)

**Comment by rudolfs** [comment]
https://github.com/radicle-dev/radicle-upstream/pull/2401
