### ISSUE TITLE
Should the discord link in `contributing.md` link somewhere else?

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2410]
It currently links to an invite page. (The same link exists on radicle.xyz) https://discord.gg/HRdnwAwGbG

Should it link here instead? https://discord.com/channels/841318878125490186/843873418205331506

**Comment by brandonhaslegs** [comment]
@abbey-titcomb Do you know which one is right?

**Comment by abbey-titcomb** [comment]
Yeah, the second one is probably right as it's a direct invite to the channel.
