### ISSUE TITLE
Potential breaking change in upcoming Svelte version

### ISSUE THREAD

**Issue by rmunn** [radicle-dev/radicle-upstream#2415]
In https://github.com/sveltejs/svelte/pull/6750, there is a proposed change to the StartStopNotifier type of Svelte stores, which will be a breaking change for anyone creating custom stores. See the PR for details, but the short version is that if that PR is accepted and merged into Svelte, you'll need to add an `update` parameter to the StartStopNotifier callback type, as follows:

```diff
diff --git a/src/runtime/store/index.ts b/src/runtime/store/index.ts
index e947fa074..afd4ccabd 100644
--- a/src/runtime/store/index.ts
+++ b/src/runtime/store/index.ts
@@ -13,7 +13,7 @@ export type Updater<T> = (value: T) => T;
 type Invalidator<T> = (value?: T) => void;
 
 /** Start and stop notification callbacks. */
-export type StartStopNotifier<T> = (set: Subscriber<T>) => Unsubscriber | void;
+export type StartStopNotifier<T> = (set: Subscriber<T>, update: (fn: Updater<T>) => void) => Unsubscriber | void;
 
 /** Readable interface for subscribing. */
 export interface Readable<T> {
```

In your repo, the affected code appears to be in [ui/src/remote.ts](https://github.com/radicle-dev/radicle-upstream/blob/cd0dadb1908fb918807ccea773767bebbd1ef8fe/ui/src/remote.ts).

If you have any comments about the proposed breaking change, please come [leave a comment on the Svelte PR](https://github.com/sveltejs/svelte/pull/6750) to let me know whether it would make your life easier or harder.

**Comment by geigerzaehler** [comment]
Thanks for the heads up. It should be easy to update our code. Maybe the affected code will even go away before (see #2417).
