### ISSUE TITLE
Add org dropdown to anchoring modal

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2419]
Change the anchoring modal to have a dropdown to select the org in which the commit should be anchored. This would make the modal usable from anywhere in the app. And when you're already on an org, it would just pre-select that org.
![image](https://user-images.githubusercontent.com/4406983/134967110-9215a87b-8d63-4d4f-820d-ee026779c697.png)

- [ ] just put another dropdown to the left of the project(?) name
- [ ] add project icon in the project dropdown (like the branches icon is)
- [ ] add orgs icon in the org dropdown

**Comment by Kaihuang724** [comment]
Closing this as orgs will not be implemented for MVP
