### ISSUE TITLE
Return 404 instead of 500 for non-existent projects

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2427]
We return a 500 when querying non-existent projects. We should switch to 404s for that, because querying non-existent projects is part of normal operation and shouldn't cause an internal server error.

<img width="1552" alt="Screenshot 2021-09-28 at 14 56 25" src="https://user-images.githubusercontent.com/158411/135091656-6d2af375-4e8b-4a5e-9040-cfa6570f395b.png">

**Comment by geigerzaehler** [comment]
Could you remind me again how I make the app query for a non-existent project?

**Comment by rudolfs** [comment]
The easiest is to search for a project that you haven't replicated.
<img width="1552" alt="Screenshot 2021-09-29 at 10 33 23" src="https://user-images.githubusercontent.com/158411/135232752-3a0fe646-e36a-424c-b207-ad769bf48a81.png">
