### ISSUE TITLE
Integrate with new Link Application Architecture

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2431]
The goal of this project is to have Upstream use the new Radicle Link Application architecture proposed in [RFC#698](https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/0698-cli-infrastructure.adoc).

We have three milestones for this project, each with their own issue.

1. **[CLI](https://github.com/radicle-dev/radicle-upstream/issues/2432).** Fully integrate Radicle CLI libraries into the proxy. Only code from `radicle_daemon` remains that is related to networking and the protocol.
2. **Linkd.** Have an experimental integration with `linkd`. We can run Upstream in development with `linkd` doing the networking instead of the proxy and `radicle_daemon`.
3. **Package.** Have a production-ready package that only uses `linkd` which is installed separately on the users system. All dependencies on `radicle_daemon` are eliminated.

**Comment by Kaihuang724** [comment]
Closing this as it's being tracked in #2432
