### ISSUE TITLE
Explore a shadow system for hover/active states

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2441]
- Instead of scale transitions, explore shadows growing/shrinking to depict hover and click effects

I did this at Grover for the card and button effects. [See here](https://grover.com)

**Comment by juliendonck** [comment]
something to look at: https://www.joshwcomeau.com/css/designing-shadows/

**Comment by brandonhaslegs** [comment]
Yeah on Grover we had big blurry shadows on hover, and more harsh smaller shadows on an object you click, to simulate the object being pressed down against the screen. This is great!

**Comment by Kaihuang724** [comment]
Closing this for now until we're going to focus on UI improvements. Added to a Notion doc.
