### ISSUE TITLE
Commit not found error

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2448]
When an anchored commit is not replicated, but is linked, when you click on it, you get an error. I thought we were only showing a link when the commit was replicated? If it's not replicated, I thought we were going to just show a tooltip that says "this commit isn't replicated" or something.

![image](https://user-images.githubusercontent.com/4406983/135520264-8c31015a-cd35-441c-b52a-1936c0e5a39b.png)

```{
  "stack": "Error: object not found - no match for id (3b6b4b3d198c0070c8ba57846ec5e154826207d4); class=Odb (9); code=NotFound (-3)\n    at tb (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:14:6680)\n    at async fJ (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:34:318323)",
  "message": "object not found - no match for id (3b6b4b3d198c0070c8ba57846ec5e154826207d4); class=Odb (9); code=NotFound (-3)",
  "code": "UnknownException",
  "details": {
    "name": "Error",
    "response": {}
  }
}```

**Comment by rudolfs** [comment]
Good point. I think it might be better for performance reasons to show the link, but it should lead to a commit page that says the commit isn't replicated yet. Would that work for you @brandonhaslegs?

**Comment by brandonhaslegs** [comment]
That would work for me, yes. Is that easier than just making the commit link not clickable?

**Comment by rudolfs** [comment]
> That would work for me, yes. Is that easier than just making the commit link not clickable?

Yeah, because otherwise we need to fetch all the commits for the anchors to decide whether to link to them or not. Not having to check this would also be faster in case there's many anchors.
