### ISSUE TITLE
Update completely empty org page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2480]
In this case where there are no projects and also no information in the about sidebar, the empty state should probably not show the "Anchored projects" page title there… looks strange.

Maybe it should be "Bojack hasn't added any anchored projects or information yet."

![image](https://user-images.githubusercontent.com/4406983/136978258-60dd5d49-17c8-42ba-b960-de17b46ae6e8.png)

**Comment by Kaihuang724** [comment]
Closing this as orgs will not be implemented for MVP
