### ISSUE TITLE
Add a backup placeholder for when the image is broken

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2507]
Add a blank placeholder when an org's avatar can't be loaded.

![image](https://user-images.githubusercontent.com/4406983/138279859-f0fca32d-2552-4ea8-b8b2-7fd8e2fd83f0.png)

**Comment by juliendonck** [comment]
Grey or HTML default

**Comment by juliendonck** [comment]
https://dev.to/mckabue/html--hide-broken-images-or-replace-then-gracefully-lmi
