### ISSUE TITLE
Orgs with anchored projects should be sorted higher on the orgs list

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2512]
Seen below, an org with 3 anchored projects is positioned below projects with no anchored projects. I'm not sure how the sorting is working right now, but orgs with anchored projects should definitely show up before orgs without anchored projects.

If the orgs list is manually sorted, then let's add this project to the top group **0x641eDB587867a703E132a4210d63e93C52AA97fF**

![image](https://user-images.githubusercontent.com/4406983/138439766-db7c158e-a88a-4259-a036-25707822b464.png)

**Comment by Kaihuang724** [comment]
Closing this as orgs will not be implemented for MVP
