### ISSUE TITLE
Prevent hovercards from overlapping

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2513]
It should never happen that two hovercards are overlapping. I think this can be solved by removing the delay when hovering away. Now there is a delay before the hovercard disappears.

![2 hovercards overlapping](https://user-images.githubusercontent.com/4406983/138440329-d85f7947-6ac8-4a1e-abd5-9764e60e9401.gif)

![two user hover cards](https://user-images.githubusercontent.com/4406983/138440737-bc0a4ae1-fcab-4b6b-8ac3-4180e504adcc.gif)

**Comment by Kaihuang724** [comment]
I believe this has been fixed. Was not able to reproduce.

**Comment by brandonhaslegs** [comment]
You probably can't see enough projects in your Upstream to reproduce this since the app doesn't work. We will run into this again once the app can replicate projects again.

**Comment by rudolfs** [comment]
We also disabled all the Ethereum features, so this won't show up in the app currently at all.

**Comment by brandonhaslegs** [comment]
Yeah just reproduced this today

https://user-images.githubusercontent.com/4406983/159706489-94c0f818-be5c-48ec-8979-e6207682090c.mp4
