### ISSUE TITLE
Following an anchored project from the org page should not link to the user's profile

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2516]
Have run into this a few times and it's really annoying. I just wanna follow all the projects in that org and I get swiftly brisked away to my profile page, where I do not want to be!

![image](https://user-images.githubusercontent.com/4406983/138453575-e2c77a5f-ebdf-462e-a704-2dba558e5695.png)

- [ ] show notification when following

**Comment by Kaihuang724** [comment]
Closing this for the time being as the org page will be removed for the MVP.
