### ISSUE TITLE
Expand identity endpoint

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#255]
To show the "registered" badge on the Profile screen we need to extend the `identity` type with `registered: Boolean!`.

<img width="453" alt="Screenshot 2020-03-25 at 21 06 01" src="https://user-images.githubusercontent.com/158411/77580745-cda19280-6edc-11ea-9150-56f2dd455ff1.png">

```graphql
type Identity {
  id: ID!
  shareableEntityIdentifier: ID!
  metadata: IdentityMetadata!
  avatarFallback: Avatar!
}
```

**Comment by xla** [comment]
Implement in #256, with the slight alteration that instead of just a boolean it's an optional `ID`, which is the user id registered on the Registry.
