### ISSUE TITLE
Cycle plan: November 1st - November 30th

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2555]
## Plan Items

Below is a summary of the top level plan items.

#### Fix replication @geigerzaehler @rudolfs   
_More issues will be added here as we progress, for more information [see this notion page](https://chip-cartwheel-3be.notion.site/Make-Replication-Work-cb7317227edb4c0b81726a54ccb412f0)_
- [x] #2560 
- [x] #2547
- [x] #2563
- [ ] #2564
- [x] #2571
- [x] #2569

#### Redesign Patches @brandonhaslegs 
Let's take a second look at the patches design work in preparation for replication working

#### Add back button (and forward button?) @rudolfs @brandonhaslegs 
Allow for faster navigation in the app
- [ ] #1891 

#### Use SquareprojectCard on org page @juliendonck 
Align project representation in the app
- [ ] #2089
- [x] #2596 

#### Add metadata sidebar to profiles @juliendonck 
Show more data in a sidebar on a profile - See progress here #2559 
- [x] #2091
- [x] #2148
- [x] #2242

#### Implement Contributors page on projects @rudolfs 
- [ ] #2125 

#### Improve diagnostics / network tab @rudolfs 
- [x] #2337
- [ ] #1871 

---

### Clean up / nice-to-haves
- [ ] #2141 💪 @juliendonck 
- [ ] #1056 💪 @rudolfs 
- [ ] #1964 @juliendonck 
- [ ] #2245 💪 @rudolfs 
- [ ] #2480 @juliendonck 
- [x] #2495 @juliendonck 
- [x] #2507 @juliendonck 
- [x] #2509 @juliendonck 
- [x] #2518 @rudolfs 

---

### Engineering tasks
- [ ] #1851 💪 @rudolfs 
- [x] #2039 @geigerzaehler 
- [x] #2505 @geigerzaehler 
- [x] #2556 @rudolfs 

---

### Design tasks
- [ ] #1882 @brandonhaslegs 
- [ ] #1982 @brandonhaslegs 
- [ ] #2440 @brandonhaslegs 
- [ ] #2441 @brandonhaslegs 
- [ ] Explore following people #2514 @juliendonck @brandonhaslegs 
- [ ] #2515 @brandonhaslegs 

---

**Legend of annotations**
💪  stretch goal for this iteration

**Comment by rudolfs** [comment]
Feature ideas for this sprint:
  - web version of Upstream for read-only features
  - use URNs aka Radicle IDs for tracking/searching

**Comment by geigerzaehler** [comment]
My update for the last week.

* Added our own upstream seed node (#2565) and improved the process infrastructure and reliability (#2575, #2581)
* Expanded the [replication document](https://chip-cartwheel-3be.notion.site/Make-Replication-Work-cb7317227edb4c0b81726a54ccb412f0) with a detailed plan on how to fix the most pressing issue that is missing update propagation (#2564)
* Add detailed test scenarios to the replication document so that we can verify any replication fixes

This week I want to tackle the following

* Implement and merge one major fix for #2564, deploy and have the team test it.
* Start work on #2569 and test a draft with the team.

**Comment by geigerzaehler** [comment]
My update for the past seven days:

* We’ve merged fixes for #2569 and major fixes for #2564. This means that basic replication with the upstream seed node is now working. There are some edge cases and minor reliability issues though.

In the next days I’ll work on the following
* Provide a stable deployment of the seed node that replicates the upstream project. This includes a systemd setup, proper logging through GCP, publishing binaries, update scripts and documentation.
* Create and run test scenarios for the replication of profile data
* Improve on #2564 by adding gossip queries and reacting to haves for non-replicated repos.
* Add retry logic to fetches of the upstream node.

**Comment by rudolfs** [comment]
This cycle is over.
