### ISSUE TITLE
Investigate how to isolate node networks when testing locally

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2560]
One idea would be to use pre-defined network interfaces and set up different topologies using whatever is provided by the host OS (iptables, route, etc). Then force the nodes to bind to the specific network interfaces.

**Comment by geigerzaehler** [comment]
Here are some links to resources I discovered
- [https://ops.tips/blog/using-network-namespaces-and-bridge-to-isolate-servers/](https://ops.tips/blog/using-network-namespaces-and-bridge-to-isolate-servers/)
- [https://people.freebsd.org/~arved/vlan/vlan_en.html](https://people.freebsd.org/~arved/vlan/vlan_en.html)
