### ISSUE TITLE
Periodic announcements and queries for seed

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2564]
We want to improve gossip queries and announcements in the Upstream seed for more stable replication. Specifically we want to ensure that
* Upstream peers that provide an identity replicate it to the seed in a timely fashion
* Upstream peers that track an identity receive updates from the seed in a timely fashion

To achieve this we need to implement the following

- [ ] Seed periodically queries identities it tracks
- [x] When a peer connects to the seed the seed asks the peer for updates to all of the identities it tracks
- [ ] Seed periodically announces the identities it tracks
- [x] When a peer connects to the seed the seed announces all identities it tracks to the peer. This should make the “Maintainer Update Propagation” [test scenario](https://chip-cartwheel-3be.notion.site/Test-Scenarios-bc8474555d804f96aae3777db5829216) pass.

**Comment by rudolfs** [comment]
We're not using the gossip transport at the moment.
