### ISSUE TITLE
Expand "user profile" using Collaborative Objects

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2582]
There's a conversation where we feel we can use Collaborative Objects to improve "user profiles" you're seeing. At the moment when going to another users' profile you only see what you both have in common (meaning projects you've both replicated) and you don't see any metadata to that. (see image below). The idea would be that with collaborative objects we could expand that to show all projects a user is part of and even show some metadata of each of these projects (title, desc, latest commit etc). It would also allow us to follow certain users and with that give the signal that you want to follow (replicate) all the projects of that user. 

This is based on the work of @alexjg in @radicle-dev/cococo 

<img width="1367" alt="Screenshot 2021-11-08 at 11 57 21" src="https://user-images.githubusercontent.com/2326909/140730205-fa03c7f2-afdf-4c1b-ad90-92a74248eb81.png">

**Comment by rudolfs** [comment]
We won't be focussing on COBs initially.
