### ISSUE TITLE
Notes on high level Upstream improvements

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2583]
## User Intention
**Try out radicle**
1. I want to see what's there already
2. I'm looking for a specific project/org (I have a project urn)
3. I am RX want to push my project to radicle to eventually sustain my project
4. I'm the upstream team and I want to move my code to radicle
  - create an org
  - Anchor it
  - Share with my org members

## Issues with current flow
- You have to create an account before I can explore or search
  - in app preonboarding
    - Org's explore page
    - Show a few curated projects' metadata (and possibly explore their code)
      - Onboarding seed node with project we handpick
      - org nodes allow us to do this (would mean that everyone runs that org node code)
    - CTA's
      - Create a project
      - Create an org
    - Explain what radicle is about?
      - "ok modal" with explanation
      - short intro text
      - contextual in after the cta
    - Search for a project / org ? 
  - Web interface with the experience described above with CTA's guiding you to download the app

- Updating current onboarding:
  - Optimize the flow to handhold through 
    - Create a project
    - Create an org
  - after p2p ID creation
    - Create a project
    - create an org (connect wallet is a step)
    - Join an org (connect your org member wallet)
    - explore

- Identity
  - what's the point of attesting your P2P
    - attesting id shouldn't block the transactions
      - should be an action on the wallet page
    - Seems dead
      - GPG attestation and ENS integration
  - 

- Modes of using the app
  - no p2p / no eth -> exploring
  - p2p / no eth -> creating projects
  - p2p & eth -> creating projects, managing orgs & anchoring
  - (no p2p / eth -> managing orgs + anchoring)

**Comment by juliendonck** [comment]
## Identity problems in radicle:
- attestation doesn't do anything
- GPG is more important
- P2P ID and ETH ID don't really feel connected -> attested with one and connected with another
- We name the Person but actually only use the device ID 
- DeviceID / Person / attested ETH address / connected ETH wallet is confusing
  - if all we're getting out the Person is a prettier name, why don't we use ETH + ENS for that.

## Person 
  - has multiple device ID's
  - has an attested ETH address (ENS supported)
  - has an attested GPG key also through ETH attestation
  - has the projects that you follow
  - does it have a name?

**Comment by Kaihuang724** [comment]
I'm going to close this one for now. I captured this in our Notion doc as something to refer back to once we're doing more discovery.
