### ISSUE TITLE
Separate application/data fetching logic from design system

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#259]
To be able to work on the design system in isolation, it would need to be independent from data fetching and other application logic.

Ideally components would be pure, they would just receive data via either props or slots and display that to the user. They can still have their own internal state and fire events based on user input, but ideally they should not have any side-effects.

Investigate whether  this is possible to implement in an idiomatic svelte way while still preserving developer ergonomics and not having to write a lot of boiler-plate.

**Comment by sarahscott** [comment]
+1 to this; I think it would tie in nicely with a data access layer + reactive store.

**Comment by sarahscott** [comment]
Outstanding components with data-fetching:
- `Folder`
- `SidebarLayout`

**Comment by rudolfs** [comment]
This is mostly done.
