### ISSUE TITLE
New onboarding

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2595]
A new onboarding that shows single and multisig orgs in the first view of the app and allows the user to explore projects and orgs before setting a password. This new onboarding also prioritizes linking your wallet and using your ENS name as your name on Radicle.

Prototype is [here](https://www.figma.com/proto/owmgsbs6lnUt8R1bixstCA/Radicle-Upstream?page-id=3584%3A14985&node-id=11772%3A179696&viewport=453%2C48%2C0.34&scaling=contain&starting-point-node-id=11760%3A192353&hide-ui=1)

**Comment by Kaihuang724** [comment]
I believe this has already been done. We're also removing orgs and ETH integration from the MVP.

**Comment by brandonhaslegs** [comment]
This definitely wasn't done. It's a total rethinking of the app's onboarding. Instead of on first launch seeing just a standard onboarding, the user is met with projects and users on the network and a prompt to sign up.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/4406983/159671663-d5cdc9de-c9b7-47e7-b903-373a4827f21a.png">

I still think this is a good idea.
