### ISSUE TITLE
Stable, maintainable deployment of upstream seed

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2620]
We want to provide a stable and maintainable deployment of the upstream seed peer so that we can use for ourselves.

* Upstream seed runs on a dedicated GCP instance and is controlled by systemd.
* The provisioning of the instance is documented to make it repeatable. (Includes firewall settings)
* Systemd service file is included in the repo
* Add a script to the repo and the instance the automatically updates the seed binary.
* Setup logging with GCP through journald and add instructions how to find and read the logs.

**Comment by juliendonck** [comment]
Just to understand is this closer to a seed node or an org node? Like will this eventually be merged with the org node or what is the thinking there?

**Comment by geigerzaehler** [comment]
The difference between the org node and our seed node is that the org node by chooses which projects to track based on org contract data. For the upstream seed we have to configure the projects to track manually.



> Like will this eventually be merged with the org node or what is the thinking there?

That is the plan. We’ve been talking with the alt-clients team and the link team about this. At the moment we’re still experimenting with the different implementations and they serve different purposes. This means it’s more important for us to be flexible and move quickly.

**Comment by juliendonck** [comment]
Thanks for explaining, that makes total sense to me.
