### ISSUE TITLE
Link in empty page placeholder is styled wrong

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2630]
All links should be styled with a border-bottom. This one is still set to underline.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/4406983/143049256-25a28246-5c99-456f-aeba-2590b9b9570c.png">

**Comment by rudolfs** [comment]
Fixed by https://github.com/radicle-dev/radicle-upstream/pull/2657.
