### ISSUE TITLE
Break this feedback into issues

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2634]
Feedback collected by @nassarhayat while working on onboarding DAOs. Just need to break this feedback down into specific issues.

https://www.notion.so/Summary-of-friction-along-onboarding-journey-fd32a1171b52449e8014468e8e46b899

**Comment by rudolfs** [comment]
<img width="490" alt="Screenshot 2022-04-06 at 12 09 15" src="https://user-images.githubusercontent.com/158411/161952051-f5094463-4c3e-48ea-8ce9-972f473e2fda.png">

**Comment by rudolfs** [comment]
Is this still relevant? Can we close this?

**Comment by brandonhaslegs** [comment]
I think that's up to @Kaihuang724 to decide.
