### ISSUE TITLE
Wallet attestation + profile sidebar issues

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2639]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/4406983/143448618-22d95b15-0d61-406e-8ae1-e9be0ba1ac83.png">
before I've actually approved the transaction, my "attested address" appears on my profile already.

---

<img width="784" alt="image" src="https://user-images.githubusercontent.com/4406983/143448769-43dabfbf-e979-40c5-a8d6-2f722a80266f.png">

also when I've only just connected a wallet, my blocky appears on my profile, which seems like it should only appear when I've fully attested

**Comment by Kaihuang724** [comment]
We're removing ETH integration for the MVP. Closing for now, but captured in a Notion doc.
