### ISSUE TITLE
seed: use gossip to find projects

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2643]
To make replication more robust we want to find project data through gossip in addition fetching from peers that connect directly.

To implement this we need the following
* Send a gossip query for all projects that we’re tracking whenever a new peer is added to the active member set
* Explicitly fetch project data from peers when it is announced but we don’t replicate the project yet. This requires us to listen to the `Uninteresting` `Gossip::Put` events.

**Comment by rudolfs** [comment]
Superseded by https://github.com/radicle-dev/radicle-upstream/issues/2675.
