### ISSUE TITLE
Timestamp handling

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#265]
We currently use [timeago](https://timeago.org/) to format timestamps. If the event was further in the past, it would be better to show the actual date.

Create a utility module that wraps timeago and chooses the formatting according to the time range.

**Comment by sarahscott** [comment]
@juliendonck @brandonhaslegs @cloudhead  how are we feeling about timestamps? Can we close this issue?

**Comment by cloudhead** [comment]
I think having access to the date is super important. How about always use relative time, but when you hover on the date, have a tooltip with the actual date?

**Comment by rudolfs** [comment]
Stale.
