### ISSUE TITLE
Sticky header broken in org screen

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2655]
Happens when the content is longer than one page and we scroll down.

<img width="1440" alt="Screenshot 2021-12-03 at 16 47 14" src="https://user-images.githubusercontent.com/158411/144631327-8196ce6a-5c8a-4d27-ba4b-e05b62e2f030.png">

**Comment by Kaihuang724** [comment]
Closing for now as we're removing org screen for MVP
