### ISSUE TITLE
Remotes added to project are not always found

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2665]
Remotes added to a followed project aren't always found reliably, even though the peers are all connected to the seed node.
Happens when using radicle-link `cycle/2021-12-07`, upstream-seed and radicle-proxy.

**Comment by geigerzaehler** [comment]
This probably was broken by the initial version of [this patch](https://lists.sr.ht/~radicle-link/dev/patches/27080). With tag 2021-11-16 `contributor-fork-replication-1-test.ts` passes. Still, `contributor-fork-replication-2-test.ts` does not pass.

**Comment by rudolfs** [comment]
Fixed by upgrading to `cycle/2021-12-14` in https://github.com/radicle-dev/radicle-upstream/pull/2677.
