### ISSUE TITLE
Bumping into rate limiting of broadcast messages in mesh with 5+ nodes

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2666]
Seeing a lot of 
```
WARN librad::net::protocol::broadcast: want rate limit breached: enhance your calm, hydbh4omqc5a3shfmqdk4on6w58j9m6jexa4tg1x4kh6neee18k4jn!
```

I've set up a mesh of 6 nodes, one of them is an upstream-seed, the rest is radicle-proxies.
All of the proxies connect to the seed on startup, one of the proxies creates a project and the rest follows that project.
After that a bunch of messages bounce around and i see a lot of these rate limit warns.

Happens on radicle-link `cycle/2021-12-07`

https://github.com/radicle-dev/radicle-upstream/commits/rudolfs/gossip-loop-test

**Comment by geigerzaehler** [comment]
Given that this is a problem with the gossip protocol I will put this into the icebox

**Comment by rudolfs** [comment]
We removed gossip transport and these tests.
