### ISSUE TITLE
integrate `radicle_daemon` into our repo

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2670]
The `radicle_daemon` package provided `radicle-link` is effectively unmaintained and only used by us. To make fixes to it we want to integrate it back into our repository.

1. Copy all code into a folder `radicle_daemon`.
2. Add the package to the Cargo workspace
3. Update `radicle-link` dependencies in `radicle_daemon` 
4. Update references to `radicle_daemon` in `proxy` to use the workspace package.

**Comment by rudolfs** [comment]
Closed via https://github.com/radicle-dev/radicle-upstream/pull/2771.
