### ISSUE TITLE
Replace Upstream org-node with our own seed node and http api

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2673]
We're running an org node from `radicle-client-services`, but it's not tracking the latest radicle-link dependency and is incompatible with the latest Upstream release. In order to have more control over it we should just run our own upstream-seed node and use the http API code from client services.

We should host it on seednode2 and change the DNS entries to point seed.upstream.radicle.xyz to it.

https://app.radicle.network/orgs/upstream.radicle.eth
hyncrnppok8iam6y5oemg4fkumj86mc4wsdiirp83z7tdxchk5dbn6@seed.upstream.radicle.xyz:8776

**Comment by geigerzaehler** [comment]
Regarding the setup: We should try to avoid compiling the code for the HTTP API service on the machine and run it manually. Instead we should download and run built binaries or docker images and should use systemd to manage these. And the setup should be integrated into the seed node instance [setup script](https://github.com/radicle-dev/radicle-upstream/blob/main/infra/seed-node/setup.sh)

**Comment by rudolfs** [comment]
Talked to the alt-clients team, they'll provide binaries for their builds next week. Will pick this issue up once that's sorted.

**Comment by rudolfs** [comment]
We can close this once https://github.com/radicle-dev/radicle-client-services/pull/124 is merged.
Deployed: https://app.radicle.network/seeds/seed.upstream.radicle.xyz.
