### ISSUE TITLE
proxy: robust gossip announcements

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2675]
We want finding a project and receiving updates to be more robust. For example, the following test case currently fails.

1. Assume two peers M (maintainer) and C (contributor) that have each other as seed nodes. Assume that M provides a project P.
2. Start M and C and have them connect to each other
3. On C, request P and wait for it to be cloned.
4. Stop C
5. On M, push a commit to P
6. After waiting a couple of seconds start C
7. C never receives the update to P

In real life, this problem occurs if a commit is made and no interested party is connected to the origin of the commit. This does not happen if the Upstream seed is configured to track the project and the peer connects to it.

To fix this we should announce all projects the proxy replicates when the proxy joins a network. We assume that the proxy joins a network whenever a peer from the seed list is made an active member. (This accounts for loss of connection and disjoint networks.) The announcement should be throttled to reduce the number of messages.

One thing we should verify is that announcing the project default urn without any path results in all updated branches being replicated to trackers.

**Comment by rudolfs** [comment]
We're not using the gossip transport at the moment.
