### ISSUE TITLE
Run tests against Link replication v3

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2678]
We want to run our test suites against Radicle Link with replication v3 enabled. Replication v3 is available behind a feature flag [introduced](https://lists.sr.ht/~radicle-link/announce/%3C20211214151737.GF58112%40schmidt.localdomain%3E) to the Link packages.

We want to evaluate whether this new version of replication works for us as expected. We also want to evaluate what code changes are necessary to use this feature.

**Comment by rudolfs** [comment]
It's on this branch: https://github.com/radicle-dev/radicle-upstream/tree/rudolfs/repl-v3-testdrive.

**Comment by geigerzaehler** [comment]
Looks good already. Could you create a PR so that we can discuss the changes and test failures?

**Comment by geigerzaehler** [comment]
I think we can consider this as closed since we have the PR now. Once we want to start using v3 we can create another issue
