### ISSUE TITLE
seed: track and replicate projects from peers not directly connected

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2681]
The seed should track and replicate project data from peers that don’t directly connect to the seed.

To achieve this, we need to react to “Have” gossip messages announcing that a certain peer has information about a project. The librad peer provides an API to listen to these messages. On receiving a “Have” message the seed should try to fetch and track the project from the remote peer.

For this to work properly the proxy needs to announce projects more reliably (#2675).

**Comment by rudolfs** [comment]
We're not using the gossip transport at the moment.
