### ISSUE TITLE
seed: replicate every seen project

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2682]
We want to make it easy for new users to publish their project and make them available even if they are behind a NAT or offline. At the moment the seed only replicates projects explicitly specified.

To accomplish this the seed would fetch any project it sees an announcement for it. To make this reliable we would need to fix the announcement logic for the proxy (#2675).

**Comment by rudolfs** [comment]
We're not using the gossip transport at the moment.
