### ISSUE TITLE
Every peer shows up as `you` for me

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2683]
<img width="443" alt="Screenshot 2021-12-15 at 11 32 29" src="https://user-images.githubusercontent.com/2326909/146226987-b06cbe16-941e-42da-ab64-150c0b53fb79.png">
<img width="511" alt="Screenshot 2021-12-15 at 11 32 32" src="https://user-images.githubusercontent.com/2326909/146226998-5ee39855-cf6b-4264-97fa-97d5cb9fc1fc.png">
<img width="434" alt="Screenshot 2021-12-15 at 11 32 35" src="https://user-images.githubusercontent.com/2326909/146227004-54dca97b-26f5-491a-bd32-090c2f130744.png">
<img width="426" alt="Screenshot 2021-12-15 at 11 32 38" src="https://user-images.githubusercontent.com/2326909/146227009-905f89ad-322c-4841-ae75-a5840331f33d.png">

**Comment by gsaslis** [comment]
+1 I also noticed this. 

But I want to add an extra data point: If I select a `peer` with the `maintainer` label, then that label (and not the `you` label) gets stuck there. i.e. the bug seems to be: if there is no label, don't update the label placeholder, even if it contained another label.

**Comment by rudolfs** [comment]
This will be fixed with the next release: https://github.com/radicle-dev/radicle-upstream/commit/69416ce69a1ba311b0444f0fabcb8f319b0c4b43.
