### ISSUE TITLE
proxy: connection status is not properly updated

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2690]
The `connectedPeers` field on the connection status change event emitted on the `/v1/notifications/local_peer_events` endpoint is not updated when the connected peers change.

The culprit is `radicle_daemon`. Instead of fixing it there I suggest to fix it on our side and expose this information via a new SSE API endpoint to avoid mixing up all the events.

**Comment by rudolfs** [comment]
We don't consume this event anymore, should we close this? @geigerzaehler
