### ISSUE TITLE
Branches for implicilty tracked peers are missing

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2691]
When a peer A clones a project for the first time it will add remote refs for all peers (e.g. peer B) that the maintainer of the project is replicating. This results in the UI displaying these peers in the peer selector of A. When the user clicks on, say, peer B the app can not load any of the head refs for that remote (they have not been replicated) and it errors.

~~We have a test case for this in #2715.~~

*edited by @geigerzaehler*

**Comment by geigerzaehler** [comment]
It looks like this happens when we initially clone a project and this also fetches information for all peers the maintainer tracks. We need to find a concrete scenario that reproduces this (ideally as an automated test).

**Comment by rudolfs** [comment]
I believe this only happened with the gossip transport, which we removed.
