### ISSUE TITLE
Overview: Search I

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#270]
When pasting (<kbd>⌘</kbd>+<kbd>v</kbd>) a shareable entity identifier anywhere in the app, it should open the given entity. This should work for **users**, **orgs** and **projects**.

The UX flows for this feature can be found here: https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=6502%3A56626

#### Notes from discussions around this feature:
 - in the sidebar we'll highlight the "search" menu item for any entities that are not our own
 - we only highlight items in the sidebar if the context already exists in the sidebar
 - for now this feature is scoped to searching only local users/projects/orgs

#### Open questions:
 - figure out what kind of error messages we could get when searching and tell #product

### UI
- [x] implement new notification style (#301)
  - [x] move notification faucet to the bottom of the screen
  - [x] restyle `Notification.svelte`
- [ ] add ability to capture `paste` event and add querying, routing and notifications
- [ ] user screen ([visitor profile view in figma](https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=3693%3A398))
- [ ] wire up project breadcrumb once implemented in proxy (it should show whether project is registered under user or org and a registered badge) (#268)
- [ ] when we're on a project page it should highlight the sidebar item depending on under what the project is registered:
  - unregistered project -> user profile should be highlighted
  - project registered under user that is myself-> highlight profile
  - project registered under user that is not myself-> don't highlight anything
  - project registered under org which I'm a member of -> highlight the org under which the project is registered
  - project registered under org which I'm not a member of -> highlight nothing

### Proxy
- [ ] search endpoint for user, project (& org) (the kind is not known on querying)

**Comment by xla** [comment]
Will be revisited at a later point.
