### ISSUE TITLE
Second project from one maintainer fails to replicate with default branch missing

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2703]
When a maintainer creates two projects and they are replicated by the seed only the first one can be sucessfully cloned from the seed by other peers.

1. Maintainer creates a project A and has the seed replicate it
2. Maintainer creates another project B and has the seed replicate it
3. Contributor clones project A from the seed and can browse it
4. Contributor clones project B. They cannot browse the source for project B. We see the error “we could not find a default branch”.

 Automated test implemented in #2707.

*edited by @geigerzaehler*

**Comment by geigerzaehler** [comment]
@rudolfs Are you able to reproduce this with a seed node running locally? Could you post the URNs for the other projects and the time you replicated them so that we can identify them in the logs?

**Comment by rudolfs** [comment]
Haven't tried to reproduce it locally yet.

Just realised that this can be reliably reproduced with the current seed and any 2 projects:

1. onboard a fresh upstream identity
2. add `hydyq6xmgp3amt44z41n6cbods1osx73j5z6fky5xx4yx33afycyfc@34.88.37.244:8776` as seed
3. follow project: `rad:git:hnrk8ueib11sen1g9n1xbt71qdns9n4gipw1o`
4. follow project: `rad:git:hnrke3q1pob41qjq5y57xn698xzt86yht74by`

The second project that gets followed always errors out, no matter of which project we follow first.

```
{
  "stack": "Error: we could not find a default branch for 'radicle-link@rad:git:hnrke3q1pob41qjq5y57xn698xzt86yht74by'\n    at Zt.fetchOk (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:1649964)",
  "message": "we could not find a default branch for 'radicle-link@rad:git:hnrke3q1pob41qjq5y57xn698xzt86yht74by'",
  "code": "UnknownException",
  "details": {
    "name": "Error",
    "variant": "INTERNAL_SERVER_ERROR",
    "body": {
      "message": "we could not find a default branch for 'radicle-link@rad:git:hnrke3q1pob41qjq5y57xn698xzt86yht74by'",
      "variant": "INTERNAL_SERVER_ERROR"
    },
    "response": {}
  }
}
```

```
2022-01-06T10:02:27.236842Z  WARN api::project: cannot find default branch project_urn=rad:git:hnrke3q1pob41qjq5y57xn698xzt86yht74by err=NoDefaultBranch { name: "radicle-link", urn: Urn { id: Oid(8cba4d80752725db06faf17be77de27f0391ee82), path: None } }
2022-01-06T10:02:27.236917Z  INFO proxy::http: GET /v1/projects/contributed 200 elapsed=46.501119ms
2022-01-06T10:02:27.237324Z  WARN api::project: cannot find default branch project_urn=rad:git:hnrke3q1pob41qjq5y57xn698xzt86yht74by err=NoDefaultBranch { name: "radicle-link", urn: Urn { id: Oid(8cba4d80752725db06faf17be77de27f0391ee82), path: None } }
2022-01-06T10:02:27.237385Z  INFO proxy::http: GET /v1/projects/tracked 200 elapsed=46.308227ms
2022-01-06T10:02:32.474999Z ERROR api::http::error: internal server error we could not find a default branch for 'radicle-link@rad:git:hnrke3q1pob41qjq5y57xn698xzt86yht74by' variant=INTERNAL_SERVER_ERRORerr=Rejection(State(NoDefaultBranch { name: "radicle-link", urn: Urn { id: Oid(8cba4d80752725db06faf17be77de27f0391ee82), path: None } }))
2022-01-06T10:02:32.475043Z  INFO proxy::http: GET /v1/projects/rad:git:hnrke3q1pob41qjq5y57xn698xzt86yht74by 500 elapsed=1.313012ms
```

**Comment by rudolfs** [comment]
This does not happen if I follow two projects from two different authors. Then if I follow a 3rd project by one of the previous authors it fails again.

**Comment by rudolfs** [comment]
This also happens with just 2 Upstream peers without a seed.

1. launch peer A
2. launch peer B and connect to A
3. create project P1 on A
4. follow project P1 on B
5. create project P2 on A
6. follow project P2 on B (fails)

**Comment by geigerzaehler** [comment]
That’s helps narrow it down. The next step would be to figure out what B tries to fetch from A (i.e. the `refspec`) and what B receives in this fetch. You can try `RUST_INFO=librad=debug` to see if that provides some logs (look for anything with `fetch` in the module). Otherwise it may be necessary to hack some log statements into librad and run the test against it.

**Comment by rudolfs** [comment]
When looking at the receiver end on B at the logs [here](https://github.com/radicle-dev/radicle-link/blob/cycle/2021-12-14/librad/src/git/replication.rs#L735), we see that for P1 there are tracked sigrefs, but for P2 there are none:

P1:
```
TRACKED_SIGREFS: {hydgo86673kinqy6nkf1s4zgp5gxicppthb1uabtszfe48e65r8ppe: Refs { categorised_refs: {"heads": {"main": Oid(1761e509924700c16929dbb1a8bf1c518f9bb4ff)}, "notes": {}, "rad": {"id": Oid(eb686f1e1d7ea95f1d4ac34d8b15d4dcb3c60cbf)}, "tags": {}}, remotes: Remotes({}) }}
DELEGATES: {Urn { id: Oid(04872aa44b915322a1edac63e87eb3943867767b), path: Some(RefLike("refs/remotes/hydgo86673kinqy6nkf1s4zgp5gxicppthb1uabtszfe48e65r8ppe/rad/id")) }}
```

P2:
```
TRACKED_SIGREFS: {}
DELEGATES: {Urn { id: Oid(721a0473eee441c03a81af653839073447171555), path: Some(RefLike("refs/remotes/hydgo86673kinqy6nkf1s4zgp5gxicppthb1uabtszfe48e65r8ppe/rad/id")) }}
```

And looking [further up](https://github.com/radicle-dev/radicle-link/blob/cycle/2021-12-14/librad/src/git/tracking.rs#L146) the remotes only contain the first project and the owner identity (the prefix is that of P2) when fetching P2:
```
REMOTES: {Some("hnrk8udaibxotpckhi5s6zcnoyhsin3szufho/hydgo86673kinqy6nkf1s4zgp5gxicppthb1uabtszfe48e65r8ppe"), Some("hnrkp3ubyais3punqwh97k5qutuzz8a7x7igy/hydgo86673kinqy6nkf1s4zgp5gxicppthb1uabtszfe48e65r8ppe")}
PREFIX: "hnrkb19yikjiqd1rie1jwtpi3t6hduhjn1xno/"
```

However, looking at the monorepo of B after the data exchange, we do see that there is a sigref created on P2 for the remote of A:

```
9404fd34e1ead476f30a3b29136cdaf64ddbbf5e refs/namespaces/hnrkb19yikjiqd1rie1jwtpi3t6hduhjn1xno/refs/remotes/hydgo86673kinqy6nkf1s4zgp5gxicppthb1uabtszfe48e65r8ppe/rad/signed_refs
```
And it contains a `heads/main` entry:
```
{"refs":{"heads":{"main":"6efede53d75313ecdd3782030b3a317f14ec029c"},"notes":{},"rad":{"id":"8c5119bec1091c774880f5859dc38c0a01309fb4"},"tags":{},"remotes":{}},"signature":"hyd8gs8utu7ypg5q6xobss56n3ykhqu3uedmuak6gh4n8sq67b7aptgamrtsngoscrfms8dipgqu1bt58jwpn5su7pr3oechp1m6hxdox"}
```

But the SHA (`6efede53d75313ecdd3782030b3a317f14ec029c`) can't be found in B's object db.

**Comment by rudolfs** [comment]
We dropped gossip support for now, so this is not relevant.
