### ISSUE TITLE
Cycle plan: January 1st - January 31th

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2705]
### Continue improving p2p replication
- https://github.com/radicle-dev/radicle-upstream/issues/2703
- ~~https://github.com/radicle-dev/radicle-upstream/issues/2713~~ We created a work-around for this.
- https://github.com/radicle-dev/radicle-upstream/issues/2678
- https://github.com/radicle-dev/radicle-upstream/issues/2564
- https://github.com/radicle-dev/radicle-upstream/issues/2675

### Investigate and create reproducible test-cases
- https://github.com/radicle-dev/radicle-upstream/issues/2691

### Start using Upstream for our own development workflow
- https://github.com/radicle-dev/radicle-upstream/issues/2712

### Reach out to potential product owner candidates
 - [x] advertise our [Upstream product owner role](https://chip-cartwheel-3be.notion.site/Product-Owner-for-Upstream-4bef4b4553614e388b13605c6efca321) on all our channels
 - [x] reach out to people we know

### Bug fixes
  - https://github.com/radicle-dev/radicle-upstream/issues/2683
  - https://github.com/radicle-dev/radicle-upstream/issues/2706

### Regular maintenance

- Upgrade radicle-link and #2722

**Comment by rudolfs** [comment]
I'll keep my notes on using Upstream for development here:
- as a maintainer, on which branch should i prepare a new patch?
- patch title/message is the same as commit title/message for simple patches, seems redundant
- i didn't realise that I don't have to add my name to the patch title
`git tag --annotate radicle-patch/rudolfs/fix-overflow` -> 
<img width="439" alt="Screenshot 2022-01-07 at 11 11 47" src="https://user-images.githubusercontent.com/158411/148528659-c0cf8b63-8216-4270-ad6a-fedb48027c91.png">
- i can't attach a screenshot to the patch, we'll have to figure out some external service where to host those
- there's no way to share a link of a patch to other contributors
- i'd like to update the patch description to add a link to the CI build

**Comment by gsaslis** [comment]
> there's no way to share a link of a patch to other contributors
> i'd like to update the patch description to add a link to the CI build

+1 I was thinking exactly these two earlier today while trying out the patch flow. 

> patch title/message is the same as commit title/message for simple patches, seems redundant
another +1, but then again, this is also true for PRs / MRs (but GitHub / GitLab can sometimes prepopulate the PR title / description if the PR is comprised of a single commit). 

... and this leads me onto a new point: 

* I was expecting the "patch creation" to be an Upstream action (i.e. not `git tag --annotate && git push --tags`) it seemed a little strange that I was performing an action that belonged in the **Radicle Upstream** business domain, by executing commands belonging to the `git` business domain, if that makes sense. Kinda like the git commands were the _implementation_ and I was expecting to be using some radicle _interface_  ...

**Comment by rudolfs** [comment]
January is over.
