### ISSUE TITLE
WalletConnect link is broken (404)

### ISSUE THREAD

**Issue by gsaslis** [radicle-dev/radicle-upstream#2711]
Hi folks, 

The "View compatible wallets" link  ( https://walletconnect.com/wallets ) is currently broken and leads to a `404`.

**Comment by gsaslis** [comment]
![Screenshot 2022-01-10 at 3 37 47 PM](https://user-images.githubusercontent.com/2420882/148775185-f472d37f-61e1-4ab2-975c-999fd1a7dfc0.png)

**Comment by rudolfs** [comment]
Good catch. Should be: https://walletconnect.com/registry/wallets.

**Comment by gsaslis** [comment]
I wanted to try and get these small patches in (also a fix for #2710 ) via upstream itself. If not, I can happily open a PR.

**Comment by geigerzaehler** [comment]
We would be very happy if you could submit a patch via Upstream

**Comment by rudolfs** [comment]
One thing, it would great if you could sign-off on our DCO in future patches.
Here's how you can do it: https://github.com/radicle-dev/radicle-upstream/blob/main/docs/contributing.md#certificate-of-origin.

**Comment by gsaslis** [comment]
New patch published that should fix this issue.

**Comment by rudolfs** [comment]
> metamask and argent both failed. (for me)

We'll be [rethinking our Ethereum integration](https://radicle.community/t/upstream-march-2022-community-update/2783#organizations-13) after the next release. Keep an eye on the [announcements forum](https://radicle.community/c/announcements/6).
