### ISSUE TITLE
seed: Announcements on connect not reliable

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2713]
Whenever a new peer connect the seed sends out announcements to the network so that the new peer is informed about all the data the seed has and can fetch what it is interested in. If many announcements have to be sent, it is possible that `librad` will not sent them all. An indicator for this is the log warning “Skipped X messages from ground control”. This results in peers not fetching the latest data from the seed and becoming stale.

Without fixing this in `librad` there are two potential solutions.

1. Rate-limit sending announcements so that `librad` can process them all.
2. Have the Upstream peers also query for identities they are interested in after connecting to a seed or other peer.

The solutions are not mutually exclusive. Solution 1 is a quick fix but depends on the correct parameters to work correctly and may stop working when the amount of announcements increases again.

Solution 2 requires more research how it would work and may require us to mess with `radicle_daemon`. This would in turn require us to integrate this library into our repository (#2670). The solution adds another piece that is responsible for replication and increases redundancy and thus, hopefully, reliability.

**Comment by rudolfs** [comment]
We're not using the gossip transport at the moment.
