### ISSUE TITLE
Commit subject lines that are too long get cut off

### ISSUE THREAD

**Issue by Jayman2000** [radicle-dev/radicle-upstream#2721]
![If a commit subject line is too long, it gets cut off.](https://user-images.githubusercontent.com/5579359/149023197-41880db8-9e6b-4f47-a51c-71ddf8547aa6.png)

Additionally, the currently open file will expand to fit the overly long subject line and also get cut off. By clicking and dragging, I can scroll the entire view to the right and see what’s cut off.

**Comment by rudolfs** [comment]
We also fixed this in https://github.com/radicle-dev/radicle-upstream/commit/0c4ab3d996a9517bba24d7cb73d46f03f32e47d6.
