### ISSUE TITLE
Avatar doesn't support SVG or IPFS

### ISSUE THREAD

**Issue by auryn-macmillan** [radicle-dev/radicle-upstream#2727]
Tried setting the avatar for [gnosisguild.radicle.eth](https://app.ens.domains/name/gnosisguild.radicle.eth/details) to an SVG hosted on IPFS. Am seeing this issue in the radicle app.

Not sure if it is an issue with the image being on IPFS, an issue with it being an SVG, or both.

![image](https://user-images.githubusercontent.com/8453294/149605354-fb572be5-4cf6-49d2-b3af-f87c5552a426.png)

**Comment by rudolfs** [comment]
SVG avatars are supported, but so far only over `http[s]`.

**Comment by geigerzaehler** [comment]
One thing we could do here is to rewrite IPFS URLs to use an [IPFS gateways](https://docs.ipfs.io/concepts/ipfs-gateway)
