### ISSUE TITLE
Upstream disconnects from seed after some time

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2730]
We've observed this in production recently. After a couple of minutes uptime Upstream shows that it is not connected to the seed node anymore. The machine is still connected to the internet and there are no other network issues. After a restart Upstream connects to the seed again.

**Comment by Kaihuang724** [comment]
In the meantime, we should at least notify the user via the Upstream client when a seed is disconnected so they know to restart the client.

**Comment by rudolfs** [comment]
This isn't relevant anymore since we disabled the gossip transport.
