### ISSUE TITLE
No find option

### ISSUE THREAD

**Issue by Jayman2000** [radicle-dev/radicle-upstream#2734]
For larger Markdown files, it would be nice if I could press <kbd><kbd>Ctrl</kbd> + <kbd>F</kbd></kbd> to search for things in the currently open file.

**Comment by rudolfs** [comment]
Nice. Yeah, we also noted this in [our review](https://chip-cartwheel-3be.notion.site/Upstream-Collaboration-Workflow-9f04a70ec5c44356ad1b905b193e5f8e) of the patches workflow.
