### ISSUE TITLE
Missing link in `docs/contributing.md`

### ISSUE THREAD

**Issue by Jayman2000** [radicle-dev/radicle-upstream#2735]
[`docs/contributing.md`](https://github.com/radicle-dev/radicle-upstream/blob/main/docs/contributing.md) says:

>- If you want to submit a design solution on GitHub, just post screenshots of
>  your solution and a description on the issue (see here for an example of this
>  in action)

The word “here” should be a link.

**Comment by geigerzaehler** [comment]
Fixed in a8df5462cca54d358f58bb09f3be7f4cfe481b23
