### ISSUE TITLE
Trial Upstream CLI for patches

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2757]
We want to trial the Upstream CLI for our code contribution workflow to see how it improves the experience of managing patches.

As part of these effort we should talk about this on discourse to see if we can get outside contributors to try this out.

**Comment by rudolfs** [comment]
Will write my feedback here:
  - can't merge my own patches with the commands given in Upstream

**Comment by geigerzaehler** [comment]
We’ve now tested this extensively and collected feedback
