### ISSUE TITLE
Make “Accepting Contributions Workflow” guide ready for the public.

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2759]
The document should be understandable for people not familiar with upstream and enable them to make a contribution to upstream.

We link the document in `CONTRIBUTING.md` and post about it on discourse. We try it ourselves. We also have two developers try it out and gather some feedback.

**Comment by rudolfs** [comment]
https://radicle.community/t/collecting-feedback-on-upstream-patches/2735
