### ISSUE TITLE
February 2022 Cycle

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2761]
The theme for the current cycle is to iterate on patches usability.

- [ ] #2757 
- [x] #2759 
- [ ] #2756
- [x] #2758 
- [ ] #2760 
- [x] #2754 
- [ ] #2673

**Comment by rudolfs** [comment]
We'll be tracking cycles in projects from now on. March -> https://github.com/radicle-dev/radicle-upstream/projects/2.
