### ISSUE TITLE
Migrate to radicle-link replication v3

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2763]
The `librad` crate has a new replication backend that can be enabled with the `replication-v3` feature. We want to use this in Upstream.

- [ ] Update the `radicle-link` dependency to use a cycle release
- [ ] Identify why test with replication v3 are more flaky (#2762)
- [ ] Test Upstream with the legacy version and `upstream-seed` compiled with replication v3 in a networking party
- [ ] Merge change where only the seed uses replication v3
- [ ] Test Upstream compiled with replication v3 and `upstream-seed` compiled with replication v3 in a networking party
- [ ] Update the production deployment of the seed with the new replication v3 version
- [ ] Release a new version of Upstream

**Comment by rudolfs** [comment]
Let's postpone this until replication-v3 is stable.

**Comment by geigerzaehler** [comment]
Shall we keep this open though? We will have to work on it.
