### ISSUE TITLE
Switch from RAD_HOME to LNK_HOME

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2770]
The 2022-03-01 release of radicle-link changes the name of the `RAD_HOME` environment variable to `LNK_HOME`. To accommodate this change we need to change Upstream so that it uses `LNK_HOME` instead of `RAD_HOME`, too. This also extends to the `--rad-home` options for the proxy and seed CLIs. This will also require a redeployment of the seed.

**Comment by rudolfs** [comment]
Closed via https://github.com/radicle-dev/radicle-upstream/commit/ff28562de24a73f882ac6a9f76f648c572a271e0.
I redeployed the `upstream-seed`.
The last thing that still needs to be done is tracked here: https://github.com/radicle-dev/radicle-upstream/issues/2772.
