### ISSUE TITLE
Blocky block is broken

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2773]
Even if there's a good reason this isn't loading, there should be a backup plan for when it doesn't load so the UI doesn't look broken.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/4406983/157430812-02032ed4-3871-4bac-9fd6-e6304f32249a.png">

**Comment by rudolfs** [comment]
This was fixed on `main`, this should be fixed once we do a new release.
