### ISSUE TITLE
Auto-refresh the UI when a new action occurs

### ISSUE THREAD

**Issue by Kaihuang724** [radicle-dev/radicle-upstream#2776]
The UI should refresh automatically when a new action occurs on a project that the user is viewing. The actions that should trigger the auto-refresh are:

**On the patch screen:**
- `upstream patch update`
    - title/description
    - new commits
    - force pushed commits
- receive an update via the network
    - title/description
    - new commits
    - force pushed commits
- patch gets merged in locally
- patch gets merged via the network

**On the patch list screen**
- `upstream patch create`
- `upstream patch update`
- receive a new patch via the network
- update an existing patch title via the network
- patch gets merged in locally
- patch gets merged via the network

The reason we want to do this is to make it easy for both maintainers and collaborators to see when new events happen on the project with them having to manually refresh the GUI.

**Comment by rudolfs** [comment]
[Part 1 of the fix](https://github.com/radicle-dev/radicle-upstream/commit/54296220bb8d3db038ef65907fc8fb2ae72786ac):

**On the patch screen updates**

- ❌ `upstream patch update` locally
    - ❌ title/description
    - ❌ new commits
    - ❌ force pushed commits
- ✅ receive an update via the network
    - ✅ title/description
    - ✅ new commits
    - ✅ force pushed commits
- ❌ patch gets merged in locally
- ✅ patch gets merged via the network

**On the patch list screen updates**

- ❌ `upstream patch create` locally
- ❌ `upstream patch update` locally
- ✅ receive a new patch via the network
- ✅ update an existing patch title via the network
- ❌ patch gets merged in locally
- ✅ patch gets merged via the network

**`Patches` tab counter updates**

- ❌ `upstream patch create` locally
- ❌ merge patch locally
- ✅ merge patch via the network
- ✅ receive a new patch via the network

**Comment by rudolfs** [comment]
Done via: https://github.com/radicle-dev/radicle-upstream/commit/72abb25ebc5ecf3b70c1e9aec8191fc6cdf4dc71.

**On the patch screen updates**

- ✅ `upstream patch update` locally
    - ✅ title/description
    - ✅ new commits
    - ✅ force pushed commits
- ✅ receive an update via the network
    - ✅ title/description
    - ✅ new commits
    - ✅ force pushed commits
- ✅ patch gets merged in locally
- ✅ patch gets merged via the network

**On the patch list screen updates**

- ✅ `upstream patch create` locally
- ✅ `upstream patch update` locally
- ✅ receive a new patch via the network
- ✅ update an existing patch title via the network
- ✅ patch gets merged in locally
- ✅ patch gets merged via the network

**`Patches` tab counter updates**

- ✅ `upstream patch create` locally
- ✅ merge patch locally
- ✅ merge patch via the network
- ✅ receive a new patch via the network
