### ISSUE TITLE
Hide all Ethereum and Organization features for MVP

### ISSUE THREAD

**Issue by Kaihuang724** [radicle-dev/radicle-upstream#2779]
We want to temporarily remove any Ethereum or Organization features from the Upstream client for the MVP. Currently, it's causing various issues within the Upstream client that makes features unreliable. Also, we need to better define what users should be able to achieve with an organization or connecting their Ethereum wallet before we integrate.

**Comment by rudolfs** [comment]
Closed via https://github.com/radicle-dev/radicle-upstream/commit/dfd2221f7bb0400f33a52d41a1d0f6405f2d095d.
