### ISSUE TITLE
Patch Statuses

### ISSUE THREAD

**Issue by Kaihuang724** [radicle-dev/radicle-upstream#2782]
# Context

We want to make it much easier for maintainers to be able to designate statuses for patches. Currently, the Upstream GUI only shows the maintainer patches that have been closed after they've been merged. There is no way for either a maintainer or collaborator to manually set a status.

# User Problems
- As a maintainer, I want to mark patches as rejected so that these patches don’t require my attention.
- (As an author, I want to be able to retract a patch so that maintainers know that it shouldn’t be reviewed anymore.)

# User Flows
- As a maintainer, when I click into an open patch, I want to see actions for rejecting and merging the patch so that I can choose what to do with it.
- As a maintainer, when I click on the Reject button on an open patch, I want the patch to automatically move to the "Closed" section and for the patch creator to be notified that their patch has been rejected
- As a maintainer, when I click the Merge button on an open patch, I want to see the CLI commands I'll need to run to merge the patch and easily copy them to my clipboard
- As a maintainer, when I run the CLI commands to merge a patch, after I've successfully merged the patch, I want the patch to automatically move to the "Merged" section.
- As a maintainer, when I click into a rejected patch, I want to be able to reopen a patch so that I can potentially accept it again.
- As a patch creator, when I click into my open patch, I want to be able to reject the patch so that I can close the patch myself.
- As a user, when my peer receives a status update event my UI should immediately reflect the new status. Specifically, the patch list view and the view for an individual patch should update.

# Implementation Details
* When the maintainer "rejects" a patch, it should not show up in the list of open patches anymore. Instead, there should be a new tab that's created for rejected patches that the patch will move to.
** There should be 3 specific categories of patch statuses: All, Rejected, Accepted
* There should be icons that communicate the patch's status so the maintainer can easily browse through the "All" patches tab and see the status for each patch.
* We want to add some indication to the Upstream GUI to clearly tell maintainers that when they merge a patch into their branch, it will "accept" them.

# Notes
* We will not fix the user problem of the long peer ID for the time being.

**Comment by geigerzaehler** [comment]
Something that we haven’t considered yet but should specify is reactivity. I’d propose to add the following

* As a user, when my peer receives a status update event my UI should immediately reflect the new status. Specifically, the patch list view and the view for an individual patch should update.

We also need to talk about how we provide APIs for that.

**Comment by efstajas** [comment]
@geigerzaehler Agreed. It should behave exactly as everything else about a patch already does — meaning it should update immediately.

Another note —

> We will be relying on the maintainer to "reject" a patch instead of giving the ability for the collaborator to "retract" a patch for the time being.

With the implementation we discussed in our last call, allowing collaborators to "reject" their own patches is actually rather trivial and IMO totally possible for the first iteration.

**Comment by Kaihuang724** [comment]
+1 - this should be added in. Will add to the original description.

@efstajas - I think that would be great to add in if possible, but are there potential testing and/or QA considerations that need to be taken into account? It might be best to limit the scope but I'm open to any recommendations.

**Comment by efstajas** [comment]
Another consideration — I'd propose renaming some of the statuses as part of this epic.

Rejected -> Closed
Closed -> Merged

Here's why:

- GitHub calls merged PRs "merged" and the equivalent action to our "rejecting a patch" is "closing a PR". While patches !== PRs, I do feel like this is a well-established naming convention and following it might make things easier to grasp for people new to Radicle.
- Currently you click "Merge" and that causes the patch to be "Closed". If it would end up being "Merged" that'd be a clearer outcome of an action called "Merge".
- "Rejected" sounds harsh and like a really bad thing even though there may be situations in which you want to not merge a patch but still include its changes in another branch, for example. You're not really "rejecting" it in this situation.
- If you're a contributor, we want to allow you to retract your patch. Clicking "Reject" on your own patch feels a little weird from the contributor's perspective. I'd except only a delegate to be able to "reject" a patch, whereas a contributor might be able to "retract" a patch. "Closing" the patch works well from both perspectives.

**Comment by geigerzaehler** [comment]
> With the implementation we discussed in our last call, allowing collaborators to "reject" their own patches is actually rather trivial and IMO totally possible for the first iteration.

I thought so, too. If it’s not harder there’s no reason to postpone it.

**Comment by Kaihuang724** [comment]
Removed the line item in the notes section and added back:

As a patch creator, when I click into my open patch, I want to be able to reject the patch so that I can close the patch myself.

to the user flows.

**Comment by efstajas** [comment]
An implementation of this epic using @geigerzaehler's backend is pushed on the `patch-status-with-ui` branch. Still missing tests.

Noting down some test cases here, lmk if you have comments:

- Project contributors can:
  - `Close` their own open patch
  - `Reopen` their own closed patch
  - not click `Merge` on any open patch
- Project delegates can:
  - `Close` any open patch
  - `Reopen` any closed patch
  - click `Merge` on any open patch

**Comment by geigerzaehler** [comment]
I created an issue to track our progress: #2827

**Comment by rudolfs** [comment]
I believe we can close this. Implemented in https://github.com/radicle-dev/radicle-upstream/commit/f081a029ad63c3a646add26a612a6d19a40a71bf.
