### ISSUE TITLE
Design patch actions and new tabs for the patches screen

### ISSUE THREAD

**Issue by Kaihuang724** [radicle-dev/radicle-upstream#2783]
We need to edit the designs of the patch screen in the Upstream client to reflect the new statuses feature.

## New Functionality
* Maintainers should be able to reject a patch
* Maintainers need to be able to quickly scan the "All" patches tab and discern the status of the patch
* There should be 4 tabs for patches: All, Open, Closed (Accepted), and Rejected
* It should be clear to maintainers that when they merge a patch, they're also accepting it

**Comment by brandonhaslegs** [comment]
> * There should be 3 tabs for patches: All, Closed (Accepted), and Rejected

Is "Open" intentionally missing here?

**Comment by juliendonck** [comment]
* Maintainers should be able to reject a patch

![image](https://user-images.githubusercontent.com/2326909/159701498-06067d30-d816-487e-8f73-0f6d541318f6.png)

* Maintainers need to be able to quickly scan the "All" patches tab and discern the status of the patch

![image](https://user-images.githubusercontent.com/2326909/159702308-8836244d-9332-44fe-9f82-1a7865c7000b.png)
 
* There should be 3 tabs for patches: All, Closed (Accepted), and Rejected

![image](https://user-images.githubusercontent.com/2326909/159701608-20e0c35d-da8f-4433-9c94-e75abb3ce7fd.png)

* It should be clear to maintainers that when they merge a patch, they're also accepting it

Don't know what is confusing here, is there a problem we're solving.

**Comment by Kaihuang724** [comment]
Also, thanks @juliendonck and @brandonhaslegs !! These designs look 🔥

**Comment by juliendonck** [comment]
> The thinking was to make it clearer to maintainers that if they want to close or accept a patch, they need to merge the patch into their branch. Overall, I wanted to make sure the wording was consistent. I like that we've named it the Merged tab, which solves this problem, imo.

Right, I understand that. I agree that with the wording consistent across the tabs, we don't need to do more here.

**Comment by juliendonck** [comment]
@radicle-dev/upstream would it be useful for me to do the ui front end for this issue? I'd be happy to

**Comment by rudolfs** [comment]
I think the majority of the work is getting the data, which depends on us [coming up with a data model first](https://github.com/radicle-dev/radicle-upstream/issues/2784). We should wire up the UI only after we get the data and the actual wiring up is trivial, as we already have the UI set up. The current "Closed" tab will go away together with the data model change and we'll get new data for the "Merged" and "Rejected" tabs.

Here's what it looks like now, for reference:
<img width="1552" alt="Screenshot 2022-03-23 at 16 58 14" src="https://user-images.githubusercontent.com/158411/159742499-6f65e2d9-9fe4-4ac0-96bd-057605999396.png">

**Comment by geigerzaehler** [comment]
Can we close this now?

**Comment by geigerzaehler** [comment]
The designs need to be updated to incorporate the changes made in #2833.

**Comment by geigerzaehler** [comment]
> The designs need to be updated to incorporate the changes made in #2833.

This is done: https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/Radicle?node-id=12615%3A211321
