### ISSUE TITLE
Create documentation for the patch status data model

### ISSUE THREAD

**Issue by Kaihuang724** [radicle-dev/radicle-upstream#2784]
We need to create some documentation for the data model we want to implement so we can have statuses for individual patches. The reason we want to do this is primarily for team alignment. The documentation will be shared with the alt-clients team as they are also implementing patches within their CLI. The data model should, at the very least, be compatible so when users create patches in the CLI, they will also be maintainable via the Upstream client.

**Comment by geigerzaehler** [comment]
Started documenting this on [Discourse](https://radicle.community/t/upstream-collaboration-with-event-logs/2825)

**Comment by geigerzaehler** [comment]
It remains to specify how events are signed and verified
