### ISSUE TITLE
Truncate the device ID in the branch comparison

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2787]
![image](https://user-images.githubusercontent.com/4406983/159715981-fb094d98-7a15-4118-adc1-be9d60b7e96e.png)

This device ID should be truncated so that this view is useful and there aren't random numbers and letters all over the page.

**Comment by rudolfs** [comment]
Closed via https://github.com/radicle-dev/radicle-upstream/commit/e7fd8853dd7fbf823f3781ee91f7336b4f148c8b.
