### ISSUE TITLE
Error while trying to link account

### ISSUE THREAD

**Issue by cwdcwd** [radicle-dev/radicle-upstream#2788]
when linking my Radicle ID to my Ethereum address I'm getting the following:
```
{
  "stack": "Error: Failed to update the Ethereum claim in your identity\n    at aZ (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:67:363757)\n    at async f (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:67:369867)\n    at async HTMLButtonElement.<anonymous> (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:67:365747)",
  "message": "Failed to update the Ethereum claim in your identity",
  "code": "UpdateEthereumClaimFailure",
  "source": {
    "stack": "Error: Something went wrong\n    at Zt.fetchOk (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:1649964)\n    at async aZ (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:67:363689)\n    at async f (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:67:369867)\n    at async HTMLButtonElement.<anonymous> (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:67:365747)",
    "message": "Something went wrong",
    "code": "UnknownException",
    "details": {
      "name": "Error",
      "variant": "INTERNAL_SERVER_ERROR",
      "body": {
        "message": "Something went wrong",
        "variant": "INTERNAL_SERVER_ERROR"
      },
      "response": {}
    }
  }
}
```

I attempted to link twice as you can see in [this transaction](https://etherscan.io/tx/0x12ebfa0b0cb2b24a71e687121d53d482b7625cc805e100bb68014b5bbd1a7aaf) and [this transaction](https://etherscan.io/tx/0x96a70df3f9aaa9a3cf273552e4997d8c6517a7121e06a746e165e353ebdeb43e)

I'm on a mac, Monterey, 12.1 (21C52)
Radicle Upstream Version 0.2.13 (0.2.13)

anecdotally, a user reached out to me directly on Discord claiming it to be an issue with my xpub key. They tried to get me to post my private keys into so random website that clearly was phishing. I subsequently went and used `ether.js` to validate that I could generate an xpub key from my mnemonic and that all worked just fine.

**Comment by cwdcwd** [comment]
@sebastinez ticket logged. thanks for you help!

**Comment by rudolfs** [comment]
Thanks for reporting this. With the last release we disabled all Ethereum integrations, we'll be rethinking how they fit into Upstream. Read more about it here: https://radicle.community/t/radicle-upstream-v0-3-0-is-out/2812#temporary-removal-of-ethereum-integration-4.
