### ISSUE TITLE
Refresh patch list when receiving updates from Git+Http peer

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2791]
The patch list and patch data should refresh in Upstream when updated patch information is fetched from a Git+Http seed.

This is a follow-up to #2776.

## Test case
1. User A creates a project and pushes it to a Git+Http seed
2. User B clones the project from the seed
3. User A opens the patch list in Upstream
4. User B creates a patch for the project and pushes it to the seed
5. The patch list in User A’s Upstream instance refreshes

**Comment by rudolfs** [comment]
Fixed via https://github.com/radicle-dev/radicle-upstream/commit/da0ad6e2a5fa9fa353687db1677bf85444cbe154.
