### ISSUE TITLE
Unlock via ssh-agent takes a long time

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2792]
For some reason `warp` seems to block and not respond to any requests during startup. It takes longer than 10sec to start responding.

**Comment by rudolfs** [comment]
This seems to only happen to my old profile. When I create a new profile and follow the upstream project app start + unlock happen instantly.

**Comment by geigerzaehler** [comment]
Are we still seeing this? I don’t

**Comment by rudolfs** [comment]
It's not a problem for me anymore.
