### ISSUE TITLE
Recurring intermittent error on project details screen

### ISSUE THREAD

**Issue by Kaihuang724** [radicle-dev/radicle-upstream#2793]
Currently on the development build (radicle-upstream_03f90a5c8f66c37becee8c589658fbcb)

Seeing this error when loading a project-details, but am able to continue:

```
{
  "stack": "Error: the path 'test' was not found\n    at Vi.fetchOk (file:///tmp/.mount_radiclisjxru/resources/app.asar/public/bundle.js:1:1838524)",
  "message": "the path 'test' was not found",
  "code": "UnhandledRejection",
  "details": {
    "name": "Error",
    "variant": "NOT_FOUND",
    "body": {
      "message": "the path 'test' was not found",
      "variant": "NOT_FOUND"
    },
    "response": {}
  }
}
```

**Comment by geigerzaehler** [comment]
I’ve committed some changes that should provide more information as part of the error. (Specifically which endpoint errors.) Could you try a recent build and update the error, @Kaihuang724?
