### ISSUE TITLE
Fall back to any other branch if a remote peer's default branch is missing

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2795]
It's not guaranteed that a remote peer will have the default branch replicated when using the push/pull transport and collaborating on patches. In this case the Upstream UI should fall back to any other branch that remote peer might have. And if the remote peer doesn't have any branches, prevent users from selecting that peer in the peer selector.

**Comment by rudolfs** [comment]
We worked around the problem by adjusting the commands to always push the default branch when collaborating on patches.

**Comment by geigerzaehler** [comment]
We should keep this open. Since we can’t guarantee that a peer has a default branch Upstream should be able to handle this gracefully.
