### ISSUE TITLE
Disable gossip replication

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2800]
Because gossip replication is unreliable and we have a viable alternative with Git+Http replication we want to disable the former.

- Remove tests that use gossip replication
  - Remove p2p tests in the `p2p-tests` folder but keep the library since it is used by the git+http tests in `test/proxy/sync.test.ts`.
  - Remove all cypress tests that run two proxies. These tests can be indentified by their use of `withTwoOnboardedNodes`.
 - Remove the `--seed` flag from the Upstream CLI
 - Optional: Do some miscellaneous cleanups in the proxy and the UI.

**Comment by rudolfs** [comment]
Closed via: https://github.com/radicle-dev/radicle-upstream/commit/45561c887b7e652174125c5242bcdbb56a4d7065.
