### ISSUE TITLE
Test new onboarding

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2804]
Add automated tests for the new onboarding flow, make sure that we cover:
  - the happy path -- all dependencies met and there is an identity -> land on profile screen
  - missing Git, rad CLI or Upstream CLI show instructions to user. This can be tested by mocking the electron IPC methods 
  - missing identity shows onboarding. When `rad auth` is run the onboarding dialog closes. This should be tested by actually running `rad auth`. This requires us to integrate the `rad` cli tooling into our test setup.

**Comment by geigerzaehler** [comment]
I’ve updated this with a couple more details.
