### ISSUE TITLE
Onboarding detection

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2817]
At the moment, the mechanism that detects whether to show the onboarding screen is implemented by blocking the startup of the `upstream-proxy` services including the HTTP endpoint. This creates the following problems.

* If a user does not have an identity yet, the UI shows a spinner for one second and only then shows the onboarding screen.
* If the proxy fails to set up its HTTP endpoint but does not crash we show the onboarding screen—even if an identity exists. This masks errors and makes them harder to debug.
* Similarly, if it takes longer than one second for the proxy to provide the HTTP endpoint, we will show the onboarding screen. Even if an identity is present and the HTTP endpoint is created later.
* When the app is run from a terminal and closed on the onboarding screen we see an error on the terminal indicating that upstream-proxy process was killed.

To address these problems, the `GET /session` endpoint of the API should provide information on whether the user is onboarded or not.

Fixing the implementation is a blocked by <https://github.com/radicle-dev/radicle-cli/issues/77> as well as the fact that `upstream-proxy` creates an uninitialized profile on startup. If <https://github.com/radicle-dev/radicle-cli/issues/77> is not addressed we can only work around this by having the `upstream-proxy` not create an uninitialized profile. Addressing the radicle-cli issue is preferred.

**Comment by efstajas** [comment]
@geigerzaehler sure thing, I will take a look after patch statuses is done 👍
