### ISSUE TITLE
UX: "Checkout [repo]" button is confusing while viewing a patch

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/radicle-upstream#2821]
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/1018218/165062809-36bb9fbe-62df-4b43-8963-4ad126670337.png">

I just tried checking out a patch and accidentally clicked the "Checkout" button at the top of the screen, which actually just checks out a working copy of the repo. What I actually wanted to click was the "Checkout patch" button at the bottom. I would argue the "Checkout" button should probably not appear while not on the "Files" view, or should explicitly say "Checkout project" in order to avoid confusion.

**Comment by rudolfs** [comment]
We'll move the "Checkout patch" button to the top and only show it in the patch tab context. The "Checkout project" button will be available in the "Files" tab context.

https://github.com/radicle-dev/radicle-upstream/issues/2834
