### ISSUE TITLE
Patch Statuses implementation

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2827]
This issue tracks the implementation of #2782

- [x] Event authentication. We want to verify the authenticity of events by signing with the peer key. If an event in an event log cannot be verified we want to not replicate the event log and not expose its events to the UI.
- [x] Manual testing and review by the team
- [x] Write down test cases. We want a comprehensive set of test cases for this feature that we can manually execute. The test cases should cover all possible interactions between the different states (open, closed, merged) and the actors (maintainer, patch author, project follower).
- [x] #2830
- [x] #2838 

## Follow-ups

* _Automated tests_. Implement test scenarios as automated tests using the infrastructure in #2819.
* _Atomic UI updates_ After the maintainer has clicked the “close” patch button and the API request responds the button to close the patch is still briefly shown. After some short time, the UI receives a project update event and re-requests all project data including the patch events. The events now include the event created by clicking on “close” and the “close” button is replaced by the “reopen”.
* Update UI to incorporate changes from #2833 ([Figma](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/Radicle?node-id=12615%3A211886)). This requires a refactoring of the `ActionBar` in `Source`.

**Comment by efstajas** [comment]
Regarding tests; I think we can expand on your previously described scenario by adding a third peer who is neither delegate nor patch owner to cover that case too.

- Create two peers A, B and C. Peer A creates project that B and C check out. Peer A follow B and C.
- Peer B creates a branch and patch with upstream patch create
- Peer A and C see the patch.
- Peer A sees "Merge" and "Close" buttons, peer B sees a "Close" button and peer C sees neither.
- Peer A presses the ”close patch” button.
- The UI updates for Peers A, B and C and the patch is marked as closed
- Peers A and B see the "Reopen" button, peer C sees none
- Peer A presses the ”Reopen patch” button
- The UI updates for Peers A, B and C and the patch is marked as open
- Peer A sees "Merge" and "Close" buttons, peer B sees a "Close" button and peer C sees neither.
- Peer B presses the ”Close patch” button
- The UI updates for Peers A, B and C and the patch is marked as closed
- Peer A presses the "Reopen patch" button
- The UI updates for Peers A, B and C and the patch is marked as open
- Peer A merges the patch by copying the instructions displayed by the "Merge" button
- The UI updates for Peers A, B and C and the patch is marked as merged

**Comment by geigerzaehler** [comment]
This is great, @efstajas! I think this pretty much covers everything. At least I can’t think of anything that is mising. Thanks a lot!

**Comment by geigerzaehler** [comment]
One note on the test cases: We should check the patch status on the patch list and the individual patch page. Not necessarily for every change and peer though.

**Comment by rudolfs** [comment]
@geigerzaehler can we close this now?

Implemented via: https://github.com/radicle-dev/radicle-upstream/commit/f081a029ad63c3a646add26a612a6d19a40a71bf.
