### ISSUE TITLE
"Register Org" Transaction Status view

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#283]
![Screen Shot 2020-04-14 at 2 01 30 PM](https://user-images.githubusercontent.com/2712962/79273879-8d3c9100-7e58-11ea-8871-84c0141b79a2.png)

Related to #277

**Comment by xla** [comment]
Looks to be the same as the single transaction view of #225

**Comment by MeBrei** [comment]
Yes, the view is already implemented. It should be checked if all the logic for the register org transaction message is in place, but other than that it should already work.
