### ISSUE TITLE
Warn user when the required version of Git cannot be found

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2837]
Upstream requires at least version 2.35.1 of Git for pushes to seed nodes. (Git pushes to seed nodes are implemented as part of event logs in #2782.) If Upstream does not run this version changes to like closing a patch do not propagate to other peers until the user calls `rad sync` (or a similar command) in the project repository from their shell. Because of that we should make users aware that a certain version of Git is necessary and help them fix the issue.

One solution could be to show the onboarding screen if the required Git version is not found. The onboarding screen would mark everything but the Git step as completed.

Alternatively, we could show an error notification informing the user that the necessary Git version was not found.

**Comment by geigerzaehler** [comment]
I’d prefer the first solution.

**Comment by rudolfs** [comment]
Fixed via: https://github.com/radicle-dev/radicle-upstream/commit/c4b045a544f7b5998d13b7e3b7157ef4d6c077db.

Went with the least effort solution for now.
