### ISSUE TITLE
Sort patches by newest first and don't group by author

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2839]
This will allow us to navigate a long patch list easier.

Refs https://github.com/radicle-dev/radicle-upstream/issues/2833#issuecomment-1127754504.

**Comment by geigerzaehler** [comment]
Before we start on this we need to specify what “newest first” means.

**Comment by rudolfs** [comment]
> Before we start on this we need to specify what “newest first” means.

How about newest by creation timestamp. We'd need to store the timestamp and trust the peers that they're not lying about the time.

**Comment by geigerzaehler** [comment]
Creation timestamps sounds good for the beginning.

**Comment by Kaihuang724** [comment]
Can we do by both created and closed, depending on which screen the user's on?

For instance, on open patches, we sort by patch creation timestamp, and on the closed page, we sort by latest closed timestamp. I assume we'll need to track both of these separately.
