### ISSUE TITLE
Explore notification system

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2854]
Now that we have comments available in Upstream, we start seeing new pain points in our daily workflow.
When there are multiple patches open, it's hard to keep track of new comments and other events that I have to react to.

We can break down the problem into these areas:

1) How do i want to be notified?
    - I periodically check the app for notifications (pull)
    - I get notified by the system/OS (push)
2) I want to know what has changed in the projects that I track, currently the following events are possible:
    - There's a new patch
    - There's a new comment on a patch
    - There's a new commit on a patch or the patch title/description got updated
      - this is a single event until we have https://github.com/radicle-dev/radicle-upstream/issues/2848)
    - A patch status has changed
      - Open -> Merged
      - Open -> Closed
      - Closed -> Reopened
3) I want a todo-list where I can distinguish events that I have _seen_ from events that I've explicitly marked as _done_

**Comment by rudolfs** [comment]
A very basic version of *2* could be changing the patch listing to show comment count and indicate _seen_ vs _unseen_ with color:
<img width="1440" alt="mvp" src="https://user-images.githubusercontent.com/158411/172891750-57301627-6c76-4c6d-ab94-271f79cb1304.png">

**Comment by efstajas** [comment]
Re point 2, i would add "a patch status has changed" to that list.

**Comment by brandonhaslegs** [comment]
> … changing the patch listing to show commit/comment count and color-code seen…

We should do this regardless of what we do. Maybe a good first start!

**Comment by brandonhaslegs** [comment]
Here are some explorations for a notifications list https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/Radicle?node-id=12951%3A218548

**Comment by rudolfs** [comment]
@brandonhaslegs regarding **3)**: how could I distinguish between I've seen/unseen/marked as done in the proposed design? I find the inbox-zero way of managing notifications quite useful in my day-to-day life.

<img width="972" alt="Screenshot 2022-06-10 at 12 21 02" src="https://user-images.githubusercontent.com/158411/173045447-c3a2af65-3e3d-4325-9c00-c24d635d6b78.png">

**Comment by rudolfs** [comment]
What is the benefit of having the notifications in a modal as opposed to a separate screen?

From a technical perspective a separate screen might be slightly easier to implement and would potentially cause less problems with all our other modals, overlays and notifications in the UI.

> Maybe floating notifications when they happen? (without pressing the bell icon)

I remember we had a transaction center previously and we removed it because it would [clash with our other notifications](https://github.com/radicle-dev/radicle-upstream/issues/1568) and had a bunch of other issues. Why would we display them in the app and not via the native OS notification system?

**Comment by rudolfs** [comment]
> just with color i think.

And would there be a button to "Archive" or "Mark as done"? And how could I switch between the All/Done lists?

**Comment by brandonhaslegs** [comment]
> What is the benefit of having the notifications in a modal as opposed to a separate screen?

So you don't have to leave the page you're on to read the notification

> would there be a button to "Archive" or "Mark as done"

No, just visited/not visited

> switch between the All/Done lists

I think this is too complicated

**Comment by rudolfs** [comment]
>> would there be a button to "Archive" or "Mark as done"

> No, just visited/not visited

What if we just show the "Mark as done" button when you hover the notification?

**Comment by brandonhaslegs** [comment]
depends on what people prefer. having to click every notification you get to get the "notified" state to go away seems annoying

**Comment by rudolfs** [comment]
> depends on what people prefer. having to click every notification you get to get the "notified" state to go away seems annoying to me

Is there another way to "bookmark" something to be done later, even if I want to look at it now?
