### ISSUE TITLE
v 0.3.2 download still displays v0.3.1 in app

### ISSUE THREAD

**Issue by suschizu** [radicle-dev/radicle-upstream#2860]
Hello - I think you forgot to update the ShortVersionString and the bundle version inside the info.plist file 
The app still shows 3.0.1 instead of 3.0.2  (https://github.com/radicle-dev/radicle-upstream/releases/download/v0.3.2/radicle-upstream-0.3.2.dmg & https://github.com/radicle-dev/radicle-upstream/releases/download/v0.3.2/radicle-upstream-0.3.2-arm64.dmg )

```
</string><key>CFBundleShortVersionString</key>
<string>0.3.1</string>
[...]
<key>CFBundleVersion</key>
<string>0.3.1</string>

```
<img width="406" alt="Screen Shot 2022-07-30 at 23 26 55" src="https://user-images.githubusercontent.com/16004333/181996726-343f3a1c-6b26-4b0f-ac7e-85d401a1e1c2.png">

**Comment by rudolfs** [comment]
Good catch. I think this happened because we recently removed the `standard-version` dependency from our release process. Will fix this manually and re-upload the release artefacts in a bit.

**Comment by rudolfs** [comment]
@suschizu the update on brew's side got merged. Could you please confirm that it's now 0.3.2?

**Comment by suschizu** [comment]
hey @rudolfs … sorry for the twisted version numbers 😬  
and yes I can confirm that both downloads now contain 0.3.2 as CFBundleShortVersionString and CFBundleVersion 👍  

```
CFBundleIdentifier:
xyz.radicle.radicle-upstream

CFBundleShortVersionString:
0.3.2

CFBundleVersion:
0.3.2

CFBundleGetInfoString:

NSHumanReadableCopyright:
Copyright © 2022 radicle team

LSMinimumSystemVersion:
10.14

```
