### ISSUE TITLE
Overview: Code Sharing II

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#288]
### UI
- [ ] tree/clone selector (#289)

### Proxy
  - [ ] protocol integration of project stats in profile project list, user project list and org project list screens

**Comment by xla** [comment]
>  tree/clone selector

We should probably stick with the terminology of `repo` instead of `clone`. The hierarchy implies multiple repos per project, afaiu the protocol that is. So it would go `project` -> `repo` -> `revision`. While writting this down I think that `revision` is more correct if we lean on Git concepts, if we want to leave the notion of a single vcs, `tree` might be better instead.

**Comment by rudolfs** [comment]
@xla: good feedback, I also think the terminology could be improved here.

I took `tree/clone selector` directly from our product roadmap, to avoid having different names for the same thing:
<img width="271" alt="Screenshot 2020-04-16 at 10 48 43" src="https://user-images.githubusercontent.com/158411/79435751-55f0f000-7fd0-11ea-901b-78b6074ce0e2.png">

AFAIK the `tree/clone selector` refers to a widget which lets you view of a repository from certain user's perspective, it also allows you to select a specific revision (so far only branches will be listed) in that user's view:
<img width="235" alt="Screenshot 2020-04-16 at 10 53 35" src="https://user-images.githubusercontent.com/158411/79435970-97819b00-7fd0-11ea-9462-57236ad38a1f.png">

I imagine this widget will also let you select tags in the future. In other words this dropdown will let you select the `user/revision` portion of a path.

Should we maybe call it `user/revision selector`?

@xla: would you still want to refer to this widget as `revision` or `tree` selector?
@cloudhead: maybe you have a better name for it?

**Comment by cloudhead** [comment]
I think we converged to repository selector, see #289 - though tree/clone selector are also valid.

**Comment by xla** [comment]
@cloudhead What is a clone in the context of a project and its repos?

**Comment by cloudhead** [comment]
A clone is just a repo. No difference.

**Comment by xla** [comment]
It's confusing, because a repo is a radicle concept where a clone is any copy created with `git clone`, but not tracked with radicle. I'd urge to reconsider using these terms interchangeably @radicle-dev/product
