### ISSUE TITLE
Misaligned avatars

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#290]
It seems like it's just me so far. If I remove the `min-width: 27px`, the problem goes away though..

![2020-04-15-180802_1037x627_scrot](https://user-images.githubusercontent.com/40774/79443301-f1d32980-7fd9-11ea-9b12-9f36271e244c.png)

**Comment by rudolfs** [comment]
Weird! There shouldn't be any differences in the electron renderer between platforms, but so far we haven't really tested much on Linux, might be that.

Maybe @MeBrei can comment more as she implemented the icons.

**Comment by MeBrei** [comment]
If I remove the `min-width` the emojis are too far left for me. It was a hack to get them to be centered as most emojis themselves are not. 
So we should look into that again anyway, but I also don't understand why it is different for you.

<img width="78" alt="Screenshot 2020-04-16 at 14 22 15" src="https://user-images.githubusercontent.com/16262137/79455774-af1b4c80-7fed-11ea-8137-eef4aa8dd758.png">

**Comment by rudolfs** [comment]
Hmm a quick google turned up this: https://stackoverflow.com/questions/44142464/how-do-i-horizontally-center-an-emoji

Could also be a retina vs non-retina issue.

Maybe we can look into this deeper when we choose a font for emojis, so they're all consistent across platforms: https://github.com/radicle-dev/radicle-upstream/issues/231.

**Comment by rudolfs** [comment]
Closed by #339
