### ISSUE TITLE
Move CSS measurements to `rem`

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#303]
I would be in favor of moving all/most CSS measurements (padding, margin, height etc.) to `rem` or "root em" units in the long term, since that is how the app is designed, and it makes it easy to catch mistakes eg. spacing that doesn't fit the system. The modules I've written are already in that system (eg. Commit.svelte).

**Comment by xla** [comment]
@sarahscott Raised awareness with regards to responsiveness of the app, this rem initiative could aid improvements in that direction.

**Comment by xla** [comment]
@rudolfs How consitent are our rems now?

**Comment by rudolfs** [comment]
@xla about 50/50.

```
radicle-upstream-2/ui » g px |wc -l
     537
radicle-upstream-2/ui » g rem |wc -l
     420
```
