### ISSUE TITLE
Come up with an approach to responsiveness

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#304]
We don't need to worry about mobile breakpoints, but we should be thinking about how things look on small screens.

**Comment by sarahscott** [comment]
e.g. on half of a 13-in laptop, upstream looks like this:

<img width="721" alt="Screen Shot 2020-04-28 at 1 14 24 PM" src="https://user-images.githubusercontent.com/2712962/80533473-8b8fc480-8952-11ea-8122-d089ed118b8e.png">

**Comment by sarahscott** [comment]
cc @juliendonck @brandonhaslegs

**Comment by rudolfs** [comment]
Here's another one. Maybe we should set a min-width for all pages as a first step (as suggested by @cloudhead)?
<img width="365" alt="Screenshot 2020-04-29 at 14 58 35" src="https://user-images.githubusercontent.com/158411/80599083-a33a7c00-8a2a-11ea-860b-0bf48d714cb0.png">

**Comment by brandonhaslegs** [comment]
Yes, this is something I'm starting to think about globally. For things like this screenshot, we should have thought about this in the design stage already. (Maybe @juliendonck thought about how this specifically would truncate or reflow.)

And once we set a min-width in the app, the problem should be less common.
