### ISSUE TITLE
Change multiple notification stacking

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#306]
@brandonhaslegs brought up the fact that we shouldn't stack notifications, like seen in the image below. A better paradigm is to replace one with the other after a timeout or an action as [illustrated here](https://material.io/components/snackbars#behavior) under "consecutive snackbars".

<img width="1284" alt="Screenshot 2020-04-23 at 12 22 50" src="https://user-images.githubusercontent.com/2326909/80088698-27898c80-855d-11ea-9550-c13d93681aab.png">

**Comment by brandonhaslegs** [comment]
In addition to this, I just noticed that notifications with an action are automatically disappearing after X seconds. Instead, notifications with actions should never automatically disappear, they should remain until the user has clicked the action.

Notifications without actions can continue to automatically disappear.

**Comment by xla** [comment]
@radicle-dev/product There has been some work on notifications recently, are the points in this issue still relevant?
