### ISSUE TITLE
Upstream UI hangs

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#320]
Happens randomly in dev-mode.
I've observed this along with @juliendonck and @cloudhead.
It seems to happen more often while the design system page is open, I have a hunch it could be something with the CSS animations.

We should investigate why this happens and fix it before the official release.

**Comment by cloudhead** [comment]
Not quite randomly for me: it only happens when an auto-reload is triggered by a code change.

**Comment by xla** [comment]
It looks to be exclusive to the watch mode and happens primarily if reloads are triggered quickly in succession.

**Comment by xla** [comment]
Closing for now as this hasn't been reported in a while. If this impedes with the developer experience we gonna dive into it more thoroughly.
