### ISSUE TITLE
Add placeholder images

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#327]
Think of a consistent way to show placeholder images in the app.

- [x] binary content
- [x] when there's no readme
- [x] other places in the app where we use plant image.

**Comment by rudolfs** [comment]
These two places:
```
ui/Screen/IdentityCreation.svelte
70:      <Placeholder

ui/Screen/Profile/Onboard.svelte
28:    <Placeholder style="width: 420px; height: 217px;" />
```

**Comment by juliendonck** [comment]
#537

**Comment by xla** [comment]
@juliendonck Does #537 close this one?

**Comment by juliendonck** [comment]
Nope

**Comment by brandonhaslegs** [comment]
Added ReadMe empty state.
