### ISSUE TITLE
Improve commit history ordering

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#344]
Currently, the commit history we get from coco is in a certain order, but that order is not that of the `committerTime` attribute. This is apparent when a commit has a different author and comitter.

This manifests in the commits view of a branch, where in some cases, a commit with an older timestamp will be shown before a commit with a newer timestamp.

There's at least two ways we could fix this:
1. Sort the array by `committerTime` (easy fix, but ugly and potentially impossible for large histories)
2. Expose some other "time" attribute upon which the array is actually sorted in coco

Might be good to look into how github deals with this.

**Comment by FintanH** [comment]
Going off of memory here: the commit history is a revwalk, so the git bindings would be a good place to figure out their ordering. Probably a parent-child ordering.

**Comment by rudolfs** [comment]
This is easy to spot in the UI:
<img width="50%" alt="Screenshot 2020-05-05 at 16 33 03" src="https://user-images.githubusercontent.com/158411/81078757-eabf7d00-8eee-11ea-822a-df7c8e6532cc.png">

**Comment by xla** [comment]
Is this still an issue?

**Comment by rudolfs** [comment]
@xla: yes, if you add registry as a repo and look for merge commits:

<img width="50%" alt="Screenshot 2020-07-20 at 09 42 36" src="https://user-images.githubusercontent.com/158411/87912346-7fa53180-ca6d-11ea-864b-e20df23daa6f.png">

**Comment by juliendonck** [comment]
@rudolfs can you double check this?

**Comment by rudolfs** [comment]
Seems like this is resolved. Tested on `0.1.4` in the radicle-contracts repo.

<img width="1552" alt="Screenshot 2020-12-03 at 13 30 33" src="https://user-images.githubusercontent.com/158411/101018401-bf2b7080-356b-11eb-97fb-7c5a4a7f81ad.png">
