### ISSUE TITLE
Make transaction view responsive

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#362]
Should be truncated:

![Screen Shot 2020-05-07 at 12 24 37 PM](https://user-images.githubusercontent.com/2712962/81336212-bfa76b80-905d-11ea-95cf-db7f6e36abdc.png)

**Comment by xla** [comment]
Part of #347

**Comment by sarahscott** [comment]
This looks a lot better when the project name is limited to 32 characters; going to close it in favor of #304
