### ISSUE TITLE
New dropdown has strange widths on Register Project flow

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#363]
Before selection, the width of the options is too small:

![Screen Shot 2020-05-07 at 1 09 43 PM](https://user-images.githubusercontent.com/2712962/81340145-3182b380-9064-11ea-9f83-22519bf67bb7.png)

Maybe org names should be truncated here? @juliendonck @rudolfs

**Comment by rudolfs** [comment]
I can't seem to reproduce this on master. Could you add steps how to get to this state please?

![cnr](https://user-images.githubusercontent.com/158411/81536181-698f3c80-936b-11ea-9fb8-44eee642fe86.gif)

**Comment by juliendonck** [comment]
Same here.

**Comment by sarahscott** [comment]
I can't repro it now either, maybe something was off for me locally. Will keep an eye on it and if it happens again I'll document the steps.
