### ISSUE TITLE
Register Project for org has 'null' value in dropdown

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#364]
![Screen Shot 2020-05-07 at 1 09 35 PM](https://user-images.githubusercontent.com/2712962/81340226-56772680-9064-11ea-9373-805cb056c5cc.png)

**Comment by xla** [comment]
Can you provide steps to reproduce this behaviour?

**Comment by xla** [comment]
This was due to the route in the originating branch not being paramterised correctly.
