### ISSUE TITLE
Feature: Org-related Transactions

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#365]
Outstanding work for org-related transaction in UI:

**Register Org flow**
- [x] Generate emoji avatar for org name
- [x] Look up existing orgs to ensure handle is not taken
- [ ] On transaction confirmation step, should show correct emoji avatar

**Add Member to Org flow**
- [ ] Fetch correct avatar for potential member
- [ ] On transaction confirmation step, subject should show correct member avatar + member name
- [ ] Upon submission, user should be redirected to org profile page

**Comment by xla** [comment]
> Upon submitting transaction, user should be redirected to new org profile page

As the transaction is just under way the new org is not really in existence at that point. For the time being routing back to another view, or the view the user came from is acceptable.

**Comment by sarahscott** [comment]
Covered by #347
