### ISSUE TITLE
Return attested identities for users if known/present

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#367]
To show users in richer ways we rely on the attested identity, which we should embbed in all responses where users (handles) are returned.

**Comment by xla** [comment]
Users don't have avatars. Instead they may have a corresponding identity, which will carry either of these things. What we really want is to return the related identity when we return a user. I rephrased the issue to reflect that.

**Comment by xla** [comment]
Reopen if this is still unadressed.
