### ISSUE TITLE
Registry validations don't adhere to spec

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#369]
[Spec](https://github.com/radicle-dev/registry-spec/blob/master/out/rad-registry-spec-0b7699a.pdf):

- Org and user handles must be unique, **i.e. not currently in use as an org identifier nor as a user identifier**, and comply with the following rules:
- [ ] Must be between 1 and 32 ASCII-encoded characters.
- [ ] Must only contain `a-z`, `0-9` and `-` characters.
- [ ] Must not start or end with a `-`.
- [ ] Must not contain sequences of more than one `-`.

<img width="50%" alt="Screenshot 2020-05-11 at 10 08 11" src="https://user-images.githubusercontent.com/158411/81538664-5aaa8900-936f-11ea-9fe5-016700130224.png">

<img width="50%" alt="Screenshot 2020-05-11 at 10 23 01" src="https://user-images.githubusercontent.com/158411/81540078-6a2ad180-9371-11ea-85fd-2c62b447777b.png">

The same user handle validation rule should be used in the identity creation form:
<img width="50%" alt="Screenshot 2020-05-11 at 11 00 17" src="https://user-images.githubusercontent.com/158411/81543689-b593ae80-9376-11ea-8160-81d63aeed587.png">

- Projects comply with the following rules:
- [ ] Must be between 1 and 32 ASCII-encoded characters.
- [ ] May only contain `a-z`, `0-9`, `-`, `.` and `_` characters.
- [ ] Must not equal `.` or `..`.

<img width="50%" alt="Screenshot 2020-05-11 at 10 14 56" src="https://user-images.githubusercontent.com/158411/81539263-4915b100-9370-11ea-9729-dd1b48260086.png">

<img width="50%" alt="Screenshot 2020-05-11 at 10 16 33" src="https://user-images.githubusercontent.com/158411/81539447-85491180-9370-11ea-8ed4-231ccdf08f56.png">

The same project handle validation rule should be used in the create local project form:
<img width="50%" alt="Screenshot 2020-05-11 at 11 00 27" src="https://user-images.githubusercontent.com/158411/81543718-c2180700-9376-11ea-9406-7c411f6e8120.png">

**Comment by cloudhead** [comment]
Yeah just to note that user and org ids should use the same validation rules.

**Comment by sarahscott** [comment]
related to #166

**Comment by rudolfs** [comment]
Closing this in favour of: 
https://github.com/radicle-dev/radicle-upstream/issues/166
https://github.com/radicle-dev/radicle-upstream/issues/556
https://github.com/radicle-dev/radicle-upstream/issues/442
