### ISSUE TITLE
Return permissions via the session endpoint

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#371]
As most of the business logic lives in proxy, it's probably the best place to answer which user actions are allowed at a given moment. Here's a list of permissions that we could use in the UI already:

- am I allowed to create a new org?
  - user handle has to be registered
- am I allowed to register a project?
  - I have to be a member of at least one org or a registered user handle
  - I have to have at least one local project
- am I allowed to register this specific project?
  - it is not registered yet
- am I allowed to register a member?
  - I have to be a member of the org

**Comment by MeBrei** [comment]
### V1 permissions
In a first iteration, the permissions would not be connected to the specific transactions, but would be `True` as soon as the user/org information can be retrieved from the registry (ie as soon as the transactions are applied to at least one block).

proposed addition to `session`:
```
permissions: {
	createOrg: True | False,
	registerProject: True | False,
}
```

> * am I allowed to create a new org?
>   
>   * user handle has to be registered

covered by `permissions.createOrg`
> * am I allowed to register a project?
>   
>   * I have to be a member of at least one org or a registered user handle
>   * I have to have at least one local project

covered by `Session.permissions.registerProject`
> * am I allowed to register this specific project?
>   
>   * it is not registered yet

covered by `Session.permissions.registerProject` + checking in the specific project response if it is registered `Project.registered` (ui)
> * am I allowed to register a member?
>   
>   * I have to be a member of the org

check if the org is one of `Session.orgs` (ui)

**Comment by cloudhead** [comment]
This looks good merle. A couple of things to consider:
* If I've registered my handle, I can't register it again (`registerHandle`)
* If I visit an org I am not a member of (this will eventually be possible), I shouldn't be able to register a project there.
* I shouldn't be able to register a member twice.
* I can register a project even if I'm not a member of any org, as long as I have a registered handle

**Comment by MeBrei** [comment]
@cloudhead Thank you for your feedback!

> * If I've registered my handle, I can't register it again (`registerHandle`)

Good point, I am not sure though if this should be part of `permissions` or rather the session should include if you are registered or not (I think  also a badge should be shown if you are registered). I will check what the plan is here.
> * If I visit an org I am not a member of (this will eventually be possible), I shouldn't be able to register a project there.

👍 This should also be covered by `Session.orgs`
> * I shouldn't be able to register a member twice.

This should not be a part of the session as this is org and not user specific. In #349 a validation for this will be added.
> * I can register a project even if I'm not a member of any org, as long as I have a registered handle

I covered that in `am I allowed to register a project?`

**Comment by MeBrei** [comment]
> > * If I've registered my handle, I can't register it again (`registerHandle`)
> 
> Good point, I am not sure though if this should be part of `permissions` or rather the session should include if you are registered or not (I think also a badge should be shown if you are registered). I will check what the plan is here.

Currently `session.identity.registered` is queried to show the badge. But it could also be added into a `session.permissions.registerHandle`

**Comment by xla** [comment]
This proposal looks good @MeBrei - I think in the next iteration we should cover the concerns @cloudhead raised in the context of specific entities (like orgs), they should carry allowed actions the current session is able to perform as well.

**Comment by MeBrei** [comment]
All current use cases of `registerHandle`, `registerProject` & `registerOrg` permissions are applied in the ui. The use of `registerMember` and additional uses of `registerOrg` only become relevant, when orgs can be visited that the user is not a member of.
