### ISSUE TITLE
Actually run clippy in builds

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#376]
Clippy is not correctly run on ci builds, locally there are errors. Once it works again, all remaining errors should be fixed.

**Comment by xla** [comment]
It is executed, so what is the actual problem?

https://github.com/radicle-dev/radicle-upstream/blob/ae0ca4f98c7d7b9e47236bbf9860c45f42f617ba/.buildkite/run.sh#L79

**Comment by rudolfs** [comment]
It is run, but it doesn't do anything:
```
Run proxy lints | 5s
  | Checking proxy v0.1.0 (/build/proxy)
  | Finished dev [unoptimized + debuginfo] target(s) in 4.43s
  | elapsed time: 4.458 (user: 8.000, system: 0.683)
  | Finished dev [unoptimized + debuginfo] target(s) in 0.34s
  | elapsed time: 0.388 (user: 0.267, system: 0.118)
```

Sometimes clippy just stops working locally as well when switching branches.
