### ISSUE TITLE
Fix orgs list in session

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#378]
With the changes of https://github.com/radicle-dev/radicle-registry/pull/433, orgs can only be registered by registered users and org members is a list of user ids (before a list of public keys was returned).

To accommodate the latter,  `list_orgs` in `registry.rs` was adjusted to filter the orgs by user_id. The session does not pass the user_id on `get` (`src/session.rs`) and so returns an empty list.

**Comment by rudolfs** [comment]
Added the workaround here: https://github.com/radicle-dev/radicle-upstream/pull/361/commits/5e7bc277e6946be737725b7409fde45e33a9ae54
