### ISSUE TITLE
EmoijAvatar initially generated for identity differs from the one returned by avatar endpoint

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#388]
Upon creating an identity (`sos`), generated avatar is:
<img width="66" alt="Screen Shot 2020-05-13 at 7 58 02 PM" src="https://user-images.githubusercontent.com/2712962/81887736-aa967500-9554-11ea-8d12-195caa6a0b6f.png">

If I try to fetch the avatar with `/v1/avatars/sos?usage=identity`, I get:
<img width="57" alt="Screen Shot 2020-05-13 at 7 57 53 PM" src="https://user-images.githubusercontent.com/2712962/81887801-cc8ff780-9554-11ea-932f-d494731d098d.png">

Steps to reproduce:

1. Create a new identity, note which emoji is generated and set as `identity.avatarFallback`
2. Either call ``api.get<EmojiAvatar>(`avatars/${id}?usage=${usage}`);`` from somewhere in the app, or try the endpoint in the swagger docs/CL/whatever

**Comment by xla** [comment]
The input used to produce the avatar is not the `handle` but the `id`. This was changed to keep the fallback avatar consistent even when the handles of identity metadata and the one registered as user on the registry differ. In your case it would be `sos@123abcd.git`.
