### ISSUE TITLE
Integrate transaction costs

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#391]
Show correct transaction costs in transaction summary.

<img width="50%" alt="Screenshot 2020-05-14 at 14 47 35" src="https://user-images.githubusercontent.com/158411/81936055-e29fc580-95f1-11ea-9b5d-9a39140e53e8.png">

**proxy**
- [x] provide transaction costs via an endpoint

**ui**
- [x] wire-up transaction costs in the following screens
  - [x] user registration
  - [x] org registration
    - [x] add member to org
  - [x] project registration

Depends on:
- [x] https://github.com/radicle-dev/radicle-registry/issues/485

**Comment by rudolfs** [comment]
@cloudhead: can I assume we won't show the Rad <-> $ conversion in the first iteration of this feature?

**Comment by cloudhead** [comment]
I think we can have it in there if we keep it in the design (we're in a redesign of the wallet atm), and keep the conversion at 1:1 for now.
