### ISSUE TITLE
Wire up "clear coco data" button in Settings

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#394]
Clicking the button should be the same as:
```rm -rf ~/Library/Preferences/xyz.radicle.radicle && rm -rf ~/Library/Application\ Support/xyz.radicle.radicle```

There's probably a more elegant way via the library we use for preference storage.

<img width="607" alt="Screenshot 2020-05-15 at 09 13 26" src="https://user-images.githubusercontent.com/158411/82022103-5ee6e700-968c-11ea-96b6-0b1575cae6a2.png">

**Comment by xla** [comment]
What you describe is wiping all the state, not just the projects. Could you outline what we actually trying to accomplish with this button, or what the common issue is we trying to address while running the app?

A larger issue with just going ahead and wiping these paths is that state is captured in more places, for example the repositories we use to initiate a project on have local state that will make it imposssible to reinitate them as radicle projects even after we wiped the state.

**Comment by rudolfs** [comment]
Whenever I do a demo of the app at bi-weekly I want to have a clean slate and create only a set of projects that I'll use for the demo. For that I clean the coco data with `rm -rf ~/Library/Preferences/xyz.radicle.radicle && rm -rf ~/Library/Application\ Support/xyz.radicle.radicle`. So that the project list under my Profile is empty.

I guess we could also remove the associated repositories as it won't be possible to re-add them since they have a `rad`. If we remove both the data and the state there should be a confirmation between clicking the button and performing the cleanup.
