### ISSUE TITLE
Make associated entity IDs required

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#397]
In order to make things more unambiguous we should make the coco attestation attributes mandatory and stick to a certain naming scheme.

Identity attestation should be named `cocoIdentityId` and project attestation should be `cocoProjectId`:

- Register a new unique Org
  - [ ] response `POST /v1/orgs`: `members/maybeEntityId` → `members/maybeURN`
- Find Org by ID
  - [ ] response `GET /v1/orgs/{id}`: `members/maybeEntityId` → `members/maybeURN`
- Lists all Projects of the Org
  - [ ] response `GET /v1/orgs/{org_id}/projects`: `maybeProjectId` → `maybeURN`
- Find Project for Org
  - [ ] response `GET /v1/orgs/{org_id}/projects/{project_name}`: `maybeProjectId` → `maybeURN`
- Register a Project on the Registry
  - [ ] request `POST /v1/projects/register`: `maybeCocoId` → `URN`
- Fetch current Session
  - [ ] response `GET /v1/session`: `orgs/members/maybeEntityId` → `orgs/members/URN`
- Register a handle on the Registry
  - [ ] request `POST /v1/users`: `maybeEntityId` → `URN`
- Fetch a User
  - [ ] response `GET /v1/users/{handle}`: `maybeEntityId` → `maybeURN`
- List all orgs the user is a member of
  - [ ] response`GET /v1/users/{handle}/orgs`: `members/maybeEntityId` → `members/maybeURN`

**Comment by FintanH** [comment]
To add to this: `RadUrn` has a `Deserialize` impl so we can use the type in the payload. DEATH TO STRINGS!

**Comment by xla** [comment]
We removed registry related functionality from the proxy.
