### ISSUE TITLE
Panic errors during testing related to project fixture

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#401]
While testing (not while running the app normally), I was seeing a lot of these errors:
```
thread 'main' panicked at 'Can't read projects dir!: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/sarahscott/.cargo/git/checkouts/radicle-link-009c17032bc5eda9/4cedafa/librad/src/project.rs:97:9
```

After following the steps in the CI setup (currently not documented in `DEVELOPMENT.md`), they went away:
```
git submodule update --remote --init --recursive
git submodule foreach "git fetch --all"
git submodule foreach "git checkout -B dev -t origin/dev"
git submodule foreach "git checkout master"
git submodule foreach "git pull origin master"
```

Will hold off on updating the documentation while this is under investigation.

**Comment by sarahscott** [comment]
Update: they happen if we don't create a project after `nukeAllState` & `nukeCache`

**Comment by FintanH** [comment]
I came across a similar issue recently. I baked it into the CI for now, but maybe adding to https://github.com/radicle-dev/radicle-surf/blob/master/build.rs would be better. Does `proxy` have a `build.rs` file?

**Comment by FintanH** [comment]
Update on the above, I added this https://github.com/radicle-dev/radicle-surf/pull/106/files#diff-a7b0a2dee0126cddf994326e705a91eaR24-R35 and it seems to work properly. 

Just realising, however, that @sarahscott's last comment means that your test harness could be manipulating the repo. But I wanted to show you the above in case you wanted a `build.rs` for `proxy` :)

**Comment by xla** [comment]
@FintanH Thanks a lot. Will look into build.rs introduction down the road. In our current case we swap the actual librad quite a lot during testing to ensure a clean environment. We make extensive use of `tempdir` for that, which I think screws with the way the `Paths` are initialized.

**Comment by xla** [comment]
Hasn't appeared anymore, let's reopen or create a fresh one when making an appearance again.
