### ISSUE TITLE
Transaction widget global progress isn't quite correct

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#418]
When there are settled transactions in the widget, the global progress should match the average (for example) of the pending txs. However, it seems to include settled txs in the average, so it looks further along than it actually is once you open the widget.

**Comment by xla** [comment]
This was implemented that way based of the design specs, it should be validated against those and then adjusted accordingly.

**Comment by xla** [comment]
Superseeded by #572
