### ISSUE TITLE
Registration status not shown in project page

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#419]
When a project is registered, we should show its org in the header, when navigating to that project, as well as the "registered" badge. Eg.
```
[avatar] radicle / upstream [registered]
```

**Comment by xla** [comment]
To be correct: it should show the `org` or `user`, depending of the top-level entity the project is registered under.

**Comment by rudolfs** [comment]
Duplicate of: https://github.com/radicle-dev/radicle-upstream/issues/268
