### ISSUE TITLE
"New project" overlay page has no top margin

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#420]
This looks like a regression :eyes:.

<img width="70%" alt="Screenshot 2020-05-26 at 09 30 05" src="https://user-images.githubusercontent.com/158411/82872571-84e57480-9f33-11ea-895d-485bb018bf37.png">

<img width="70%" alt="Screenshot 2020-05-26 at 09 30 56" src="https://user-images.githubusercontent.com/158411/82872655-a0507f80-9f33-11ea-83e1-2ebe066ebc72.png">

**Comment by xla** [comment]
Could you provide screenshots of the actual page and maybe figma source-of-truth with margin in pixels highlighted? This will help address this swiftly.

**Comment by rudolfs** [comment]
Added screenshots.
