### ISSUE TITLE
Registered project shows up in "Add project"

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#422]
1. Add/register <project> to <org>
2. Go to <org>
3. Click "Add project"
4. <project> shows up in list of available projects to register

**Comment by cloudhead** [comment]
Note that it's perfectly valid to register a given project in multiple orgs.

**Comment by xla** [comment]
> Note that it's perfectly valid to register a given project in multiple orgs.

Is this desirable tho? What are the use-cases and application of that possibility?

**Comment by cloudhead** [comment]
I'm more worried about abuse: since the registry has no way to check that you own the project you're registering, I can easily register someone else's project.
