### ISSUE TITLE
Proxy stays alive after Upstream is terminated on macOS

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#423]
Steps to reproduce:

1. install Upstream from DMG package
2. launch Upstream
3. close Upstream window with <kbd>⌘</kbd> + <kbd>w</kbd> (but don't kill the app)
4. open a new Upstream window by clicking on the Upstream icon in the dock
5. close the app <kbd>⌘</kbd> + <kbd>q</kbd>

Expected result: Upstream is terminated and there is no `proxy` running in the background.
Actual outcome: Upstream is not running, but `proxy` is still running.

![bug](https://user-images.githubusercontent.com/158411/82894484-eff27380-9f52-11ea-94bb-129f2d78dc6b.gif)

**Comment by xla** [comment]
This sounds like the lifecycle management of the processes is tight to the initial window. Do we know how electron is setting up the process tree?

**Comment by rudolfs** [comment]
> This sounds like the lifecycle management of the processes is tight to the initial window. Do we know how electron is setting up the process tree?

Yeah, we start the proxy once we get the `ready` event from electron:
```
app.on("ready", startApp);
```

The `activate` event should only recreate the window, and not try to start the proxy again.
