### ISSUE TITLE
What to do with external links

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#428]
Now that there is basic markdown support in the app, it is possible to "inject" external links into the app.

![markdown](https://user-images.githubusercontent.com/158411/82902931-7eb9bd00-9f60-11ea-8039-1fafbcec378f.gif)

We should figure out what to do in this case as there are security implications: https://www.electronjs.org/docs/tutorial/security#isolation-for-untrusted-content.
\cc @cloudhead, @juliendonck

**Comment by juliendonck** [comment]
Yeah it's annoying this. Cause you get stuck. I saw some articles how you can just prompt a default browser to open the links. I don't know what this'll have as a security concern.

**Comment by cloudhead** [comment]
I think we should open your browser with the link.

**Comment by rudolfs** [comment]
This might be useful: https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl.
