### ISSUE TITLE
Create new project branch selector shows remote branches

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#434]
This dropdown should only contain local branches, no remote branches should be shown.

<img width="50%" alt="Screenshot 2020-05-29 at 13 18 52" src="https://user-images.githubusercontent.com/158411/83254475-17de1300-a1af-11ea-8124-77fd935233ff.png">

**Comment by cloudhead** [comment]
Is this an issue with `surf`?

**Comment by rudolfs** [comment]
It's proxy, I think I have an idea on how to fix it.
