### ISSUE TITLE
Add ability to register project under a user

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#441]
In [proxy](https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/src/registry/transaction.rs#L97), we can only register projects under orgs at the moment, but the UI implies that it's possible to register one under the current user too.

**Comment by sarahscott** [comment]
Currently proxy rejects user projects with `ERROR proxy::http::error > Rejection([Transaction(RegistryError(InexistentOrg)), MethodNotAllowed])`

**Comment by NunoAlexandre** [comment]
> Currently proxy rejects user projects with `ERROR proxy::http::error > Rejection([Transaction(RegistryError(InexistentOrg)), MethodNotAllowed])` (as it should)

@sarahscott how do you get to this response? From the UI I appear to be able to register a project under a user and I don't see any errors in the logs.

**Comment by sarahscott** [comment]
My steps to reproduce are:
- Register my handle
- Go though project registration flow
- Submit transaction

The error in the console is `Incorrect input` and in terminal it's `Rejection([Transaction(RegistryError(InexistentOrg)), MethodNotAllowed])`

**Comment by sarahscott** [comment]
I'm able to register projects under orgs without any issues

**Comment by NunoAlexandre** [comment]
Thank you, @sarahscott. I was missing the last step of actually registering the project on-chain, now I get the error :ok_hand:
