### ISSUE TITLE
Move all validation logic out of components & unit test it

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#442]
Screens or components that include validation:
- `ProjectCreation.svelte`
- `IdentityCreation/Form.svelte`
- `ProjectRegistration/RegistrationDetailsStep.svelte`
- `UserRegistration/PickHandleStep.svelte`

Also might be a good opportunity to make these flows state-based instead of `Step`'s

**Comment by MeBrei** [comment]
> Screens or components that include validation:
> 
> * `ProjectCreation.svelte`
> * `IdentityCreation/Form.svelte`

Both are renamed and the validation logic is extracted.

> * `ProjectRegistration/RegistrationDetailsStep.svelte`
> * `UserRegistration/PickHandleStep.svelte`

Both no longer exist.
