### ISSUE TITLE
Implement Peer Run Loop

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#455]
We're discarding the event loop in https://github.com/radicle-dev/radicle-upstream/pull/414. In the next steps, we should implement the handling of this loop and allow the peer to subscribe to events. There are a couple of small examples of this behaviour in `radicle-link/tests/propogation_basic.rs`.

https://github.com/radicle-dev/radicle-upstream/blob/600f29ba57f69601979402e9978b60fab8d0610e/proxy/src/coco.rs#L79-L85

Follow-up to #414

**Comment by kim** [comment]
You're aware that dropping this value means that no networking will
run at all? Wondering if, instead of a tuple, `Peer::accept` should
return an ad-hoc struct, so we could add a #[must_use]

**Comment by FintanH** [comment]
Ya, I'm aware :sweat_smile: The first phase of integrating the proxy was to get as much feature parity as possible so that we can open up the rest of the feature work. The second phase would be to start working on the networking features.

The `#[must_use]` would make sense though :ok_hand:

**Comment by xla** [comment]
We spawning the `run_loop` and at least consume some of the events superficially.
