### ISSUE TITLE
not-yet-tracked projects

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#459]
When a user wants to track a project but its repository has not been located on the network or isn't yet replicated locally, show a pending/download state:

![Screen Shot 2020-07-27 at 5 17 32 PM](https://user-images.githubusercontent.com/2712962/88604798-0f7a4b00-d02d-11ea-8d80-ae722ebbb2e6.png)

**Comment by sarahscott** [comment]
I'm having trouble imagining how a project in the discovery feed would be incomplete - if I understand correctly, the event stream will contain fully-formed entities. Perhaps this issue belongs in project replication @FintanH ?

**Comment by FintanH** [comment]
I'm not sure what this issue is outlining, can you shed some more light please?

**Comment by sarahscott** [comment]
This ticket is supposed to encompass states in which a user has started tracking a project but for whatever reason (connectivity most likely), the source code hasn't been replicated locally yet.
