### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#461]
It would be nice to have syntax highlighting for the B1.

There's https://github.com/trishume/syntect if we want to do it in the backend (which we should).

**Comment by xla** [comment]
@cloudhead While not opposed to the idea, what would be the benefits of doing it in the backend as opposed to treating it like a presentation concern (similar to how we approach markdown rendering atm)?

**Comment by rudolfs** [comment]
Was wondering about the same thing.

Seems like having it in the proxy might be more performant and more correct, but would also be harder to pull off. On the other hand, implementing it in the UI would take less time.

**Comment by cloudhead** [comment]
Benefit would be that it's a lot faster. If we do it in the frontend, large files will probably be displayed without highlighting for a couple seconds, or worse, nothing would be displayed until they're highlighted (if we do it like we do markdown).
