### ISSUE TITLE
Consider dropping duplicated types

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#464]
> > I see that we duplicate some of the registry types, such as Id and ProjectName. I followed the example for ProjectDomain, but I wonder if there's another motive to do this besides being able to derive certain traits that are not derived in the Registry?
>
> The main reason for the duplication is serialisability esp. types who want to use hex for that. Would love to avoid it by moving it upstream into the registry repo.

Quote from https://github.com/radicle-dev/radicle-upstream/pull/453#pullrequestreview-425900351

## Types

This consideration affects the following types:

### `Id`
https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L23

This types implements:

* `Display`
      https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L25

* `TryFrom<String>`
    https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L31

* `TryFrom<&str>`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L39

* Serde `Deserialize`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L48

* Serde `Serialize`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L61

### `ProjectName`
https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L23

This types implements:

* `Display`
      https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L74

* `TryFrom<String>`
    https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L104

* `TryFrom<&str>`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L112

* Serde `Deserialize`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L80

* Serde `Serialize`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L95

### `ProjectDomain`

Introduced in #453.
This types implements:

* Serde `Deserialize`

* Serde `Serialize`

* `Into<Id>`

## Consideration

I don't see any implementation being too `upstream`-related, so it seems like a good idea to move these to the `registry`, resulting in dropping these types from this module, where the respective wrapped types should be re-exported.

@xla do you have more to add?

**Comment by xla** [comment]
Looks good, would be great to get this reflected in the registry repo.

**Comment by NunoAlexandre** [comment]
@xla actually, `Hash` is a struct only useful in the upstream, it has no application in the registry, so I am removing it to the list and include `ProjectDomain`, introduced in #453.

**Comment by xla** [comment]
@NunoAlexandre `Hash` is just as important as the others, it should be addressed in the context as well.

**Comment by NunoAlexandre** [comment]
Alright, closing this. All sensible type trait impl were moved to the registry #470. Hash was kept as is since moving it to the registry introduced a considerable overhead for no value #493.
