### ISSUE TITLE
Make `http > org > Project` more general

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#465]
> >We currently have a struct Project defined in http > org. I made the code make it right so to keep this setup but it seems to me that this struct can better be generalized to work for both user and org?
>
> That seems adequate. It probably shouldn't live in http::org at all then, which one are you referring to?

Quoted from https://github.com/radicle-dev/radicle-upstream/pull/453#pullrequestreview-425900351

### Problem

Currently, we have a `struct Project` defined in `http > org.rs` that is meant to only work in the context of orgs as project domains:

https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/http/org.rs#L390-L402

### Improvement

I don't think there is value in having this dedicated `Project` struct.

Instead, we should:

- have a more general `Project` struct that has a `ProjectDomain` field. 
- have a more general, dry `get_projects` method that also operates on `ProjectDomain`

By doing so, we have operational infrastructure for both user and org regarding projects.
These changes could be moved into `http > project.rs`.

@xla thoughts?

**Comment by xla** [comment]
> By doing so, we have operational infrastructure for both user and org regarding projects.
> These changes could be moved into `http > project.rs`.

This stands in opposition to the proposal to have a projects endpoint per entity (org, user) - which seems like the more straightforward way to model the API. I agree tho that the `Project` in `http::org` should be dropped/moved. The issue we have here is that we have multiple understandings of what a project is: registry, coco and upstream itself. And we need different data to be available to populate either of these. For now we can move the one existing in `http::org` into the `registry` model and use that as the response for both org and user project listing queries. Down the road we attempt a larger merge across all domains.

**Comment by NunoAlexandre** [comment]
> > By doing so, we have operational infrastructure for both user and org regarding projects.
> > These changes could be moved into `http > project.rs`.
> 
> This stands in opposition to the proposal to have a projects endpoint per entity (org, user) - which seems like the more straightforward way to model the API.

That's right. Though I like the sound of "orgs projects register" and "user projects register", when regarding the registry projects this approach seems to only add duplication. Whenever a new domain is introduced, a new endpoint would need to be created, where that would be, type-wise, completely unnecessary.

> The issue we have here is that we have multiple understandings of what a project is: registry, coco and upstream itself. And we need different data to be available to populate either of these.

Indeed! Though that's a different concern than the issue above regarding the endpoints. Or not?

> For now we can move the one existing in `http::org` into the `registry` model and use that as the response for both org and user project listing queries.

Sounds good!

> Down the road we attempt a larger merge across all domains.

How do you mean?

**Comment by xla** [comment]
> That's right. Though I like the sound of "orgs projects register" and "user projects register", when regarding the registry projects this approach seems to only add duplication. Whenever a new domain is introduced, a new endpoint would need to be created, where that would be, type-wise, completely unnecessary.

Maybe I wasn't explicit, when I talk about endpoints I mean the http API, these can still use a single method on the `registry::Registry`. The concern I raise is about ergonomics of the API used by the ui. We don't need to mirror those in the `registry::Client` trait.

> Indeed! Though that's a different concern than the issue above regarding the endpoints. Or not?

It's the reason we have multiple materialisations of Project in the codebase and I expanded on it to give context for my thinking.

> How do you mean?

In direct relation to the comment about multiple understandings of project, as in different domains.

**Comment by xla** [comment]
Addressed in #597
