### ISSUE TITLE
ui: Display registered (user) projects badge

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#469]
With #453, we can effectively register a project under a user as well as under an org.

When a project is registered under an org, the registration badge for said project. However, the same does not happen for projects listed under a user that are in fact registered in the registry.

It seems like `project.registration`, a property used to define the state of the badge in this context, is always null. We need to check why that is and fix the ux issue.

Edit: in `proxy > http > projects > fn list`, `registration` is always set to `None`.
https://github.com/radicle-dev/radicle-upstream/blob/32c8c25c0f1908c1f3e74d2226cd931ca2f809a7/proxy/src/http/project.rs#L179

Its type is `Registration`, which is a duplication of `ProjectDomain`:

https://github.com/radicle-dev/radicle-upstream/blob/32c8c25c0f1908c1f3e74d2226cd931ca2f809a7/proxy/src/project.rs#L50-L57

### To be done

- Check whether the registry has any project with the given name under the handle the user is registered with if any. (I can't think of any other way, for now. suggestions are welcome)

- Replace `Registration` with `ProjectDomain`

- Ensure the registration badge is shown accordingly in the UI

**Comment by NunoAlexandre** [comment]
For the record, I had a call with @xla regarding the deeper implications of this feature. 

FWW, my idea here was:

1. pass the registry user handle, if any, from the UI when requesting the list of coco projects from proxy
    This would require either passing this value as a query string param or make the request POST to be able to pass a payload

2. in proxy (first code block shared above), for each coco project, query the `registry` for a project with said user handle and with the project name. 
   If it exists, we know its registered and we would build the appropriate `registration` value that would then be consumed by the UI, showing the registration badge as expected.

@xla has mentioned work is on the line around this function and around two-way attestation, which very much touches this matter, so I better leave this one to those champions.

**Comment by cloudhead** [comment]
Another aspect of this is showing the org and badge in the top-bar when navigating to the project. Eg. it should show `radicle / radicle.xyz [badge]` for a registered project.

**Comment by xla** [comment]
Registry functionality has been removed.
