### ISSUE TITLE
Cache transaction deposits along with transaction fee

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#473]
#457 implements transaction fees and deposits. As registration deposits weren't implemented on the Registry side we only cache the transaction fee on disk.

However, there is an edge case where incorrect deposit fees would be shown in the UI. This could happen if a user has some old transactions cached and we would update the registration deposits with an app upgrade. In this case the old transactions would show the new deposit values.

This could be fixed by making the registration deposit part of the transaction and writing it to disk along the chosen transaction fee.

**Comment by xla** [comment]
Registry functionality has been removed.
