### ISSUE TITLE
Improve API ergonomics regarding project registration

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#474]
In #453 we introduce the ability to register a project under a user in addition to the ability to register a project under an org.

Such a change has led @xla to suggest improving the API ergonomics regarding project registration.

@xla, my understanding of your suggestion is that now we need the API request is, in pseudo-code:

```
POST /projects/register 
    {   domain_type: Org|User, 
        domainId: a1b2, 
        projectName: upstream, 
        .. 
    }
```

So when you speak about bad ergonomics here, you might be referring to having to pass the `domainType` and `domainId`, where those are already known from the context of the call site triggering this request.

The idea would, therefore, to have:

A dedicated `orgs` endpoint:

```
POST /orgs/{org_id}/projects/register 
    {
        projectName: upstream, 
        .. 
    }
```

and a dedicated `users` endpoint:

```
POST /users/{user_id}/projects/register 
    {
        projectName: upstream, 
        .. 
    }
```

For both of these endpoints, we could then build the respective `ProjectDomain`, where the variant is known from the context and the id is obtained from the URI.

### Open questions

**Q1**: Is that the idea?
**Q2**: If so, to help me understand your point of view, can you explain how you find the suggestion a solution with better ergonomics?
   I wonder since this approach introduces duplication, where each project domain entity will need to implement the same endpoint for project registration, build its `ProjectDomain` variant, call the same handler in the `registry`. That duplication seems to introduce maintenance efforts that don't seem to outweigh an issue with ergonimics (again, as far as I see).

**Comment by xla** [comment]
While duplication is a concern, it's in my view second to the correct hierarchy. If you look at the API as a representation of the entity tree and locations of resources (those being, orgs, users and projects under each). Utilizing HTTPs nouns and verbs, you can disambiguate operations on the entity tree. A `POST /orgs/<id>/projects/<name>` is distinct from a `POST /users/<id>/projects/<name>` and more clearly communicate the intend and rely less on information carried in the payload.  With that proposal the only thing the body needs to carry is the additional metadata stored for a project. In turn this makes it clear where in the API to query for the projects of an org and where to go for a user. And reflects the entity layout and resource locations.

**Comment by NunoAlexandre** [comment]
Thanks for explaining, @xla.

I now understand where you are coming from and I get your point. What I see here is that in this trade-off, one the one hand we have a concrete concern, duplication, that aids maintenance considerably, and on the other hand we have a principle.

> That means (de)serialisation is simplified and less code has to be built around that.

That is true for each individual handler, but not really true overall, since having a dedicated endpoint per entity comes with its overhead as well.

 ------

Say we go ahead with this, the API will appear inconsistency since some project-related endpoints will still live on its own, such as `POST projects` and `GET projects`. These are different "projects", but it might be a good idea making that more explicit. A start could be in addressing the registry projects as `RegistryProject` or `RegisteredProject`. I am not sure how we could make that clear from the API standpoint, though.

All in all, I still think we are preferring an ideal over practicality, especially given the stage we are in, but your point is now clear and I appreciate that.
