### ISSUE TITLE
Errors banners don't stack properly visually

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#486]
When there's multiple errors, they both get the same size. It's expected that they each have their own size and are centred.

<img width="458" alt="Screenshot 2020-06-12 at 17 03 48" src="https://user-images.githubusercontent.com/2326909/84516888-bb124a80-acce-11ea-9192-fc3eb8b313be.png">

**Comment by juliendonck** [comment]
Is there an easy way to create some fake errors so I can fix this? @rudolfs @MeBrei @sarahscott?

**Comment by xla** [comment]
Helped @juliendonck IRL.
