### ISSUE TITLE
separate clippy step

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#500]
Clippy recompiles a lot of code when called, so it's a good candidate for running in parallel in the build steps.

We run into some issues, however:
```
Status: Image is up to date for gcr.io/opensourcecoin/radicle-upstream:0.4.0
gcr.io/opensourcecoin/radicle-upstream:0.4.0
docker: Error response from daemon: error while mounting volume '': File exists (os error 17).
```

It may be that there is contention for some shared state as @xla said [here](https://github.com/radicle-dev/radicle-upstream/pull/497#discussion_r440622274).

**Comment by xla** [comment]
This has not been addressed, so why was it closed without providing further context?

**Comment by FintanH** [comment]
I advised to close it. My thinking was that it's not a perceived issue right now and was only adding noise to the backlog. Do you think it's worth keeping open?

**Comment by xla** [comment]
The build times for Upstream CI jobs are significant, anything which would improve on the speed of that feedback cycle should be taken seriously to improve DX on this repository.

**Comment by FintanH** [comment]
Fair point. I'll re-open and we can look into it again

**Comment by geigerzaehler** [comment]
Since we introduced the fast key store in #1969 clippy only takes 8 seconds. This doesn’t warrant a separate step.
