### ISSUE TITLE
Rename 'protocol' to 'registry'

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#506]
In _some_ places the `registry` is aliased to `protocol`. In others, it's `registry`.

I find `protocol` confusing as that's how I think of `CoCo`.

I suggest we rename all `protocol` alias to `registry` to have it consistent and avoid introducing another name to the registry.

**Comment by xla** [comment]
We refer to `protocol` as an alias to `radicle-regisrtry-client` and only inside of `registry` module, which to the rest of the codebase is known as `registry`. Both `coco` and `registry` offer a protocol and operation of a network. From the upstream perspective we integrate with two protocols. If we have places where we leak the alias of protocol outside of the `registry` module we should address that, otherwise I think this naming is sound.

**Comment by NunoAlexandre** [comment]
I don't follow your reasoning here. If the alias to `protocol` is to support the fact that the upstream integrates with two protocols, then that alias should be used in the rest of the codebase, not within `registry`. Being inside `registry` and calling the underlying sdk `protocol` really gets in the way to me and I don't see it delivering any value to the project.

**Comment by geigerzaehler** [comment]
My two cents: As a casual reader of the code and contributor to the project I find the current naming creates some mental overhead. I understand the reasoning behind this but I would prefer being more straightforward and transparent in the naming and not rely on additional concepts. This would make the code easier to understand and choosing names in contributions would be more straightforward

**Comment by kim** [comment]
A very undervalued language feature seems to be module namespacing: `registry::protocol`, `link::protocol`. Using qualified names by default makes a lot of naming decisions go away (and -discussions unnecessary). Think of the idiomatic `my::Error`, `your::Error`, for example.

**Comment by NunoAlexandre** [comment]
> A very undervalued language feature seems to be module namespacing: `registry::protocol`, `link::protocol`. Using qualified names by default makes a lot of naming decisions go away (and -discussions unnecessary). Think of the idiomatic `my::Error`, `your::Error`, for example.

I agree that it is a great feature. However, as you said, that's about _module_ or _type_ namespacing, not about renaming crates.

**Comment by NunoAlexandre** [comment]
> We refer to `protocol` as an alias to `radicle-regisrtry-client` and only inside of `registry` module, which to the rest of the codebase is known as `registry`. Both `coco` and `registry` offer a protocol and operation of a network. From the upstream perspective we integrate with two protocols. If we have places where we leak the alias of protocol outside of the `registry` module we should address that, otherwise I think this naming is sound.

For the record, I got what you meant, sorry for my misunderstanding. Closing this, for now, we have bigger fish to fry.
