### ISSUE TITLE
Project creation feels slow when adding a large existing project

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#512]
When adding a large project, there's a weird break after I click the button. See gif

![slow-project-creation](https://user-images.githubusercontent.com/2326909/85044405-db8a4b00-b18d-11ea-9ca6-02cf3af6b0c7.gif)

**Comment by rudolfs** [comment]
Refs: https://github.com/radicle-dev/radicle-upstream/issues/912.
