### ISSUE TITLE
Emoji avatar should appear when creating an identity

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#531]
When typing in a handle upon first launch, the avatar should appear inside the field as you type. This functionality already exists in the org registration in the "org name" field.
![image](https://user-images.githubusercontent.com/4406983/85268058-4f6e7100-b476-11ea-80a9-9f8784e4ff2b.png)

---

Example in the org name field:
![image](https://user-images.githubusercontent.com/4406983/85277845-57cda880-b484-11ea-9e70-975b657412cf.png)

**Comment by rudolfs** [comment]
I believe this won't be possible, because we base the identity avatar on the created ID and not the user handle. We get the ID only after we create the identity.

**Comment by xla** [comment]
That's correct, the first possible point is the identity card in the next step. Please reopen if we need to address this in other ways.

**Comment by brandonhaslegs** [comment]
In that case, we should make this consistent and remove it from the field in org registration. We should be consistent with how we present avatar generation. Doesn't make sense to make it invisible when generating a user handle, but then make it visible when generating an org avatar.

**Comment by xla** [comment]
Follow-up in #553
