### ISSUE TITLE
Update empty page template

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#533]
### Global template updates
- [x] Change button to a "primary" (pink) button
- [x] Add a secondary link option under the button instead of a second button
- [x] Change illustration to be a 48x48 SVG placeholder.

---

### Empty Profile
![image](https://user-images.githubusercontent.com/4406983/85280525-949b9e80-b488-11ea-86d8-5f45dde05e6c.png)
- [x] Remove "Register so your friends can find you! [Register handle]" from empty profile state
- [x] Change text to "There’s nothing here yet, get started by starting your first project."
- [x] Change button text to "Start your first project"
- [x] Add "Or register your handle" as the secondary link
- [x] illustration should be [this potted plant illustration](https://www.dropbox.com/s/o343a2dfvsrtoqr/empty-profile.svg?dl=0) which is not a standard emoji, it's a mashup I made specifically for this context.

---

### Other empty states
- [ ] [Revision empty state](https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=9726%3A545)
- [x] [Issues empty state](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8F%97-Components?node-id=1983%3A0)
- [ ] [Registered profile empty state](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8F%97-Components?node-id=1983%3A0)
- [ ] [Untracked profile empty state](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8F%97-Components?node-id=1983%3A0)

**Comment by juliendonck** [comment]
related to #327

**Comment by juliendonck** [comment]
@brandonhaslegs do you have one of these for orgs?

**Comment by brandonhaslegs** [comment]
> @brandonhaslegs do you have one of these for orgs?

![image](https://user-images.githubusercontent.com/4406983/85293826-2cf04e00-b49e-11ea-9620-31a005498ab3.png)
Same as empty user profile but without the "Or register your handle" part.
