### ISSUE TITLE
Change modal style from full screen to "floating" style

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#542]
Modals should be floating instead of full screen.

- [ ] 600px width
- [ ] vertically and horizontally centered
- [ ] animated in from off screen from the bottom, animate out off screen to the bottom. [Prototype here](https://www.figma.com/proto/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=12935%3A698&viewport=2481%2C1447%2C0.5&scaling=min-zoom)
- [ ] close by clicking outside
- [ ] transparent background color is `rgba(02, 12, 21, 0.75)` (This should be a hard coded color value, as it does not change from dark to light mode)
- [ ] X button in the top right should be removed

![image](https://user-images.githubusercontent.com/4406983/85311475-c840ed80-b4b5-11ea-9527-d9219dcdd534.png)

**Comment by rudolfs** [comment]
Whoops, wrong button...

**Comment by juliendonck** [comment]
This is the case as far as the current feature set of the app is concerned.
