### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#544]
Currently `src/http/error.rs` does not match all errors from `src/error.rs` explicitly and returns unspecific error messages for the API requests.
In order to improve error handling in the frontend we need to return more specific errors with informative messages. Once this is in place, we can make sure that the ui reacts consistently to all variants.

This will also prepare moving the validations into the proxy #166.

**Comment by rudolfs** [comment]
@geigerzaehler Is this still relevant after stuff got moved back to link and surf?

**Comment by geigerzaehler** [comment]
We now include the error code and message from the proxy in the exception.
