### ISSUE TITLE
Derive TS definitions for error variants

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#545]
To make error handling (#544) more adaptable, we should use a macro to derive the typescript definitions of the error variants. The resulting `.d.ts. file can then directly be used in the ui to handle the errors.

example for a macro: https://crates.io/crates/typescript-definitions

Depends on #544.

**Comment by geigerzaehler** [comment]
The future of the API and the RPC mechanism is now very much in the air. This would also needs some discussion to determine the effort.
