### ISSUE TITLE
Remove transaction center when all transactions are settled.

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#554]
Transaction center can be dismissed after all transactions have been settled, with a 60 sec delay.

<img width="385" alt="Screenshot 2020-06-23 at 15 00 45" src="https://user-images.githubusercontent.com/2326909/85406597-52df2680-b562-11ea-9b0b-6260b56a504a.png">

**Comment by xla** [comment]
> Transaction center can be dismissed after all transactions have been settled, with a 60 delay.

Is this delay in seconds? Will there be a way to see the list anyway through other means?

**Comment by juliendonck** [comment]
Yeah on the wallet page

**Comment by xla** [comment]
Registry functionality has been removed.
