### ISSUE TITLE
Add feature flags in UI

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#558]
Certain features won't be available in B1, these should be hidden by feature flags, or greyed out. They include:

- [x] Revisions (top-bar and overflow menu)
- [x] Issues (top-bar and overflow menu)
- [x] Remove member from org (overflow menu)
- [x] Go to member profile (overflow menu)
- [x] Org fund tab
- [x] Project support button
- [x] Track button *number*

**Comment by xla** [comment]
We could also just delete these navigations, if they are leading nowhere.

**Comment by cloudhead** [comment]
Yup, as long as we don't need to redo any work when we need them back.

**Comment by FintanH** [comment]
I think adding feature flags will make sense for future development in general. We may want to release features as we work on others, and so hiding the WIP features would be desirable.

**Comment by xla** [comment]
No doubt about it, but let's implement them when the need arises.

**Comment by juliendonck** [comment]
Possible solution, only show certain things in `dev mode`

**Comment by MeBrei** [comment]
If the `Org fund` tab is hidden, how will an org receive funds in B1 for registering a project or a member?
