### ISSUE TITLE
Remove avatar from commit author

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#559]
We currently show some generated avatar next to the commit author. We should remove this until we are able to correlate commit users with radicle users.

**Comment by juliendonck** [comment]
I don't see these 
<img width="513" alt="Screenshot 2020-06-24 at 14 52 21" src="https://user-images.githubusercontent.com/2326909/85559774-50480400-b62a-11ea-9683-6c44b567e82b.png">

**Comment by cloudhead** [comment]
Ah they are in the commit history, and file view.
