### ISSUE TITLE
Project Discovery

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#568]
This is the tracking issue for all things Project Discovery.

* [ ] Event stream format for trackable projects
  * [ ] Fold function that converts the last N stream items into a fixed set of trackable projects
  * [ ] Integration of event stream entity type into `radicle-link`
* [ ] Create discovery page in app
  * [ ] Show available projects to track
  * [ ] Implement working track button
* [ ] Create menu or sidebar button to navigate to discovery page
* [ ] Add settings in Settings page, relating to discovery
  * [ ] Textarea that simply lists seed hosts

**Comment by FintanH** [comment]
Should we avoid tickets like this and instead add these sub-points to a board as separate issues?

**Comment by xla** [comment]
> Should we avoid tickets like this and instead add these sub-points to a board as separate issues?

Highly in favour!

**Comment by cloudhead** [comment]
I think having both makes the most sense. This is just an overview of the work, and ensures we haven't forgotten anything.

**Comment by FintanH** [comment]
My thinking is that it's easier to link work in progress to issues and this ticket doesn't become some kind of weird catch-all. Also the conversations will be focused on the exact issue. Having both is not the end of the world either :)

**Comment by xla** [comment]
As we have wroked with tracking issues in the past, they excatly have this tendency @FintanH pointed out, to become tedious to maintain and to reference properly. It also makes it easier to automate issue closing with single issue per work unit and PRs referencing them properly and also not accidentally closing the tracking one.

**Comment by cloudhead** [comment]
Cool, well feel free to create the issues and then I'll close this.

**Comment by FintanH** [comment]
#588 - #594
