### ISSUE TITLE
Have a better way of handling overflows on repo/branch selector

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#570]
Perhaps we could for example hide the user handle and only show the avatar and branch name, when the dropdown isn't expanded. In addition, we probably don't want to wrap the branch name to the next line?

![2020-06-24-114208_507x455_scrot](https://user-images.githubusercontent.com/40774/85532184-c723d380-b60f-11ea-8f2d-6a3c64f0963c.png)

Something like this could work, when the dropdown is collapsed (notice the handle is no longer there):

![2020-06-24-114722_383x219_scrot](https://user-images.githubusercontent.com/40774/85533065-7e204f00-b610-11ea-863c-ebff0d2e0d43.png)

**Comment by juliendonck** [comment]
I think that's a good solution

**Comment by rudolfs** [comment]
<img width="306" alt="Screenshot 2020-06-24 at 14 15 00" src="https://user-images.githubusercontent.com/158411/85554360-1cb6ab00-b625-11ea-87d0-d7b629a8647c.png">

I already worked on it a bit in my feature branch: https://github.com/radicle-dev/radicle-upstream/pull/510/commits/9204309775a832e49c0ac6ba30819cf4f37ea51a.

**Comment by cloudhead** [comment]
> this

Yes, this is broken in master
