### ISSUE TITLE
Make responsiveness consistent

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#577]
### Ideally I'd like to pair with you on this just to make sure it all looks good and see how it affects different pages.

- [x] change `var(--content-max-width)` to `90rem` (currently it's 72rem)
- [x] change `issue-card` div's max width to `var(--content-max-width)`
- [x] change `content` div on the project page to `var(--content-max-width)` (currently it's 100%) and center the content
- [x] change the `commit-page` (commit details page) to max width `max-width: var(--content-max-width);`  and center the content
- [x] change the `commits-page` (commit overview page) to max width `max-width: var(--content-max-width);`  and center the content

**Comment by sarahscott** [comment]
Related to https://github.com/radicle-dev/radicle-upstream/issues/304; will close that one in favor of this

**Comment by xla** [comment]
@brandonhaslegs All points are checked off, can this be closed?
