### ISSUE TITLE
Transaction list updates

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#578]
#### Change text on transaction statuses to be less jargonny
- [ ] change "Settled" to "Completed"
- [ ] change "Pending" to "In progress"
- [ ] change "Settled" to "Completed"
- [ ] change "Insufficient balance" to "Not enough funds"
---
- [x] change `border-radius` to `8px`
- [x] change `border-color` to `foreground-level-2`
- [x] change the `border-color` between rows to `foreground-level-2`
- [x] remove the `background-color` from the expanded transactions list
- [x] change the hover state `background-color` on the transaction list items to `foreground-level-1`
![image](https://user-images.githubusercontent.com/4406983/85568281-d61b7d80-b631-11ea-9cc3-5927f44c4094.png)

---
#### Animation update
- [ ] similar to our other dropdowns, when the list is expanded, hide the "Summary" row when the list is expanded. [Here's a prototype](https://www.figma.com/proto/HV5YDSx0FWFLs4qCSAiTL9/Transaction-expand-animation?node-id=1%3A72&viewport=318%2C696%2C0.5&scaling=min-zoom) of what I mean 
![image](https://user-images.githubusercontent.com/4406983/85568341-e4699980-b631-11ea-829b-abb04cd34a08.png)

**Comment by juliendonck** [comment]
related to #554 & #572
