### ISSUE TITLE
Update transaction banners to have only one color

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#579]
### 😰 Before:
White icon + black text is wacko
![image](https://user-images.githubusercontent.com/4406983/85569980-4971bf00-b633-11ea-953f-c831cc3239d8.png)

---

### 💁‍♀️ After:
![image](https://user-images.githubusercontent.com/4406983/85569909-3b23a300-b633-11ea-80ce-4402308feae0.png)
- [ ] change text style to `p.bold`
- [ ] change color to `background`

**Comment by juliendonck** [comment]
@brandonhaslegs do we still have this after the transaction view update?
<img width="551" alt="Screenshot 2020-06-24 at 18 07 40" src="https://user-images.githubusercontent.com/2326909/85591447-99f21800-b645-11ea-8ef4-b7ed85e4f29e.png">

**Comment by brandonhaslegs** [comment]
Nope 🤙
