### ISSUE TITLE
Create Project New or Existing

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#599]
As far as I'm aware our `create` for a project does not have the option of creating a new or an existing project, and where the `Path` is for either of those options. Creating a `rad` remote https://github.com/radicle-dev/radicle-link/issues/219 is also relevant to setting up these repositories.

**Comment by xla** [comment]
This is confusing, are you referring to project creation for existing **repositories**?

**Comment by FintanH** [comment]
Sorry, I should be more clear.

When we want to *create a working copy* in Upstream and add it to the rad monorepo, I imagine two cases:
* The working copy exists in your filesystem.
* The working copy doesn't exist in your filesystem so we want to create it at a desired `Path`.

We can then link the working copy and the monorepo representation.

Is that clearer?

**Comment by xla** [comment]
Creating a new project from an existing repository and creating one from an empty directory, which will be initialised as a git repo in the process, is both working. The use of project, working copy and creation in the monorepo is not clear here. From what I understand a project is an initialised entity in the monorepo, a working copy is the git cloned checkout of the source tree. And then there is the case where a project is created from an existing working copy/so far referred as repository. Maybe we can clarify further what flows we are referring to in this issue.

**Comment by FintanH** [comment]
Ya that makes sense to me! Part of this was making sure I track the work whether it's done or not :) I'll have a look at the code to ensure that what I was thinking is there. If not, then we can have a chitty-chat :cat:
