### ISSUE TITLE
Ask for a URN

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#600]
The integration work for https://github.com/radicle-dev/radicle-link/issues/221

**Comment by FintanH** [comment]
One point here is that asking for a `RadUrn`'s entity isn't guaranteed to complete in any deterministic amount of time. We may have to keep track of the `RadUrn` we asked for and if we made any progress on this. I'm thinking some kind of request queue to see if a request was successful or still in progress.

This would allow the UI to at least say that it's still waiting on the request.

We may also want to timeout on a request.

**Comment by FintanH** [comment]
I think it would be good to keep this issue scoped to having the [`providers`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/net/peer.rs#L182-L193) function added to the `Api` struct, along with a simple test case to confirm it works.

The hardest part of this will probably be the test where we've seen funkiness when we're trying to statically connect to another peer via adding them as a seed.

**Comment by NunoAlexandre** [comment]
>The hardest part of this will probably be the test where we've seen funkiness when we're trying to statically connect to another peer via adding them as a seed.

Thanks for this info. Is there a place where I can learn more about this experience or how to reproduce it?

**Comment by FintanH** [comment]
My brain or trying to write a test 😅 I can give you a run down, but if you could try link up the function call and maybe prep a test then we can go from there

**Comment by NunoAlexandre** [comment]
> I think it would be good to keep this issue scoped to having the [`providers`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/net/peer.rs#L182-L193) function added to the `Api` struct, along with a simple test case to confirm it works.

The [`providers`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/net/peer.rs#L182-L193) function is already part of the `PeerApi`, what am I missing? :thinking:

**Comment by NunoAlexandre** [comment]
Ah wait, we are in the upstream :exploding_head: ahah sorry!

**Comment by xla** [comment]
:seedling: :seedling: :seedling:
