### ISSUE TITLE
Create Working Copy

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#601]
Integration endpoint of https://github.com/radicle-dev/radicle-link/issues/138. If there is a project in the monorepo that doesn't have a working copy then we should be able to create one.

How will we know if there is a working copy or not or do we even care and it should always be possible? :thinking:

**Comment by rudolfs** [comment]
At what point, starting from clicking the "Track" button on a project, will start showing the "checkout" button in the UI?

**Comment by rudolfs** [comment]
Would the working copy be per project or per peer in the project?

**Comment by rudolfs** [comment]
The UI will provide a path where the checkout should happen.
If possible we should provide back a response upon successful checkout.

<img width="227" alt="Screenshot 2020-06-26 at 17 11 26" src="https://user-images.githubusercontent.com/158411/85872654-52e45e00-b7d0-11ea-8105-38ecc97d7545.png">
<img width="336" alt="Screenshot 2020-06-26 at 17 11 30" src="https://user-images.githubusercontent.com/158411/85872659-537cf480-b7d0-11ea-861a-e79f8f630bb9.png">

**Comment by FintanH** [comment]
> At what point, starting from clicking the "Track" button on a project, will start showing the "checkout" button in the UI?

As soon as there's a copy of the project in the monorepo, I would say.

>  Would the working copy be per project or per peer in the project?

Per project. You have your local view and every peer would look like another server essentially. You could checkout their branches as a local copy and edit them, but they would have to choose to integrate those changes once you announce them. Does that make sense?

**Comment by rudolfs** [comment]
> Does that make sense?

👍
