### ISSUE TITLE
discovery: Proxy API

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#613]
An API the frontend can query to get a set of unique projects with metadata, to be displayed in #591 

This API should be high-level, and expose a deduplicated, ordered set with all the necessary metadata embedded within.

**Comment by sarahscott** [comment]
Note: once this API is integrated with the existing UI, what should happen when a user clicks on an org they are not a part of? Will there be a public-facing org page (similar to viewing another user's profile) or are some orgs completely private for non-members?

cc @cloudhead @juliendonck

**Comment by cloudhead** [comment]
So I think the easiest is to just not link them if they aren't "known", ie. in your sidebar already. We can revisit the question when we tackle org public profiles.
