### ISSUE TITLE
Handle repository with no commits gracefully

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#614]
If you try to add an existing repository, but that repository has no commits, you are redirected to the `NotFound` page, and get an error message. The logs are:

```
 ERROR proxy::http::error > Rejection(Git(Git(Error { code: -3, klass: 4, message: "revspec \'master\' not found" })))
 INFO  proxy::http        > "GET /v1/source/local-state//home/cloudhead/src/cloudhead/popol HTTP/1.1" 400 7.572776ms
 ERROR proxy::coco::peer  > error while trying to find default branch: Error { code: -3, klass: 4, message: "no reference found for shorthand \'master\'" }
 ERROR proxy::http::error > Rejection([MethodNotAllowed, DefaultBranchMissing("hwd1yreyo98cstjfi8fo4fpq15g6jb3p3anbdttxfj5uu3aygn6bakgd75y", "master"), MethodNotAllowed])
```

Then, when the user profile is loaded, we get:
```
 ERROR proxy::http::error > Rejection([MethodNotAllowed, Git(NamespaceRevParseFailure { namespace: Namespace { values: ["hwd1yreyo98cstjfi8fo4fpq15g6jb3p3anbdttxfj5uu3aygn6bakgd75y"] }, rev: "master" })])
```

Ideally, we should handle this case in the creation form.

**Comment by rudolfs** [comment]
Refs: https://github.com/radicle-dev/radicle-upstream/issues/912.

**Comment by rudolfs** [comment]
Steps to repro:
1. `mkdir test`
2. `cd test git init`
3. create project in upstream

![Screen Shot 2020-09-16 at 4 27 15 PM](https://user-images.githubusercontent.com/18275452/93354193-06437880-f83d-11ea-8d67-fb8160f5fedc.png)
![Screen Shot 2020-09-16 at 4 54 11 PM](https://user-images.githubusercontent.com/18275452/93354479-54f11280-f83d-11ea-9339-90a11982be8f.png)
