### ISSUE TITLE
Empty state behaves incorrect on short viewports

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#631]
When making the viewport shorter, the button and the SVG icon shrink in a weird way. Probably because we're using some calc of the viewport height to determine the size. The height should be based on something more dynamic than just `calc(100vh - var(--bigheader-height))`

![86465219-84f64280-bd31-11ea-8bc8-a2d7c387c0a9](https://user-images.githubusercontent.com/4406983/86466145-698c3700-bd33-11ea-8658-96028881aed8.gif)

**Comment by xla** [comment]
Follow-up to #630
