### ISSUE TITLE
Make it possible to change unregistered handle

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#635]
1. From the profile, you can click on the handle to change it.
2. When handle is changed, show a notification that says "Done, your handle was changed to [new handle]."

![image](https://user-images.githubusercontent.com/4406983/86583222-2f18d900-bf83-11ea-8cbc-68b3fc9a34b3.png)

[Figma design here.](https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=13493%3A0)

**Comment by NunoAlexandre** [comment]
That's a kind, handsome, and - most importantly - humble guy right there :ok_hand:

**Comment by FintanH** [comment]
> That's a kind, handsome, and - most importantly - humble guy right there

The face of Radicle
