### ISSUE TITLE
Reformat and standardize all RadUrns

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#643]
## To do
Make the design match [this component](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8F%97-Components?node-id=3372%3A10405).

<img width="216" alt="Screenshot 2020-07-09 at 15 15 04" src="https://user-images.githubusercontent.com/2326909/87044568-01d46100-c1f7-11ea-82f0-10b0a6cb04ec.png">

- [x] Standardize the component across the app so it always looks the same
- [x] the RadID should show the first 6 and last 6 characters and truncate from in the middle
- [x] always has a background
- [x] always has rounded corners
- [x] same font size and colors
- [x] always copyable on hover

---

## Places where RadID is displayed
- [x] Clone overlay
![image](https://user-images.githubusercontent.com/4406983/87038220-b9647580-c1ed-11ea-8bbe-f0549606109f.png)
- [x] Project ID
![image](https://user-images.githubusercontent.com/4406983/87038336-dd27bb80-c1ed-11ea-8e90-130eea78aabf.png)
- [x] Profile ID
![image](https://user-images.githubusercontent.com/4406983/87038357-e4e76000-c1ed-11ea-8c7d-5411648ff9b8.png)
- [x] Discover page project tiles
![image](https://user-images.githubusercontent.com/4406983/87038429-01839800-c1ee-11ea-9b44-470f470f318a.png)
- [x] Org ID
![image](https://user-images.githubusercontent.com/4406983/87038454-0b0d0000-c1ee-11ea-9da3-11745a525442.png)
- [x] Profile overflow ••• menu
![image](https://user-images.githubusercontent.com/4406983/87038613-4ad3e780-c1ee-11ea-9894-52ea455c828b.png)
- [x] Project overflow ••• menu
![image](https://user-images.githubusercontent.com/4406983/87038691-69d27980-c1ee-11ea-905b-3e95841bb7a9.png)
- [x] Transaction id
![image](https://user-images.githubusercontent.com/4406983/87038867-a1412600-c1ee-11ea-8519-1232f5cf16d6.png)
- [x] Wallet send screen
![image](https://user-images.githubusercontent.com/4406983/87042574-2549dc80-c1f4-11ea-87cd-d0555e6d3950.png)

**Comment by cloudhead** [comment]
Would be good to know also what parts can be ommitted, and whether we can encode the `git` part somehow. Otherwise it'll be weird. Another option would be to hide `rad:git`, but include it on copy. Kind of like how chrome doesn't show `http://`, but when you copy, it includes it.

**Comment by cloudhead** [comment]
Another thing that would be nice is that the Urn expands on hover.

**Comment by FintanH** [comment]
So... The shareable identifiers are wrong I think. We're currently doing them as `<handle>@<rad_urn>` they _should_ be `<handle>@<peer_id>`. I'm actually fixing this in https://github.com/radicle-dev/radicle-upstream/pull/654/files

**Comment by brandonhaslegs** [comment]
BTW since the handle doesn't identify the user, can we just remove the `<handle>@` part of it?

**Comment by FintanH** [comment]
Sorry, I was confused above. Met with @cloudhead and @rudolfs. What I said above was for repository selection.

> BTW since the handle doesn't identify the user, can we just remove the <handle>@ part of it?

The handle doesn't identify the user but it is a human-readable indicator. For example in the repository selector, I wouldn't have any idea of who's `PeerId`s are whose. Unless I memorised them :sweat_smile:

**Comment by brandonhaslegs** [comment]
Oh yep, different thing.
