### ISSUE TITLE
Link up the README empty state button

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#646]
- [ ] Link up the "open a new issue to make one" button to the new issue creation flow
- [ ] Change ReadMe to README

![image](https://user-images.githubusercontent.com/4406983/87037832-21ff2280-c1ed-11ea-9d99-b0d67d85cb90.png)

**Comment by cloudhead** [comment]
We don't have issues right now though, so we shouldn't have a button here for now.
