### ISSUE TITLE
Move avatar api endpoint under ids

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#671]
With the introduction of the `/ids` endpoint in #670, we should move the `/avatars` endpoint under this group since the avatar is a resource under `id`.

So instead of `GET /avatars/<id>?usage=<usage>`, we should have `GET /ids/<id>/avatar?usage=<usage>`. This results in dropping `http/avatar.rs` and updating the API call in the `ui`.

**Comment by xla** [comment]
This will force the same restrictions on different `ids`, for the allowed inputs for avatars is way more relaxed than the strict character set we have for registry ids. Not all ids are made equal. In essence the `id` param in the avatar endpoints is miss-leading. Furthermore avatars are not hierarchically connected. Will close this for now, happy to reopen if we have strong reasons to push for this change.
