### ISSUE TITLE
DRY registry messages

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#672]
While reviewing some code in proxy, I came across some code that has the same pattern. Two examples of which I've pointed out here:
* https://github.com/radicle-dev/radicle-upstream/pull/653#discussion_r454294179
* https://github.com/radicle-dev/radicle-upstream/pull/670#discussion_r454925229

In the first link, I documented what I tried to do. In the end, I couldn't massage the type system to accept my shenanigans. I'd be interested in finding a way to clean this duplication up. Ideally, it would just be proxy oriented, but maybe we need to tweak something in the registry to make it work.

**Comment by xla** [comment]
There has been effort to improve the usability of `Message` in radicle-dev/radicle-registry#387 - maybe it's worth opening up the discussion again @geigerzaehler @NunoAlexandre

**Comment by FintanH** [comment]
Ya, `result_from_events` makes this impossible I think, without any other changes that is.
