### ISSUE TITLE
Logging in the proxy

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#680]
I wanted to create this ticket for discussing logging in the proxy. Currently, we use `pretty_env_logger` + `log`. I was wondering if we may want to use something like `tracing` so we have structured logs. And the other thing I'm wondering is when and where we could/should do logging.

I started to find it useful when running tests and needing to see what the endpoints were doing. Maybe we want to standardise on this.

**Comment by xla** [comment]
Superseeds #138

**Comment by xla** [comment]
Superseded by #854
