### ISSUE TITLE
Show the actual account id on the wallet page

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#684]
#658 exposed the account ids for orgs and users in the responses. Once #662 is merged, we should show the actual account id in the `Receive` tab.

**Comment by NunoAlexandre** [comment]
Just a note that we should be using the SS58 encoding format to display account ids. That's the advised procedure, used in the Registry CLI and the expected format in the new "accounts" endpoint as well.

**Comment by MeBrei** [comment]
👍 I believe the account ids are already returned in the correct format by the user and org endpoints
