### ISSUE TITLE
Identity avatars different on summary screens

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#695]
The avatar of our own identity (generated on first start of the app) doesn't match the ones in:
  - handle registration summary
  - transaction summary

<img width="50%" alt="Screenshot 2020-07-20 at 11 08 38" src="https://user-images.githubusercontent.com/158411/87920464-8f2a7780-ca79-11ea-80e1-0f593e42fedc.png">
<img width="50%" alt="Screenshot 2020-07-20 at 11 08 49" src="https://user-images.githubusercontent.com/158411/87920471-905ba480-ca79-11ea-8b26-84c67cad65ca.png">
<img width="50%" alt="Screenshot 2020-07-20 at 11 09 04" src="https://user-images.githubusercontent.com/158411/87920478-918cd180-ca79-11ea-9b2d-1580d85b1458.png">
<img width="50%" alt="Screenshot 2020-07-20 at 11 09 11" src="https://user-images.githubusercontent.com/158411/87920480-92256800-ca79-11ea-8338-08acddc153f6.png">

**Comment by FintanH** [comment]
It might be that the `id` passed in here: https://github.com/radicle-dev/radicle-upstream/blob/1c19b53cff4b273a93830704e7dd94d8de5c4bea/proxy/src/http/avatar.rs#L54 is different from the OG `id`. Could be worth making this a `RadUrn` ensuring that we're not passing in _any_ string.

**Comment by xla** [comment]
Registry functionality has been removed.
