### ISSUE TITLE
Transfer funds modal

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#707]
- [x] transfer transaction modal (in this first version, only the account id can be passed in)
- [x] wire up the modal with the `send` form on the Wallet page (for now the form should be restricted to passing an account id)
- [x] handle the transfer transaction type in the transaction center and detail view
- [x] add test for the wallet page and transfer modal

**Comment by NunoAlexandre** [comment]
This one has been done in #712.
