### ISSUE TITLE
Don't allow registration of a project under more than one domain

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#708]
A project should only be registered in one place, whether an org or a user. Otherwise it can be very confusing for the user.

cc @geigerzaehler @CodeSandwich @NunoAlexandre @lftherios this should probably also be implemented at the registry level.

**Comment by NunoAlexandre** [comment]
@cloudhead I don't quite understand. Is this saying that we won't support projects under orgs or users but decide between one or the other exclusively?

**Comment by cloudhead** [comment]
@NunoAlexandre It means that a registered project cannot be under more than one namespace. Or put differently you can only register a project once (unless you unregister it and re-register it)

**Comment by cloudhead** [comment]
Thinking about this more, I wonder how necessary this is at the registry level. Since at the Link level, it will only be pointing to at most one org/user. So perhaps it's enough for the application to enforce this.

Here's an example:
1. I create project `rx`.
2. I register it under my user `cloudhead`. It's now displayed as `cloudhead/rx` under my profile.
3. I now register it under my org `radicle`.
4. ???

Currently it would show the project in both orgs, which doesn't really make sense. Once we have attestations working, the re-registration would essentially invalidate the registration under `cloudhead`. This means that the registry's first entry under the `cloudhead` user would be invalid, or unverifiable.

**Comment by geigerzaehler** [comment]
If I understand you correctly you want to prevent that two registry projects link to the same link project? This makes sense and is a constraint that should be considered as part of the attestation work.

**Comment by NunoAlexandre** [comment]
> If I understand you correctly you want to prevent that two registry projects link to the same link project? This makes sense and is a constraint that should be considered as part of the attestation work.

I think the issue is a UX one though?

**Comment by CodeSandwich** [comment]
What should it take to re-register a project? Specifically if I register a project and then lose my registry key, is the project state forever frozen on registry?

**Comment by cloudhead** [comment]
> If I understand you correctly you want to prevent that two registry projects link to the same link project? This makes sense and is a constraint that should be considered as part of the attestation work.

Exactly. And yeah, I think it's part of the attestation work.

> I think the issue is a UX one though?

It's UX, but perhaps best prevented at the registry level.. this is what we should discuss.

> What should it take to re-register a project? Specifically if I register a project and then lose my registry key, is the project state forever frozen on registry?

Yeah this is a real problem.

**Comment by CodeSandwich** [comment]
> > What should it take to re-register a project? Specifically if I register a project and then lose my registry key, is the project state forever frozen on registry?
> 
> Yeah this is a real problem.

Maybe we should allow anybody on registry to track the state of any project? It brings no security danger, so it shouldn't hurt (rogue copy of a project under a slightly different name will always be a problem). Imagine an audit company, which has a project tracked up to a point of the last review. It would also make the logic way simpler.

**Comment by cloudhead** [comment]
Yeah, this is what I'm thinking too. It should work if the attestations are verified in-app.

**Comment by xla** [comment]
Registry functionality has been removed.
