### ISSUE TITLE
Show transactions of different authors

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#713]
Currently we only show the locally cached transactions in the transaction center and wallet pages. On the wallet pages we want to show additional transactions:

**Identity wallet page**
- _DONE_ transactions the session identity has authored (eg user/project/org registrations, outgoing transfers)
- incoming transfer transactions, ie transactions authored by other entities that increased this identities balance

**Org wallet page**
- _DONE_ transactions the session identity has authored (eg member/project registrations, outgoing transfers)
- transactions other members of the org have authored (eg member/project registrations, outgoing transfers)
- incoming transfer transactions, ie transactions authored by other entities that increased the orgs balance

**Comment by xla** [comment]
Registry functionality has been removed.
