### ISSUE TITLE
CI builds the same commit twice

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#717]
The CI server is slowed down by unnecessary builds.
See: https://github.com/radicle-dev/radicle-upstream/pull/716.

<img width="416" alt="Screenshot 2020-07-23 at 16 38 11" src="https://user-images.githubusercontent.com/158411/88300233-89e05d80-cd03-11ea-8630-0a7d88bdb11a.png">
<img width="882" alt="Screenshot 2020-07-23 at 16 38 20" src="https://user-images.githubusercontent.com/158411/88300238-8a78f400-cd03-11ea-9c45-2d2fe438fdba.png">
<img width="1178" alt="Screenshot 2020-07-23 at 16 38 40" src="https://user-images.githubusercontent.com/158411/88300239-8c42b780-cd03-11ea-96cb-4e2cc3be40ba.png">
<img width="1201" alt="Screenshot 2020-07-23 at 16 39 36" src="https://user-images.githubusercontent.com/158411/88300242-8cdb4e00-cd03-11ea-8f85-1f39299bb01d.png">

**Comment by xla** [comment]
I updated the Pipeline Settings in buildkite to promote existing builds for PRs if they should exist. Also disabled fresh builds for PRs when they become ready for review. Let's keep an eye on it and see if this helped with the issue.

**Comment by geigerzaehler** [comment]
Can’t we just make the branch builds required on github and disable PR builds alltogether?

**Comment by rudolfs** [comment]
@geigerzaehler that could work.

**Comment by xla** [comment]
> Can’t we just make the branch builds required on github and disable PR builds alltogether?

Happy to try that approach!

**Comment by geigerzaehler** [comment]
Ok, I’m moving forward with this then.

**Comment by rudolfs** [comment]
Seems like it got fixed.
