### ISSUE TITLE
spec: navigate to entity

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#719]
### Given a URN, track a project you're interested in

**What can be navigated to?**
- **Projects**
  - **Untracked**
    - User has never indicated a desire to track this project, or has deleted and/or stopped trying to find it ([spec](https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=16978%3A1610))
  - **Untracked, not yet located**
      - User has asked to track this project but it has not yet been located on the network
       - Status can be monitored on the Tracking tab of user Profile, or on tentative project page

  - **Tracked, not yet cloned**
    - User has asked to track this project and it has been located on the network, but it's not yet replicated locally
    - Status can be monitored on the `Tracking` tab of user `Profile`([spec](https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=16978%3A2302)), or on tentative project page ([spec](https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=16978%3A3056))
  - **Tracked, cloned**
    - User is actively tracking this project and it has been replicated
    - Project shows up on `Tracking` tab & can be browsed locally
- Users (later)
- Orgs (later)

**Where does it come from?**
- User enters a URN (or name?) into "search or jump to..." bar
    - If user already tracks this project, they can jump to its screen (loading or replicated)
    - If it is not found locally, user can track the project
      - There is no guarantee that the project exists or will be found, but we'll start looking for it
- Can you search for a project's registered name? (could be an incentive to pay for the registration)

**Proxy**
- Should there be a separate queue related to search or should search requests fall under a pre-existing flow?

**Existing Figma designs**
https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=6502%3A56626

**Relevant existing tickets**
https://github.com/radicle-dev/radicle-link/issues/221
https://github.com/radicle-dev/radicle-upstream/issues/600
https://github.com/radicle-dev/radicle-link/issues/141

**Comment by xla** [comment]
To flag this early, calling this feature Navigation is miss-leading. As it describes the set of functionality which enables us to navigate between any screen/view/fragment in the application - driven by user interactions like button presses. Often referred to as Routng as well, which is less applicable for the structure of a native app. We should find a more suitable name for this feature, imho this could be the first iteration of a Search feature vertical which could see expansion down the road with a proper bar and more ability to fine tune to discover, flagigng @radicle-dev/product 

Furthermore this is a good opportunity to look at the structure and format of the identifiers we like to share. As before I'd like us to explore URN/URLs which are easy to map onto the entity hierarchy in the application and can potentially serve for deep-linking down the road.

**Comment by cloudhead** [comment]
Yeah good point, it could be more specific. Perhaps **Navigate to Entity** is a better name.

**Comment by xla** [comment]
Superseded by #984
