### ISSUE TITLE
project tracking notifications

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#725]
When we locate a desired project on the network, notify user with message and notification dot in sidebar:
![Screen Shot 2020-07-27 at 5 13 01 PM](https://user-images.githubusercontent.com/2712962/88604519-6e8b9000-d02c-11ea-9978-1b6688e49280.png)
![Screen Shot 2020-07-27 at 5 13 18 PM](https://user-images.githubusercontent.com/2712962/88604534-7814f800-d02c-11ea-8ead-73a2d66359f9.png)

We don't need a 'could not find' notification because.. we might never find certain projects 🤷‍♀️ . User can cancel the lookup process for a particular project in their `Tracking` tab.

**Comment by xla** [comment]
Superseded by #984
