### ISSUE TITLE
Improve send funds recipient validation

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#729]
In the send funds modal created in #712, when entering a malformed account address, the validation requesting if the account `exists` errors out, which is displayed in the ui as `Cannot validate <account address>: undefined`.

We need to either check if the provided account address is correctly formatted before checking the existence (eg a new api request) or adjust the validation to show a more helpful validation message.

**Comment by NunoAlexandre** [comment]
In #712, for now I have considered the 400 response case as "false", as in, the given (malformed) address does not exist.

**Comment by xla** [comment]
Registry functionality has been removed.
