### ISSUE TITLE
Absolute paths

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#734]
Wouldn't it be nice if we could type 
```
import * as thing from "src/thing";
```
instead of 
```
import * as thing from "../../../../src/thing";
```
?
[Potential approach](https://dev.to/sjafferi/absolute-paths-in-svelte-488c)

**Comment by xla** [comment]
Both @rudolfs and I attempted to make this work with our pre-processor toolchain. Would love this to see work, but so far all attempts have been futile. If you have a PR that addresses this, please submit.

**Comment by geigerzaehler** [comment]
With webpack and typescript this should be possible using [`tsconfig-paths-webpack-plugin`](https://github.com/TypeStrong/ts-loader#baseurl--paths-module-resolution). We need to figure out if this works with Svelte too.
