### ISSUE TITLE
proxy: endpoints for all replicated & tracked-but-not-yet-replicated projects

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#735]
We need to query for all tracked, replicated projects as well as all tracked, unreplicated projects (these may never be located on the network).

We could technically use the existing `projects/` endpoint and have the client filter by replication status, but it would be helpful to also know immediately if a project has been found at all.

**Comment by FintanH** [comment]
Can you expand on what you mean by replicated and un-replicated in this context?
