### ISSUE TITLE
Known identities API endpoints

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#741]
Create two endpoints, one that lists all "tracked" identities of the session identity and another one that lists all projects (ie projects locally stored) of the tracked identity. As explained in #740 for the first version, tracked identities are all identities involved with locally stored projects.

The endpoints should serve data to two places:
1. Tracking screen of the session identity profile
- list of identities with ✅ 
  - handle
  - avatar
  - URN
2. visitor view of the profile
- identity
  - handle
  - avatar
  - URN
- list of project names + description + stats + maintainer badge

**Comment by xla** [comment]
> Create two endpoints, one that lists all "tracked" identities of the session identity and another one that lists all projects (ie projects locally stored) of the tracked identity. As explained in #740 for the first version, tracked identities are all identities involved with locally stored projects.

If we foresee that we want to get the tracked list of entities for other identitie than the one of the session, we should encode that in the endpoints. Wouldn't be more general to have these endpoints be parameterised so that the caller can get a filtered list of tracked entities, e.g. by passing a `RadUrn`?

**Comment by MeBrei** [comment]
I updated the comment above, as I confused some things. What we want for this Issue, is still `identities/tracked` (we could do `identities/<id>/tracked` but there is currently no plan how we would implement that, ie if we need the `id` for it or the `peer_id`. 
For the lists of projects for a visited profile, we could do `/projects` and pass the peer_id (and urn ?) via json.

**Comment by xla** [comment]
Great, thanks for the clarification. As we toss around terms like session identity I think it's important to highlight what the determining dimensions is that we narrow the query for tracked identities/projects is. In my limited understanding this would be per peer and not per librad user. Maybe @FintanH can clarify.

In any case I think it's more powerful if the endpoints expect such `peer_id` as this could serve in other scenarios, beyond the session use-case, e.g. show me all the projects a seed node is tracking.

**Comment by FintanH** [comment]
> In my limited understanding this would be per peer and not per librad user. 

Well, to show any meaningful information we need to get the librad user this peer is using as their associated user. So if want to show the user's handle for the given peer id, we also need their profile.

Also, I could be sharing with `xla@peer1` and `xla@peer2`. And their projects might be disjoint. So that's an interesting case. We could attempt to correlate them using their advertised keys. But not sure we want to open that can of worms yet :upside_down_face: :bug:

**Comment by xla** [comment]
@FintanH Thanks for the follow-up. Given your outline, how would the flow look like for a query that says: return all tracked identities for a user RadUrn?

It might be more reasonable to start of with the endpoints expecting a peer_id and we build the high-level merge views on top of it.

**Comment by MeBrei** [comment]
Summary of the discussion around the endpoints:

`GET /identities` will return the list of identities the current session identity knows of and will be shown in the `Tracking` tab

`GET /projects` will be extended with an optional param `user_urn`. If it is not passed, the projects of the session identity will be returned. Otherwise the projects of the session identity will be listed that include the `user_urn` as a remote. This list will be shown in the `Projects` tab of a visited profile.

**Comment by rudolfs** [comment]
After consulting with @cloudhead and @brandonhaslegs we decided that having a list of all the known user identities in the system will not be very useful.

We still need to be able to navigate to a user profile that is not our own (aka visitor view). For this we decided to add a link in the revision selector that allows us to navigate to a specific user profile.

This means we don't need a separate endpoint to list all the known identities (point 1). The links to user profiles will be implemented in: https://github.com/radicle-dev/radicle-upstream/issues/742.

**Comment by xla** [comment]
@rudolfs Should we close this then? Or do we need to remove the endpoint from the proxy?

**Comment by rudolfs** [comment]
@xla we need the endpoints for point number 2 (on which @geigerzaehler is working on in https://github.com/radicle-dev/radicle-upstream/pull/789).

**Comment by xla** [comment]
Doesn't seem like we need the list of known identities for point 2 so this one can be removed:

https://github.com/radicle-dev/radicle-upstream/blob/eee4291993100891524470d9f382c9d565f0c526/proxy/src/http/identity.rs#L86-L87

and

https://github.com/radicle-dev/radicle-upstream/blob/eee4291993100891524470d9f382c9d565f0c526/proxy/src/identity.rs#L88-L91
