### ISSUE TITLE
Show known identities

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#742]
Use the endpoint created in #741 to list known identities in the `Tracking` tab of the sessions identity profile view. The project list of the `Tracking` tab is implemented in #724 

**Design:** tbd

For more info see also #740

**Comment by rudolfs** [comment]
While discussing the design we opted to add a link to the repo selector instead, for more detail see: https://github.com/radicle-dev/radicle-upstream/issues/741#issuecomment-675521865.

**Comment by xla** [comment]
What does that mean for this issue? close, rephrease?

**Comment by rudolfs** [comment]
@xla rephrased my comment above. I'll rephrase the issue.
