### ISSUE TITLE
Parameterize Api on Signer

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#753]
> In the latest changes of librad, the method of signing was
parameterised. For now, we will fill in this parameter using the
SecretKey. In reality, it should be a parameter itself so we can choose
SecretKey for tests or a client for the main application.

@FintanH in https://github.com/radicle-dev/radicle-upstream/pull/752/commits/4cde468a22fef61f8ab7408f008c73b9a2441aba

**Comment by xla** [comment]
While #853 moves large part of the codebase to use the `Signer` we are blocked on radicle-dev/radicle-link#195 as the `PeerConfig` requires the `AsPKCS8` constraint on the signer.

**Comment by geigerzaehler** [comment]
This is issue is obsolete: We’re using `BoxedSigner` so that the APIs don’t need to be generic in the signer.
