### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#756]
Global:
`⌘`+`T` or `⌘`+`P` or `⌘`+`F` or `S` (maybe we should decide on one) - open search
`⌘`+`,` opens Settings

Profile page (org and user)
`⌘`+`N` to create new project

I'll add more if I think of them.

**Comment by rudolfs** [comment]
Also related: https://github.com/radicle-dev/radicle-upstream/issues/623.
