### ISSUE TITLE
Update notification interactions

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#760]
Right now notifications that timeout disappear even when the user is hovering over them. They should remain on screen until the user moves the cursor away from the notification. Hovering should essentially reset the timeout countdown.

**Comment by juliendonck** [comment]
@geigerzaehler Hasn't this been done now?

**Comment by geigerzaehler** [comment]
> @geigerzaehler Hasn't this been done now?

Not yet. We have persistent notifications that never vanish unless the user dismisses them. But we don’t put a hold on the timeout when a user hovers a notification as this issue suggests.

**Comment by brandonhaslegs** [comment]
> We have persistent notifications that never vanish unless the user dismisses them.
We do?
