### ISSUE TITLE
Fix scrollbars on source code view

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#762]
We should style these scrollbars to something that looks good.

![2020-08-07-153605_816x1052_scrot](https://user-images.githubusercontent.com/40774/89652337-a238a680-d8c5-11ea-93ba-cbecf325507a.png)

**Comment by juliendonck** [comment]
@cloudhead so there's two ways of solving this. One is to remove the scrollbars and keep the functionality. Another is to style the scrollbars. I'd be in favor of option one (removing the scrollbars), cause I feel there are many ways to scroll vertically (mousepad, shift + mouse scroll, etc) 
Wdyt?

cc @brandonhaslegs

**Comment by juliendonck** [comment]
@cloudhead like this: https://github.com/radicle-dev/radicle-upstream/pull/765
