### ISSUE TITLE
Set up rad-remote-helper on app start

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#763]
We need the `rad-remote-helper` binary to be installed locally for the checkout feature to work. It is not enough to have the binary be relative to the proxy binary as on Linux the AppImage package gets unmounted when the app is not running. And we need the `rad-remote-helper` binary to be in a stable path so users can interact with the monorepo even when Upstream is not running.

To provide a nice UX we'll copy the `rad-remote-helper` binary to a stable location: `~/.radicle/bin` upon first start of Upstream.

Scope of this issue:
1. copy helper into `~./radicle/bin` on proxy startup if it's not there, make sure it's `+x`
2. add hint to the checkout modal about how to set up your environment.
3. add hint to the project creation flow that instructs the user to set up the path.

Note: a simple check if the binary is in the path is sufficient for now, we'll think about upgrades when we get there.

Follow up for: https://github.com/radicle-dev/radicle-upstream/pull/722.

**Comment by cloudhead** [comment]
Nice. I'd expect this to go in `%USERPROFILE%\.radicle\bin` on windows and `~/.radicle/bin` as well on macOS, just like `cargo install` works for example.

**Comment by xla** [comment]
This is rather odd. Radicle is not a general purpose dependency and binary manager like Cargo. A more reasonable expectation would for it to live in `XDG_BIN_HOME`.

**Comment by rudolfs** [comment]
@xla the problem is that `XDG_BIN_HOME` only works for Linux:
https://docs.rs/directories/3.0.1/directories/struct.BaseDirs.html#method.executable_dir

macOS and win don't have an equivalent.

**Comment by xla** [comment]
Fair point, I guess we already committed to maintaining a file tree under `.radicle`, so just the logical next step. We are building a universal paperclips machine after all.
