### ISSUE TITLE
Set up remotes for peers other than self in a checkout

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#766]
We have a remote for our own peer called `rad`, but are still missing fetchspecs for other peers.
See: https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/identity_resolution.md#working-copies.

Follow up to: https://github.com/radicle-dev/radicle-upstream/pull/722.

**Comment by FintanH** [comment]
Integration of work done in https://github.com/radicle-dev/radicle-link/pull/300

**Comment by xla** [comment]
DONE
