### ISSUE TITLE
Specify Default Branch on New Project

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#775]
Just realised that there's no way to specify what I want my default branch name to be in the UI if I select "Create a New Project".

I think it would make sense to have this available, and not hard-code anything in the creation, or maybe the box auto-filled as a suggestion.

@radicle-dev/product I have some thoughts around the project creation flow:
1. There'd be two choices - create new or create existing (but no form boxes for name/description yet) - and you choose one
2. In the case of new, we get presented with `name`, `description`, `branch`, and `path`
3. In the case of existing, we get presented with `description` and `path`, and then we have the `name` and `branch` pop up with the disabled values filled.

Lemme know what you think :)

**Comment by rudolfs** [comment]
> Just realised that there's no way to specify what I want my default branch name to be in the UI if I select "Create a New Project".

That was implemented according to the spec at that time -- it should fall-back to whatever the default branch name is configured to. The reasoning was to keep things simple and not spend too much time on details about which we're unsure will be relevant to users before we can run the product through user testing. \cc @cloudhead.

**Comment by FintanH** [comment]
But if it's a new project, then it's not configured :) And then we have the choice when we choose an existing project :shrug:

**Comment by rudolfs** [comment]
@FintanH https://github.com/radicle-dev/radicle-upstream/blob/master/ui/src/config.ts#L2

**Comment by FintanH** [comment]
Sure, but why have it hardcoded when we could have an input value? Just for simplicity sake?

**Comment by rudolfs** [comment]
> Just for simplicity sake?

Yes. When was the last time you started a new project with a non-default branch name?

**Comment by FintanH** [comment]
I was never given the option :cry:

**Comment by rudolfs** [comment]
Are you saying editing the config & recompiling the project is bad UX ; P

**Comment by rudolfs** [comment]
I think changing the default branch name should go in settings, and not the project creation modal, if we choose to do it.

**Comment by juliendonck** [comment]
So let me get this straight, the question here is about having any default or not. If so, having some default is always better from a UX perspective. The less choices people need to make the better. For power users that want to change things they can do that, but everyone else shouldn't have to think about it.

**Comment by FintanH** [comment]
Sure, I guess that makes sense. So they would have a global default? But I still think it wouldn't be necessarily a _bad idea_ to auto-fill the field with their default, but still allow them to edit it, no?

**Comment by FintanH** [comment]
> The less choices people need to make the better.

Yup, fair point. And that's why my suggestion is to have it auto-filled. But if that's too much of a pain in the ass then we can drop it or do it via settings as @rudolfs proposed :)

**Comment by juliendonck** [comment]
I see so the options are: 
1. Have a default value you set up in settings and that's pre-filled in a field every time you create a project, but you can still change it
2. Have a default value you set up in settings but you're not asked every time?

**Comment by FintanH** [comment]
Yup! That sounds right to me

**Comment by brandonhaslegs** [comment]
Just want to confirm: You want the default branch dropdown to be disabled in the case of starting from an existing repo? We do allow the user to set the default branch now for existing repos.
![image](https://user-images.githubusercontent.com/4406983/90241158-c8f95e80-de2a-11ea-9540-c2d884438b7c.png)

That said, if we do disable that dropdown, I think we should just remove the "Default branch" field altogether in the project creation modal. If you can set your default branch name in settings, and if you can't change the default branch of an existing repo you're importing, there would be no reason to have it there anymore. I'm all for simplifying it and making it easier. The faster we get users to see their own projects in the app, the more traction we'll have, so anything in the way of that flow should be simplified and smoothed out.

**Comment by FintanH** [comment]
Agh, I'm explaining myself poorly :sweat_smile: 

My gripe was that you **can't specify** the default branch when creating a new project. 

I think it's **perfectly fine** that you can select a default branch for an existing repository (although my spidey-senses are tingling about setting it up correctly, but we can ignore that for now).

**Comment by xla** [comment]
@abbey-titcomb The terminology changes that are underway are part of ß1?

**Comment by rudolfs** [comment]
We removed the whole "new project" flow, it's done via the `rad` cli now.
