### ISSUE TITLE
Notifications should show up above everything, including modals

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#777]
Example of this not happening:

![image](https://user-images.githubusercontent.com/4406983/90217669-3a70e700-de02-11ea-8dab-9b0d87ee178e.png)

**Comment by rudolfs** [comment]
This should be addressed in the modal PR, which is still in progress...
https://github.com/radicle-dev/radicle-upstream/pull/738

**Comment by juliendonck** [comment]
This is resolved
