### ISSUE TITLE
lint typescript in svelte components 

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#801]
Currently, `eslint-plugin-svelte3` doesn't support typescript because it would require preprocessing, and there is currently no support for preprocessors of any kind. There is a cli tool to check for typescript errors (`svelte-check`), but no straightforward linting solution for typescript-enabled svelte components.

We might consider something like [this approach](https://github.com/NicoCevallos/eslint-svelte3-preprocess-test), but with a more recent version of `svelte-preprocess`; in any case, getting `eslint-plugin-svelte3` working with a preprocessor and specifically with typescript will be a nontrivial chore. 

Relevant issues to track:
- https://github.com/sveltejs/eslint-plugin-svelte3/issues/68
- https://github.com/sveltejs/eslint-plugin-svelte3/issues/10

Inspo from other frameworks, should we take this on:
- [eslint + typescript + react](https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project)
- [angular-eslint with typescript support](https://github.com/angular-eslint/angular-eslint)
- [eslint-plugin-vue with typescript support](https://eslint.vuejs.org/user-guide/#faq)

**Comment by NicoCevallos** [comment]
@sarahscott take a look at [this repo](https://github.com/NicoCevallos/svelte-template) where I did more or less the same as you mention in the other repo I made but using patch-package to avoid weird tricky fix lol... in that case you only would need to copy the patch related to `eslint-plugin-svelte3`, install [`patch-package`](https://www.npmjs.com/package/patch-package) and add the `postinstall` script to apply the patch after install the `eslint-plugin-svelte3`
