### ISSUE TITLE
Create project from existing repo deletes your master branch

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#822]
Using this git config, trying to create a rad project from this repo will nuke the master branch and fail to create the rad remotes.

```
[core]
	bare = false
	repositoryformatversion = 0
	filemode = true
	logallrefupdates = true
[remote "rad"]
	url = file:///home/cloudhead/.local/share/radicle/git/
	fetch = +refs/namespaces/hwd1yrenyw7wymtmxams3rwcemk73chydfjpinji86yqjywawjeu31d7b6c/refs/heads/*:refs/heads/*
	push = +refs/heads/*:refs/namespaces/hwd1yrenyw7wymtmxams3rwcemk73chydfjpinji86yqjywawjeu31d7b6c/refs/heads/*
[remote "origin"]
	url = git@github.com:cloudhead/popol.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

**Comment by rudolfs** [comment]
Possible cause: https://github.com/rust-lang/git2-rs/blob/97a855443f5678b6f71db59cfaf03b857ec38fac/src/repo.rs#L571-L572

**Comment by kim** [comment]
The "rad" remote looks wrong -- it should be:

```
[remote "rad"]
    url = rad://hwd1yrenyw7wymtmxams3rwcemk73chydfjpinji86yqjywawjeu31d7b6c.git
```

The `fetch` spec also maps the remote heads to the local heads -- it should map to `refs/remotes/rad/*`. So yes, if you `git remote rm rad`, git will unsurprisingly remove `refs/heads`.

**Comment by cloudhead** [comment]
Yeah this is a config of a project setup with a previous version of radicle

**Comment by FintanH** [comment]
Sorry, my bad. I didn't realise the extent of the deletion.

An alternative is to use [remote_set_url](https://docs.rs/git2/0.13.10/git2/struct.Repository.html#method.remote_set_url) instead. This is a weird enough case since we moved away from that remote structure though.

**Comment by cloudhead** [comment]
Yeah I'm not sure how specific this test case is, eg. could this happen to someone down the road?

**Comment by FintanH** [comment]
I'm just thinking if we somehow change scheme again that it might happen. Deleting the remote is probably a bad idea in general. Maybe we could "deprecate" the old remote by renaming it and creating the remote with the new URL?
