### ISSUE TITLE
Improve error handling when proxy can't be started

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#828]
If the proxy doesn't start up when the app is started, we're presented with a screen that is not helpful in this situation.
Clicking on "clear session" doesn't do anything, because the proxy isn't running.

<img width="772" alt="Screenshot 2020-08-27 at 11 54 26" src="https://user-images.githubusercontent.com/158411/91425942-1a0e4700-e85c-11ea-9d77-38cb7771d6d9.png">

```
Contents/MacOS » ./radicle-upstream
Error: Command failed: /Applications/radicle-upstream.app/Contents/Resources/proxy --registry=emulator
Error: Store(Json(Error("missing field `accountId`", line: 1, column: 352)))

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Applications/radicle-upstream.app/Contents/Resources/proxy --registry=emulator'
}
```

**Comment by xla** [comment]
We should reset the local state if we run into these storage incompatibility issues. Further down the road we should devise a proper strategy to migrate between "schemas" of our local store.

**Comment by rudolfs** [comment]
This is shown when the proxy can't be started at all.

**Comment by xla** [comment]
I know, the error the proxy throws could be addressed. My point is with being more graceful handling these we could help to not get into the state of the proxy crashing.And the button could run a state clear and restart the proxy.

**Comment by rudolfs** [comment]
I'm not sure it's a good idea to just wipe all the user state if there's an error.
I think the proper way to address this is to implement migrations for the state storage, so users don't bump into this issue.

**Comment by xla** [comment]
Yeah, as I said in my original comment.

**Comment by rudolfs** [comment]
@juliendonck could we have a design for a generic error screen please?

**Comment by brandonhaslegs** [comment]
Just putting this here https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=5952%3A204
![image](https://user-images.githubusercontent.com/4406983/96894190-c438d280-148b-11eb-8ea8-8d27f459eb01.png)

**Comment by xla** [comment]
While this issue improves the CTA and styling of the error screen it does not address the host of errors stemming from startup issues of the proxy. I created #1095 as a follow-up.
