### ISSUE TITLE
Adjust the wording according to the Glossary

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#836]
Go through all copy of the app and check if it is up to date with the outcome of the [Glossary](https://www.notion.so/monadic/Glossary-5026cc02dca14629bb9d4058c7fa527a). Changes should be listed here to be worked on in PRs.

**Comment by abbey-titcomb** [comment]
I've added comments with outstanding copy changes & questions to the [Figma file](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=4147%3A7246). Will wait to resolve these before moving ahead with changes.

Main points of conflict are between use of RadicleID throughout App and the distinction between Tracking & Following.

**Comment by abbey-titcomb** [comment]
Some copy updates being addressed here -> https://github.com/radicle-dev/radicle-upstream/issues/877

**Comment by rudolfs** [comment]
Another small wording change addressed here -> #919

**Comment by abbey-titcomb** [comment]
Reviewed latest build (https://buildkite.com/monadic/radicle-upstream/builds/5170) and came up with some outstanding TODOs & comments. Capturing here:

- [ ] Replace with correct links once website is up (will create an issue for this)

- [ ] Add "Be sure to put this in a safe place" on second part of onboarding (@MeBrei )

- [ ] Replace Radice ID and Project ID with user handle and project handle respectively *after* #840 is resolved. Needs to be replaced in onboarding and search bar

**Some bugs**

- [ ] Does Project Description have a max? Seems that there is no way to expand the description when it gets to long...
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/18275452/94798417-df12ac80-03e1-11eb-8c2b-0dad45492647.png">

- [ ] After something is pasted the <kbd>⌘</kbd><kbd>V</kbd> should go away right?
<img width="445" alt="image" src="https://user-images.githubusercontent.com/18275452/94799759-ec309b00-03e3-11eb-96bf-b346445137c7.png">

- [ ] Project URN does not appear in text box
<img width="469" alt="image" src="https://user-images.githubusercontent.com/18275452/94799793-fd79a780-03e3-11eb-8ee8-ef043608eda7.png">

@MeBrei @rudolfs - should I make these into issues?

**Comment by rudolfs** [comment]
@abbey-titcomb 

> Does Project Description have a max? Seems that there is no way to expand the description when it gets to long...
Captured in: https://github.com/radicle-dev/radicle-upstream/issues/840.

> After something is pasted the ⌘V should go away right?
https://github.com/radicle-dev/radicle-upstream/issues/987

> Project URN does not appear in text box

The whole Search feature has still to be completed, including showing the waiting area, etc. -> https://github.com/radicle-dev/radicle-upstream/issues/984.

**Comment by MeBrei** [comment]
> * [ ]  Add "Be sure to put this in a safe place" on second part of onboarding (@MeBrei )

This is such a small change, I can just open a PR and link it to this issue.

> * [ ]  Replace Radice ID and Project ID with user handle and project handle respectively _after_ #840 is resolved. Needs to be replaced in onboarding and search bar

An issue would be great

> * [ ]  Does Project Description have a max? Seems that there is no way to expand the description when it gets to long...

This is a bug, so an issue would be great. I don't think this is addressed in #840 

> * [ ]  After something is pasted the ⌘V should go away right?

This was fixed in #980 

> * [ ]  Project URN does not appear in text box

I would also suggest waiting for the search to be finished. Will try to keep it in mind when reviewing related PRs

**Comment by rudolfs** [comment]
> This is a bug, so an issue would be great. I don't think this is addressed in #840

Good catch, amended it.

**Comment by rudolfs** [comment]
When the [docs]( http://docs.radicle.xyz) are done we should update the app with the correct permalinks in these places:

<img width="30%" alt="Screenshot 2020-11-04 at 13 28 31" src="https://user-images.githubusercontent.com/158411/98112267-3523b580-1ea2-11eb-97e3-857a0c005b06.png">
<img width="30%" alt="Screenshot 2020-11-04 at 13 28 39" src="https://user-images.githubusercontent.com/158411/98112272-3654e280-1ea2-11eb-94cc-957f326cadaa.png">
<img width="30%" alt="Screenshot 2020-11-04 at 13 28 47" src="https://user-images.githubusercontent.com/158411/98112277-37860f80-1ea2-11eb-84e4-a6446e84f620.png">

**Comment by MeBrei** [comment]
Extracted the remaining task into #1271
