### ISSUE TITLE
Unify shareable identifiers across app

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#840]
@cloudhead, @brandonhaslegs and I decided that the format of shareable identifiers for β1 in Upstream should be like this:

Shown in the UI: `@hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6.git`
Copied to clipboard: `@hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6.git#rudolfs`
Passed down as URN to proxy: `rad:git:hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6`
👇 
```json
{
  "displayName": "rudolfs",
  "urn": "rad:git:hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6"
}
```

Figma design is [here](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=3372%3A10405).

**Comment by xla** [comment]
> Passed down as URN to proxy: `rad:hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6.git#rudolfs`

This is not a valid `RadUrl` afaik. Again I urge for us to devise an upstream url/urn scheme which can be translated to and from the underlying protocol. We are doing us a disservice by not approaching this structurally.

Also what's up with the random `@` prefixes?

**Comment by cloudhead** [comment]
Passed down to proxy should be `rad:git:<id>` without the `#rudolfs`

**Comment by cloudhead** [comment]
> Also what's up with the random @ prefixes?

This identifies a random string of alphanumerics as an identity.

**Comment by rudolfs** [comment]
> Passed down to proxy should be rad:git:<id> without the #rudolfs

@cloudhead: But if we don't pass it down when searching, then we would not be able to easily tell what is queued up for tracking in this screen:

<img width="785" alt="Screenshot 2020-08-28 at 13 51 35" src="https://user-images.githubusercontent.com/158411/91558022-d12ac100-e935-11ea-9951-c4628d197890.png">

**Comment by cloudhead** [comment]
We can pass the identifier separately from the URN, I don't think that should be a problem.

**Comment by rudolfs** [comment]
> We can pass the identifier separately from the URN, I don't think that should be a problem.

Ok. Amended the issue text.

**Comment by cloudhead** [comment]
> > We can pass the identifier separately from the URN, I don't think that should be a problem.
> 
> Ok. Amended the issue text.

Still not quite, see https://github.com/radicle-dev/radicle-upstream/issues/840#issuecomment-682476851

**Comment by rudolfs** [comment]
> Still not quite, see #840 (comment)

Now :3

**Comment by juliendonck** [comment]
@rudolfs for us to be able to do this we need to have the urn's properly formatted from the proxy? Or do we format the urns in the frontend?

**Comment by rudolfs** [comment]
@juliendonck we should do it in proxy.

**Comment by FintanH** [comment]
Is there something we're gaining from having `@hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6.git` in the UI?

From my perspective, it adds more hoops to jump through in turning that into the form of `rad:git:hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6`, and then back again going the other way.

Whereas if it's consistent then you're just relaying the same data.

I'd possibly only see `@hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6` being useful (note the lack of `.git`) because then this may be protocol agnostic and the front-end chooses which protocol it's using. Although, we only have git protocol at the moment :P

**Comment by cloudhead** [comment]
They're different things. One is a handle, the other is a URN. So what we're doing is converting from a user-facing handle, to a protocol-level URN. The URN is of course useful if what you need is .... a URN, eg. to paste into an external program that can resolve things other than radicle entities.

**Comment by FintanH** [comment]
That's clear, thanks @cloudhead. And what about the .git suffix, is that there to ensure protocol compatibility?

**Comment by FintanH** [comment]
Also, what about handles for other things that aren't users? E.g. projects, issues, etc.

**Comment by cloudhead** [comment]
All handles for top-level entities (users, projects) should look that way. The `.git` is to make sure things are future compatible, when we have other backends.

For stuff like issues, we need to think about it, but it would either be prefixed with the project handle, eg. `@abcdef123.git/<issue-hash>`, or somehow on its own, if it's easy to look-up, since the hash would be unique across projects.

**Comment by xla** [comment]
As brought up before in https://github.com/radicle-dev/radicle-upstream/issues/719#issuecomment-663593291 -- this discussion and any place in the application where the this feature comes up would outright benefit from a proper URN scheme. Instead there seems to be a tendency to ad-hoc solution and the need to revise this once the entity space expands that we want to share, reference, etc. Not only would it give us structure to defined how we allocate the namespace but make future use-cases like deep-linking a side-effect. Important to reiterate that identity in the context of the app is not only scoped to the CoCo domain, but has and will have to accommodate registry/wallet/economics types.

Would like to understand what we hope to gain from the homebrew approach? Why we continue on with it? To preempt the answer of effort, the amount of time that already has been sunk into this, would have amortised a slightly higher time investment upfront by now.

**Comment by cloudhead** [comment]
> They're different things. One is a handle, the other is a URN. So what we're doing is converting from a user-facing handle, to a protocol-level URN.

:point_up: 

This doesn't preclude us from having URNs for deep linking. This is just a user-facing handle people can share, with a format people are familiar with.

> To preempt the answer of effort, the amount of time that already has been sunk into this, would have amortised a slightly higher time investment upfront by now.

Not sure what you're referring to..

**Comment by rudolfs** [comment]
@FintanH: [you mentioned](https://github.com/radicle-dev/radicle-link/issues/221#issuecomment-650159251) that we might want to know the type of a requested entity to be able to handle errors better. Do we know more about it now? If we need to encode more than just the project name in the request URN this issue would be the perfect place to discuss that.

**Comment by cloudhead** [comment]
Afaik, we still don't have a way to do this..

**Comment by rudolfs** [comment]
@xla: let me add a bit of context, so we can better understand which problem we are trying to solve and whether your objections apply.

## How we got here?

So, @brandonhaslegs was looking at the headers of a `user` and a `project` and noticed that currently they don't look consistent:

<img width="50%" alt="Screenshot 2020-09-29 at 10 49 25" src="https://user-images.githubusercontent.com/158411/94535692-27936400-0242-11eb-8fe4-3559a4310106.png">

<img width="50%" alt="Screenshot 2020-09-29 at 10 55 42" src="https://user-images.githubusercontent.com/158411/94535861-5ad5f300-0242-11eb-8612-d0032207450a.png">

Note, how a user's identifier contains the `display name` in the identifier: `rudolfs@...`, but the project doesn't.

And when you copy the identifiers to the clipboard:

- `rudolfs@hybc66xsdxmwgg4knmxo6bgthoii7utwhgm8pidz4awcb6atoaxtpk` ← this is a `user`
- `%rad:git:hwd1yredrye14esjk6ht4d4p9bg9h83e6h8zom81r3is6uqpwez83futhmr` ← this is a `project`

Again, they don't look consistent -- the `user` has a `rudolfs@` prefix (the `display name`), but the project doesn't. However, the project has a `%rad:git` prefix.

Also, `display name` in the `user` header appears twice (as a heading and in the identifier `rudolfs@...`), there is no need for such redundancy.

Beyond these inconsistencies @brandonhaslegs also pointed out, that to newcomers of Upstream it might not be entirely obvious that the `display name` and `project name` is *just* metadata, which could change any time and doesn't uniquely identify the `user` or `project`.

## Requirements

Given these observations, we got together and came up with the following requirements:
  1) To make things consistent, the `user` and `project` identities should have the same format.
  2) To make it more obvious to users *what* the actual unique identity is, we should use a format which is familiar to a broad audience -- in other products identities are usually denoted with an `@` sign, so e.g. on GitHub, Twitter, Instagram my identity is `@rudolfs`.
  3) Because the metadata of an identity can't be derived from the hash and it isn't immediately available when querying the network, we need to also encode this metadata into the `shareable identifier` which gets copied to the clipboard. For `user`s it's the `display name` and for `project`s it's the `project name`. This has the additional benefit that it's easier to tell what a given identity *is* when shared out-of-band.
  4) Last but not least, @cloudhead pointed out, that we also need to include the *protocol* in the `shareable identifier`, because in the future we might have different protocol backends and the application would need to know which protocol to query.

## Proposed solution

With these requirements in mind, we came up with the following solution for identities on the Upstream application-level:

```
┌─ prefix which means this is a `shareable identifier` ┌── delimiter which separates identity from protocol
│                                                      │┌─ protocol
@hybc66xsdxmwgg4knmxo6bgthoii7utwhgm8pidz4awcb6atoaxtpk.git#radicle-upstream
 │                                                         │└─ optional metadata: `display name` or `project name`
 └─ $HASH as defined in link rfc/identity_resolution.md    └─ delimiter which separates the mandatory and optional parts of a `shareable identifier`
```

In the UI it would look like this:
<img width="50%" alt="Screenshot 2020-09-29 at 12 28 46" src="https://user-images.githubusercontent.com/158411/94547356-77c4f300-024f-11eb-8532-65ac40ef29c5.png">

<img width="50%" alt="Screenshot 2020-09-29 at 12 29 30" src="https://user-images.githubusercontent.com/158411/94547364-78f62000-024f-11eb-9e47-7c07e41a0646.png">

When you copy the identifiers to the clipboard, you'll get:
`@hybc66xsdxmwgg4knmxo6bgthoii7utwhgm8pidz4awcb6atoaxtpk.git#rudolfs`
`@hwd1yredrye14esjk6ht4d4p9bg9h83e6h8zom81r3is6uqpwez83futhmr.git#radicle-upstream`

These `shareable identifiers` then can be shared with other Upstream users out-of-band. When you receive one of these, you can open the search modal in Upstream via <kbd>⌘</kbd>+<kbd>p</kbd> and paste them into the search input.

<img width="50%" alt="Screenshot 2020-09-29 at 12 31 52" src="https://user-images.githubusercontent.com/158411/94547877-2cf7ab00-0250-11eb-9931-e7a3615fba74.png">

Upon receiving a `shareable identifier`, like `@hybc66xsdxmwgg4knmxo6bgthoii7utwhgm8pidz4awcb6atoaxtpk.git#rudolfs`, the UI should make a request to the proxy with the following payload:
```
{
  "displayName": "rudolfs",
  "urn": "rad:git:hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6"
}
```

As pointed out in **Requirements point nr. 3** -- we need the additional metadata so that we can immediately show the `displayName` or `projectName` in the preliminary `user` or `project` page which is opened right after the search is submitted (before we get any data back from the network):

<img width="60%" alt="Screenshot 2020-09-29 at 14 39 52" src="https://user-images.githubusercontent.com/158411/94560175-8bc62000-0262-11eb-9dc1-d390c8ea1b21.png">


## Objections

> > Passed down as URN to proxy: rad:hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6.git#rudolfs

> This is not a valid RadUrl afaik.

This was corrected in the issue text to:
- urn: `rad:git:hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6`
- request:
```
{
  "displayName": "rudolfs",
  "urn": "rad:git:hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6"
}
```

> Again I urge for us to devise an upstream url/urn scheme which can be translated to and from the underlying protocol.

See the **Proposed solution** section.


> We are doing us a disservice by not approaching this structurally.

I should have started with an issue outlining the problem first instead of going straight with the solution, sorry about that!
However, we did try to approach this structurally in the meeting we had.

I hope that the 👉 **How we got here?** section cleared up any confusion, I'm also curious to hear if you have an alternative proposal on how `shareable identities` should be handled in Upstream.


> Also what's up with the random @ prefixes?

See **point nr. 2** in the **Requirements** section.


> As brought up before in #719 (comment) -- this discussion and any place in the application where the this feature comes up would outright benefit from a proper URN scheme. Instead there seems to be a tendency to ad-hoc solution and the need to revise this once the entity space expands that we want to share, reference, etc. Not only would it give us structure to defined how we allocate the namespace but make future use-cases like deep-linking a side-effect. Important to reiterate that identity in the context of the app is not only scoped to the CoCo domain, but has and will have to accommodate registry/wallet/economics types.

You're right, we didn't think about things like the blockchain domain and deep linking when devising our solution, thanks for bringing this up!

**Deep linking**

Could be solved by combining the individual entities to form a URL, for example:
```
<project>/issues/<issue>/comments/<comment>
<project>/source/<revision>/<url-encoded-path-to-object>
```

Which would expand to:
```
@hybc66xsdxmwgg4knmxo6bgthoii7utwhgm8pidz4awcb6atoaxtpk.git#radicle-upstream/issues/dfgc66xsdxmwgg4knmxo6bgthoii7utwhgm8pidz4awcb6atoaxtre.git/comments/qwec66xsdxmwgg4knmxo6bgthoii7utwhgm8pidz4awcb6atoaxrty.git
@hybc66xsdxmwgg4knmxo6bgthoii7utwhgm8pidz4awcb6atoaxtpk.git#radicle-upstream/source/main/%2Fui%2Fsrc%2FApp.svelte
```

AFAIK we don't know yet how collaboration artefacts such as `issue`s or `comment`s would be addressed on the protocol level, so it's hard to reason about how we should format these on the application level. But this doesn't mean that we can't expand our proposed scheme to make deep-linking work down the line.


**Economics/blockchain domain**

As we are defining the funding feature from scratch, it is not yet clear what the exact needs for addressing `transactions`, `accounts`, `contracts`, etc will be. However, since we prefix CoCo `shareable identifiers` with an `@`, it should be easy to devise another prefix for the economics domain to be able to distinguish them.

I don't see either of those objections as blocking, as most likely we'd have a parser in the front-end which would deal with the incoming search requests.

> Would like to understand what we hope to gain from the homebrew approach? Why we continue on with it?

Could you please expand on what you mean by *the homebrew approach*?
Are you asking why do we have to come up with a new scheme for Upstream, rather than re-using the protocol-level URN scheme?


> To preempt the answer of effort, the amount of time that already has been sunk into this, would have amortised a slightly higher time investment upfront by now.

But we already put some upfront effort into this in our [previous (now deprecated) attempt](https://www.notion.so/monadic/Shareable-Entity-Identifiers-406a170c78f241238caef9affa11b4f1) to define `shareable identifiers`.

The problem is that we're periodically uncovering new things while defining the product and implementing the protocol, that we have to continuously revise our thinking until we get to a more stable definition. Our thinking regarding how to approach the economics side of the product changed, for example, if we had put more thought into incorporating that into the Search architecture earlier, we would have wasted even more time.

So I'm not sure what exactly you're getting at, but if you think this is still not addressed and relevant to the discussion, then please elaborate some more.

**Comment by sarahscott** [comment]
Thanks for this writeup @rudolfs - we should figure this one out asap because the search bar design depends heavily on it: https://github.com/radicle-dev/radicle-upstream/pull/969/files#diff-bd4d65ed2b213f2f3e5b27b40225b460R104

**Comment by xla** [comment]
> Could you please expand on what you mean by _the homebrew approach_?

I'm referring to the outline above and all attempts made earlier. Where a scheme is developed which tries to incorporate all the needs of encoding. I agree with the observation that we uncover new things, but there is a misconception that the solution space I proposed for the better part of the year would not have given us the flexibility and expandibility to be prepared for these new discoveries, no matter how many more domains we incorporate into Upstream. To make it perfectly clear I do not have a stance on how we present the information on the screens, i.e. user/project profile. My point is about the structure and forward compatibility of the ascii blobs we pass around.

To cut to the chase all our needs are met with a well-formated URL and an URN scheme. Where domains are placed on the top-level and from there can be broken down into their respective entity hierarchies. As in:

```
upstream://<domain>/<entity_fragments/...#<navigation_hint>?<metadata_key>=<metadata_value>&...
```

Examples:

```
upstream://link/users/hyndb5gs95gwtsf37tncz4ag3wqrg4ejw3qqga6x1srw9jp8jw59d6?display_name=rudolfs

upstream://link/projects/hybc66xsdxmwgg4knmxo6bgthoii7utwhgm8pidz4awcb6atoaxtpk/git/source/ui/src/App.svelte#L12?project_name=radicle-upstream&revision=main

upstream://registry/orgs/radicle/contracts/213asdqi13782
```

**Comment by FintanH** [comment]
Just to give my 2c here. I can see where @xla is coming from. There's a well-defined scheme for fetching resources -- which are URNs and URLs, or [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)s in the general case. If we use URIs then we don't have to come up with any kind of scheme for fetching resources on our network -- we just follow the well-defined scheme.

Now, if we're set on coming up with a scheme ourselves, then I would think that we should have a formal document of what the specification is. What does this scheme look like? How will it be parsed? How will it be expanded for future uses? What are the advantages of using this scheme? etc.

I believe @xla's point is that if we went with URIs then all those questions are answered and we would have libraries to support us when writing code, as opposed to writing things from scratch.

**Comment by rudolfs** [comment]
After *many* conversations with @xla, @cloudhead, @brandonhaslegs, we reached a compromise which prioritises the completion of our β1 milestone.

For this we will:

1) use plain `radicle-link` URNs as `user` and `project` shareable identifiers;
when copied to clipboard they look like this:
`rad:git:hwd1yre8ttugonm77udfkti4ou89p4e37gdebmj3o544hzrg3r8dupn8hmr`
2) show an `@` *icon* in the UI followed by only the HASH part of the URN
    <img width="50%" alt="Screenshot 2020-10-07 at 16 13 05" src="https://user-images.githubusercontent.com/158411/95342811-1d174100-08b8-11eb-85e6-cfd2c832a109.png">
3) not pass any additional metadata around when sharing identifiers out-of-band, this means that we'll need to redesign the following screens to work without the additional metadata:

    <img width="536" alt="Screenshot 2020-10-07 at 16 18 20" src="https://user-images.githubusercontent.com/158411/95344136-995e5400-08b9-11eb-8793-d3bd305ae806.png">
    <img width="551" alt="Screenshot 2020-10-07 at 16 24 23" src="https://user-images.githubusercontent.com/158411/95344143-9b281780-08b9-11eb-8dda-f989e56af79e.png">

    Note: it's not possible to determine whether a shareable identifier is a `user` or a `project` before its metadata is fetched from the network.

4) After the β1 release, we'll work on a more comprehensive scheme for addressing content, which should:
 - support deep-linking;
 - work across multiple client applications (not only in Upstream);
 - allow passing around meta-data;
 - be recognisable and consistent.

**Comment by brandonhaslegs** [comment]
Just want to update this thread to say that not passing any metadata through these identifiers is gonna introduce a few big changes in the UI of the app. I hope we get around to building the **after β1 release** stuff very soon! Here are three significant changes I could think of:

---

1. Search will no longer show project name (unless the project is already replicated).

Before             |  Now
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/4406983/95736812-0477a400-0c87-11eb-9d22-150c082e09ba.png)  |  ![image](https://user-images.githubusercontent.com/4406983/95735139-bb265500-0c84-11eb-97bc-8cf01e36b60d.png)

---

2. Projects that have been followed but not yet replicated have no name anymore, so the user can't keep track of what these projects were.

Before             |  Now
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/4406983/95735803-9da5bb00-0c85-11eb-8d99-37f7587653f6.png)  |  ![image](https://user-images.githubusercontent.com/4406983/95735530-36880680-0c85-11eb-8872-92d515517439.png)

---

3. Profiles that are not replicated will no longer have a name. And actually we won't be able to know if they are users or projects, so the page for an out of network user or project will be the same design.

Before             |  Now
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/4406983/95735978-e2c9ed00-0c85-11eb-9939-c38ba638f679.png)  |  ![image](https://user-images.githubusercontent.com/4406983/95736196-30465a00-0c86-11eb-8539-7e11eafc8cff.png)
