### ISSUE TITLE
[fetching] Implement Fetch

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#845]
We want to be able to fetch changes for a repo via [`fetch_repo`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/git/storage.rs#L715).

This should be similar to the `clone` functionality.

**Comment by xla** [comment]
@FintanH Could we expand more on the use-case and when/how these fetches are triggered, currently the description is sparse and would not make it possible for someone to understand the context.

**Comment by FintanH** [comment]
Sure, sorry about the sparsity. I just want to add the `fetch_repo` function into the `Api` struct `impl` and test that it works. Nothing else.

The fetching trigger can be implemented in the next iteration.
