### ISSUE TITLE
Replace log crate with tracing crate in proxy

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#854]
We have positive results from using the `tracing` crate in oru org. The proxy codebase should be overhauled and be equipped with a sound logging strategy.

**Comment by juliendonck** [comment]
Can we close this now that the proxy code isn't in this repo anymore?

**Comment by geigerzaehler** [comment]
I think this still might be valuable since we still have some Rust code and logging with `tracing` provides more information. I’ll follow up on this.

**Comment by rudolfs** [comment]
This seems to have been done in https://github.com/radicle-dev/radicle-upstream/pull/2165. Please re-open if that's still not the case.
