### ISSUE TITLE
Reintroduce notifications of meaningful events in the proxy

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#864]
We used to have notification machinery in the proxy which could be use to inform the UI of meaningful events based on a push model. Given that we start to introduce more and more activity, esp. network related, in the proxy it would be helpful to surface these signals to the UI for at least debugging purposes. Ultimately we can enable more advanced use-cases like #725.

**Comment by rudolfs** [comment]
@xla is this done?

**Comment by xla** [comment]
There is still the UI part to be done, have a some infrastructure to set up listeners and show the events in ways that make sense, i.e.: notifications when project requests make advances.

**Comment by rudolfs** [comment]
@xla now?
