### ISSUE TITLE
TypeScript error crashes rollup in watch mode

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#871]
When running rollup in watch mode (for example with `yarn start`) a typescript error will lead to a crash of the rollup process which requires it to be restarted. There is a known issue and workaround: https://github.com/rollup/plugins/issues/272.

**Comment by xla** [comment]
I have applied this fix, described in the issue, in another project with success:

``` js
  typescriprt((
    noEmitOnError: true,
  })
```
