### ISSUE TITLE
Add feedback section in settings

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#873]
[Link to Figma file.](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=4147%3A7518)

![image](https://user-images.githubusercontent.com/4406983/92250970-6f85cc00-eecc-11ea-99de-2646aa5ad765.png)

**Comment by brandonhaslegs** [comment]
@abbey-titcomb anything else we want to put here? Just made it super simple.

**Comment by abbey-titcomb** [comment]
@brandonhaslegs - sorry just saw this.

I'm thinking that linking to the radicle.community could be a good idea as well for feedback that *doesn't* fit in an issue. Could restructure the Feedback category for this purpose. 

https://radicle.community/c/site-feedback/2
