### ISSUE TITLE
CoCo monorepo impact on UX

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#876]
At the moment we can't concurrently access the underlying `PeerApi`, due to the constraints of the `git2` primitives:

https://github.com/radicle-dev/radicle-link/blob/0fe8bf2691ce9bde9fe17db81d933a9ab98e13f4/librad/src/net/peer.rs#L138-L145

In the proxy code we wrap the API in a Mutex to guarantee serialised access. With the increase in concurrent tasks like announcing, syncing and ~~queue~~ requests we have to anticipate a lot of background activity which needs access to the shared resource. For example our fetch is currently implemented as:

https://github.com/radicle-dev/radicle-upstream/blob/bd9aed435db2efa9d5680501c3c4dbd496266250/proxy/coco/src/peer.rs#L336-L353

Given that we fetch from other end users with varying connection quality such a fetch could take significant time, where significant is noticeable to a human.

* **Is it correct to assume that a fetch will lock the monorepo?**
* **Would that imply that while such an operation is underway no other (even reads) can be performed on the state of the monorepo?**

@cloudhead @FintanH @kim

**Comment by cloudhead** [comment]
It should be possible to have multiple readers no? If we can have that, eg. via RwLock, then it wouldn't impact the UI too much I think.

**Comment by kim** [comment]
`libgit2` is not thread-safe per-se:

> Most data structures do not guard against concurrent access themselves. This is because they are rarely used in isolation and it makes more sense to synchronize access via a larger lock or similar mechanism.

(from https://github.com/libgit2/libgit2/blob/master/docs/threading.md)

However, it goes to great lengths to detect and handle concurrent modifications to the _on disk_ repo -- with git's multiprocess architecture, this can always legitimately happen. For example, it will reload the `refdb` if it determined that it has changed on-disk. A `fetch` can also be considered safe to perform concurrently -- worst thing that can happen is that we end up with two overlapping packfiles, which will eventually be GC'ed.

It is up to the caller to decide which price to pay: either the `Repository` handle is guarded by a lock, or a new handle is acquired when a task should be executed concurrently. The drawbacks of the first are described above, whereas the second option adds to memory pressure, and potentially IO. The `PeerApi` implements a variant of `ToOwned` -- `TryToOwned` -- so the caller can decide (and has to handle any errors which might occur when reopening the repo from disk).

**Comment by kim** [comment]
> RwLock

`RwLock<T>` requires `T` to be `Sync` to be itself `Sync` -- so that doesn't help much (been there).

**Comment by xla** [comment]
> `RwLock<T>` requires `T` to be `Sync` to be itself `Sync` -- so that doesn't help much (been there).

We all have. :<

**Comment by xla** [comment]
> It is up to the caller to decide which price to pay: either the `Repository` handle is guarded by a lock, or a new handle is acquired when a task should be executed concurrently. The drawbacks of the first are described above, whereas the second option adds to memory pressure, and potentially IO. The `PeerApi` implements a variant of `ToOwned` -- `TryToOwned` -- so the caller can decide (and has to handle any errors which might occur when reopening the repo from disk).

Was eyeing that and thought this might be the direction to go. I think this answers the questions sufficiently and we can rework the implementation to not block the UI when a background task is executed. Thanks @kim!
