### ISSUE TITLE
CoCo::peer

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#887]
# CoCo::peer

With the advent of a range of ongoing network tasks (#600, #602, #786, #803, #852)
the coco crate is in need of an entity to manage these, while advancing the
network protocol - to observe and react to signifcant events from peers.
Addtionally striving for the ability to have our the algorithms for the
mentioned isues easy to understand and iterate on, given that we for most of
them are in exploration phase.

So far our organisation of network related code was haphazard at best, with
setting up some subscribers in the `coco::Api` and starting a single
background task in our main. Neither does that give clear contracts to test, nor
does it help collaborators contribute safely when tasked with the introduction
of a new subroutines.

To remedy these points, the design proposed here introduces a dedicated
`coco::Peer` to manage all network responsibilities to uphold:

* separate state access from network machinery
* manage network subroutines concurrently
* surface "peer protocol"
* expose significant peer events so UX features can be satisfied
* give contributors simple tools to add/iterate on subroutines
* enable integration test suite

## Interface

To illustrate the peer API we use a trait, might not be needed in the final
implementation.

``` rust
trait Peer {
    /// Consume the `RunLoop` we obtain when calling accept on a librad peer. We hold onto it
    /// until `run` is explicitely scheduled.
    fn new(run_loop: RunLoop, state: State, store: kv::Store) -> Self;

    /// Long-running task to be scheduled that consumes the `Peer` and keeps the machinery running.
    /// Responsible to keep the `RunLoop` alive and of the peers background tasks.
    async fn run(self) -> Result<(), Error>;

    /// Subscribe to peer events emitted while running the "peer protocol".
    ///
    /// NB(xla): Must be called before `run` is started, as that consumes the peer.
    fn subscribe(&self) -> tokio::sync::broadcast::Receiver<Event>;
}
```

Zooming into the run loop of the peer this is how the central, concurrent way
of advancing its protocol could look like:

``` rust
/// Start up the internal machinery to advance the underlying protocol, react to significant
/// events and keep auxiliary tasks running.
///
/// # Errors
///
/// * if one of the handlers of the select loop fails
pub async fn run(self) -> Result<(), Error> {
    // Start announcement timer.
    let mut announce_timer = todo!();

    // Subscribe to API events.
    let api_subscriber = todo!();

    // Subscribe to protocol events.
    let protocol_subscriber = todo!();

    // Subscrbe to project urn requests.
    let request_projects_subscriber = todo!();

    // Advance the librad protocol.
    tokio::spawn(self.run_loop);

    loop {
        let res = tokio::select! {
            _ = announce_timer.tick() => {
                let updates = todo!();
                Ok(Event::Announced(updates))
            },
            Some(event) = api_subscriber.next() => {
                // React to api events.
                Ok(Event::API(event))
            },
            Some(event) = protocol_subscriber.next() => {
                // React to protocol events like fetching.
                // Issues feteches for the first N connected peers on startup.
                Ok(Event::Protocol(event))
            },
            Some(request) = request_projects_subscriber.next() => {
                // Issue a Want.
                // Update request.
                Ok(Event::Requested(request))
            },
            else => break,
        };

        match res {
            // Propagate if one of the select handlers failed.
            Err(err) => return Err(err),
            Ok(event) => {
                // Send will fail, if there are no active receivers.
                if self.subscriber.receiver_count() > 0 {
                    if let Err(err) = self.subscriber.send(event).map_err(Error::Broadcast) {
                        return Err(err);
                    }
                }
            }
        }
    }

    Ok(())
}
```

Events emitted by the peer could be shaped like this:

``` rust
/// Significant events that occur during a [`Peer`]s lifetime.
#[allow(clippy::large_enum_variant)]
#[derive(Clone)]
pub enum Event {
    /// Gossiped a list of updates of new heads in our [`crate::state::State`]`.
    Announced(announcement::Updates),
    /// Received a low-level api event.
    API(peer::PeerEvent),
    /// Received a low-level protocol event.
    Protocol(protocol::ProtocolEvent<Gossip>),
    /// Requested a project from the network
    Requested(Request),
}
```

_The current design does not explicitely propose a "peer protocol", this is
left for future iterations._

**Comment by xla** [comment]
@FintanH This should give some clarity on my thinking when talking about project requests.

**Comment by FintanH** [comment]
So, just to clarify that I'm understanding this approach, we have a single centre for where events are generated. The events then get propagated to any listeners that wish to use them.

Is that the gist?

**Comment by xla** [comment]
> Is that the gist?

More or less, yet to clarify I expect this pseudo-routing table of listeners to be static and small. Something we set up in main at the start of the app. For now the only subscriber would be the notifications we reintroduced recently. Does that answer your question?

**Comment by FintanH** [comment]
Ya, I think so :+1:

**Comment by NunoAlexandre** [comment]
> So far our organisation of network-related code was haphazard at best, with
setting up some subscribers in the `coco::Api` and starting a single
background task in our main. Neither **does that give clear contracts to test**, **nor
does it help collaborators contribute safely when tasked with the introduction
of new subroutines.**

Could you expand on the bold blocks? I'm not sure what you mean by "clear contracts to test" neither how I as a contributor would feel unsafe when introducing subroutines.

If you could lay these out in more concrete detail that will help better analyse what the solution is actually tackling. :+1:

**Comment by xla** [comment]
@NunoAlexandre Does this https://github.com/radicle-dev/radicle-upstream/pull/881#issuecomment-691024494 answer your qeustion? Or would you see need for more detail?

**Comment by NunoAlexandre** [comment]
> @NunoAlexandre Does this [#881 (comment)](https://github.com/radicle-dev/radicle-upstream/pull/881#issuecomment-691024494) answer your qeustion? Or would you see need for more detail?

yes it does. maybe for future similar work I'd be nice to do these preemptively do make sure everyone is on the same page about the problem and about the proposed solution :100:

**Comment by xla** [comment]
> yes it does. maybe for future similar work I'd be nice to do these preemptively do make sure everyone is on the same page about the problem and about the proposed solution 100

Noted, always good to get perspective from the outside for how much context should be provided for reviewes.
