### ISSUE TITLE
Decouple the feature flag from the env

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#888]
When starting the app with `yarn start` etc. it starts electron with `NODE_ENV=development`. The feature flag `isDev()` depends on this environment. 

To flexibly develop the app and see what features the production user will see, it should be possible to easily and independently set the feature flag and environment.

**Comment by rudolfs** [comment]
What would be the correct thing to do here for the design system guide?

<img width="525" alt="Screenshot 2020-09-14 at 17 32 45" src="https://user-images.githubusercontent.com/158411/93106268-59d48b80-f6b0-11ea-991e-91b990db6024.png">

**Comment by xla** [comment]
Are we concerned of showing the design system to end-users? It doesn't really affect any feature which we want to roll out, so it might not be a concern to feature flag.

**Comment by NunoAlexandre** [comment]
@MeBrei @rudolfs so the desired end result is to be able to specify which environment to run the app with, right? meaning `NODE_ENV=development yarn start` / `yarn start` for development and `NODE_ENV=production yarn start` for production.

**Comment by cloudhead** [comment]
No the concern is that feature flags should not be coupled with the environment.

**Comment by NunoAlexandre** [comment]
Cool I see.

**Comment by NunoAlexandre** [comment]
_Just me rumbling, which might be useful for others._

So currently have `NODE_ENV` which is used to define `isDev`.

❓Where else do we set `NODE_ENV`?

On `electron:start` , which is called on `start` and `test`

❓How is `NODE_ENV` used to define `isDev()`

- `const isDev = process.env.NODE_ENV === "development";`

❓How is `isDev` used that requires decoupling?

1. For development-only stuff:

    ```rust
    if (isDev) {
        watcher = require("chokidar").watch(path.join(__dirname, "../public/**"), {
          ignoreInitial: true,
        });
    ```

    ```rust
    const startProxy = () => {
      if (isDev) {
        return;
      }
    	...
    ```

2. For feature flagging

```rust
isDev() &&
      items.push({
        icon: Icon.Wallet,
        title: "Wallet",
        href: path.orgFund(orgId),
        looseActiveStateMatching: false,
      });
```

```rust
if (isDev()) {
    sendFundsMenuItem = {
      title: "Send funds",
      icon: Icon.ArrowUp,
      event: () => console.log("event(send-funds-to-org)"),
    };
  } 
```

```rust
isDev() &&
      items.push(
        {
          icon: Icon.ExclamationCircle,
          title: "Issues",
          href: path.projectIssues(projectId),
          looseActiveStateMatching: false,
        },
        {
          icon: Icon.Revision,
          title: "Revisions",
          href: path.projectRevisions(projectId),
          looseActiveStateMatching: false,
        }
      );
```

```rust
if (isDev()) {
    codeCollabMenuItems = [
      {
        title: "New issue",
        icon: Icon.ExclamationCircle,
        event: () => console.log("event(new-issue)"),
      },
      {
        title: "New revision",
        icon: Icon.Revision,
        event: () => console.log("event(new-revision)"),
      },
    ];
  }
```

```rust
{#if isDev()}
  <AdditionalActionsDropdown menuItems={menuItems(member)} />
{/if}
```

```rust
{#if isDev()}
  <SupportButton on:click={() => console.log('event(support-project)')} />
{/if}
```

**What features are flagged?**

- Funding/Wallet
- Issues
- Revisions
- "AdditionalActions"
- Support

It's clear why we need the decoupling :heavy_check_mark: 

### Solutions

- **Alternative #A:** one flag, `futureFeaturesEnabled`

    Toggle all features that are meant for the future 

    **Pros:**

    - Simple, one flag, one environment variable
    - We can enable or disable all such features at once
    - Fulfils the current needs
    - Delivering a feature to the public only requires removing the conditional code where it's conditionally set

    **Cons:** 

    - No flexibility ***if*** we need to have tighter control 🔍

- **Alternative #B:** one flag per feature

    Each flagged feature would have its own flag: `walletsEnabled/fundingEnabled`, `issuesEnabled`, `revisionsEnabled`, `supportEnabled`, etc. We would have a `flaggedFeatures` object in the UI:

    ```jsx
    flaggedFeature {
      funding: env.RADICLE_FUNDING_ENABLED === "true",
      issues: env.RADICLE_ISSUES_ENABLED === "true",
      support: env.RADICLE_SUPPORT_ENABLED === "true",
      //etc...
    } 
    ```

    **Pros:**

    - Granular control over which future features are enabled or hidden

    **Cons:**

    - More machinery that solves no current need, as far as I see.
    - Adding a new flagged feature requires:
        - Add a new environment variable
        - Add a new field to the `flaggedFeature`
        - Use the new flag where appropriate: `if flaggedFeature.newFlag {..}`
    - Delivering a feature requires undoing all the previous steps

    ### Conclusion

    I see no need for nothing more granular than having a single feature flag for all future features, so option #A is clearly a winner.

**Comment by cloudhead** [comment]
We could sort of get around the multiple vars thing like this:
```
RADICLE_FEATURES=wallet,orgs,discovery
```
```js
if (featureEnabled("wallet")) { ... }
if (featureEnabled("org")) { ... }
...
```

**Comment by NunoAlexandre** [comment]
> We could sort of get around the multiple vars thing like this:
> 
> ```
> RADICLE_FEATURES=wallet,orgs,discovery
> ```
> 
> ```js
> if (featureEnabled("wallet")) { ... }
> if (featureEnabled("org")) { ... }
> ...
> ```

ahah I just thought about that :laughing: :brain:  

indeed. though the question about that being necessary remains.

**Comment by rudolfs** [comment]
Can we still keep `isDev` in the renderer for things like the design system guide and "Clear session" @cloudhead?

**Comment by NunoAlexandre** [comment]
> Can we still keep `isDev` in the renderer for things like the design system guide and "Clear session" @cloudhead?

Don't mean to answer in place of @cloudhead but I guess the answer is yes, and those are `development` concerns, different from flagging features :+1:

**Comment by rudolfs** [comment]
> indeed. though the question about that being necessary remains.

It might complicate things if certain features depend on each other. Also would have to remember how to get a list of all the possible features that we can enable.

**Comment by cloudhead** [comment]
> > Can we still keep `isDev` in the renderer for things like the design system guide and "Clear session" @cloudhead?
> 
> Don't mean to answer in place of @cloudhead but I guess the answer is yes, and those are `development` concerns, different from flagging features

:+1: 

> > indeed. though the question about that being necessary remains.
> 
> It might complicate things if certain features depend on each other. Also would have to remember how to get a list of all the possible features that we can enable.

We don't really need it right now anyway, so let's keep it simple. We can have a `RADICLE_EXPERIMENTAL` var or something.
