### ISSUE TITLE
Disseminate transaction state

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#89]
For proper feedback to the user about create, updated and lists of current/past transaction we want to have a quick way to let the UI know if the state of a given transaction has changed. Naturally we would turn to GraphQL subscriptions. Unfortunately the juniper crate we rely on to provide the API through the proxy is still not providing that functionality, see [#54](https://github.com/graphql-rust/juniper/issues/54) which tracks the progress and the implementation in [#433](https://github.com/graphql-rust/juniper/pull/433) - which in turn is blocked on [#497](https://github.com/graphql-rust/juniper/pull/497) (a change we personally would welcome as well).

That said we can look to alternatives to satisfy this need. A simple stopgap solution is a to offer a single [SSE](https://www.w3.org/TR/2009/WD-eventsource-20090421/) the UI subscribes to and gets its fix of juicy new transaction upates.

### Design
Originally proposed by @rudolfs in https://github.com/radicle-dev/radicle-upstream/issues/81#issuecomment-575285681:
```graphql
type Query {
  transactions(walletId: ID!): [Transaction]!
}
```

The transaction status subscription could look something like this:
```graphql
type Subscription {
  transactionStateChanged(transactionId: ID!): Transaction
}
```

Potentially we could also use a subscription for new transactions to show a badge on the wallet icon:
```graphql
type Subscription {
  newTransaction(walletId: ID!): Transaction
}
```

**Comment by xla** [comment]
We need to validate what the current state around transactions lifecycles are with @geigerzaehler and @NunoAlexandre.

**Comment by geigerzaehler** [comment]
Currently we have the following transaction states
* Invalid
* Accepted by a node and disseminated to the network
* Included in a block (with Aura this is almost equivalent to being finalized)

I’ve documented this more clearly in https://github.com/radicle-dev/radicle-registry/pull/206

Note that these states don’t tell us if a transaction was “successful” in the ledger, i.e. whether some money was transferred. This is what `TransactionApplied::result` is for.

**Comment by xla** [comment]
Superseeded by #225.
