### ISSUE TITLE
Create include file on checkout

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#894]
When we checkout we should generate include file using `radicle-link` [utilities](https://github.com/radicle-dev/radicle-link/pull/300). 

So when we are [creating](https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/coco/src/project/checkout.rs#L52) the working copy we should also be creating an include file for that working copy.

This means we need to place the include file in a canonical location. This means that we should use a data directory for placing the set of include files. I believe upstream already has it's own data directory, so this should be passed to the `Checkout` struct.

We should end up with something like `$XDG_DATA_HOME/includes/<project.urn.id>.inc` and the working copy should create a config entry to point to this include path.

There's an integration test called [working_copy.rs](https://github.com/radicle-dev/radicle-link/blob/master/librad/tests/working_copy.rs) to see an example use of creating the working copy with this include file.

**Comment by xla** [comment]
@FintanH The description mentions to create an include file for a working copy. Wouldn't it be as correct to create an include file per project, which can be used for all working copies?

**Comment by FintanH** [comment]
I think there are two things to unpack here:
1. A working copy is created based on a project, and so we create an include file which indeed is based on that project. The include file's name will be of the form `format!("{}.inc", urn.id)`
2. I'm interpreting what you're saying is that a user may create multiple working copies per project, is that correct? If so then ya, we should check if the include file already exists and just add the section in the working copy to point to the existing include file.

**Comment by xla** [comment]
Yeah that clarifies it and matches my understanding.

To outline what my current approach would be: For every project we indiscriminately maintain an include file. With the work tracked in #930 can be expected to be up-to-date at "all" times. Whenever the user creates a working copy it will be set up with the projects include file. This will not tie the creation of the include files to the creation of a working copy, but to significant events in the project lifecycle.

**Comment by FintanH** [comment]
My only critique of this is if the user hasn't created a working copy then they don't need an include file. So if they're merely tracking the project there's no need to create one. 

I suppose we should create an include file when we initialise a project too :)

**Comment by xla** [comment]
> My only critique of this is if the user hasn't created a working copy then they don't need an include file. So if they're merely tracking the project there's no need to create one.

Fair, we should do it lazily on first checkout.

> I suppose we should create an include file when we initialise a project too :)

Right on, mentioned that in #930.
