### ISSUE TITLE
App opens in onboarding on every app start

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#900]
Steps to reproduce:

1. start app
2. create identity and complete onboarding
3. close the app
4. start the app again

Expected outcome: the app opens in the profile view without going through onboarding again.

The identity still exists, but the session endpoint always returns an empty identity on app start:
```json
{
  "identity": null,
  "settings": {
    "appearance": {
      "theme": "light",
      "hints": {
        "showRemoteHelper": true
      }
    },
    "coco": {
      "seeds": []
    }
  }
}
```

Seems like this regression was introduced in: https://github.com/radicle-dev/radicle-upstream/pull/881. Other settings (like theme) aren't persisted either.

**Comment by xla** [comment]
Tracked down the issue being introduced in this commit: https://github.com/zshipko/rust-kv/commit/9d208d4be60b99a7ed9f505b36d325c58ce74dca

Going to prepare a patch to integrate on a working commit and look into how to report this meaningfully to the upstrea project.

**Comment by rudolfs** [comment]
Fixed in #907.

**Comment by xla** [comment]
I left this open as the underlying issue wasn't addressed and we only landed a stop-gap.

**Comment by juliendonck** [comment]
@xla check this out and clooooose please

**Comment by geigerzaehler** [comment]
@xla: I’m closing this. Feel free to reopen or create a new issue with the underlying issue details if this is still relevant.
