### ISSUE TITLE
Add project display names to following tab

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-upstream#902]
![image](https://user-images.githubusercontent.com/18275452/93198663-a02bf800-f74d-11ea-8875-e786f566db1d.png)

The Still Looking... section of a user's Following section should include the name of the project in addition to the URN. 

Figma [here](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=4147%3A7717)

@juliendonck - another one to pick up if you want.

**Comment by juliendonck** [comment]
@abbey-titcomb this is from the beta1 spec. In the first release we're going for the simplified version -> screenshot below

<img width="1318" alt="Screenshot 2020-09-15 at 15 14 42" src="https://user-images.githubusercontent.com/2326909/93215046-33712780-f766-11ea-83c2-5a2d9fdbd3ff.png">
