### ISSUE TITLE
Deleted files not showing up in commit view

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#918]
Refs: https://github.com/radicle-dev/radicle-upstream/issues/912.

Created files show up like this:
<img width="50%" alt="Screenshot 2020-09-17 at 11 56 38" src="https://user-images.githubusercontent.com/158411/93455644-ecf20900-f8dc-11ea-83cd-1dc605e16a2b.png">

Deleted files not:
<img width="50%" alt="Screenshot 2020-09-17 at 11 56 47" src="https://user-images.githubusercontent.com/158411/93455652-ee233600-f8dc-11ea-8702-e9e686024810.png">

**Comment by rudolfs** [comment]
File renames might be missing as well.

**Comment by MeBrei** [comment]
> File renames might be missing as well.

Renames are currently not exposed in the commit response #929

**Comment by FintanH** [comment]
Do we know if the missing deletes is down to surf or is it something happening in proxy?

**Comment by MeBrei** [comment]
@FintanH The missing deletes is a ui problem, proxy already provides them. visuals added in #925

For the other diff types, see #929

**Comment by FintanH** [comment]
Ok perfect, just wanted to make sure where the problem was happening :)
