### ISSUE TITLE
Minor UI changes for release preparation

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#919]
- [x] "Handle" needs to be replaced with display name in error state copy
- [ ] ~~Contributors tab shouldn't have a changing cursor on hover since it is not yet clickable.~~
- [ ] ~~Is there a page for viewing branches? If not, we should remove the changing cursor on hover over the Branches tab~~

Refs: https://github.com/radicle-dev/radicle-upstream/issues/912.

**Comment by MeBrei** [comment]
> * Contributors tab shouldn't have a changing cursor on hover since it is not yet clickable.
> * Is there a page for viewing branches? If not, we should remove the changing cursor on hover over the Branches tab

I think these two points are addressed in #886, as they are moved into the header (without link/button functionality for now)

**Comment by cloudhead** [comment]
> * "Handle" needs to be replaced with display name in error state copy

I'm not sure we've settled on this yet. There was a discussion in Figma.

**Comment by rudolfs** [comment]
> I'm not sure we've settled on this yet. There was a discussion in Figma.

According to this discussion, it looks like "display name" was the outcome: https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA?node-id=4147:7815#39219315.

\cc @abbey-titcomb

**Comment by juliendonck** [comment]
> > * "Handle" needs to be replaced with display name in error state copy
> 
> I'm not sure we've settled on this yet. There was a discussion in Figma.

@rudolfs @abbey-titcomb This is what @cloudhead was talking about. We should decide this once and for all so we don't have to make the change twice.

**Comment by abbey-titcomb** [comment]
@juliendonck - based on decision, it seems like the change still has to be made, as this error occurs when user is inputting their display name.
