### ISSUE TITLE
Refactor remote.ts & Remote.svelte 

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#926]
In light of recent developments, we can now use typescript within actual svelte components. Because `remote.ts` + `Remote.svelte` were conceived when we could only use js in svelte, `remote.ts` caters to the needs of a javascript-only counterpart. I think the syntax could be improved and perhaps the whole `remote.ts` file condensed into a single `Remote.svelte` component (unless we want to keep `remote.ts` for exporting types).

**Comment by geigerzaehler** [comment]
This has been improved. We’ll open follow-up issues if more opportunities arise.
