### ISSUE TITLE
Single source of truth for dealing with keyboards

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#927]
We reference keyboard shortcuts in multiple places now, so we should have a module for consistency and type-safety. This looks like a cool thing to add: https://github.com/nfriend/ts-key-enum/blob/master/Key.enum.d.ts

**Comment by rudolfs** [comment]
It seems like we're already typing key events and svelte language tools provides us with safeguards.

https://github.com/radicle-dev/radicle-upstream/blob/53a0971fd44ccead44682d3e91953b52207c185b/ui/Hotkeys.svelte#L21:L22

<img width="892" alt="Screenshot 2020-09-28 at 09 23 05" src="https://user-images.githubusercontent.com/158411/94402634-956d5c00-016c-11eb-92f2-276db34e0e99.png">

Is there some added benefit to `ts-key-enum` that I'm not aware of?

**Comment by rudolfs** [comment]
This is not relevant at the moment.
