### ISSUE TITLE
Expose file renames in commit

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#929]
Currently what shows up in git as 
```
[master 911f560] Rename file
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename test.txt => testing/test.txt (100%)
```
shows up in the api response for `/commit` as a creation/deletion
```diff: {created: ["testing/test.txt"], deleted: ["test.txt"], moved: [], copied: [], modified: []}```

- [ ] Expose all types in the response
- [ ] Show them in the ui Commit view (still needs designs)

**Comment by kim** [comment]
I think `surf` does surface renames, but needs to be told to apply the heuristics (`git` doesn't actually track renames, it's just guessing). See:

https://docs.rs/git2/0.13.11/git2/struct.Diff.html#method.find_similar
https://github.com/radicle-dev/radicle-surf/blob/57ff3c843a41420978ce4c91f8cfe320dcb5c46d/src/vcs/git/repo.rs#L351
