### ISSUE TITLE
Keep include files fresh and clean

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#930]
Once #894 has landed we should tie into significant actions affecting the tracking graph of a project to update the corresponding include file, so that local working copies can access to the most up-to-date information.

**Comment by xla** [comment]
Did a little inventory and it seems there are only three significant operations which should trigger an create/update of an include file:

* init_project
* clone_project
* track

@FintanH Is that list exhaustive or is there more?

**Comment by FintanH** [comment]
* untrack

Is the only one missing that I can think of :)
