### ISSUE TITLE
Hide tags in revision selector behind `isExperimental`

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#933]
Handling git tags is an unsolved problem in the protocol at the moment, see https://github.com/radicle-dev/radicle-link/issues/145.

Therefore the tag feature is not yet complete and shouldn't be used in production, however we can't just remove them entirely, because a lot of our integration tests depend on them.

As a workaround we can hide tags in the revision selector UI behind the `isExperimental` switch before the imminent β1 release. ~~We can fix the error handling once know how tags should be handled on a protocol level.~~

~~Besides the feature not being ready, I also discovered at least one edge case where it could break for users.~~ → https://github.com/radicle-dev/radicle-upstream/issues/934
<details>
<summary>

~~Steps to reproduce:~~
</summary>

1. create a new project from an existing repository: https://github.com/radicle-dev/git-platinum
2. push all tags to Radicle: `git push rad --tags`
3. open the Upstream UI and go to the platinum project
4. select the `master` branch in the revision selector
5. select the file `.i-too-am-hidden`
6. switch to the tag 'v0.0.1` in the revision selector

Expected to see an informative message that this file is not available on that tag, instead got an error message:
```
 ERROR api::http::error      > Rejection(Coco(PathNotFound(Path(NonEmpty { head: Label { label: ".i-am-well-hidden", hidden: false }, tail: [] }))))
```

<img width="202" alt="Screenshot 2020-09-18 at 15 41 03" src="https://user-images.githubusercontent.com/158411/93605085-9660f980-f9c6-11ea-9aca-af21840d321a.png">
</details>

**Comment by FintanH** [comment]
Seems informative to me: `PathNotFound` <- it's literally saying that this file can't be found. What's the desired outcome here? :) Formatted errors, perhaps?

**Comment by rudolfs** [comment]
> Seems informative to me: PathNotFound <- it's literally saying that this file can't be found. What's the desired outcome here? :) Formatted errors, perhaps?

You only see that message in the CLI in development. The user sees "Incorrect input". Besides, we don't know what will happen when people start using tags in a multi-peer environment, as the feature is half-baked.

**Comment by rudolfs** [comment]
Hm, I think I wasn't expressing myself properly, sorry for that. Let me try to re-phrase.

My proposal is to hide this feature in the UI for the β1 release, because:
 - we haven't thought this feature through (radicle-dev/radicle-link#145) and
 - there are bugs related to it.

**Comment by FintanH** [comment]
> we haven't thought this feature through (radicle-dev/radicle-link#145) and

Agreed :+1: 

> there are bugs related to it.

I don't think this is a bug per-say but more that we're doing something wrong with errors. I can bet this isn't specific to tags and the same thing would happen if you do something similar between switching from `master` to `dev`, or am I wrong on this account?

**Comment by rudolfs** [comment]
> I don't think this is a bug per-say but more that we're doing something wrong with errors. I can bet this isn't specific to tags and the same thing would happen if you do something similar between switching from master to dev, or am I wrong on this account?

You're right, I'm conflating things here, sorry again for the ambiguities -- this bug could also happen with branches. So we should tackle this bug separately, propagating the error message to the UI should be sufficient for now.

I'd still want to hide tags in the UI though, because of radicle-dev/radicle-link#145. I'm suggesting hiding because that seems the least effort to me, compared to removing tags completely from proxy/ui, rewriting integration tests and updating git-platinum.

**Comment by FintanH** [comment]
> I'd still want to hide tags in the UI though, because of radicle-dev/radicle-link#145. I'm suggesting hiding because that seems the least effort to me, compared to removing tags completely from proxy/ui, rewriting integration tests and updating git-platinum.

Sounds like a good plan :+1:
