### ISSUE TITLE
Fix error message when switching between branches

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#934]
Steps to reproduce:

1. create a new project from an existing repository, use this repo as source: https://github.com/radicle-dev/git-platinum
2. check out the `dev` branch `git checkout dev`
3. push the branch to Radicle: `git push rad`
4. open the Upstream UI and go to the platinum project
5. select the `dev` branch in the revision selector
6. select the file `here-we-are-on-a-dev-branch.lol`
7. switch to the `master` branch in the revision selector

Expected to see an informative message in the UI, that this file is not available on the selected branch, instead got this error message:
<img width="202" alt="Screenshot 2020-09-18 at 15 41 03" src="https://user-images.githubusercontent.com/158411/93605085-9660f980-f9c6-11ea-9aca-af21840d321a.png">

The error on the proxy side looks like this:
```
 ERROR api::http::error      > Rejection(Coco(PathNotFound(Path(NonEmpty { head: Label { label: "here-we-are-on-a-dev-branch.lol", hidden: false }, tail: [] }))))
```

Refs https://github.com/radicle-dev/radicle-upstream/issues/544.

**Comment by xla** [comment]
A better approach is to return an appropriate 404 and have the UI show a corresponding screen with alternative actions (e.g. `navigate to root`).

**Comment by xla** [comment]
#937 addresses it in earnest but is pending input from @radicle-dev/product for what to show when a file wasn't found.
