### ISSUE TITLE
Lint and fmt markdown during CI

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#935]
Ensure that we have consistent formatting and don't introduce unnecessary noise in unrelated PRs.

**Comment by geigerzaehler** [comment]
We should discuss whether and how we want to approach this with all contributors.

**Comment by rudolfs** [comment]
Personally, I like artisanal hand-crafted markdown 🤷 
What do you think @geigerzaehler?

**Comment by geigerzaehler** [comment]
I’d prefer some more consistent markdown and linting would prevent mistakes like typos in references. However I don’t see this as a huge priority. Let’s keep it open and  move it to the tech project

**Comment by geigerzaehler** [comment]
In a discussion @rudolfs and I agreed that this would be ok to have but it’s also ok if we don’t lint the markdown. We‘ll not make an effort to tackle this but anybody is free to pick this up again.
