### ISSUE TITLE
Make user handle and project name validation messages friendlier

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#949]
[While doing QA](https://github.com/radicle-dev/radicle-upstream/issues/912#issuecomment-693499113.) we discovered that the display name and project name validation messages can be confusing to users. Particularly it's not instantly obvious why a single character is not valid (names have to be at least 2 characters).

Currently we only show the regex that the input is validated against.

<img width="50%" alt="Screenshot 2020-09-22 at 15 38 01" src="https://user-images.githubusercontent.com/158411/93889589-a9870880-fce9-11ea-9575-657090506261.png">
<img width="50%" alt="Screenshot 2020-09-22 at 15 38 14" src="https://user-images.githubusercontent.com/158411/93889590-aab83580-fce9-11ea-8de7-8c423bc5a487.png">

My proposal is to split up the validations in parts and write a separate message for each of them, like so:

- **display name:**
  - Must start with a letter or digit
  - Must be at least 2 characters long
  - Only letters `a`-`z`, `A`-`Z`, digits `0`-`9` and special characters `-`, `_` are allowed

- **project name:**
  - Must start with a letter or digit
  - Must be at least 2 characters long
  - Only letters `a`-`z`, `A`-`Z`, digits `0`-`9` and special characters `-`, `_`, `.` are allowed

We would still want to show only one validation at a time to save space.

**Comment by rudolfs** [comment]
Does this make sense @abbey-titcomb, @juliendonck, @brandonhaslegs?

**Comment by brandonhaslegs** [comment]
Yes, but I'd make them even friendlier!

**Display name**
- Your display name should start with a **letter** or a **number**.
- Your display name should be **at least 2 characters long**.
- Your display name has unsupported characters in it. You can only use basic **letters**, **numbers**, and the `_`, `-`, and `.` characters.

**Project name**
- Your project name should start with a **letter** or a **number**.
- Your project name should be **at least 2 characters long**.
- Your project name has unsupported characters in it. You can only use basic **letters**, **numbers**, and the `_`, `-`, and `.` characters.
