### ISSUE TITLE
Add svelte-check to a husky pre-commit check

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#961]
Seems like people are tripping over `svelte-check` on CI, would be nice to catch this earlier.

https://buildkite.com/monadic/radicle-upstream/builds/4999#c21ac7a7-9cb4-4f9d-a1b6-9534d3577ec4.

**Comment by MeBrei** [comment]
I am in favor of putting it into the pre-commit check `svelte-check --fail-on-warnings`, but it is quite slow. For me it takes around 18s to run. Maybe there is a way to limit it to only check the files that have changed in the commit.

**Comment by MeBrei** [comment]
There is an open issue about this https://github.com/sveltejs/language-tools/issues/353

**Comment by juliendonck** [comment]
@rudolfs can we follow up on this?

**Comment by rudolfs** [comment]
Takes 13s on my machine, seems like it's better it is only running on CI.
