### ISSUE TITLE
Two-way attestation of project identity between librad and registry

### ISSUE THREAD

**Issue by garbados** [radicle-dev/radicle-upstream#98]
The project ID generated by librad should be included in the metadata of project registration and the project ID of the registered project (a tuple of `(domain, name)`) should be included in the metadata of the librad project, so that each can attest to the other's veracity.

To accomplish this:

- The proxy must include the librad project ID (`librad::project::ProjectId`) in the metadata sent during project registration, as part of the `metadata` field of `radicle_registry::client::message::RegisterProject`. This will require casting a `String` to `Bytes128`.
- The proxy must include the registry's project ID (the tuple) in the librad project's metadata (`librad::meta::project::Project#add_rel`) either using the Relation::Label variant (as `Label("radicle", "({domain}, {name})")`) or as a new Relation variant which does not require serializing and deserializing the project ID.

These requirements raise two issues:

- Can librad-ProjectID exceed 128 bytes? If so, how should we handle compressing the ID?
- De/serializing a `(domain, name)` tuple to and from a String raises questions about forbidden characters, to distinguish elements of the domain and the name from special characters like those separating them. If, as an example, `||` is used as a separator, how would we handle the project name `He||o`?

**Comment by xla** [comment]
Thanks for putting this together. The serialisation story is a bit more intricate as we need to address forward and backward compatibility. To ensure that metadata written today can still be made sense of many years down the road, which is esp. important for the `Registry` as the metadata is immutable. For binary we looked at [CBOR](https://cbor.io/) in the past and might be a good first candidate to evaluate. If we stick to the string value in `librad` we should turn to JSON and investigate how we could do versioning.

**Comment by garbados** [comment]
CBOR seems like a good candidate. Particularly the [serde_cbor}(https://github.com/pyfisch/cbor) library seems appropriate.

**Comment by garbados** [comment]
After diving into the issue, I've come up with two questions:

1. It is possible to serialize the `(domain, name)` tuple into CBOR as `vec<u8>` but converting that to a string presents problems. `String::from_utf8` accepts `vec<u8>` as a parameter, but can fail if the vector doesn't contain valid UTF-8, which isn't important to our purposes. I know CBOR has an explicit string form so I suspect I'm missing something that would otherwise make this easy. How would you recommend serializing to a string?
2. To update a librad project's metadata, you need the project's name and a PeerId. We get the name from parameters, and the author's keypair, but I can't figure out how to create a PeerId from a `ed25519::Pair`. Is this possible? Should I just be creating a PeerId on the fly?

**Comment by cloudhead** [comment]
> Can librad-ProjectID exceed 128 bytes? If so, how should we handle compressing the ID?

As far as I know, the project id is a `SHA-1`, so its max length would be 20 bytes.

**Comment by cloudhead** [comment]
> If, as an example, || is used as a separator, how would we handle the project name He||o?

Could you use two `rel`s? One for domain, one for name?

**Comment by kim** [comment]
> As far as I know, the project id is a SHA-1, so its max length would be 20 bytes.

No it is a variable-length string. As hash algorithms may change / be different for different backends, a binary representation would also be of variable length - at least digest size + 1. As digests > 512 bits are somewhat unlikely to appear anytime soon, 128 bytes seems safe.

For all purposes, `ProjectId` should be treated as an opaque type. Thus, if a binary encoding is required, it should be provided by `librad`.

> To update a librad project's metadata, you need the project's name and a PeerId. We get the name from parameters, and the author's keypair, but I can't figure out how to create a PeerId from a ed25519::Pair. Is this possible? Should I just be creating a PeerId on the fly?

The `PeerId` is simply an encoding of the public part of a device key (where the fact that this is an ed25519 keypair should be opaque). `PeerId` impls `From<device::Key>` and `From<device::PublicKey>`.

**Comment by xla** [comment]
>     1. It is possible to serialize the `(domain, name)` tuple into CBOR as `vec<u8>` but converting that to a string presents problems. `String::from_utf8` accepts `vec<u8>` as a parameter, but can fail if the vector doesn't contain valid UTF-8, which isn't important to our purposes. I know CBOR has an explicit string form so I suspect I'm missing something that would otherwise make this easy. How would you recommend serializing to a string?

I'd not go through the length of using CBOR for that use-case, unless we champion a new `Relation` variant of form `Bytes(Label, Vec<u8>)`. For now we can look towards JSON here and get some clarity of how we would encode a version field.

>     2\. To update a librad project's metadata, you need the project's name and a PeerId. We get the name from parameters, and the author's keypair, but I can't figure out how to create a PeerId from a `ed25519::Pair`. Is this possible? Should I just be creating a PeerId on the fly?

It's currently not supported to update the metadata of a project and according to @kim is dependent on radicle-dev/radilce-link#39.

**Comment by xla** [comment]
> Could you use two `rel`s? One for domain, one for name?

This might not be advisable as this opens up the possibility for divergence and doesn't really solve the issue to support forward and backward compatibility.

**Comment by kim** [comment]
It is not unthinkable to allow application-specific extensions to the `radicle-link` project metadata. If we stick to a JSON-ish format, [JSON-LD](https://json-ld.org/) comes to mind.

**Comment by garbados** [comment]
> It's currently not supported to update the metadata of a project and according to @kim is dependent on radicle-dev/radilce-link#39.

Is there another way to attach the attestation to a librad project, or should it wait for that PR?

> For now we can look towards JSON here and get some clarity of how we would encode a version field.

Makes sense to me :+1:

**Comment by xla** [comment]
One-way of the two still missing.

**Comment by xla** [comment]
This might be relevant in the future when the registry materialised again.
