### ISSUE TITLE
Show CoCo network connectivity indicator

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#991]
For users of the application to be aware if and how connected they are, there should be an indicator in the UI. This would help greatly gaining some insight about the healthiness of the app with regards to the code-collaboration network. We currently keep of these states

https://github.com/radicle-dev/radicle-upstream/blob/2ca050344582afe4ca4cfc601ed6e6de20b3401f/proxy/coco/src/peer/run_state.rs#L128-L141

* Stopped - local peer is not set up, we don't listen on a port
* Started - local peer is listening on a socket, but is not connected
* Offline - local peer lost its connections to all its peers
* Syncing - local peer tries get latest project data after connecting/reconnecting with at least 1 other peer
* Online - local peer is operational and is able to interact with the peers it has connected to

For the online case we would want to show how many remote peers we are connected to.

**stretch goal**
Show an expanded view with detailed peer information: peer_id, address/ip, statistics (bandwith, ping, etc.)

**Comment by cloudhead** [comment]
I think `Started` and `Offline` can be merged into one.

**Comment by xla** [comment]
> I think `Started` and `Offline` can be merged into one.

They are different, tho. Offline is when we lost connections after we've been connected.

**Comment by cloudhead** [comment]
But why does it matter how you got there? The state is the same..

**Comment by xla** [comment]
Not saying it might end up mattering per se. It'd be good to think about these cases and have a conversation if there is value/signal to surface: For example knowing if you ever were connected would remove a set of issues to look into.

**Comment by juliendonck** [comment]
> But why does it matter how you got there? The state is the same..

Might make sense to keep the difference in the code, but I agree that the indicator to the user might read the same.

**Comment by cloudhead** [comment]
If it's about preserving this information, I would propose something like this:

```
 enum Status { 
     Stopped,
     Offline { since: Option<Instant> }, // If `since == None`, it has always been offline, ie. the `Started` state above
     Syncing { since: Instant }, 
     Online { since: Instant }, 
 } 
```

This way we don't conflate states with transitions.

**Comment by xla** [comment]
In the light of of #1001 the status changes we want to push for now should be: `Stopped`, `Offline`, `Syncing(number_of_syncing_peers)`, `Online(number_of_connected_peers)`.

**Comment by juliendonck** [comment]
> In the light of of #1001 the status changes we want to push for now should be: `Stopped`, `Offline`, `Syncing(number_of_syncing_peers)`, `Online(number_of_connected_peers)`.

@xla what does "stopped" mean in this context? @cloudhead  do we need to communicate this to the user?

cc @brandonhaslegs

**Comment by xla** [comment]
> @xla what does "stopped" mean in this context? @cloudhead do we need to communicate this to the user or can we merge this with offline in the UI?

Stopped means the peer is not running, offline means the peer is running but is not connected.

**Comment by rudolfs** [comment]
> Stopped means the peer is not running, offline means the peer is running but is not connected.

In what circumstances would a peer be stopped @xla? Will the user have control over that? Or does that happen only when there's a bug and it's an error state?

**Comment by xla** [comment]
> In what circumstances would a peer be stopped @xla? Will the user have control over that? Or does that happen only when there's a bug and it's an error state?

Currently we don't give control, but could be at some point. The peer is also not running when no identity is set up. Furthermore there could be errors when binding locally (listening) for various reasons.

**Comment by xla** [comment]
Semantically those are distinct and carry quite different signal that would be actionable in distinct ways.

**Comment by rudolfs** [comment]
@xla isn't `Offline` the same as `Online` with a connection count of 0?

**Comment by xla** [comment]
> isn't `Offline` the same as `Online` with a connection count of 0?

From which perspective are you asking?

**Comment by rudolfs** [comment]
> From which perspective are you asking?

From the user's perspective.

**Comment by xla** [comment]
> From the user's perspective.

There are many reasons that upstream can be offline, like no route to the public internet. One of the heuristics at the moment is when there are no peers present.

**Comment by xla** [comment]
> isn't `Offline` the same as `Online` with a connection count of 0?

There is no case where the status is `Online` and the count is 0.

**Comment by xla** [comment]
> In what circumstances would a peer be stopped @xla? Will the user have control over that?

Thought more about this. As upstream is currently the gateway to an operating peer on the users machine it should extend control to the end-user to not assume and operate on their behalf.

**Comment by xla** [comment]
Done in #1027
