### ISSUE TITLE
Add sealed keystore filter guard

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#997]
This prepares the api endpoints availability depending on the future key store and if it is un-/sealed.

We want to add a guard (similar to `with_owner_guard`) that guards those endpoints only available to unsealed key stores. In the first iteration, the guard checks if the `signer` in `Context` is present, if not `401 Unauthorized` is returned. `signer` will be optional in `Context`

In this first iteration, the signer will always be set on app start, so that no password input is prompted.

**Comment by FintanH** [comment]
> In this first iteration, the signer will always be set on app start, so that no password input is prompted.

Curious as to how that's going to work? Via the hardcoded password?

**Comment by MeBrei** [comment]
> > In this first iteration, the signer will always be set on app start, so that no password input is prompted.
> 
> Curious as to how that's going to work? Via the hardcoded password?

With the hardcoded password. From what I understand it, setting the signer would be the same as it is currently done on app start.
I am trying to split up the work into steps that can be merged without breaking anything. Otherwise we will have a huge PR

**Comment by FintanH** [comment]
Sounds good to me, just wanted to make sure I understood correctly when I saw the PR coming :)
